### ISSUE TITLE
Symbols not displayed when ssh'ing into Ubuntu12.04 from OSX10.8

### ISSUE THREAD

**Issue by ergelo** [powerline/powerline#100]
Hi, 

my development server is an AWS instance running Ubuntu 12.04. I followed the instructions to set up fallback fonts. Currently I have the `PowerlineSymbols.otf` file in the `~/.fonts/` directory and `10-powerline-symbols.conf` in `~/.fonts.conf.d`.
After running `fc-cache -vf ~/.fonts` this is the response i get:

![Screen Shot 2013-01-22 at 16 01 35](https://f.cloud.github.com/assets/485553/86847/152221c0-64ad-11e2-8fb7-8f46f21b32d8.png)

when I ssh in from OSX (Terminal.app, default font is Monaco for Powerline) and open vim this is what the powerline looks like:

![Screen Shot 2013-01-22 at 15 56 51](https://f.cloud.github.com/assets/485553/86852/29cc44de-64ad-11e2-9695-7c91a084a9e8.png)

this is the relevant `.vimrc` i have:

```
python from powerline.bindings.vim import source_plugin; source_plugin()
let g:Powerline_symbols = 'fancy'
```

I tried restarting my ssh but nothing changed. The weird thing is that I have [powerline-shell](https://github.com/milkbikis/powerline-shell) installed and that powerline seems to work fine (when I ssh from OSX, still broken when I use [Prompt](http://panic.com/prompt/) from iPad).

Any help in sorting out the issue would be appreciated.

**Comment by jeffmccune** [comment]
I ran into this as well.  Make sure `LANG` is set correctly and matches the terminal encoding.  I fixed this with:

```
# ~/.ssh/config
Host *
  SendEnv LANG
```
