### ISSUE TITLE
tmux: gaps between sessions in status bar

### ISSUE THREAD

**Issue by kruton** [powerline/powerline#1029]
In tmux there are gaps between the session lists. Also, changing the active session moves the text around because of these gaps.

Attached screenshots showing the way the text moves around while toggling between sessions:
![tmux-status-1](https://cloud.githubusercontent.com/assets/50407/4064096/0fb3c208-2e0e-11e4-94e5-bfa37814f0ea.png)
![tmux-status-2](https://cloud.githubusercontent.com/assets/50407/4064097/0fb59f9c-2e0e-11e4-9da5-d2596b10fc5a.png)

**Comment by ZyX-I** [comment]
There is nothing I can do with that gap.
