### ISSUE TITLE
pip uninstall does not work

### ISSUE THREAD

**Issue by fonnesbeck** [powerline/powerline#1115]
Unfortunately, powerline is not working out for me, and I would like to uninstall it. I installed it from this repo via pip, but when I try to `pip uninstall powerline`, I get:

```
Cannot uninstall requirement powerline, not installed
Storing debug log for failure in /Users/fonnescj/.pip/pip.log
```

The package installed without error, so its not clear why it does not uninstall.

**Comment by ivaylov** [comment]
try with "powerline-status" instead of powerline

$sudo pip uninstall powerline-status
