### ISSUE TITLE
tmux: Failed to obtain renderer both on the right ant left side

### ISSUE THREAD

**Issue by tbabej** [powerline/powerline#1139]
I am in the process of setting up the powerline, the shell prompt and vim statusline are now working.

Moving to tmux, I am experiencing "Failed to obtain renderer" on both sides of the powerline.

My tmux.conf:

```
# Renumber windows sequentially after closing any of them
set -g renumber-windows on

# set window and pane index to 1 (0 by default)
set-option -g base-index 1
setw -g pane-base-index 1

# Setup powerline
run-shell "powerline-daemon -q"
source "/usr/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"
```

The powerline-render is on $PATH

```
$ which powerline-render
/usr/bin/powerline-render
```

And the powerline-lint outputs no errors.

**Comment by ashishsc** [comment]
I am having the same issue, no output is being produced from powerline tmux left either. The right side is rendering fine however (powerline tmux right does indeed produce output).

**Comment by ZyX-I** [comment]
@ashishsc Please read this issue carefully. I did ask OP for additional information and I do not know what makes you think I can debug the issue without you providing it.

Also do not write to a closed issue. And you did *not* have the same issue, OP had “Failed to obtain renderer”. `powerline tmux left` is not supposed to output anything in default configuration. “Segments” present on the left by default are defined in tmux configuration, are rendered by tmux and have nothing to do with powerline except for the fact that they are defined in powerline tmux bindings file.
