### ISSUE TITLE
Prompt not colorized in tmux

### ISSUE THREAD

**Issue by tbabej** [powerline/powerline#1141]
The bash/zsh commandline prompt is not displaying colors in tmux, even though I managed to get the powerline itself working (with colors).

The prompt works fine in pure bash/zsh.

I am getting the proper output, only the colors are not displayed.

I have

```
set -g default-terminal "xterm-256color"
```

in my .tmux.conf

I also tried setting "screen-256color" or running tmux with -2 option. Any ideas?

**Comment by cbcoutinho** [comment]
I apologize for resurrecting this thread, but I think I have the same issue. I'm trying to use powerline in my tmux setup, and my prompt is not being correctly rendered.

Where does this `term_truecolor` setting go? So far my `~/.config/powerline` directory is empty so I'm assuming I'm just using the defaults for now. I've tried putting it in `~/.config/powerline/config.json` and `~/.config/powerline/themes/tmux/default.json`, but `powerline-lint` doesn't like either of those places

**Comment by tbabej** [comment]
This minimal config.json could work:

    {
        "common": {
            "term_truecolor": false
        }
    }
