### ISSUE TITLE
Can't change base background color (vim & tmux)

### ISSUE THREAD

**Issue by maddie927** [powerline/powerline#1157]
This is the first time I've used powerline, so I'm probably just missing something.  I copied the config files to my user profile as the docs suggested and have looked through every file for defaults, vim-specific, and tmux-specific, but I can't seem to find an option for changing the base background color of the bars.  I use a light theme and the bar is always black.  I've also tried changing the definition of "black", which only affected the tmux session color.  I also tried the terminal color options in both Terminal.app and iTerm2.

**Comment by MareoRaft** [comment]
I think I have the same issue, but I'm not sure.  The little triangle symbol on the left of my powerline in tmux is black, even though i've set status-bg to green.  see image:

![screen shot 2016-06-24 at 1 20 32 pm](https://cloud.githubusercontent.com/assets/860303/16345165/7a7fc164-3a0e-11e6-9c81-ab5d0468f45c.png)

Is there a solution to this?
