### ISSUE TITLE
[osx, zsh] {...}/powerline/bindings/zsh/powerline.zsh:192: no such file or directory: {...}/scripts/powerline-config

### ISSUE THREAD

**Issue by oluckyman** [powerline/powerline#1189]
After installation by this [guide](https://powerline.readthedocs.org/en/latest/usage/shell-prompts.html#zsh-prompt) I have an error when open new terminal window:  

```
/Users/oluckyman/Library/Python/2.7/lib/python/site-packages/powerline/bindings/zsh/powerline.zsh:192: no such file or directory: /Users/oluckyman/Library/Python/2.7/lib/python/site-packages/scripts/powerline-config  
/Users/oluckyman/Library/Python/2.7/lib/python/site-packages/powerline/bindings/zsh/powerline.zsh:196: no such file or directory: /Users/oluckyman/Library/Python/2.7/lib/python/site-packages/scripts/powerline-config
```

**Comment by shiningbridge** [comment]
actually my pip is installed here

$ which pip
/usr/local/bin/pip

but using `pip` to install powerline lead to a totally different folder.
without --user option
installed in /usr/local/lib/python2.7/site-packages/powerline/
and exe I couldn't remember but definitely NOT in /usr/local/bin/ as `pip` does.

with --user option
installed in ~/Library/Python/2.7/lib/python/site-packages/powerline/
and exe in ~/Library/Python/2.7/bin/

This is where I append the $PATH and make powerline-config work.

So I doubt add a note would work for me. :(
