### ISSUE TITLE
Messed colors in tmux status line

### ISSUE THREAD

**Issue by grodzik** [powerline/powerline#1214]
Hi,

After recent `git pull` my status line in tmux started to look messed in terms of colors.
Currently it looks like this 
![powerline-tmux-wrong-colors](https://cloud.githubusercontent.com/assets/102063/5295727/0bc6f184-7b9c-11e4-8f79-7ea5b094bea8.png)

Right status is ok, but left one and window list has problems with separators and backgrounds.
 I did a bisect and it started with those two commits:
`f3ba38e Move all configuration to powerline-base.conf`
`e6fc291 Get color configuration from variables exported by setcolors`

Before it looked ok: 
![powerline-tmux-correct-colors](https://cloud.githubusercontent.com/assets/102063/5295741/360d6b58-7b9c-11e4-887f-ccc73d6f1a99.png)

Also tried to remove my personal config for tmux (it just adds segments and changes date format) but without any improvement.

**Comment by phongvcao** [comment]
I got this same color messing-up problem in Termite's Tmux/Powerline today. I did upgrade my Powerline to the latest version and it is still not resolved. Here is a screenshot of my Termite terminal:

![selection_002](https://cloud.githubusercontent.com/assets/874795/6887907/607c29a2-d63b-11e4-976e-9efcdc9fe9f9.png)

Here is my Termite config file:

```
# Solarized dark color scheme

[colors]
foreground = #839496
foreground_bold = #eee8d5
#foreground_dim = #888888
background = #002b36
cursor = #93a1a1

# if unset, will reverse foreground and background
#highlight = #839496

# colors from color0 to color254 can be set
color0 = #073642
color1 = #dc322f
color2 = #859900
color3 = #b58900
color4 = #268bd2
color5 = #d33682
color6 = #2aa198
color7 = #eee8d5
color8 = #002b36
color9 = #cb4b16
color10 = #586e75
color11 = #657b83
color12 = #839496
color13 = #6c71c4
color14 = #93a1a1
color15 = #fdf6e3

# Other options
[options]
font = DejaVu Sans Mono for Powerline bold 10
```

**Comment by ZyX-I** [comment]
@phongvcao I am wondering how you managed to get this screenshot in first place because necessary colors are not set for tmux colorscheme at all. This can’t be powerline failure because powerline should fail with error on solarized colorscheme.
