### ISSUE TITLE
Not working with Tmux 1.9a

### ISSUE THREAD

**Issue by cousine** [powerline/powerline#1236]
Hi,

I can't seem to get powerline to work with tmux 1.9a/iterm2.

I've followed the recommendations adding powerline-config to $PATH and I can trace that tmux can see the command correctly.

After a lot of tracing, what is weird is that running the config commands in terminal seems to produce results however tmux's run-shell does nothing.

If I try to run the run-shell command manually it gives me exit code 1 without any change to the status line.

At the moment all I can see is the default tmux green bar.

(note: working fine with vim)

**Comment by paralin** [comment]
I can't seem to get it to work under 1.9 either yet, any ideas?
