### ISSUE TITLE
Did the codes change for fancy symbols?

### ISSUE THREAD

**Issue by pmcmorris** [powerline/powerline#1250]
I recently migrated from vim-powerline to powerline to work around a font issue on my linux machine.  It seems that between the two editions the codes for the fancy fonts has changed.  Which is fine on my linux box as I just created more with the scripts.  But this is not an option on windows for several reasons.  What I would really prefer is to simply continue to use the modified version of Consolas that I was already using.

Is there a way to overrided which symbols are used in Vim?  I'd like to simply redirect it to the old values.  Is that possible?

**Comment by ZyX-I** [comment]
It is possible. Do read documentation and note that issue tracker is for issues, mailing list is for questions.
