### ISSUE TITLE
'Namespace' object has no attribute 'config'

### ISSUE THREAD

**Issue by paralin** [powerline/powerline#1258]
Running on linux with the latest `master` commit under tmux 1.9.

Everything looks OK but on the left bottom side I see the session number > 'Namespace' obj > windows

On the right side I see 'Namespace' object has no attribute 'config'

How can I troubleshoot this?

**Comment by ZyX-I** [comment]
If you are not using daemon then log will appear if you run `powerline tmux right`. If you are then log is in daemon stderr. In any case you may use config.json/common/log_file configuration option to put it to the other location.

Given how error spells I assume that you are *not* using master, but rather a mix of partially updated powerlines: develop branch contains a number of incompatible changes, one of which was renaming `--config` to `--config-override`. I am very unsure how you can get this result though: if this was “has no attribute 'config_override'” I would assume you have updated powerline, but have not restarted daemon afterwards, but “… 'config'” needs you use latest `powerline/commands/main.py` file with outdated rest of the files.

What do

    which powerline
    which $POWERLINE_COMMAND
    for m in powerline powerline.commands.main powerline.commands.daemon ; do python -c "import $m; print($m.__file__)" ; done

show?

**Comment by ZyX-I** [comment]
Closing due to lack of feedback.
