### ISSUE TITLE
The online documentation is not up to date?

### ISSUE THREAD

**Issue by omega** [powerline/powerline#1266]
https://powerline.readthedocs.org/en/latest/develop/segments.html still says `highlight_group`, while it seems it should be `highlight_groups` now? The docs in the repo seem to be updated, so it might be a problem with readthedocs?

**Comment by ZyX-I** [comment]
It appears that RTD does not know about project transfer and thus does not build updates.

**Comment by ZyX-I** [comment]
And /latest/ as well as /master/ is documentation for the release that should not be updated. I have told RTD to use new URLs and that /latest/ should use develop branch. Default is still and will always be /master/ though.

Should be fine now, thanks for the alert.
