### ISSUE TITLE
archlinux package not working out of the box

### ISSUE THREAD

**Issue by phaezah7** [powerline/powerline#1267]
phaezah7@argon ~ % vim
Traceback (most recent call last):
  File "<string>", line 9, in <module>
ImportError: No module named powerline.vim
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Unable to import powerline, is it installed?

[...]

phaezah7@argon ~ % yaourt -Ql python-powerline-git |grep powerline.vim
python-powerline-git /usr/lib/python3.4/site-packages/powerline/bindings/vim/plugin/powerline.vim
python-powerline-git /usr/lib/python3.4/site-packages/powerline/vim.py
python-powerline-git /usr/share/vim/vimfiles/plugin/powerline.vim

**Comment by ZyX-I** [comment]
Arch linux packages are not maintained here.

**Comment by phaezah7** [comment]
it wasn't my idea, post instalation message says:
If Powerline doesn't work out of the box on your system, please submit an issue
on GitHub: https://github.com/powerline/powerline/issues

**Comment by ZyX-I** [comment]
@phaezah7 If arch linux package shows this message after installation then I would suggest filing two bugs to the package maintainer. In this repository only pip package is supported and some issues regarding vim-specific Vundle/VAM/… installations. Arch linux package is neither hosted nor supported here and this message is not correct if you saw it .

**Comment by ZyX-I** [comment]
You could also get a reply about Gentoo ebuild because I am a maintainer of it, but it is not supported here either.
