### ISSUE TITLE
Ubuntu oh-my-zsh permision denied

### ISSUE THREAD

**Issue by ahmgeek** [powerline/powerline#1269]
I've installed powerline and moved it to ```~/powerline ```. when adding this line
```powerline/bindings/zsh/powerline.zsh```  to the end of my ```.zshrc```
and re poening my terminator terminal I got this message : ```/home/ubuntu/.zshrc:83: permission denied: powerline/bindings/zsh/powerline.zsh```

**Comment by ZyX-I** [comment]
Line you added to zshrc is invalid: you need dot or `source` commands, *not* running powerline.zsh as a script.

**Comment by ZyX-I** [comment]
Also do not use relative paths.

**Comment by ahmgeek** [comment]
Like that ? ```./powerline/bindings/zsh/powerline.zsh``` also permission denied.

**Comment by ZyX-I** [comment]
Dot *command*. Not *path, starting with dot*. And this is again relative path.

**Comment by ZyX-I** [comment]
Commands are always separated by space with their arguments.
