### ISSUE TITLE
Doc not working

### ISSUE THREAD

**Issue by pickfire** [powerline/powerline#1272]
When I click on the documentation link on the first page and the SSL handshake error is shown.

**Comment by ZyX-I** [comment]
1. I am unable to reproduce this issue.
2. It is either readthedocs or your configuration issue, not a powerline one.

**Comment by ZyX-I** [comment]
I would try to check whether

1. Other documentation hosted on readthedocs works, including site own documentation.
2. Some other relatively unpopular https site works.
3. Some other site that obtained their certificate from the same company works.
4. And also what may be the cause of this error at all.

I am not a security expert and know only a very limited amount of reasons https is not working:

1. You do not have necessary root certificate. This should give you another error AFAIK.
2. Readthedocs was configured not to accept too insecure protocol version and your browser does not know/is not configured to use the new secure ones. No idea what will the error be.
3. Some temporary failure caused by the RTD server. No idea what it can be and what error will be shown.
4. Attempted MitM attack by some unqualified "hacker".
5. You can have any possible kind of error if you told somebody down the layer (e.g. iptables) do strange things.

As you see I even know no reason which will for sure give you SSL handshake error.


In any case I am not changing URLs to http:// even assuming they work.

**Comment by pickfire** [comment]
I tried using another browser with tor but that doesn't seem to work either.

**Comment by ZyX-I** [comment]
I have no problems with browser from the tor browser bundle as well.

**Comment by pickfire** [comment]
And I can't work when using epiphany-browser too.

**Comment by ZyX-I** [comment]
As I said this is not powerline issue. I am not changing links to http://. Also you should not check whether powerline documentation works in different browsers, you should check whether other https sites work.

And check whether date and time on your system are valid. If they are too far in the future no https sites should work because their certificates had already been expired.

**Comment by pickfire** [comment]
> As I said this is not powerline issue. I am not changing links to http://. Also you should not check whether powerline documentation works in different browsers, you should check whether other https sites work.
I tried changing to http:// but I automatically changes to https://

> And check whether date and time on your system are valid. If they are too far in the future no https sites should work because their certificates had already been expired.
My date and time are valid and `date` shows:

    Fri Jan 16 13:31:22 MYT 2015

**Comment by ZyX-I** [comment]
> I tried changing to http:// but I automatically changes to https://

HSTS? My Yandex.Browser Beta does not change, neither does Firefox. In case you were trying powerline.readthedocs.org.

---

You may get more details after running

    openssl s_client -connect powerline.readthedocs.org:443

. If this does not show any errors immediately (note: in this case it will wait for your input in place of exiting) type

    GET / HTTP/1.0

followed by two carriage returns. This should show you some HTTP headers (starting with `HTTP/1.1 302 FOUND`) and a redirect page (HTML, obviously not rendered, has four lines: doctype, page title, in-page header and a paragraph).

**Comment by pickfire** [comment]
I did what you told and when I typed `openssl s_client -connect powerline.readthedocs.org:443`:
```
CONNECTED(00000003)
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.readthedocs.org
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
 1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
 3 s:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFXDCCBESgAwIBAgIRAL+eaKK8u2zMbR8dvClC8DowDQYJKoZIhvcNAQELBQAw
gZAxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTYwNAYD
VQQDEy1DT01PRE8gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIg
Q0EwHhcNMTQwNDE1MDAwMDAwWhcNMTUwNDE1MjM1OTU5WjBeMSEwHwYDVQQLExhE
b21haW4gQ29udHJvbCBWYWxpZGF0ZWQxHTAbBgNVBAsTFFBvc2l0aXZlU1NMIFdp
bGRjYXJkMRowGAYDVQQDFBEqLnJlYWR0aGVkb2NzLm9yZzCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAM7V8nqTwcUSg4pMH2DMzNoZOV6KMZOwLmfnsTDA
7gRUAEOaQPD9dn2PxRoPT3xzcdoSs49Pvd8JiC7Yezzp2Oo1hD6VPlJ0jwQw4w6I
AtcKyPcqSu/TNBVLqcJ5+gxTCIwqqOKLyRcq6f1m6ou3fxKcrfg43ECxUQI7EHIq
iJqfsyDx50U/+gP7kU8p6Q9IqdQbRrG96GzYqMryKBRnh66cDWhRAKmzPSCFeWy+
Z1QvhbxdxJhgImY84HizrslaKuvRlSM4jQq2IZU44CCDTkMkWTFfrDg7h5PDZWjS
PWEEg41HmbzoCSEYUJGMiCVyDI4tHd4N6m79F+GHLMFkn5kCAwEAAaOCAeAwggHc
MB8GA1UdIwQYMBaAFJCvajqUWgvYkOoSVnPfQ7Q6KNrnMB0GA1UdDgQWBBQG+CWd
hwmpDSrawOVyU0fXZ0Dv5jAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAd
BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwUAYDVR0gBEkwRzA7BgwrBgEE
AbIxAQIBAwQwKzApBggrBgEFBQcCARYdaHR0cHM6Ly9zZWN1cmUuY29tb2RvLm5l
dC9DUFMwCAYGZ4EMAQIBMFQGA1UdHwRNMEswSaBHoEWGQ2h0dHA6Ly9jcmwuY29t
b2RvY2EuY29tL0NPTU9ET1JTQURvbWFpblZhbGlkYXRpb25TZWN1cmVTZXJ2ZXJD
QS5jcmwwgYUGCCsGAQUFBwEBBHkwdzBPBggrBgEFBQcwAoZDaHR0cDovL2NydC5j
b21vZG9jYS5jb20vQ09NT0RPUlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZl
ckNBLmNydDAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuY29tb2RvY2EuY29tMC0G
A1UdEQQmMCSCESoucmVhZHRoZWRvY3Mub3Jngg9yZWFkdGhlZG9jcy5vcmcwDQYJ
KoZIhvcNAQELBQADggEBAGc7gixQk45fTl6jhJUSKQWXgPNjN415YAePqnOL3Icy
2rkXOhXIx+QbZ4stVVzDSADTDyO9J/BQpNxzxhbRDL+/zr837y9iO8TKMvPovGhR
trj6dM1sLnAiWD92xf5DRjsRoruTwBjHJy0nvrK08HAiZvLioUxPmlsakesUdgLe
AqlaM8YnspjNMoIyT7NU1KWluWB8Flg70aoFHz6k/Kz1GzMBNY6N9CXeAdTTxlvy
ALiY4pOmXxjIrrkz2c3hbiBiYtHyISMatjkt+Ew1NclG3y/qaUoLnxo8KX8vFUev
yNPrHxCDgBWp/mDTI2rnHN9VDfsN1CnTJLZpLfs7LSU=
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.readthedocs.org
issuer=/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
---
No client certificate CA names sent
---
SSL handshake has read 6132 bytes and written 522 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : DHE-RSA-AES128-SHA
    Session-ID: FB39E15AA56568DFB58C2CB10BC469353BFA851617BD4C347D4A182440AFA281
    Session-ID-ctx: 
    Master-Key: 005495ECC0FA577C5FA5FEA1C994DD8684AA8A7BFC835E1983561ACEEF5F955287A3F728997C9121E04B9A6A6B1363CF
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1421387601
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
---
GET / HTTP/1.0
read:errno=0
```

**Comment by ZyX-I** [comment]
```
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify error:num=19:self signed certificate in certificate chain
verify return:0
```

It looks like if you do not have the root certificate or have some other problems with it. On my system this is

```
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify return:1                                                                                                                                                                                                                                
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority                                                                                                                           
verify return:1                                                                                                                                                                                                                                
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Domain Validation Secure Server CA                                                                                                                
verify return:1                                                                                                                                                                                                                                
depth=0 OU = Domain Control Validated, OU = PositiveSSL Wildcard, CN = *.readthedocs.org                                                                                                                                                       
verify return:1
```

. Do not ask me how to fix this.

**Comment by ZyX-I** [comment]
Other then that and lines starting with “Verify return code: 19 (self signed certificate in certificate chain)” output is identical. At least you now know exactly what the error is and may ask it somewhere in the IRC (I would start with `##linux` channel on freenode or go directly to https://superuser.com with the output you posted here and my quote from the first message highlighted).
