### ISSUE TITLE
Tmux statusline has incorrect spacing or characters on the left side in iTerm 2

### ISSUE THREAD

**Issue by devth** [powerline/powerline#1274]
This has looked like this since I first installed powerline about a year ago. Just upgraded to latest powerline via pip, and tmux 1.9a via homebrew but no change. Note that the characters look right at my zsh prompt and in my vim status line. See bottom left of this screenshot for weirdness:

![http://i.imgur.com/inxC7wv.png](http://i.imgur.com/inxC7wv.png)

Anyone else seeing this? iTerm 2 on OS X.

**Comment by ZyX-I** [comment]
I am wondering what is “latest powerline”, how did you upgrade (specifically did you restart tmux after upgrading powerline).

Note that killing one session and starting it again is not ever going to restart tmux, unless it was the very last session (and I am not sure that you cannot tell tmux server to stay alive in this case). You need `kill-server` (which will kill all sessions) tmux command.

Also if you are using daemon you should restart it after upgrade. If you are using Vundle/VAM/NeoBundle/… separate installation for Vim you should remove it and specifically make sure that it is not used by tmux bindings.

Note that current (develop) version of tmux bindings is broken and will stay the same up until I will not make tmux integration tests work in Travis. Latest release does not have this problem.

**Comment by devth** [comment]
I don't know TBH :) I poked around the powerline source to see if `VERSION` was specified but didn't find it. I'm not a big python / pip user.

Vim isn't related to this problem, right?

I did `tmux kill-server` and restarted iTerm 2 several times while I messed with settings.

**Comment by devth** [comment]
Ok found it:

```
pip show powerline-status
---
Name: powerline-status
Version: 1.3.1
Location: /usr/local/lib/python2.7/site-packages
Requires:
```

**Comment by devth** [comment]
From `pip list` I just noticed I have a Powerline (beta) package installed too.

**Comment by ZyX-I** [comment]
@devth Vim may be. I do not know your tmux config: if you do have a separate installation for Vim and do reference it in tmux config (because relevant path to tmux configuration file is far easier to find). Restarting iTerm 2 is not going to make any sense because it will not even trigger client death. Daemon should not be related (the problematic segments you are seeing are not controlled by powerline, even though they *were* created by powerline bindings) though, but it is in any case good idea to restart.

Also wondering whether running

    powerline-config tmux setenv
    powerline-config tmux source

yields anything interesting like fixing tmux (should be unlikely because if you did restart tmux, but tmux config was not able to call powerline-config then you shouldn’t’ve seen anything at all) or reporting some errors.

If the above actions did not work, can you show `tmux show-options -g` output? The situation looks much like if colors were reversed in tmux which is strange. I can get the same result by selecting tmux statusline in konsole, except that konsole is discarding the selection on each redraw and redraws of statusline happen rather often.

And also check out `powerline-lint` output, just in case.

**Comment by ZyX-I** [comment]
@devth I guess you have some very outdated `pip install --editable` installation, which is most likely the separate installation for Vim. Very outdated because `Powerline` name and `beta` version were used prior to the first release. If this is the case you must remove it, double installations are not supported.

**Comment by ZyX-I** [comment]
I mean remove both from pip (e.g. `pip uninstall Powerline`) *and* from the place where it is actually located.

**Comment by devth** [comment]
Ok, I made sure to completely remove all powerline via pip and reinstall.

Output from commands:
```
powerline-config tmux source
set option: status -> on
set option: status-utf8 -> on
set option: status-interval -> 2
set option: status-left-length -> 20
set option: status-right -> "#(eval $POWERLINE_COMMAND tmux right -R pane_id=`tmux display -p "#D"`)"
set option: status-right-length -> 150
set option: window-status-format -> "#[fg=colour244,bg=colour233,nobold,noitalics,nounderscore]  #I #[fg=colour240,bg=colour233,nobold,noitalics,nounderscore] #[default]#W   "
set option: window-status-current-format -> "#[fg=colour233,bg=colour31,nobold,noitalics,nounderscore] #[fg=colour117,bg=colour31,nobold,noitalics,nounderscore]#I  #[fg=colour231,bg=colour31,bold,noitalics,nounderscore]#W #[fg=colour31,bg=colour233,nobold,noitalics,nounderscore] "
set option: status-left -> "#[fg=colour16,bg=colour254,bold,noitalics,nounderscore] #S #[fg=colour254,bg=colour233,nobold,noitalics,nounderscore] #(eval $POWERLINE_COMMAND tmux left)"
```

```
tmux show-options -g
assume-paste-time 1
base-index 0
bell-action any
bell-on-alert off
default-command "reattach-to-user-namespace -l zsh"
default-shell "/bin/zsh"
default-terminal "screen-256color"
destroy-unattached off
detach-on-destroy on
display-panes-active-colour red
display-panes-colour blue
display-panes-time 1000
display-time 750
history-limit 4096
lock-after-time 0
lock-command "lock -np"
lock-server on
message-attr none
message-bg yellow
message-command-attr none
message-command-bg black
message-command-fg yellow
message-command-style fg=yellow,bg=black
message-fg black
message-limit 20
message-style fg=black,bg=yellow
mouse-resize-pane off
mouse-select-pane on
mouse-select-window off
mouse-utf8 on
pane-active-border-bg cyan
pane-active-border-fg black
pane-active-border-style fg=black,bg=cyan
pane-border-bg black
pane-border-fg white
pane-border-style fg=white,bg=black
prefix C-a
prefix2 none
renumber-windows off
repeat-time 500
set-remain-on-exit off
set-titles on
set-titles-string "#W(#P) - #T"
status on
status-attr none
status-bg colour233
status-fg colour231
status-interval 2
status-justify left
status-keys vi
status-left "#{?client_prefix,#[fg=colour254]#[bg=colour31]#[bold]#[noitalics]#[nounderscore],#[fg=colour16]#[bg=colour254]#[bold]#[noitalics]#[nounderscore]} #S #{?client_prefix,#[fg=colour31],#[fg=colour254]}#[bg=colour233]#[nobold] #(eval $POWERLINE_COMMAND tmux left)"
status-left-attr none
status-left-bg default
status-left-fg default
status-left-length 20
status-left-style default
status-position bottom
status-right "#(eval $POWERLINE_COMMAND tmux right -R pane_id=`tmux display -p "#D"`)"
status-right-attr none
status-right-bg default
status-right-fg default
status-right-length 150
status-right-style default
status-style fg=colour231,bg=colour233
status-utf8 on
terminal-overrides "*256col*:colors=256,xterm*:XT:Ms=\E]52;%p1%s;%p2%s\007:Cs=\E]12;%p1%s\007:Cr=\E]112\007:Ss=\E[%p1%d q:Se=\E[2 q,screen*:XT"
update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"
visual-activity on
visual-bell off
visual-content off
visual-silence off
word-separators " -_@"
```

`powerline-lint` doesn't report anything.

**Comment by ZyX-I** [comment]
Regarding the colors these are exactly my options. Given that the result looks like if this statusline was selected by mouse this is rather strange.

Can you check the following:

1. `powerline tmux left | hexdump -C`
2. Run `tmux set-option -g status-left "$(tmux show-options -gv status-left)#[none]"`. This may or may not fix the issue.
3. Check out `tmux show-options -gw`.
4. Check out whether setting window option `window-status-current-format` in a similar fashion to `tmux set-option -gw window-status-current-format "#[none]$(tmux show-options -gwv window-status-current-format)"`.
5. If 3. does not contain something criminal and both 2. and 4. do not work then I do not think it is a powerline issue. Try running tmux with empty configuration, setting only `window-status-current-format` to the value set by powerline, but with powerline symbols removed. If the result is still reversed colors you can report this to the tmux bug tracker.

**Comment by ZyX-I** [comment]
Closing due to lack of feedback.
