### ISSUE TITLE
Powerline not working when logging in over SSH

### ISSUE THREAD

**Issue by ruslanosipov** [powerline/powerline#1276]
Powerline works perfectly for bash when I use it locally (or via tmux). However when I SSH to the machine in question - I get following errors:

    powerline-daemon: command not found
    -bash: /usr/local/{organization}/home/{username}/.local/lib/python2.7/site-packages/powerline/bindings/bash/../../../scripts/powerline-config: No such file or directory
    -bash: /usr/local/{organization}/home/{username}/.local/lib/python2.7/site-packages/powerline/bindings/bash/../../../scripts/powerline-config: No such file or directory
    powerline-daemon: command not found
    -bash: /usr/local/{organization}/home/{username}/.local/lib/python2.7/site-packages/powerline/bindings/bash/../../../scripts/powerline-config: No such file or directory
    -bash: /usr/local/{organization}/home/{username}/.local/lib/python2.7/site-packages/powerline/bindings/bash/../../../scripts/powerline-config: No such file or directory

If I start tmux after this - I can see powerline for bash in tmux just fine though.

**Comment by ZyX-I** [comment]
You must have path to powerline executables in $PATH.
