### ISSUE TITLE
Weather error in status bar 

### ISSUE THREAD

**Issue by jhwhite** [powerline/powerline#1279]
You can also see the json for the weather in the screenshot.

![tmux_error](https://cloud.githubusercontent.com/assets/1574572/5791210/ed93298a-9e91-11e4-8b1b-60cd03a506c8.jpg)

**Comment by ZyX-I** [comment]
You should post the full traceback. It can be seen either in daemon stderr (use `powerline-daemon --replace --foreground` to run it in foreground) if you use daemon or in stderr when you run `powerline tmux right`, or in both cases in log file if it was specified in configuration (in which case it will not be displayed in stderr). I guess that

1. You are not using daemon.
2. Tmux for some reason took stderr of powerline command and displayed it. Normally this message should be in discarded stderr (or in the log file) and weather segment should not be displayed at all due to the error.

By the way, what does `powerline tmux right 2>/dev/null` show? Neither tmux-1.6 nor tmux-1.9 display `Test` if I use `set-option -g status-right "#(echo Test >&2)"`.

**Comment by jhwhite** [comment]
>By the way, what does powerline tmux right 2>/dev/null show? Neither tmux-1.6 nor tmux-1.9 display Test if I use set-option -g status-right "#(echo Test >&2)".

#[fg=colour3,bg=default,nobold,noitalics,nounderscore] #[fg=colour231,bg=colour3,bold,noitalics,nounderscore] ✉ 1#[fg=colour236,bg=colour3,nobold,noitalics,nounderscore] #[fg=colour252,bg=colour236,bold,noitalics,nounderscore] ⌚ 21:58#[fg=colour247,bg=colour236,nobold,noitalics,nounderscore] #[fg=colour247,bg=colour236,nobold,noitalics,nounderscore] 2015-01-17#[fg=colour233,bg=colour236,nobold,noitalics,nounderscore] #[fg=colour247,bg=colour233,nobold,noitalics,nounderscore] 76.104.85.152#[fg=colour252,bg=colour233,nobold,noitalics,nounderscore] #[fg=colour16,bg=colour252,bold,noitalics,nounderscore]  Firefly#[fg=colour233,bg=colour252,nobold,noitalics,nounderscore] #[fg=colour209,bg=colour233,nobold,noitalics,nounderscore] 37%#[fg=colour241,bg=colour233,nobold,noitalics,nounderscore] #[fg=colour247,bg=colour233,nobold,noitalics,nounderscore] ☾ #[fg=colour97,bg=colour233,nobold,noitalics,nounderscore]36°F %

**Comment by ZyX-I** [comment]
@jhwhite And where is the full traceback requested in the first paragraph? Last paragraph was just a test that this traceback is *not* printed to stderr for whatever reason (which obviously failed).

**Comment by jhwhite** [comment]
Here's the output of powerline tmux right

![screen shot 2015-01-18 at 11 54 51 am](https://cloud.githubusercontent.com/assets/1574572/5793191/e087f94c-9f08-11e4-8795-54125258a061.png)

**Comment by ZyX-I** [comment]
@jhwhite I see no traceback here and weather segment is working just fine. Try restarting tmux.

**Comment by jhwhite** [comment]
How do I get a traceback? And I have restarted tmux and my computer and it still happens.

**Comment by ZyX-I** [comment]
@jhwhite It is in the very first my message. *I do not know whether you are using daemon*, so have provided two ways of getting the traceback. Though in any case you must not see proper `powerline tmux right` *and* start of the log message in tmux at the time. What is your tmux configuration? Also what is `env | grep POWERLINE`?

**Comment by jhwhite** [comment]
Honestly I'm a little confused.

It looks like I can get traceback in two ways.

1.
>You should post the full traceback. It can be seen either in daemon stderr (use `powerline-daemon --replace --foreground` to run it in foreground) if you use daemon 

2.
>or in stderr when you run `powerline tmux right`,

I ran `powerline tmux right` and posted the output above.

If that's not the right info my apologies. I went ahead and did the following:

Running `powerline-daemon --replace --foreground` does nothing. My terminal sits like it's waiting for something and I have to ctrl-c out.

**Comment by ZyX-I** [comment]
@jhwhite `powerline-daemon --replace --foreground` will obviously launch daemon in foreground. This means that it will wait for clients to connect and use it. If no errors are to be displayed daemon will display nothing. Same if no clients are connecting it and requesting something which will result in the error.

Second variant that does not get you traceback means that you should not get the error in tmux. This is why I ask for `.tmux.conf` and `env | grep POWERLINE` (and also missing: `tmux show-environment -g |grep POWERLINE`). I have no idea how you managed to get first lines of error log in tmux statusline at all (AFAIK this is only possible if you specify `log_file` `/dev/stdout`) and still not get it while running `powerline tmux right`.

And, just in case: `tmux show-options | grep status-right`.

**Comment by jhwhite** [comment]
While running the daemon in the foreground when I get that error there is no traceback message displayed to the screen.
```
tmux show-environment -g |grep POWERLINE
POWERLINE_COMMAND=powerline
POWERLINE_CONFIG_COMMAND=powerline-config
_POWERLINE_ACTIVE_WINDOW_FG=colour31
_POWERLINE_ACTIVE_WINDOW_STATUS_COLOR=fg=colour31,bg=colour233,nobold,noitalics,nounderscore
_POWERLINE_ACTIVITY_STATUS_ATTR=nobold]#[noitalics]#[nounderscore
_POWERLINE_ACTIVITY_STATUS_ATTR_LEGACY=none
_POWERLINE_ACTIVITY_STATUS_COLOR=fg=colour11,bg=colour233,nobold,noitalics,nounderscore
_POWERLINE_ACTIVITY_STATUS_FG=colour11
_POWERLINE_BACKGROUND_BG=colour233
_POWERLINE_BACKGROUND_COLOR=fg=colour231,bg=colour233,nobold,noitalics,nounderscore
_POWERLINE_BACKGROUND_FG=colour231
_POWERLINE_BELL_STATUS_ATTR=nobold]#[noitalics]#[nounderscore
_POWERLINE_BELL_STATUS_ATTR_LEGACY=none
_POWERLINE_BELL_STATUS_COLOR=fg=colour1,bg=colour233,nobold,noitalics,nounderscore
_POWERLINE_BELL_STATUS_FG=colour1
_POWERLINE_LEFT_HARD_DIVIDER= 
_POWERLINE_LEFT_HARD_DIVIDER_SPACES=  
_POWERLINE_LEFT_SOFT_DIVIDER= 
_POWERLINE_SESSION_ATTR=bold]#[noitalics]#[nounderscore
_POWERLINE_SESSION_ATTR_LEGACY=bold
_POWERLINE_SESSION_BG=colour254
_POWERLINE_SESSION_COLOR=fg=colour16,bg=colour254,bold,noitalics,nounderscore
_POWERLINE_SESSION_FG=colour16
_POWERLINE_SESSION_HARD_DIVIDER_NEXT_COLOR=fg=colour254,bg=colour233,nobold,noitalics,nounderscore
_POWERLINE_SESSION_PREFIX_ATTR=bold]#[noitalics]#[nounderscore
_POWERLINE_SESSION_PREFIX_ATTR_LEGACY=bold
_POWERLINE_SESSION_PREFIX_BG=colour31
_POWERLINE_SESSION_PREFIX_FG=colour254
_POWERLINE_WINDOW_COLOR=fg=colour244,bg=colour233,nobold,noitalics,nounderscore
_POWERLINE_WINDOW_CURRENT_COLOR=fg=colour117,bg=colour31,nobold,noitalics,nounderscore
_POWERLINE_WINDOW_CURRENT_HARD_DIVIDER_COLOR=fg=colour233,bg=colour31,nobold,noitalics,nounderscore
_POWERLINE_WINDOW_CURRENT_HARD_DIVIDER_NEXT_COLOR=fg=colour31,bg=colour233,nobold,noitalics,nounderscore
_POWERLINE_WINDOW_DIVIDER_COLOR=fg=colour240,bg=colour233,nobold,noitalics,nounderscore
_POWERLINE_WINDOW_NAME_COLOR=fg=colour231,bg=colour31,bold,noitalics,nounderscore
_POWERLINE_WINDOW_STATUS_COLOR=fg=colour249,bg=colour233,nobold,noitalics,nounderscore
_POWERLINE_WINDOW_STATUS_FG=colour249
```
```
env | grep powerline
POWERLINE_COMMAND=powerline
POWERLINE_CONFIG_COMMAND=powerline-config
```
```
.tmux.conf
unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g default-terminal "screen-256color"

set -g status-bg blue
set -g status-fg white

# border colors
# set -g pane-border-fg magenta
set -g pane-active-border-fg blue
set -g pane-active-border-bg default

# powerline fonts
source /usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf
```

**Comment by ZyX-I** [comment]
@jhwhite And what about `tmux show-options | grep status-right`? Also

1. Is error fixed if you define `$POWERLINE_COMMAND_ARGS` to an empty string (`tmux set-environment -g POWERLINE_COMMAND_ARGS ""`)?
2. Can you see the error by running

        env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=`tmux display -p "#D"`

    (basically what powerline actually runs, since 2.0 release). (Note: run from inside tmux using whatever shell tmux uses.)
3. Is this error present if you run

        mkdir /tmp/nonexistent-directory
        cd /tmp/nonexistent-directory
        tmux -S /tmp/nonexistent-filename -v -f /usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf new-session 'bash --norc --noprofile -i'`

    ? This will check whether problem is in your tmux configuration. Note: you do *not* need to close tmux in this case, `-S /tmp/nonexistent-filename` is there to be sure that new tmux server will run.
4. If it is, check the same with `env -i TERM="$TERM" PATH='/usr/bin:/usr/local/bin'` before `tmux` command (this will run tmux with almost empty environment, except for $TERM and $PATH; $PATH should include path where powerline executables are located and path where tmux executable is located, this may be not /usr/bin and /usr/local/bin). This should check whether problem is in environment variables.
5. If it still is add the following variables to the `env` call:

        POWERLINE_CONFIG_PATHS=/usr/local/lib/python2.7/site-packages/powerline/config_files
        POWERLINE_THEME_OVERRIDES='default.segments.right=[{"function":"powerline.segments.common.wthr.weather", >>>PUT THE CONFIGURATION OF THE WEATHER SEGMENT HERE<<<}]'

    (note: POWERLINE_THEME_OVERRIDES variable must contain valid JSON after equal sign. JSON does not allow trailing comma, so if you do not have any configuration besides `"function"` key you must remove it.)

    (note: you must use 2.0 release for this to work as expected.)

    (by the way, I forgot to ask you how your tmux theme looks like: default theme does not have weather segment). This will check whether problem is in some your configuration, but *not* in your additions to weather segment.
6. What does `python -c 'import powerline; print(powerline.__file__)'` report? And how did you install powerline (and what is its version)?
7. After steps 2, 3, 4 and 5 some logs should be left by tmux in `/tmp/nonexistent-directory`. I do not think they will give me a clue, but who knows.

**Comment by rmartinho** [comment]
I had this issue and traced it back to here: https://github.com/powerline/powerline/blob/develop/powerline/segments/common/wthr.py#L147. One of these indexing operations returns a `None`, and then a `TypeError` is thrown (there is an `except` for `KeyError` and `ValueError`, but indexing `NoneType` doesn't throw those).
