### ISSUE TITLE
Powerline causes flickering in vim.

### ISSUE THREAD

**Issue by person808** [powerline/powerline#1281]
After opening a file with vim I can scroll flicker-free. When I open another file, or even another buffer like Unite, vim starts to flicker when switching files and scrolling. Repeated switching makes the flickering worse. Sometimes, I can't even see text until I stop scrolling.

```
vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 14 2015 20:16:36)
Included patches: 1-580
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             -ebcdic          +localmap        +printer         +title
+arabic          +emacs_tags      +lua             +profile         +toolbar
+autocmd         +eval            +menu            +python          +user_commands
+balloon_eval    +ex_extra        +mksession       -python3         +vertsplit
+browse          +extra_search    +modify_fname    +quickfix        +virtualedit
++builtin_terms  +farsi           +mouse           +reltime         +visual
+byte_offset     +file_in_path    +mouseshape      +rightleft       +visualextra
+cindent         +find_in_path    +mouse_dec       +ruby            +viminfo
+clientserver    +float           +mouse_gpm       +scrollbind      +vreplace
+clipboard       +folding         -mouse_jsbterm   +signs           +wildignore
+cmdline_compl   -footer          +mouse_netterm   +smartindent     +wildmenu
+cmdline_hist    +fork()          +mouse_sgr       -sniff           +windows
+cmdline_info    +gettext         -mouse_sysmouse  +startuptime     +writebackup
+comments        -hangul_input    +mouse_urxvt     +statusline      +X11
+conceal         +iconv           +mouse_xterm     -sun_workshop    -xfontset
+cryptv          +insert_expand   +multi_byte      +syntax          +xim
+cscope          +jumplist        +multi_lang      +tag_binary      +xsmp_interact
+cursorbind      +keymap          -mzscheme        +tag_old_static  +xterm_clipboard
+cursorshape     +langmap         +netbeans_intg   -tag_any_white   -xterm_save
+dialog_con_gui  +libcall         +path_extra      -tcl             -xpm
+diff            +linebreak       +perl            +terminfo
+digraphs        +lispindent      +persistent_undo +termresponse
+dnd             +listcmds        +postscript      +textobjects
```

Terminal is gnome terminal.

**Comment by ZyX-I** [comment]
What is your configuration? Are some of those files version-controlled?

You can use profiling to get the results:

    vim --cmd 'let g:powerline_pyeval="powerline#debug#profile_pyeval"' \
        --cmd 'set rtp+=/path/to/powerline/repository/powerline/bindings/vim' \
        {other arguments if needed}

. After doing some splitting and experiencing performance issues for some time do `:WriteProfiling /tmp/profile` and post the written file here (make sure not to have any passwords in your powerline configuration, like password for `email_imap_alert` segment, I am not sure they are not saved).

Possibly related: #1280.

**Comment by person808** [comment]
> What is your configuration?

I am using the default powerline configuration for vim.

I also made a minimal .vimrc:
```
call plug#begin('~/.vim/plugged')                                                                   
Plug 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
Plug 'w0ng/vim-hybrid'
call plug#end()

set nocp
set shell=bash
set cursorline
set laststatus=2
set showtabline=2
set t_Co=256
let g:hybrid_use_Xresources = 1
colorscheme hybrid
let mapleader=","
nnoremap <Leader>l :bnext<CR>
nnoremap <Leader>h :bprevious<CR>
```
Note: The flickering is less severe compared to my full .vimrc, but I can still get the bottom quarter of the buffer to flicker. At one point I scrolled down to the bottom a file and held `j` and powerline began flickering by itself.

> Are some of those files version-controlled?

If you mean the files I opened, I was able to reproduce the issue regardless of if the files were in a repo.

/tmp/profile
http://hastebin.com/yuxizebiki.md

**Comment by person808** [comment]
Problem also occurs in vim with `+python3`

**Comment by ZyX-I** [comment]
> /tmp/profile
> http://hastebin.com/yuxizebiki.md

Unknown domain. Also note that `/tmp/profile` is a *binary* file. I do not think pastebin variations are right way to post it, not unless you use `base64` encoding or the like.

**Comment by person808** [comment]
Would a Google Drive link be better?

https://drive.google.com/open?id=0B16rp5cev5IDVVRXVlVsb2E5dWc&authuser=0

**Comment by ZyX-I** [comment]
> I also made a minimal .vimrc:

I am wondering does this mean that colorscheme is relevant? (I.e. removing it resolves the issue?)

---

I was able to download and use profile file, but cannot seem to find anything bad there so far.

**Comment by ZyX-I** [comment]
I guess I need to make it possible to start profiling at some point, not from the very begginning.

You said that problems start after you open another buffer. How much time did you spend with problems compared to time without problems when preparing profiling? Does setting `showtabline=1` fix it?

Also note that powerline with profiling enabled is a wrong way to determine minimal vimrc (in case you did it this way, I do not know): enabled profiling is causing performance degradation on its own.

**Comment by ZyX-I** [comment]
Oh, no, I do see something unusual: you have too much calls to `get_segments`/`process_segments`. I am wondering if problem is still present if you do

    let g:powerline_config_overrides={'common': {'reload_config': 0}}

**Comment by person808** [comment]
> I am wondering does this mean that colorscheme is relevant? 

No, the colorscheme does not matter. Removing it did not affect the flickering.

> `let g:powerline_config_overrides={'common': {'reload_config': 0}}`

Adding that to my regular .vimrc did not help with the flickering but setting `showtabline=1` did solve my problem.

**Comment by kubahorak** [comment]
I have the same problem. Setting `showtabline=1` solved the flickering.

**Comment by tomphp** [comment]
I have the same thing, showtabline=1 fixes it, but crazy flickering with showtabline=2.

An interesting point though, there's no flickering if I run it inside of tmux.

**Comment by 0xFN89** [comment]
I am facing this issue of vim flickering after using powerline. Although gvim is out of this problem , the oringinal vim inside terminal is flickering. I used `showtabline=1 ` but it was useless. It is kind of frustrating .

**Comment by 0xFN89** [comment]
I solved it. I had set lines and columns to 999 and since I was opening vim inside a tmux pane of 80x24 it was not possible so I just removed the line `set lines=999 columns=999` and everything is sane now. VIM is working flawlessly.
