### ISSUE TITLE
vim broken after January  5th

### ISSUE THREAD

**Issue by zuloo** [powerline/powerline#1282]
Hi, I installed dev on January 5th to my laptop, when I installed dev today vim support was broken, the powerline looks very bad..

can you create a realease at fb652d5126534f4a881473b9af5ad8db6b62dc53, that is the last good state I found - I did not really try others, but that works great for me....

Best regards
Jan

**Comment by ZyX-I** [comment]
Most likely you have not updated your configuration. “Vim support was broken, the powerline looks very bad” is not descriptive. I am not supporting 1.x any longer, changes between 2.x and 1.x are not that large.
