### ISSUE TITLE
Shell and VIM broken since update

### ISSUE THREAD

**Issue by MarcoDeBortoli** [powerline/powerline#1286]
Hi everyone,

as per subject I'm having issues since my last update, neither the shell prompt or the vim status line are currently working. I tried also a clean reinstall but it didn't help.

Following are errors and the relative configurations that are causing them. I'm running on OSX Yosemite latest version and using iTerm.

Any help or hint about how to solve/debug this it will be very appreciated. Also, if you need any further details please let me know.

#####  Shell
```fish
Last login: Mon Jan 26 16:56:45 on ttys002
/usr/local/lib/python2.7/site-packages/powerline/bindings/fish/powerline-setup.fish (line 79): 		_powerline_bind_mode
                                                                                                               ^
in function 'powerline-setup',
	called on line 40 of file '/Users/marco.debortoli/.config/fish/config.fish',

in . (source) call of file '/Users/marco.debortoli/.config/fish/config.fish',
	called on standard input,
```
```fish
# Powerline
set -gx fish_function_path $fish_function_path "/usr/local/lib/python2.7/site-packages/powerline/bindings/fish"
powerline-setup
```
##### vim
```fish
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/site.py", line 75, in <module>
    __boot()
  File "/usr/local/lib/python2.7/site-packages/site.py", line 3, in __boot
    import os
ImportError: No module named os
```
```fish
"""""""""""""""""""""""""""""""""""""""
" Powerline setup
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
let g:Powerline_symbols = 'unicode'
```

**Comment by ZyX-I** [comment]
Error in `site.py` has nothing to do with Powerline, you have some problems in your setup. `site.py` is imported during initialising of Python interpreter and not by powerline.

**Comment by ZyX-I** [comment]
Also note that this line:

> let g:Powerline_symbols = 'unicode'

has nothing to do with powerline. It could earlier be used to configure vim-powerline, but it is of no use now: to only use unicode symbols you need to set in `~/.config/powerline/config.json` `ext/vim/top_theme` key to `unicode` (e.g. `echo '{"ext":{"vim":{"top_theme":"unicode"}}}' > ~/.config/powerline/config.json`) or have the equivalent override.

**Comment by ZyX-I** [comment]
First issue is easily fixable. Am I right that it does not prevent you from using fish bindings? Fish tests pass even with this problem.

**Comment by ZyX-I** [comment]
About the second: check out

    vim -u NONE -i NONE -c 'python import os'

. Failing this should prove that powerline is not involved because you run with no configuration. I only know two sure ways to get this problem though:

1. Remove `os.py` from where it lives (normally under something like `/usr/lib64/python2.7/os.py`, you should have `/usr/local/lib` in the beginning I guess).
2. Modify `sys.path` in `site.py` so that `os.py` is no longer in `sys.path`.

**Comment by ZyX-I** [comment]
> as per subject I'm having issues since my last update, neither the shell prompt or the vim status line are currently working. I tried also a clean reinstall but it didn't help.

Does just running `python` from shell work? The error you referenced first should not make shell prompt not work. The error referenced second indicates problems with your Python setup.

**Comment by MarcoDeBortoli** [comment]
Yes I think it does:
```bash
debo ~ python --version
Python 2.7.9
debo ~
```
Python has been installed using brew.

As per the VIM command you are right, it fails regardless. I take it as a coincidence then although my personal laptop still works without problem but it uses a very old version of powerline as well as this one I'm writing from did before the update.

So you are telling me that if I upgrade again to the latest dev version the first problem will go away?

**Comment by ZyX-I** [comment]
`python --version` is of no use for testing whether python works. If you `strace` it (if there is `strace` on OS X) you will see that it is importing nothing. You should check whether `python` works as I said, not `python --version`.

**Comment by ZyX-I** [comment]
@MarcoDeBortoli You need to do something with your Python installation. Powerline is not ever importing `site.py`, it is being imported during interpreter initialisation which is long before powerline can interfere.

**Comment by MarcoDeBortoli** [comment]
@ZyX-I I was actually talking about this c606db7

**Comment by MarcoDeBortoli** [comment]
@ZyX-I ok everything seem to work fine on my personal laptop with the latest dev build and with the new base configurations. I think something went wrong during the brew python update on the other machine.

**Comment by MarcoDeBortoli** [comment]
@ZyX-I just for the record what created the problem was the fact I removed older versions of python and likely macvim installed via brew carried some dependencies with it. In order to solve the issue I needed to run the following:

```bash
$ brew unlink python
$ brew uninstall --force macvim
$ brew install macvim --with-lua --with-luajit --override-system-vim
$ brew link python
```

I hope it helps in case someone has the same issue.
