### ISSUE TITLE
Battery segment doesn't work with dual-battery laptops.

### ISSUE THREAD

**Issue by pcchou** [powerline/powerline#1288]
My laptop is Lenovo Thinkpad X240, and it got two batteries, which is `battery_BAT0` and `battery_BAT1` in UPower.
The battery segment of powerline display only the percentage of `battery_BAT0`, where it should be something like:
(`percentage of BAT0` * `capacity of BAT0` + `percentage of BAT1` * `capacity of BAT1`) / ( `capacity of BAT0` + `capacity of BAT1` )

**Comment by mynameisfiber** [comment]
This seems to have been reverted and also not addressed in the dbus+upower battery mechanism
