### ISSUE TITLE
Question: Is it possible to colorize segments?

### ISSUE THREAD

**Issue by frdmn** [powerline/powerline#1293]
When I use the default configuration ([pastebin](http://pastebin.com/dH9CKXAQ)) for tmux, my right segment group looks like this:

![bildschirmfoto 2015-02-01 um 18 56 32](https://cloud.githubusercontent.com/assets/944459/5993072/2449fb4e-aa44-11e4-9dfb-835f379aa743.png)

When I now change adjust the configuration ([pastebin](http://pastebin.com/8S9aYH8Z)) to add new ones or get rid of uninteresting segments, it will look like this:

![bildschirmfoto 2015-02-01 um 18 58 31](https://cloud.githubusercontent.com/assets/944459/5993080/57451bfa-aa44-11e4-8056-5d718a49173f.png)

My question is: where do you configure the color options of the segments? As you can see in the default configuration they have different backgrounds. But whenever i add some new ones (which were not in there before), they all have black background. Is there any way to change this?

**Comment by ZyX-I** [comment]
https://powerline.readthedocs.org/en/master/configuration/reference.html#colorschemes to customize colors and https://powerline.readthedocs.org/en/master/configuration/reference.html#color-definitions if predefined color set is not enough.

And questions go to https://groups.google.com/forum/#!forum/powerline-support, not here.
