### ISSUE TITLE
Python error "AttributeError: 'NoneType' object has no attribute 'startswith'"

### ISSUE THREAD

**Issue by michelalbers** [powerline/powerline#1294]
When trying to start powerline inside a zsh shell in tmux, I get the following error:

```AttributeError: 'NoneType' object has no attribute 'startswith'```

The related code inside main.py:
```python
    def write_output(args, powerline, segment_info, write, encoding):
    	if args.renderer_arg:
    		segment_info.update(args.renderer_arg)
    	if args.side.startswith('above'):
    	       for line in powerline.render_above_lines(
    		width=args.width,
    		segment_info=segment_info,
    		mode=segment_info.get('mode', None),
    	       ):
    		write(line.encode(encoding, 'replace'))
    		write(b'\n')
    	       args.side = args.side[len('above'):]
    
    	if args.side:
    		rendered = powerline.render(
    			width=args.width,
    			side=args.side,
    			segment_info=segment_info,
    			mode=segment_info.get('mode', None),
    		)
    		write(rendered.encode(encoding, 'replace'))
```

I guess args.side is just undefined. 

Any ideas?

**Comment by ZyX-I** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On February 2, 2015 12:41:58 PM EAT, Michel Albers <notifications@github.com> wrote:
>When trying to start powerline inside a zsh shell in tmux, I get the
>following error:
>
>```AttributeError: 'NoneType' object has no attribute 'startswith'```
>
>The related code inside main.py:
>```python
>    def write_output(args, powerline, segment_info, write, encoding):
>    	if args.renderer_arg:
>    		segment_info.update(args.renderer_arg)
>    	if args.side.startswith('above'):
>    	       for line in powerline.render_above_lines(
>    		width=args.width,
>    		segment_info=segment_info,
>    		mode=segment_info.get('mode', None),
>    	       ):
>    		write(line.encode(encoding, 'replace'))
>    		write(b'\n')
>    	       args.side = args.side[len('above'):]
>
>    	if args.side:
>    		rendered = powerline.render(
>    			width=args.width,
>    			side=args.side,
>    			segment_info=segment_info,
>    			mode=segment_info.get('mode', None),
>    		)
>    		write(rendered.encode(encoding, 'replace'))
>```
>
>I guess args.side is just undefined.
>
>Any ideas?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/powerline/powerline/issues/1294

You should show a traceback, not related code.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJNBAEBCgA3BQJUz4NMMBwfMDI7PjIgHTg6PjswOSAQOzU6QTA9NEA+MjhHIDxr
cC1wYXZAeWFuZGV4LnJ1PgAKCRBu+P2/AXZZIm69EACUde+K0R9N8eGkmzsQbgpY
OAzYEKSM73Ur9dcy0V82o05JVy8yfd3Szv7vJNyCj5AiD33hjTG4Yrc5ZNgPWK68
9Lf1clYrfGxDROpt9QU9xDFKZxr2jk1Vu7Ej5Ez68Z71v2slmdcn1Duk4+mfudp7
i4qZinBYYI6Mgts39lj6DNDMRML8oOCfepwbR415jA3Yli+fnSYwXb5y9fioo3kk
vrewpQv7T0LIR/cdZIldN+q5ief7XiWByakJ5LNRxaoPeYl+cama/tesRdEqsPMP
x0oXCW/Fl0aRiRzI2CPWtMcWRxKQAEZR5/JbHSbSVFWCkVvTJS38BeDG17RjMdjR
PJwfTrPzeUtoYs4PNSR7VATJT8JZVWLDrQ9KSVgFJFSF1mv9qwC3RHANnCPFPOWE
Jmc2x0qqgo1sSfKJFpS4g4TiiaQ2eQftvjiDUpcwabfHtAyF0soP36sEdIR++aMH
7oSpArycQoO+nmcMVUIJ+x9uBM63G+uFtRviVPJmSnhQK/Kjvbhc6vKGVS1iXtcs
IUFbmESibNLmN4Vr6Aw7tlMOhMDsASBWPjNsYHVI3zNXVys2cirhXuDaRVOxJvo8
7IbYWLDtKrAkc4Oa1O/PzfHvaHF3ek5ukLXsxmFQXK5vxWmzQ15tkXTeYx5ANsb4
FaW4KI2c22XLtquwnBXqfA==
=tC4+
-----END PGP SIGNATURE-----

**Comment by michelalbers** [comment]
Well allright then:

```
Traceback (most recent call last):
  File "/usr/local/bin/powerline-render", line 30, in <module>
    write_output(args, powerline, segment_info, write, get_preferred_output_encoding())
  File "/usr/local/lib/python2.7/site-packages/powerline/commands/main.py", line 156, in write_output
    if args.side.startswith('above'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by ZyX-I** [comment]
I am wondering, how do you “start powerline”. All bindings use powerline with `powerline {ext} {side} {other args…}` and this error never happens. The only thing I am willing to do with this is replacing an exception with `argparse` error message since `powerline {ext} {other args …}` format is never used in any case.

**Comment by ZyX-I** [comment]
At least the only way to get this error I know is using something like `powerline shell` (normally it should look something like `powerline shell left`).
