### ISSUE TITLE
Tmux config printed out on start

### ISSUE THREAD

**Issue by tom95** [powerline/powerline#1295]
Not sure if that's intentional or if it can somehow be suppressed, but the powerline setup for tmux is printing all the settings, basically the output of "powerline-config tmux setup".

As seen here:

![screenshot from 2015-02-03 18 32 21](https://cloud.githubusercontent.com/assets/4313751/6025501/3b943176-abd3-11e4-8eb9-19525ec50623.png)

I tried resetting my config to just sourcing of the tmux script and the daemon start, which did not cause any changes.

**Comment by ZyX-I** [comment]
This only happens once at server start up. I could’ve suppressed it by adding additional argument `-q` to `set-option` command in `powerline-base.conf` script, but this is not supported by some older tmux versions and I do not want to copy a configuration with just that change. Also the tail of your option list clearly indicates that you have version 1.8 or lower which means using compatible code (`-q` was introduced in 1.7, first supported version is 1.6).

**Comment by tom95** [comment]
Upgrading to 1.9 fixed it, thanks for the hint!
