### ISSUE TITLE
Can't see powerline docs

### ISSUE THREAD

**Issue by pdoak** [powerline/powerline#1296]
When I try and view the powerline docs at https://powerline.readthedocs.org/en/latest/ , my browser can't open the page. If I try and ping to https://powerline.readthedocs.org/en/latest/ , in terminal, it says cannot resolve.
Is it possible to give me another link to the docs please.

Many Thanks

Paul

**Comment by ZyX-I** [comment]
There is a copy of the latest *release* documentation in PyPI (i.e. https://powerline.readthedocs.org/en/master/, **not** /en/latest/). But I would highly suggest to fix your DNS (or e.g. have `nameserver 8.8.8.8` as the first line in `/etc/resolv.conf` (this is configures your system to use Google DNS)).

Other than that you can just read documentation on github (I mean, source files present in the `docs/source` folder). You can always create a local copy by doing `cd {powerline_root}/docs && make html`, then viewing `file://{powerline_root}/docs/_build/html/index.html`. Gentoo ebuilds do this for you, placing the result into `/usr/share/doc/powerline-{version}/`.

**Comment by pdoak** [comment]
Thank you. It was a problem with my DNS which I have now changed.

**Comment by pdoak** [comment]
Thank you. It was a problem with my DNS which I have now changed.

**Comment by pdoak** [comment]
Thank you. It was a problem with my DNS which I have now changed.

**Comment by pdoak** [comment]
Thank you. It was a problem with my DNS which I have now changed.
