### ISSUE TITLE
Right segments disappeared after update

### ISSUE THREAD

**Issue by burningTyger** [powerline/powerline#1298]
Today I updated powerline to the current stable version via pip. I restarted tmux and my terminal (I'm on current Arch 64). Powerline loads just fine but my right segments which had network info and weather stuff in it don't display. Have there been any changes to the config files? My old version was about 6 months old. Can't tell exactly.

**Comment by ZyX-I** [comment]
You need to run `powerline-lint` to check for the errors. But in the last six months I created a new major release with intentionally incompatible changes, including some changes in configuration files. More details in Github versions page.

**Comment by burningTyger** [comment]
@ZyX-I ok, I can see the errors now. Maybe there should be an extra section for upgraders in the docs. I will check my config files to fix it then. Thank you very muich for your great work on powerline.

**Comment by ZyX-I** [comment]
@burningTyger Basically “incompatible changes” are only some cleanup (e.g. I renamed a few keys and values (rather widespread ones), not touching configuration file structure). Needed to do this (especially changes to shell bindings) to not carry wrong choices all over the place. Though I guess I will have to create a new major release for #1287 (should not touch user at all though).
