### ISSUE TITLE
Is /themes/powerline.json override possible?

### ISSUE THREAD

**Issue by ShiroiKuma** [powerline/powerline#1302]
I've got my theme and config up-to-date with the latest style on github now. No more modifying defaults or __main__'s... however there is one last file I need to modify, but I'd like to avoid this if possible.
I'd like to override certain options in ```/theme/powerline.json``` with my own config file. DejaVu Sans Mono lacks several font glyphs. Such as U+231A [Watch].

As such I've altered my ```/theme/powerline.json``` to <pre><code>		"time": {
			"before": "◔ "
		},</code></pre>

However it'd be nice to do this globally without modifying 'core' files where possible.

**Comment by ZyX-I** [comment]
You do not need to do this globally. Configuration files from all user directories are merged recursively, so you need to place *just the override* into `~/.config/powerline/themes/powerline.json` with a proper structure (i.e. `{"segment_data": {"time": …}}`).

**Comment by ShiroiKuma** [comment]
I was just trying to avoid altering ```~/.config/powerline/themes/powerline.json``` by going via ```~/.config/powerline/config.json``` as much as possible.

**Comment by ZyX-I** [comment]
@ShiroiKuma You are not supposed to *alter* `~/.config/powerline/theme/powerline.json`. You are supposed to *create* it with the contents you want *and only* the contents you want to override. `~/.config/powerline` is no place for core files.

**Comment by ShiroiKuma** [comment]
Oh, that would make sense now. I followed the Quick Start at https://powerline.readthedocs.org/en/latest/configuration.html#quick-guide

```mkdir ~/.config/powerline```
```cp -R /path/to/powerline/config_files/* ~/.config/powerline```

And the only place ```powerline/config_files``` existed after a pip install was ```/lib/python2.7/site-packages/powerline/config_files```, so I ended up with a copy of every config file.

**Comment by ZyX-I** [comment]
@ShiroiKuma It was left from the times this was actually required (i.e. before even the first release). I think I need to update the documentation.
