### ISSUE TITLE
powerline-daemon prints usage instead of shell powerline

### ISSUE THREAD

**Issue by S0lll0s** [powerline/powerline#1306]
I installed the latest powerline version from git via `setup.py install`. Removed all old installations and config files beforehand. Now when I activate the bash or fish binding this is what I get as a prompt every time:

    usage: powerline-daemon [-h] [-r MODULE] [-w WIDTH] [--last_exit_code INT]
                        [--last_pipe_status LIST] [--jobnum INT]
                        [-c KEY.KEY=VALUE] [-t THEME.KEY.KEY=VALUE]
                        [-R KEY=VAL] [-p PATH] [--socket ADDRESS]
                        ext [{left,right,above,aboveleft}]

however `powerline shell left` prints the correct prompt.

`_powerline_local_prompt left` and `_powerline_prompt left` do the same...

Actually `powerline` is being called though; I put a little bash wrapper there and these are the arguments supplied:

`shell aboveleft --last-exit-code=1 --last-pipe-status=1 --jobnum=0 --renderer-arg=client_id=19211 --width=158 --renderer-arg=default_mode=default`

**Comment by ZyX-I** [comment]
Check out argument names in the usage message and argument names supplied. You need to restart daemon after the update: daemon is clearly using pre-2.0 arguments, bindings use post-2.0 arguments.

**Comment by ZyX-I** [comment]
I am though unsure why `_powerline_local_prompt left` and `_powerline_prompt left` print correct prompt: they should not, especially given that you have not supplied all needed arguments to these functions.

**Comment by ispass-anonymous** [comment]
I just had the same problem. Running "powerline-daemon --replace" solved the problem.

**Comment by schfan** [comment]
I just had the same problem. Running "powerline-daemon --replace" solved the problem.
