### ISSUE TITLE
Powerline fish breaks when in cloned powerline directory

### ISSUE THREAD

**Issue by cjbrowne** [powerline/powerline#1309]
When I checked out powerline from git I installed it and it looked like it didn't work, so I installed it from pip instead (latest version).  Then it still didn't look like it worked, so I gave up and changed directory to ~ ready to remove the fish config... and suddenly it worked again.

Changing back to the cloned repo directory breaks it.

See attached screenshot for what exactly happens when I move into the bad dir.

![Screenshot](https://cloud.githubusercontent.com/assets/375847/6199614/6aa8c3a8-b44f-11e4-91ea-9db5cfb977e6.png)

**Comment by ZyX-I** [comment]
How do you install it and what is in fish configuration? Also what fish version? This does not look like a powerline bug: fish is known to replace prompt with `>` if `fish_prompt` function yields something fish considers inappropriate.

**Comment by cjbrowne** [comment]
Fish version 2.0.0
Fish config:
```
set fish_function_path $fish_function_path "/opt/powerline/powerline/bindings/fish"
powerline-setup
```

**Comment by ZyX-I** [comment]
@cjbrowne How do you install it. I see two possible reasons for this behaviour: powerline breaks because it is in powerline directory and powerline breaks because displayed prompt is too long.

By the way, what is the output of `set | grep -e 'POWERLINE\|COLUMNS'`?

**Comment by ZyX-I** [comment]
fish-shell/fish-shell#767. You must update your fish to at least 2.1.0 if I am not mistaking.
