### ISSUE TITLE
Better Music Plugin

### ISSUE THREAD

**Issue by S0lll0s** [powerline/powerline#1321]
I wrote something like this last time I set up my linux environment, but it got lost in a reformat. Basically you could/should be able to split the line into subsegments:

    ▶ | Some Band  - Album | Some Title | 3:75

This could be realized rather easily parallel to the way the format string works already:

    "args": {
      "format": [
         {
            "highlighting_group": "player_symbol",
            "format": "{state_symbol}"
         },
         {
            "highlighting_group": "player_artist",
            "format": "{artist} - {album}"
         },
         {
            "highlighting_group": "player_title",
            "format": "{title}"
         },
         {
            "highlighting_group": "player_duration",
            "format": "{total}"
         }
       ]
    }

The only issue I see is the handling ofe player state and highlight groups together.

**Comment by ZyX-I** [comment]
Specifying highlight groups is not the responsibility of themes. You cannot do this for function segments without spamming powerline-lint errors. I would not do this even for text segments if initially there was a choice (when this key was added to themes there was no `name` key to use; by the way I think I can now deprecate `highlight_groups` key in themes via powerline-lint and remove in next release).

This way powerline-lint is no longer able to check colorscheme consistency without inventing a way to describe the arguments as well (I was actually going to do this some day).

If you want you may create a PR which adds arg like `bits` which accepts a list (or a list of pairs `(name, format)`) which adds a possibility to select an order, format (in pairs case) and presense of some predefined “subsegments” which have fixed highlighting described in documentation. I am not accepting a suggestion to define highlight group names in configuration.

**Comment by S0lll0s** [comment]
I don't have the motivation to get started on this atm, but expect a PR within the next two weeks or something.

**Comment by ZyX-I** [comment]
The one thing I did not think of in my concept is that “pairs” should actually be 1-tuples (name[, default format]) or 2-tuples (name, format). Maybe dictionaries, but I cannot think of something that can be a third value there which will justify dictionary presense.

**Comment by ZyX-I** [comment]
Note that I am not actually using player segment (and music players as a whole as well), so can only verify code and its functionality, but not the usability of the concept or the implementation.

**Comment by S0lll0s** [comment]
Well, I wanted this once and I want it again. And stuff like this just doesn't look very powerline-y:
![img](http://i.imgur.com/FDIZzLz.png)
