### ISSUE TITLE
Tmux line should hide stuff on the right instead of the window list

### ISSUE THREAD

**Issue by voidus** [powerline/powerline#1328]
When using tmux with a narrow terminal window, powerline will draw the uptime, load, date, etc over the list of windows on the left.

As the window list is contextual and the status information on the right is background, I feel that the stuff on the right should be hidden if there is not enough room for both.

**Comment by ZyX-I** [comment]
Left side is not powerline controlled and powerline does not know its width. I can make powerline know width of the whole window, but this is not helpful without knowing size of the adjacent window. Which of the sides will be hidden depends on tmux, powerline has no control of it.

**Comment by wernight** [comment]
Is there a way to read the length of that left side? Or detect it by cursor position, whatever way.

If not, it'd be better to expect something like 4 windows space than just show nothing when the area gets too small. Currently it results in a full black line:

![screenshot from 2015-05-19 14 27 38](https://cloud.githubusercontent.com/assets/145667/7702841/4acbe9d8-fe33-11e4-925c-5bae38dee495.png)

**Comment by wernight** [comment]
Sweet!
