### ISSUE TITLE
Leaks build environment into documentation

### ISSUE THREAD

**Issue by jcharaoui** [powerline/powerline#1329]
Building the Sphinx documentation leaks the current environment into `html/develop/extensions.html`. I can't tell if this is a problem with the way the docstrings are written or if it's an upstream (Sphinx) bug.

This issue was identified as part of the Debian [reproducible build](https://wiki.debian.org/ReproducibleBuilds) effort and was initally reported on the [Debian Bug Tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778250).

**Comment by ZyX-I** [comment]
Neither I, nor Sphinx is doing anything bad here: just I am setting the default to `os.environ` at the time class attribute is defined and Sphinx simply uses repr.

Do you know some way to check whether module is imported by Sphinx or not? It would be the best way to fix this problem and problem with importing `vim` module, though not the only one.

**Comment by jcharaoui** [comment]
I don't know if thats possible but looking at the [sphinx.ext.autodoc](http://sphinx-doc.org/ext/autodoc.html) documentation, it may be possible to pass certain options at build-time to customize the build output, and hence remove the environment strings.

**Comment by ZyX-I** [comment]
@jcharaoui Which options? I do not know any which may help.

**Comment by jcharaoui** [comment]
How about this function:
> autodoc-process-signature(app, what, name, obj, options, signature, return_annotation)
> Emitted when autodoc has formatted a signature for an object. The event handler can return a new tuple (signature, return_annotation) to change what Sphinx puts into the output.`

**Comment by jcharaoui** [comment]
Also, according to this [Stackoverflow answer](http://stackoverflow.com/questions/12082570/override-function-declaration-in-autodoc-for-sphinx/12087750#12087750), you could override the autodoc signature by writing it by hand as the first line of the docstring.

**Comment by ZyX-I** [comment]
@jcharaoui What you see is not a function.

**Comment by ZyX-I** [comment]
And `autodoc-process-signature` is useless because it was only intended for functions. I can change the way attribute in question is displayed, but the result is not even consistent with other functions in the class.

**Comment by jcharaoui** [comment]
I understand the consistency problem but do you agree that it's a small inconvenience compared to the privacy benefit and the advantage of making the docs reproducible?

**Comment by ZyX-I** [comment]
@jcharaoui No.

**Comment by ZyX-I** [comment]
This is not the only way to do this.

**Comment by jcharaoui** [comment]
Oh, well... I was just trying to help with suggestions. If you know other ways to fix the problem, that's great.
