### ISSUE TITLE
powerline in tmux - time won't update

### ISSUE THREAD

**Issue by jimerickson** [powerline/powerline#1330]
currently using powerline on fedora 21 in tmux-1.9a. when i open tmux the time is correct but it never updates, it just shows the time the window was opened. how can i resolve this?

**Comment by ZyX-I** [comment]
What is your tmux configuration? Are you using daemon? If yes, show its stderr (run it with `powerline-daemon --replace --foreground`). What is `tmux show-options -g | grep statusline`?

**Comment by jimerickson** [comment]
tmux show-options -g | grep statusline returns nothing
powerline-daemon --replace --foreground returns nothing

~/.tmux.conf:

set-option -g mode-mouse on
set-option -g mouse-select-pane on
set-option -g status-interval 1
set-option -g status-left "#[fg=blue]#(curl ipv6.icanhazip.com)"
set-option -g status-justify centre 
set-option -g status-left-length 45
set-option -g renumber-windows on
set-option -g status-utf8 on
set-option -g utf8 on
 
set-option -g default-terminal "screen-256color"

source "/home/jim/.local/lib/tmux/powerline.conf"

**Comment by ZyX-I** [comment]
@jimerickson It was a typo: should be `|grep status`, not `… statusline`.

> set-option -g status-left "#[fg=blue]#(curl ipv6.icanhazip.com)"

This part is useless because powerline replaces this.

> source "/home/jim/.local/lib/tmux/powerline.conf"

This part is suspicious. What is the contents of this file and how it appeared in that location?

**Comment by jimerickson** [comment]
how did it get there? i put it there. where should it be?

/home/jim/.local/lib/tmux/powerline.conf:

if-shell 'env "$POWERLINE_CONFIG_COMMAND" tmux setup' '' 'run-shell "powerline-config tmux setup"'
# vim: ft=tmux

**Comment by ZyX-I** [comment]
@jimerickson Surround listings with <code>\`\`\`</code>.

It should be where pip puts it because this way it is pip who is responsible for the update. Or where you checked out `powerline` if you use `--editable` installation. If it is not a symlink you will not get updates in ~/.local/lib/tmux.

Still what is `tmux show-options -g | grep status`? Or, better,

    tmux show-options -g \; show-options -g -w \; show-options \; show-options -w | grep status

so that I will not need to repeat the question if nothing is suspicious.

By the way, does running `powerline-config tmux setup` manually from within tmux fix the issue? (Please do this *after* checking out tmux options.)

Also: `status-interval` set to 1 is useless as well because powerline overwrites this. All status settings should go after sourcing powerline.conf and you should pray tmux does this correctly (it *loves* killing powerline-config with HUP or running it in parallel with some other config which is why I had to reduce `powerline.conf` to a single line).

**Comment by jimerickson** [comment]
tmux show-options -g | grep status
status on
status-attr none
status-bg colour233
status-fg colour231
status-interval 2
status-justify centre
status-keys emacs
status-left "#{?client_prefix,#[fg=colour254]#[bg=colour31]#[bold]#[noitalics]#[nounderscore],#[fg=colour16]#[bg=colour254]#[bold]#[noitalics]#[nounderscore]} #S #{?client_prefix,#[fg=colour31],#[fg=colour254]}#[bg=colour233]#[nobold] #(env $POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS tmux left)"
status-left-attr none
status-left-bg default
status-left-fg default
status-left-length 20
status-left-style default
status-position bottom
status-right "#(env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=`tmux display -p "#D"`)"
status-right-attr none
status-right-bg default
status-right-fg default
status-right-length 150
status-right-style default
status-style fg=colour231,bg=colour233
status-utf8 on

**Comment by ZyX-I** [comment]
@jimerickson *Do* surround listings with <code>\`\`\`</code>. It is very common that part of the code in the listing is treated as markdown highlighting.

**Comment by ZyX-I** [comment]
I do not see anything suspicious here. Does `powerline tmux right` show the correct time?

**Comment by jimerickson** [comment]
'powerline tmux right' shows the correct time in its output. i installed powerline from yum. shall i try doing it with pip?

**Comment by ZyX-I** [comment]
@jimerickson To surround listings with <code>\`\`\`</code> you need to place them on the *separate* lines. Otherwise it is inline code blocks which makes matters worse.

I do not think reinstalling powerline with pip will help. But what about

> Still what is tmux show-options -g | grep status? Or, better,
>
>     tmux show-options -g \; show-options -g -w \; show-options \; show-options -w | grep status
>
> so that I will not need to repeat the question if nothing is suspicious.

and

> By the way, does running powerline-config tmux setup manually from within tmux fix the issue? (Please do this after checking out tmux options.)

**Comment by ZyX-I** [comment]
Also: are other segments updated? By default these are uptime and system_load segments.

**Comment by jimerickson** [comment]
uptime and sytem_load are not updated either.

[code]
tmux show-options -g \; show-options -g -w \; show-options \; show-options -w | grep status
status on
status-attr none
status-bg colour233
status-fg colour231
status-interval 2
status-justify centre
status-keys emacs
status-left "#{?client_prefix,#[fg=colour254]#[bg=colour31]#[bold]#[noitalics]#[nounderscore],#[fg=colour16]#[bg=colour254]#[bold]#[noitalics]#[nounderscore]} #S #{?client_prefix,#[fg=colour31],#[fg=colour254]}#[bg=colour233]#[nobold] #(env $POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS tmux left)"
status-left-attr none
status-left-bg default
status-left-fg default
status-left-length 20
status-left-style default
status-position bottom
status-right "#(env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=`tmux display -p "#D"`)"
status-right-attr none
status-right-bg default
status-right-fg default
status-right-length 150
status-right-style default
status-style fg=colour231,bg=colour233
status-utf8 on
window-status-activity-attr none
window-status-activity-bg colour233
window-status-activity-fg colour11
window-status-activity-style fg=colour11,bg=colour233
window-status-attr none
window-status-bell-attr none
window-status-bell-bg colour233
window-status-bell-fg colour1
window-status-bell-style fg=colour1,bg=colour233
window-status-bg colour233
window-status-content-attr reverse
window-status-content-bg default
window-status-content-fg default
window-status-content-style reverse
window-status-current-attr none
window-status-current-bg default
window-status-current-fg default
window-status-current-format "#[fg=colour233,bg=colour31,nobold,noitalics,nounderscore] #[fg=colour117,bg=colour31,nobold,noitalics,nounderscore]#I  #[fg=colour231,bg=colour31,bold,noitalics,nounderscore]#W #[fg=colour31,bg=colour233,nobold,noitalics,nounderscore] "
window-status-current-style default
window-status-fg colour249
window-status-format "#[fg=colour244,bg=colour233,nobold,noitalics,nounderscore]  #I #[fg=colour240,bg=colour233,nobold,noitalics,nounderscore] #[default]#W   "
window-status-last-attr none
window-status-last-bg colour233
window-status-last-fg colour31
window-status-last-style fg=colour31,bg=colour233
window-status-separator " "
window-status-style fg=colour249,bg=colour233
[/code]

**Comment by ZyX-I** [comment]
@jimerickson Can you check out

    env -uTMUX tmux -S /tmp/nonexistent-file -f /dev/null new-session \; set-option -g status-right '#(date)' \; set-option -g status-interval 2

and see whether status line is updated each two seconds on the right? If it is not you should report the issue to tmux bug tracker.

**Comment by ZyX-I** [comment]
@jimerickson By the way, scroll to your last comment and press edit. *This* is how listings should be formatted in GH (one of the variants, others include indenting and using `<pre>…</pre>`).

**Comment by jimerickson** [comment]
will report to tmux bug tracker, thanks much!

**Comment by ZyX-I** [comment]
@jimerickson So, it is not updated even with simple `date` and no config (`-f /dev/null`), except for command-line?

**Comment by jimerickson** [comment]
no it is not, sorry to say.
