### ISSUE TITLE
"Void-variable left" with latest version (powerline-20150312.2049)

### ISSUE THREAD

**Issue by fniessen** [powerline/powerline#1333]
Hello,

I did not change anything regarding my Powerline config. Though, just after updating this morning, I now have:

    Error during redisplay: (eval (let* ((active (powerline-selected-window-active)) (mode-line (if active (quote mode-line) (quote mode-line-inactive))) (face1 (if active (quote powerline-active1) (quote powerline-inactive1))) (face2 (if active (quote powerline-active2) (quote powerline-inactive2))) (default-dictionary-face (if active (quote powerline-default-dictionary-active-face) (quote powerline-default-dictionary-inactive-face))) (other-dictionary-face (if active (quote powerline-other-dictionary-active-face) (quote powerline-other-dictionary-inactive-face))) (separator-left (intern (format "powerline-%s-%s" powerline-default-separator (car powerline-default-separator-dir)))) (separator-right (intern (format "powerline-%s-%s" powerline-default-separator (cdr powerline-default-separator-dir)))) (lhs (list (when (and (fboundp (quote vc-switches)) buffer-file-name vc-mode) (if (eq (vc-state buffer-file-name) (quote up-to-date)) (powerline-vc (quote powerline-normal-face) (quote r)) (powerline-vc (quote powerline-modified-face) (quote r)))) (when (and (not (fboundp (quote vc-switches))) buffer-file-name vc-mode) (powerline-vc face1 (quote r))) (when (and buffer-file-name vc-mode) (if (eq (vc-state buffer-file-name) (quote up-to-date)) (funcall separator-left (quote powerline-normal-face) mode-line) (funcall separator-left (quote powerline-modified-face) mode-line))) (if (not (buffer-modified-p)) (powerline-raw "%*" nil (quote l)) (powerline-raw "%*" (quote mode-line-emphasis) (quote l))) (powerline-raw mode-line-mule-info nil (quote l)) (powerline-buffer-id nil (quote l)) (when (and (boundp (quote which-func-mode)) which-func-mode) (powerline-raw which-func-format nil (quote l))) (powerline-raw " ") (funcall separator-left mode-line face1) (when (boundp (quote erc-modified-channels-object)) (powerline-raw erc-modified-channels-object face1 (quote l))) (powerline-major-mode face1 (quote l)) (powerline-process face1) (powerline-raw " " face1) (funcall separator-left face1 face2) (powerline-minor-modes face2 (quote l)) (powerline-narrow face2 (quote l)) (powerline-raw " " face2) (funcall separator-left face2 mode-line))) (rhs (list (powerline-raw global-mode-string mode-line (quote r)) (funcall separator-right mode-line face1) (powerline-raw "%l" face1 (quote l)) (powerline-raw ", " face1 (quote l)) (powerline-raw "%c" face1 (quote r)) (funcall separator-right face1 mode-line) (powerline-raw " ") (powerline-raw "%4p" nil (quote r)) (funcall separator-right mode-line face2) (powerline-buffer-size face2 (quote l)) (powerline-raw " " face2) (let ((dict (and (featurep (quote ispell)) (or ispell-local-dictionary ispell-dictionary)))) (cond (buffer-read-only (powerline-raw "%%%%  " default-dictionary-face (quote l))) ((null dict) (powerline-raw "--  " default-dictionary-face (quote l))) (t (powerline-raw (concat (substring dict 0 2) "  ") other-dictionary-face (quote l)))))))) (concat (powerline-render lhs) (powerline-fill mode-line (powerline-width rhs)) (powerline-render rhs)))) signaled (void-variable left) [5 times]

**Comment by ZyX-I** [comment]
Powerline uses semantic versioning. And it does not use lisp.

I do not know what project you are talking about, but it definitely has nothing to do with this repository.

**Comment by jiahut** [comment]
@fniessen 
yeah, I had the same issues with you. I'm considering downgrading

just open *scratch* type as follow, then `C-x C-e` 

    (require 'powerline)

**Comment by fniessen** [comment]
"zhijia,.zhang" wrote:
> @fniessen 
> yeah, I had the same issues with you. I'm considering downgrading

How do you downgrade within MELPA?

-- 
Best regards,
Fabrice
