### ISSUE TITLE
How configure to show git branch 

### ISSUE THREAD

**Issue by lipemorais** [powerline/powerline#1336]
I finded this part but I don't know what I have to do with this information.

I would like to show the virtualenv and the gemset too, if it's possible.

**Comment by ZyX-I** [comment]
You need to add branch segment and virtualenv segment to the segments list in the theme (copy it to `~/.config/powerline/themes/{ext}/*.json` from {repository root}/powerline/config_files/themes/{ext}/*.json` and strip everything, but the segments list). There currently is no segment for gemset, you should write one if you want.

And this is issue tracker and not support forum. Support forum is mailing list in google groups, mentioned in README.
