### ISSUE TITLE
Error while installing powerline via pip

### ISSUE THREAD

**Issue by aviralg** [powerline/powerline#1338]
sudo pip-2.7 install powerline                                                                                                                              

Downloading/unpacking powerline
  Downloading powerline-0.2.4.tar.bz2 (61kB): 61kB downloaded
  Running setup.py egg_info for package powerline
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-root/powerline/setup.py", line 27
        zip_safe = False,
    SyntaxError: keyword argument repeated
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build-root/powerline/setup.py", line 27

    zip_safe = False,

SyntaxError: keyword argument repeated

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-root/powerline
Storing complete log in /home/aviral/.pip/pip.log

**Comment by ZyX-I** [comment]
Powerline does not have version 0.2.4. Most likely you are installing powerline package which has nothing to do with this repository. Correct pypi name is written in the documentation.
