### ISSUE TITLE
Support tmux zoom status

### ISSUE THREAD

**Issue by nemith** [powerline/powerline#1339]
When zoomining a pane there should be some notification that we are zoomed in int he status bar. 

http://blog.sanctum.geek.nz/zooming-tmux-panes/

**Comment by darvelo** [comment]
I tried a simple hack for this, putting the `#F` flag into `bindings/tmux/powerline-base.conf` like so:

```tmux
set -g window-status-format "#[$_POWERLINE_WINDOW_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER_SPACES#I#F #[$_POWERLINE_WINDOW_DIVIDER_COLOR]$_POWERLINE_LEFT_SOFT_DIVIDER#[default]#W $_POWERLINE_LEFT_HARD_DIVIDER_SPACES"
set -g window-status-current-format "#[$_POWERLINE_WINDOW_CURRENT_HARD_DIVIDER_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER#[$_POWERLINE_WINDOW_CURRENT_COLOR]#I#F $_POWERLINE_LEFT_SOFT_DIVIDER#[$_POWERLINE_WINDOW_NAME_COLOR]#W #[$_POWERLINE_WINDOW_CURRENT_HARD_DIVIDER_NEXT_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER"
```

but unfortunately it didn't work. I've tried to put those two lines into my tmux config file, but I haven't yet found a way to get access to those powerline environment variables. Any help is appreciated.

**Comment by mhweaver** [comment]
It looks like someone recently took care of this: https://github.com/powerline/powerline/pull/1436
