### ISSUE TITLE
Where are the fonts?

### ISSUE THREAD

**Issue by davidbarratt** [powerline/powerline#1346]
In the docs
https://github.com/powerline/powerline/blob/develop/docs/source/installation/osx.rst#fonts-installation
it says "Install downloaded patched font by double-clicking the font file in Finder"

What folder would this be in?

**Comment by ZyX-I** [comment]
Link to the repository is in https://powerline.readthedocs.org/en/latest/installation.html#fonts-installation. I would also highly suggest not to use github for viewing documentation: it is not using sphinx to compile it and some files are missing critical pieces.

**Comment by ZyX-I** [comment]
It is downloaded. It will be in whatever folder you downloaded it. Marking as `s:not a bug` because I do not want to repeat information from top-level installation documentation.
