### ISSUE TITLE
Unicode comparison warining

### ISSUE THREAD

**Issue by sandnon** [powerline/powerline#1347]
I installed powerline with [ctrlspace](https://github.com/szw/vim-ctrlspace) in vim. When I open the ctrlspace window, I got a warning said
```python
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
```

You may fix it easily by modifying the code at [line 244](https://github.com/powerline/powerline/blob/develop/powerline/vim.py#L244) of vim.py
```diff
- if window.options['statusline'] != statusline:
+ if type(window.options['statusline']) != type(statusline) or window.options['statusline'] != statusline:
```

**Comment by ZyX-I** [comment]
@sandnon First part of this check will always be false then: `window.options[string_option]` returns bytes object *always*, `statusline` is unicode object *always*. Thus types will be never equal.

**Comment by ZyX-I** [comment]
And, given that `bytes` object can no longer be compared with `str` object in Python 3 like it used in Python 2 (always returns `False`) this is an always false comparison on Python 3. Guess this may cost some additional redraws.

**Comment by sandnon** [comment]
How about the modification below
```diff
- if window.options['statusline'] != statusline:
+ if window.options['statusline'] != statusline.encode('utf-8'):
```
I  tested it in python 2.7 and it works well. However, my vim does not compile with python3 so that I cannot test it. 
But as you said, `window.options[string_option]` always returns bytes object, I think the code may work.

**Comment by ZyX-I** [comment]
@sandnon I prefer to generate `statusline` correctly in first place rather then have one or two recodings (two: when you assign an option because values are unequal it is encoded according to `&encoding`).
