### ISSUE TITLE
More themes for vim

### ISSUE THREAD

**Issue by justrajdeep** [powerline/powerline#1349]
Hi 
i use powerline for gvim. I see there are a limited number of themes. Any other repo where I can get more themes for powerline?

Thanks in advance.

**Comment by ZyX-I** [comment]
If such a repository exists I don’t know it. And this is not question for an issue tracker.

**Comment by justrajdeep** [comment]
sorry for opening it as a question.

**Comment by ZyX-I** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On April 22, 2015 12:39:05 PM EAT, justrajdeep <notifications@github.com> wrote:
>sorry for opening it as a question.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/powerline/powerline/issues/1349#issuecomment-95099434

There is a mailing list for questions. I do not think you will get a useful reply there.

Though maybe someone will provide a link to his own theme. I personally have only a theme with one additional segment, but this theme is in private repository.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJNBAEBCgA3BQJVN7YrMBwfMDI7PjIgHTg6PjswOSAQOzU6QTA9NEA+MjhHIDxr
cC1wYXZAeWFuZGV4LnJ1PgAKCRBu+P2/AXZZIhUUEACRCHLjQUTd/xIiUkgbsQxo
YB2doVmbYLqsCs6KK/j8MDqf6rH6ghvpaiPdXKV/Z6PuSea4ZV04L+g0A0SIMe5N
iqW2umgXBjkJzOXfJHew5qngvNiicNdZpleN7kBIJybcuu1/hm47xisxp2rS0dLy
n0lJXPDIexj9hya7RuGAD4IDHx2LIW+PyZ/QUzr9boJ934ANP4OyZqv5TqATyW53
d6FhCD0odF+w4WHOdjrudGBZSc2YcmKmB+U94mi2Y7wtforYC3nWq+SlPJoD0Eal
gksUwnUnIxzGqS0AvwwORxyxloiLrFR5rO3fQQZuR++ruTaHIr1YRk8rpE7lnBVB
/T/vLXeVwJAYTOWngio3gneYK0I3tiXESamkCjsqNQygAdwJFe3cOistL8ptQPfF
QCfLSnn44wBx+7v9LVIiGrTOLg8tLMvSPnq8GAjACT9JO3NSAosHIfHwd000Ljc1
EEBtK8607TaBT+v/YpnKHK8n04B9Zix8L2Sl1p1d06qyKQ6PWBw8e4Bc/tHuVNfi
GWS5sKXUL7GmmR8hObLL/8jEnD9CR0ezSl+PXUQCIAorNSF/60VREs0u+T1A/rcS
LWLGWyKHgFZgEe6DSSQafxtb9h7qgdyHwltlxkhXH6/XlmqZUtyUzR7hPvX0YObs
Ofe7wQ2sA8wUgPYZ5tGOYw==
=fiAw
-----END PGP SIGNATURE-----
