### ISSUE TITLE
Email-Segment mail.py displays un and pw if pc has no network

### ISSUE THREAD

**Issue by mwuehrer** [powerline/powerline#1350]
On my laptop if I have no internet connection, powerline bar throws exception, because imap connection doesn't work (of course because of no internet)

because the exception message contains un and pw in plaintext, it would be better, if the pw is replaced by some stars. 

maybe it's also possible with a simple try-catch block, to catch the exception and disable the output complete, if the system has no internet or better, check if internet, before imap-connection.

**Comment by ZyX-I** [comment]
Can you post the screenshot? (Do not forget to hide the password.)
