### ISSUE TITLE
Custom segment not showing up with powerline-daemon

### ISSUE THREAD

**Issue by jaspernbrouwer** [powerline/powerline#1352]
I'm the author of a segment for Powerline, and have run into an issue when upgrading to Powerline 2.1:

When using Bash and running the daemon, the segment won't show. I've setup a Debian box, installed Powerline, my segment and started it like this:

```bash
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1 POWERLINE_BASH_SELECT=1 . /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh
```

The interesting thing is, when I kill the daemon the segment immediately appears. Starting it again and the segment is also gone again.

I've enabled a log-file and set the log level to DEBUG, but nothing is showing that can give me a hint. The only thing that is showing is:

```txt
2015-05-02 23:28:37,515:DEBUG:shell:watcher:Trying to use inotify watcher
```

I hope you guys can give me some hint on how to proceed :)

Please see here for some more discussion: https://github.com/jaspernbrouwer/powerline-gitstatus/issues/1

**Comment by ZyX-I** [comment]
You should’ve enabled logging in your segment first before asking here. I think that the problem is

>     status, err = self.execute(['git', 'status', '--branch', '--porcelain'])

: powerline-daemon provides a way to get the current directory, but used current directory *is the current directory of the daemon*. If it does not contain git repository you will not get the output.

**Comment by jaspernbrouwer** [comment]
You're absolutely right, I blindly assumed the segment wasn't used at all. Really shows assumption is the root of all evil ;)

I'll indeed add some logging to the segment.

Thanks for the hint. I really appreciate you took some time to look into the segment!
