### ISSUE TITLE
Can't install tmux config in Fedora 21

### ISSUE THREAD

**Issue by Poorchop** [powerline/powerline#1356]
I have installed powerline locally using pip (`pip install --user powerline-status`). I have followed the instructions to edit ~/.tmux.conf properly:

```
run-shell "/home/me/.local/bin/powerline-daemon -q"
source "/home/me/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"
```

When I launched tmux however, I found that nothing was changed. I tried to manually execute the setup in powerline.conf with `.local/bin/powerline-config tmux setup`, which returned the following error:

```pytb
failed to connect to server: Connection refused
Traceback (most recent call last):
  File ".local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/home/me/.local/lib/python2.7/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/home/me/.local/lib/python2.7/site-packages/powerline/bindings/config.py", line 168, in tmux_setup
    init_tmux_environment(pl, args)
  File "/home/me/.local/lib/python2.7/site-packages/powerline/bindings/config.py", line 116, in init_tmux_environment
    set_tmux_environment(varname, powerline.renderer.hlstyle(**highlight)[2:-1])
  File "/home/me/.local/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 51, in set_tmux_environment
    run_tmux_command('set-environment', '-g', varname, value)
  File "/home/me/.local/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 32, in run_tmux_command
    _run_tmux(subprocess.check_call, args)
  File "/home/me/.local/lib/python2.7/site-packages/powerline/bindings/tmux/__init__.py", line 27, in _run_tmux
    return runner([get_tmux_executable_name()] + list(args))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'tmux', u'set-environment', u'-g', u'_POWERLINE_BACKGROUND_COLOR', u'fg=colour231,bg=colour233,nobold,noitalics,nounderscore']' returned non-zero exit status 1
```

I tried to temporarily disable my firewall to see if that was causing an issue, but I am still getting the same error message with the firewall disabled.

My tmux version is 1.9a-5.fc21.

**Comment by ZyX-I** [comment]
Duplicate of #1354.

**Comment by ZyX-I** [comment]
No, not that: it fails on `set-environment -g`, not on `set-environment -r`.

**Comment by ZyX-I** [comment]
You have “failed to connect to server: Connection refused” as a first line of the error. It means that you tried to manually execute `.local/bin/powerline-config tmux setup` from a wrong place or time (specifically: after you quit tmux or from another user).

If you want to run this manually you must run it from launched tmux with properly set $TMUX variable (should be done automatically).

**Comment by Poorchop** [comment]
Executing `.local/bin/powerline-config tmux setup` worked after running from within tmux. I assumed that tmux had to be closed first in order for the changes to take effect.

`tmux setup` does not run automatically after first launching tmux, however. It's not a huge issue since I never close tmux anyway, but it would be nicer if this process could be properly automated in case I reboot my server.

**Comment by ZyX-I** [comment]
@Poorchop If you are executing `.local/bin/…` I assume that `.local/bin` is not in `$PATH`. You must add it there (use full path obviously) or define `$POWERLINE_CONFIG_COMMAND` (and `$POWERLINE_COMMAND` because I am not sure that daemon will be properly used without this) variables that hold full path to the `powerline-config` and `powerline` executables respectively.

**Comment by Poorchop** [comment]
@ZyX-I you were right, ~/.local/bin was not in my PATH. Ensuring that the powerline binaries were in my PATH solved the issue. Now the problem is that I still can't see some glyphs even after installing some patched fonts, but that's another issue altogether.

This issue should be marked as "invalid" because it's not a bug, it was just stupidity on my part.

**Comment by ZyX-I** [comment]
@Poorchop Font patcher adds only powerline-specific glyphs in Unicode private use area. But powerline is using a number of other glyphs which are not always present in a font and fontpatcher does nothing with this. You may want to replace them by creating `~/.config/powerline/themes/powerline.json` with the following contents: take `powerline/config_files/themes/powerline.json` as a base and

1. Replace each glyph you do not see with a glyph you do.
2. Remove everything you did not modify.

If offending character is located *not* in `powerline.json` then this is a bug (there are exceptions though: offending characters in directory, branch or user name, composition attributes, etc are not powerline bugs as long as they are just displayed as another (replacement) glyph like U+FFFD REPLACEMENT CHARACTER (“used to replace an incoming character whose value is unknown or unrepresentable in Unicode”) or a sequence of glyphs (directory named `"\x80"` may be represented as `\M-^?`, this is OK) without any visual bugs).

**Comment by Poorchop** [comment]
Thank you for the instructions. It looks like only the clock emoji/glyph is missing, so that will be easy to replace.
