### ISSUE TITLE
Interval in segment does nothing

### ISSUE THREAD

**Issue by jespern** [powerline/powerline#1367]
I've written a few segments, which take a few seconds to execute, not unlike the IMAP segment.

However, I find that my segment's `"compute_state"` (I'm subclassing `KwThreadedSegment`, like the IMAP one), is being called continuously, sometimes even several times per second, and entirely ignores the `"interval"` setting.

In addition to bombarding the remote service I'm fetching data from, this also causes powerline to flicker.

Being certain that I was doing something wrong, I splashed a healthy amount of debugging onto the IMAP fetcher, and noticed the same behavior there. It connects to the remote mail server several times per second, and does not respect the `"interval"` specified on the class (60 seconds).

Am I misunderstanding how to write segments entirely, or is this a bug?

**Comment by ZyX-I** [comment]
How exactly do you try to use it? KwThreadedSegment only makes any sense if Powerline instance was created with `run_once=False` which happens in IPython, Vim and powerline-daemon (i.e. when there is long-running Python process).
