### ISSUE TITLE
[docs] Clear explanation of what's exactly {repository_root} in docs

### ISSUE THREAD

**Issue by igorsantos07** [powerline/powerline#1376]
While trying to install powerline as a bash plugin, I found trouble discovering where it was installed. The docs refer to a `{repository_root}` but there's no clear explanation on where it is. As a python newbie I had a hard time using find to discover it was installed at `/usr/local/lib/python2.7/dist-packages/powerline`.

I'm not sure how to specify it generically enough for all users in the docs to create a PR, tho.

**Comment by ZyX-I** [comment]
Except for the pip case package maintainers are supposed to move bindings to better suited location (e.g. Gentoo ebuild moves bash bindings to /usr/share/powerline/bash, though it is not as good place as /usr/share/zsh/site-contrib for zsh bindings) and document this.

I have no idea how to determine the location where pip install powerline in, but `dist-packages/powerline` is definitely *not* a pip installation. Though with pip path would not be much better. I can only suggest users to refer to package manager documentation.

Note: whenever you use any package manager including pip, but excluding `pip install --editable` variant of installation “`{repository_root}`” makes no sense and there is no convenient and uniform replacement. For `pip` it appears that you can use `pip show`, should probably update documentation with this.

**Comment by igorsantos07** [comment]
I'm a Python newbie... So I cannot discuss on `dist-packages`. The only thing I can confirm is that, indeed, I've installed the package through pip, following *exactly* the instructions in the docs. And I can confirm those are the files it's reading for settings as well.

I've just installed it in my home computer (that was my work desktop) and it happened through the exact same way. Without `sudo` it complaint about this, for instance: `error: could not create '/usr/local/lib/python2.7/dist-packages/powerline': Permission denied`.

**Comment by igorsantos07** [comment]
I can confirm that `pip show` does what you think. It tells package name, version and location (exactly the one I've reported).

**Comment by ZyX-I** [comment]
@igorsantos07 Actually I am wrong here: pip indeed installs `powerline` (it installs to `dist-packages` and `powerline` directory contains opened files, I for some reason thought it should have directory per package (package name is `powerline-status`)). `pip show` does report something like `{repository_root}`, though only files installed in setup.py are `{repository_root}/powerline`.

Without `sudo` you need to use `pip install --user`, this installs to something like ~/.local/lib64/python2.7/site-packages. Additionally you will need to have $HOME/.local/bin in $PATH.

**Comment by igorsantos07** [comment]
awesome, @ZyX-I  :)
