### ISSUE TITLE
Can't use powerline-i3

### ISSUE THREAD

**Issue by aleprovencio** [powerline/powerline#1382]
Hello!

The bar shows up with anything but a ",[" when I pipe powerline-i3 to lemonbar like this: /usr/local/lib/python2.7/dist-packages/powerline/bindings/i3/powerline-i3.py | lemonbar

When using bar-aint-recursive instead, it returns a: File "/usr/local/lib/python2.7/dist-packages/powerline/bindings/i3/powerline-i3.py", line 38, in render sys.stdout.flush() IOError: [Errno 32] Broken pipe

Testing powerline-status 2.1.4 with nothing on .config/powerline

**Comment by ZyX-I** [comment]
@aleprovencio When you don’t pipe what does it print to stdout?

**Comment by aleprovencio** [comment]
I'm sorry @ZyX-I maybe there was another instance somewhere but seems working fine by now. Thanks for trying to help.
