### ISSUE TITLE
Include configurable gradient in uptime, like it's in mail segment

### ISSUE THREAD

**Issue by igorsantos07** [powerline/powerline#1383]
Would be cool to be able to configure a gradient background for the Uptime segment, much like the Mail segment currently does. That would serve as a warning to know the computer is running for too long (or maybe a whooray?).

**Comment by ZyX-I** [comment]
I do not see why uptime should be highlighted this way. Normally long runtime should not cause any problems (except that this may mean that you have outdated kernel). You also get no benefits from long runtime after some (rather short) warmup time to fill FS caches/optimize JIT-compiled functions (JS and java VMs, especially the second one)/…

If you need this you may run a PR, but note that gradient must not be the default in any case. I would highly suggest to include an explanation into the commit message in this case: mail segment gradient means “the more unread messages you have the harder it will be to read them all and respond if needed”.
