### ISSUE TITLE
Homebrew Python 2.7.10 upgrade causing powerline to error

### ISSUE THREAD

**Issue by djbender** [powerline/powerline#1385]
after upgrading python to 2.7.10 and reinstalling powerline-status (2.1.4) from pip, i get the following error when loading up vim:

```
$ vim
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Error detected while processing /usr/local/lib/python2.7/site-packages/powerline/bindings/vim/plugin/powerline.vim:
line  157:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
Press ENTER or type command to continue
```

**Comment by sigmavirus24** [comment]
Did you reinstall pip?

**Comment by ZyX-I** [comment]
@sigmavirus24 Is not `site` module part of the Python? On my system (Gentoo) `qfile /usr/lib64/python2.7/site.py` reports `dev-lang/python (/usr/lib64/python2.7/site.py)`.

@djbender I see that this issue has nothing to do with powerline: check out `vim -u NONE -i NONE -N -c 'python import vim'`, this should fail as well, complaining about site module that cannot be loaded.

**Comment by paambaati** [comment]
@sigmavirus24 Reinstalling `pip` doesn't seem to solve the issue.

**Comment by ZyX-I** [comment]
@paambaati `vim -u NONE -i NONE -N -c 'python import vim'` throwing an exception means that this issue has absolutely nothing to do with powerline. It is better ask on vim-use (describe the result of `vim -u NONE…` call, *not* powerline output) because I do not know how to fix this.

**Comment by tjanson** [comment]
Here’s how to downgrade to 2.7.9 (for those who came here via Google as I did), which works fine with Vim (and Powerline):

```sh
brew unlink python
brew install https://raw.githubusercontent.com/Homebrew/homebrew/1681e193e4d91c9620c4901efd4458d9b6fcda8e/Library/Formula/python.rb
```

That’s the formula from [this commit](https://github.com/Homebrew/homebrew/blob/1681e193e4d91c9620c4901efd4458d9b6fcda8e/Library/Formula/python.rb), the most recent before 2.7.10. You can then switch between the two with `brew switch python <version>`.

**Comment by paambaati** [comment]
@tjanson Thanks a ton! This seems to solve the issue for now. I'd rather stick to 2.7.9 for now that deal with the vim issue.

**Comment by MarcoDeBortoli** [comment]
@tjanson @paambaati I just tried this myself and discovered that weirdly enough what breaks powerline is the absence of python 2.7.9 if you follow @tjanson advise but you keep 2.7.10 linked everything works fine too. It stops working the moment you run a `brew cleanup`.

I hope it helps.

**Comment by ZyX-I** [comment]
@MarcoDeBortoli You clearly either have Vim compiled with something 2.7.10-specific (not sure what exactly: Python libraries are named without patch portion of the version and I do not remember anything else specific) or wrong environment that somewhere still points to 2.7.9.

**Comment by MarcoDeBortoli** [comment]
@ZyX-I I surely don't. My macvim has been installed via brew ages ago as per powerline documentation.
The only purpose of my comment was to tell @paambaati that if he wants he can still use powerline and python 2.7.10.
I can make a test on another mac that I have where vim is working without problem and try to run a `brew cleanup` and see if powerline for vim stops working if that helps

**Comment by MarcoDeBortoli** [comment]
@ZyX-I I just tried and I can reproduce.

```bash
~$ brew cleanup
~$ vi anyfile
```
And this is the error generated
```bash
Error detected while processing /Users/debo/.vimrc:
line   83:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
line   84:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
line   85:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
```
which refers to the following lines
```bash
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
```
Launching the following commands solve the problem and let the user work with python 2.7.10
```bash
~$ brew unlink python
~$ brew install https://raw.githubusercontent.com/Homebrew/homebrew/1681e193e4d91c9620c4901efd4458d9b6fcda8e/Library/Formula/python.rb
~$ brew switch python 2.7.10
```
I hope that helps

**Comment by paambaati** [comment]
@MarcoDeBortoli Thanks a ton, that works!

**Comment by MarcoDeBortoli** [comment]
@paambaati you are welcome. I'm glad it helped.

**Comment by RatanRSur** [comment]
I tried @ZyX-I solution except I didn't have 2.7.10 in my cellar (instead 2.7.10_2) and I'm still getting the same module not loaded error.

Also, my problem isn't with powerline but rather vim-autoformat.

Any suggestions?

**Comment by MarcoDeBortoli** [comment]
@RatanRSur did you try my suggestion instead?

**Comment by RatanRSur** [comment]
oops, sorry, that's what I meant. I tried yours.

**Comment by MarcoDeBortoli** [comment]
@RatanRSur oh I see. Did you try to ask the vim-autoformat guys about the issue?

**Comment by ZyX-I** [comment]
@MarcoDeBortoli @RatanRSur What’s the point in asking this in an unrelated project’s bug tracker? If `:python` command does not work you should go to vim-dev.

**Comment by MarcoDeBortoli** [comment]
@ZyX-I that's exactly what I said

**Comment by ZyX-I** [comment]
@MarcoDeBortoli You suggested to ask “vim-autoformat guys” (I read this as “go to vim-autoformat project bug tracker/mailing list/etc”). I am suggesting vim-dev or vim-use mailing list.

**Comment by MarcoDeBortoli** [comment]
@ZyX-I because that's the plugin @RatanRSur seems to have problem with so I think it would be better. vim-dev will likely work too

**Comment by RatanRSur** [comment]
I did ask the autoformat guys, was linked here from there. I'll try vim then.

**Comment by rudedogg** [comment]
I was able to keep python 2.7.10 by rebuilding macvim after upgrading.

Try:
```bash
brew uninstall macvim
brew install macvim
```

**Comment by devilelephant** [comment]
Arguments about if this is the appropriate place aside, @rudedogg's fix worked for me and is probably the correct answer for this annoyance.

**Comment by rdonkin** [comment]
I had this after uninstalling Homebrew python 2.7.* (all versions) and installing latest which is 2.7.13.

The solution for me was to do `brew uninstall macvim vim` which removed the latest versions of both (8.0.x).  This left both macvim and vim at 7.4.x, and powerline now works, still using Python 2.7.13.

From `brew info vim`:
```
/usr/local/Cellar/vim/7.4.2290 
```
