### ISSUE TITLE
Gmail folder name for mail segment

### ISSUE THREAD

**Issue by CaptainQuirk** [powerline/powerline#1389]
Hi there,

Could you provide an example of a segment mail configuration example where something else than INBOX is used or a link to the folders/subfolders format used by gmail is explained ?

Thanks in advance !

**Comment by ZyX-I** [comment]
You need to check out gmail documentation if any. I am not using mail segment. I think that you may use [imaplib.IMAP4.list](https://docs.python.org/3/library/imaplib.html?highlight=imaplib#imaplib.IMAP4.list) if you do not find anything in the documentation.
