### ISSUE TITLE
Docs do not cover setup for vim

### ISSUE THREAD

**Issue by bendavis78** [powerline/powerline#1390]
I went to https://github.com/Lokaltog/vim-powerline, which says the plugin is deprecated in favor of Localtog/powerline, which redirects to powerline/powerline. This project has no information on setting up vim. The documentation only says what the prerequisites are for vim -- but what repo do I use for the actual vim plugin??

**Comment by ZyX-I** [comment]
Documentation has this in Usage/Plugins/Other plugins.
