### ISSUE TITLE
ERROR:tmux:uptime:Exception while computing segment: 'module' object has no attribute 'BOOT_TIME'

### ISSUE THREAD

**Issue by narzero** [powerline/powerline#1391]
I'm running a fresh version of OS X 10.10.3.

After installing Powerline (iTerm 2.1.1), in the bottom right corner I get the following error message:
```
ERROR:tmux:uptime:Exception while computing segment: 'module' object has no attribute 'BOOT_TIME'
```

![Screenshot](http://i.imgur.com/WPkZXp4.png)

Does this have something to do with psutil?

**Comment by ZyX-I** [comment]
Yes, it means that `psutil` module is missing BOOT_TIME attribute. You need to disable uptime segment then or find `psutil` module that has this attribute if there is such a thing.

**Comment by ZyX-I** [comment]
It appears that new psutil has `boot_time` function in place of `BOOT_TIME` attribute.

**Comment by ZyX-I** [comment]
psutil documentation states that old constants are still available, though should produce DeprecationWarning. So it is probably not your problem.

**Comment by ZyX-I** [comment]
Apparently this is only the case for psutil-2.x. psutil-3.x does not have this attribute.

**Comment by jottr** [comment]
I am seeing this error message as well, since I updated via `pip install powerline-status --upgrade`.
Before the upgrade, the `uptime`-module worked without a glitch.

```pip freeze | grep powerline
powerline-status==2.1.4
```

I understand that a fix has been merged 12 days ago, is this supposed to be inside the pip package, or should I rather install from head?

**Comment by ZyX-I** [comment]
It is currently not in release.

**Comment by ZyX-I** [comment]
Now it is in release 2.2.
