### ISSUE TITLE
powerline on ubuntu server (non-gui)

### ISSUE THREAD

**Issue by wrfc** [powerline/powerline#1392]
I installed powerline using the patched fonts as shown [on the docs page](http://powerline.readthedocs.org/en/latest/installation/linux.html), but I'm still unable to get the status line to display the proper symbols: 

![powerline](http://i.stack.imgur.com/STUcB.png)

After installing the patched fonts in  ~/.fonts, I updated the font cache, and restarted the system but I still get the same results.  I've never really worked with fonts before so I'm thinking I'm missing something in my configuration to allow the system to use the patched fonts. 

Things I've done so far:
1. Installed powerline using Vundle, uninstalled it in favor of the pip install version as mentioned above
2. Intalled patched fonts with provided install.sh script (I also copied the fonts to /usr/share
3. Updated fc-cache 
4. set the locale, and 256 color for my terminal
5. In my .vimrc file
* set rtp+=/usr/local/lib/python2.7/dist-packages/powerline/bindings/vim/
* set t_Co=256
* set laststatus=2
* set encoding=utf-8
* let g:Powerline_symbols = 'fancy' (I tried it with and without this line)

Any help or suggestions are appreciated.

**Comment by ZyX-I** [comment]
1. Setting `g:Powerline_symbols` is not going to do anything useful because it is vim-powerline setting.
2. `install.sh` and fc-cache are *installing* fonts. To use them you must configure your terminal emulator to use the patched font.

**Comment by wrfc** [comment]
dfadsf

**Comment by KumaCool** [comment]
How did you solve the problem?
No icon for non-remote access

system: ubuntu server 22.04.1
shell: fish / oh-my-fish / bobthefish

@wrfc
