### ISSUE TITLE
2.2 update stops supporting blank lines in zsh prompt

### ISSUE THREAD

**Issue by mpounsett** [powerline/powerline#1399]
In powerline 2.1 I could leave a blank line in my prompt by having an empty dictionary in the JSON configuring the shell prompt.

In the example default.json file below, 2.1 would have a blank line, followed by the line starting with the shell mode, followed by the line starting with the date.  In powerline 2.2 the empty hash at the end of the 'above' array is ignored, and no blank line is left.

``` json
{
  "segments": {
    "above": [
      {
        "left": [
          {
            "function": "powerline.segments.shell.mode"
          },
          {
            "function": "powerline.segments.common.env.user",
            "priority": 30
          },
          {
            "function": "powerline.segments.common.net.hostname",
            "priority": 10
          },
          {
            "function": "powerline.segments.shell.cwd",
            "priority": 10,
            "args": {
              "use_path_separator": "false",
                            "dir_limit_depth": 0
            }
          }
        ],
        "right": [
          {
            "function": "powerline.segments.shell.last_pipe_status",
            "priority": 10
          }
        ]
      },
      {
      }
    ],
    "left": [
      {
        "function": "powerline.segments.common.time.date",
        "priority": 10,
        "args": {
          "format": "%H:%M:%S"
        }
      },
      {
        "function": "powerline.segments.common.env.virtualenv",
        "priority": 50
      },
      {
        "function": "powerline.segments.common.vcs.branch",
        "priority": 40,
        "args": {
          "status_colors": "true"
        }
      }
    ],
    "right": [
    ]
  }
}
```

**Comment by ZyX-I** [comment]
You can have a blank line by adding a text segment with automatic width, no actual text and highlighting configured to be equal to background. Removal of empty lines was intentional (#1322).

**Comment by mpounsett** [comment]
I see no 'text' segment in the documentation.  I've tried inserting other segment types that normally return text, but configured not to (e.g. powerline.segments.common.env.environment with no environment variable specified) but that just winds up with an empty, and therefore ignored, segment.

**Comment by ZyX-I** [comment]
@mpounsett Filler segments example can be seen in Vim statusline configuration (though you are right: “text” segmets have “string” type).
