### ISSUE TITLE
powerline-config tmux fails on blank lines

### ISSUE THREAD

**Issue by TimGremalm** [powerline/powerline#1401]
Trying to setup the config-files for tmux, running:
```bash
powerline-config tmux setup
```

Get IndexError:
```python
Traceback (most recent call last):
  File "/home/user/.local/bin/powerline-config", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/user/builds/powerline/scripts/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/home/user/builds/powerline/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/home/user/builds/powerline/powerline/bindings/config.py", line 212, in tmux_setup
    source_tmux_files(pl, args, tmux_version=tmux_version, source_tmux_file=stf)
  File "/home/user/builds/powerline/powerline/bindings/config.py", line 74, in source_tmux_files
    source_tmux_file(os.path.join(TMUX_CONFIG_DIRECTORY, 'powerline-base.conf'))
  File "/home/user/builds/powerline/powerline/bindings/config.py", line 198, in source_tmux_file_nosource
    args = [args[0]] + [replace_env(arg) for arg in args[1:]]
IndexError: list index out of range
```

What's causing this is a newline in the configfile: powerline/bindings/tmux/powerline-base.conf
```bash
...
set -g window-status-current-format "#[$_POWERLINE_WINDOW_CURRENT_HARD_DIVIDER_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER

#Blank line above ^
 # Legacy status-left definition to be overwritten for tmux Versions 1.8+
...
```

I'm at
Branch: master
Commit: 03195cf93f

**Comment by ZyX-I** [comment]
This line is handled earlier in

    if line.startswith('#') or line == '\n':
    	continue

. You need to patch source with `print(repr(line))` to check what is it failing on. Note: if it is failing because you for some reason configured git to check out sources with Windows CRLF line endings then this is not a bug.

**Comment by ZyX-I** [comment]
By the way, you cannot *possibly* be on branch master *and* on this commit at the same time because *all* recent master commits start with `Release `.

**Comment by ZyX-I** [comment]
And except for release commits branch master only ever referenced

1. Blindly merged PRs to master (these ones were removed by push -f).
2. “Initial commit”.

**Comment by TimGremalm** [comment]
Yes you are correct. I accidentally had
```conf
autocrlf = true
```
in my newly copied .gitconfig.
I was wondering why your files would contain carriage return in the first place :P

And yeah, I'm in branch develop, not master. I assumed wrong.

Please close this Issue.
