### ISSUE TITLE
Issues with tmux from master.

### ISSUE THREAD

**Issue by zackp30** [powerline/powerline#1402]
Not sure if you're aware, or if it's an issue with just me, but I've had some issues with tmux's master branch and Powerline, the issue is gone when I downgrade to tmux 2.0.

The problem starts after I start tmux, this will appear in the right status bar.

![](http://i.imgur.com/r9TU0ra.png)

After a few seconds it will go back to:

![](http://i.imgur.com/GRifx6h.png)

Then, if I were to create a few more windows, say, 5, this happens:

![](http://i.imgur.com/b2hP7YM.png)

The right status bar is blank, so I create a few more windows, which causes the first image to appear in the right status bar.

`powerline-config tmux setup` does nothing to change this.

`powerline-render tmux right -R pane_id=$(tmux display -p "#D")` has everything I want, but tmux doesn't display it.

`tmux.conf`:
```
run-shell "powerline-daemon -q"
set -g mode-keys vi
set -g status-keys vi

bind-key m split-window mutt
bind-key q run-shell -b tmux-charsel
bind-key t run-shell -b tmux-task

set -g prefix C-b
bind-key a send-prefix
bind-key C-a last-window

bind-key 0 select-window -t :10

bind-key C-d detach-client -P

bind-key "#" last-window
bind-key @ switch-client -l
  
#bind-key ] paste-buffer -p
  
set -g base-index 1
  
set -g display-time 2000
  
set -s escape-time 0
  
set -g aggressive-resize on
  
set -g message-bg colour235
set -g message-fg white
  
  
  
set -g pane-border-fg '#333333'
set -g pane-active-border-fg cyan
  
set -g mode-keys vi
set -g default-terminal 'screen-256color'
set -g update-environment "REMOTE_HOSTNAME SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"
  
set-window-option -g pane-base-index 1
  
set -g history-limit 200000
  
source ~/powerline/powerline/bindings/tmux/powerline.conf
run-shell ~/.tmux/tmux-pain-control/pain_control.tmux
run-shell ~/.tmux/tmux-copycat/copycat.tmux
  
```

**Comment by ZyX-I** [comment]
> Not sure if you're aware, or if it's an issue with just me, but I've had some issues with tmux's master branch and Powerline, the issue is gone when I downgrade to tmux 2.0.

Development versions are not supported. This is not a single example of a problem with development tmux version, usually they are fixed before release.

**Comment by zackp30** [comment]
I see. Thanks!

On 4 July 2015 22:37:45 BST, Nikolai Aleksandrovich Pavlov <notifications@github.com> wrote:
>> Not sure if you're aware, or if it's an issue with just me, but I've
>had some issues with tmux's master branch and Powerline, the issue is
>gone when I downgrade to tmux 2.0.
>
>Development versions are not supported. This is not a single example of
>a problem with development tmux version, usually they are fixed before
>release.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/powerline/powerline/issues/1402#issuecomment-118556679

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zackp30** [comment]
tmux 2.1 has been released, same problem, could this be reopened? thanks!

**Comment by ZyX-I** [comment]
@zackp30 No. If this is not fixed with fixing #1470 you need to open new issue.

**Comment by ZyX-I** [comment]
Though I hope it is either something similar or can be caught in #1471 (after bot-ci compiled tmux-2.1 it should also be used for tests).

**Comment by ZyX-I** [comment]
@zackp30 #1471 is OK with new tmux in tests (except that pexpect developers have dropped python-3.2 support which fails one of the tests). Can you check?

**Comment by ZyX-I** [comment]
@zackp30  I see something like

![image](https://cloud.githubusercontent.com/assets/322097/10591659/00d56e52-76c0-11e5-8bf4-490f5e486a98.png)

with tmux-2.1, but it disappears almost immediately. No blanking up to ten windows (did not try more).

Note: the following command-line shows nearly the same thing:

    LD_LIBRARY_PATH=/home/zyx/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu TMUX= tests/bot-ci/deps/tmux/tmux-2.1/tmux -S tmux-socket -f /dev/null start-server \; set-option -g status-right '#(zsh -c "sleep 1s ; echo foo")' \; new-session

(LD_LIBRARY_PATH is needed because I use tmux executable compiled for travis). Specifically I see

![… not read](https://cloud.githubusercontent.com/assets/322097/10591883/5eaf637e-76c1-11e5-9179-80bf68b7ff26.png)

. For this reason I am *not* considering this is a bug and it would be useless to open the new issue: this sequence of steps reproduces the behaviour without using powerline. To make “few seconds” more “few” run powerline-daemon: this will render right side faster. Most likely also blanking will disappear.

**Comment by zackp30** [comment]
Ah, okay. It's rather annoying. So it's a bug in tmux? I see. Thanks!

**Comment by ZyX-I** [comment]
@zackp30 It is not a bug. Just previously, if I am not mistaking, it did not print anything in that area until `#(…)` finishes. Now it informs user that it is waiting for `#(…)` to receive its contents. But if you want to do anything with this you need to go to tmux bug tracker and not here.

**Comment by ZyX-I** [comment]
So previous variant looked like “blank space filled with powerline output”, now it looks like “some data suddenly replaced with powerline output”, which is more disturbing. Maybe there is an option for this.

**Comment by zackp30** [comment]
Ah, alright, thanks!
