### ISSUE TITLE
Powerline and »normal« statusbar of other plugins

### ISSUE THREAD

**Issue by iorek1988** [powerline/powerline#1405]
Hello,

I am using the ATplugin for LaTeX support within vim. The ATplugin generates its own statusbar at the bottom of the page with some useful hints for LaTeX. But now while loading a tex file the powerline gets somehow overwritten. It would be nice, to see them both, for example powerline above the statusbar of ATP or at the top of the editor...is there a way to manage that?

**Comment by ZyX-I** [comment]
There is only one statusline per window in Vim. This is not possible.
