### ISSUE TITLE
Using MacPorts python

### ISSUE THREAD

**Issue by joeroback** [powerline/powerline#1406]
I have MacPorts python selected. The problem with powerline is all the binaries that use python use

#!/usr/bin/python

which goes to the system python and crashes or fails to load the proper python bindings like mercurial bindings (also from MacPorts).

If I change all of the #!/usr/bin/python to

#!/usr/bin/env python

Everything works and I can use MacPorts python with MacPorts MacVim and MacPorts zsh.

**Comment by joeroback** [comment]
Basically the following scripts in bin
powerline-config
powerline-daemon
powerline-lint
powerline-render

changed #!/usr/bin/python
to #!/usr/bin/env python

**Comment by joeroback** [comment]
oh idiot is me. i was looking at powerline 2.2 but now noticed in HEAD of git this is already fixed.. sorry for the confusion

**Comment by ZyX-I** [comment]
@joeroback It was not *fixed* in the current HEAD, it was using `/usr/bin/env` *always*. It is setuptools package that changes shebangs during the installation process.

**Comment by joeroback** [comment]
weird. pip installing 2.2 setuptools replaces it with usr/bin/python, pip installing it with git URL, setuptools replaces it with the full path to /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python

weird. python is weird. thanks for the info on setuptools though. good to know.

**Comment by ZyX-I** [comment]
@joeroback Pip has nothing to do with setuptools except that it expects setup.py script accept setuptools-compatible arguments. Pip only checks out powerline and then runs setup.py with some arguments (there is actually a bit more work, but e.g. requirements.txt file that lists package dependencies is not present in powerline). The rest is done by setup.py.
