### ISSUE TITLE
Spotify segment not working

### ISSUE THREAD

**Issue by alex88** [powerline/powerline#1410]
Hi guys, I'm trying to setup the spotify segment on OSX:

```
{
  "segments": {
    "right": [
      {
        "function": "powerline.segments.common.players.spotify",
        "name": "player"
      }
    ]
  }
}
```

I've tried also `spotify_apple_script ` but in both cases the right part of the bar disappear, if I shutdown spotify or remove the segment it works again, is it something wrong in the config?

**Comment by ZyX-I** [comment]
You need to post the traceback here. Enable logging to a file in config.json and post the log here.

**Comment by alex88** [comment]
I've just set:

```
{
  "common": {
    "log_file": "~/powerlog",
    "log_level": "DEBUG"
  }
}
```

and the only thing I get after starting tmux in the log is:

```
2015-07-11 22:33:01,908:DEBUG:tmux:Using libuv-based watcher
2015-07-11 22:33:01,908:DEBUG:tmux:Using libuv-based watcher
2015-07-11 22:33:01,908:DEBUG:tmux:Failed to import pyuv
2015-07-11 22:33:01,908:DEBUG:tmux:Failed to import pyuv
2015-07-11 22:33:01,908:DEBUG:tmux:Using stat-based watcher
2015-07-11 22:33:01,908:DEBUG:tmux:Using stat-based watcher
```

**Comment by ZyX-I** [comment]
@alex88 In both cases (spotify_dbus and spotify_apple_script)? (`spotify` is an alias to either `spotify_dbus` or `spotify_apple_script`)

**Comment by ZyX-I** [comment]
@alex88 Also does running `powerline-config tmux setup` inside tmux fix the issue? And check out the output of `powerline-lint`.

**Comment by alex88** [comment]
Oh right, so, I've installed python's pyuv, now:

`spotify_dbus`:

```
2015-07-11 22:40:18,360:DEBUG:tmux:Using libuv-based watcher
2015-07-11 22:40:18,360:DEBUG:tmux:Using libuv-based watcher
```

(right segment doesn't disappear now, but still no info)

`spotify_apple_script`:

```
2015-07-11 22:41:53,286:DEBUG:tmux:Using libuv-based watcher
2015-07-11 22:41:53,286:DEBUG:tmux:Using libuv-based watcher
```

(right segment disappear).

`powerline-config tmux setup` doesn't fix anything, no output in stdout/stderr but in log (with `spotify_apple_script`:

```
2015-07-11 22:42:44,615:ERROR:tmux:battery:Failed to connect to system bus: org.freedesktop.DBus.Error.NoMemory: Not enough memory
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/powerline/segments/common/bat.py", line 22, in _get_battery
    bus = dbus.SystemBus()
  File "/usr/local/lib/python2.7/site-packages/dbus/_dbus.py", line 194, in __new__
    private=private)
  File "/usr/local/lib/python2.7/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/local/lib/python2.7/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
DBusException: org.freedesktop.DBus.Error.NoMemory: Not enough memory
2015-07-11 22:42:44,615:DEBUG:tmux:battery:Not using /sys/class/power_supply: no directory
2015-07-11 22:42:44,616:INFO:tmux:battery:Using dumb “which” which only checks for file in /usr/bin
2015-07-11 22:42:44,616:DEBUG:tmux:battery:Using pmset
```
which seems unrelated. Btw, with `spotify_dbus` nothing happens, just again those `DEBUG:tmux:Using stat-based watcher` lines.

Output of `powerline-lint`:

```
Error while checking theme (key /segments/right/list item 0/function)
found highlight groups list (player_fallback, player) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/alessandro/.config/powerline/themes/tmux/default.json", line 5, column 49:
     ... werline.segments.common.players.spotify_dbus",
                                         ^

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player_fallback not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight groups list (player_play, player) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/alessandro/.config/powerline/themes/tmux/default.json", line 5, column 49:
     ... werline.segments.common.players.spotify_dbus",
                                         ^

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player_play not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight groups list (player_pause, player) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/alessandro/.config/powerline/themes/tmux/default.json", line 5, column 49:
     ... werline.segments.common.players.spotify_dbus",
                                         ^

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player_pause not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight groups list (player_stop, player) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/alessandro/.config/powerline/themes/tmux/default.json", line 5, column 49:
     ... werline.segments.common.players.spotify_dbus",
                                         ^

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player_stop not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 4/function)
found highlight groups list (network_load_sent_gradient, network_load_recv_gradient, network_load_gradient) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/alessandro/.config/powerline/themes/tmux/default.json", line 27, column 52:
     ...  "powerline.segments.common.net.network_load",
                                         ^

Error while checking theme (key /segments/right/list item 4/function)
found highlight group network_load_sent_gradient not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 4/function)
found highlight group network_load_recv_gradient not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 4/function)
found highlight group network_load_gradient not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 5/function)
found highlight group external_ip not defined in the following colorschemes: solarized
(If not specified otherwise in documentation, highlight group for function segments
is the same as the function name.)
  in "/Users/alessandro/.config/powerline/themes/tmux/default.json", line 33, column 52:
     ...  "powerline.segments.common.net.external_ip"
                                         ^

Error while checking theme (key /segments/right/list item 6/function)
found highlight groups list (battery_full, battery_gradient, battery) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/alessandro/.config/powerline/themes/tmux/default.json", line 36, column 52:
     ...  "powerline.segments.common.bat.battery"
                                         ^

Error while checking theme (key /segments/right/list item 6/function)
found highlight group battery_full not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 6/function)
found highlight group battery_gradient not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 6/function)
found highlight group battery not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 6/function)
found highlight groups list (battery_empty, battery_gradient, battery) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/alessandro/.config/powerline/themes/tmux/default.json", line 36, column 52:
     ...  "powerline.segments.common.bat.battery"
                                         ^

Error while checking theme (key /segments/right/list item 6/function)
found highlight group battery_empty not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 6/function)
found highlight group battery_gradient not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 6/function)
found highlight group battery not defined in the following colorschemes: solarized
```

**Comment by alex88** [comment]
Anyway, just tested the applescript at https://github.com/powerline/powerline/blob/master/powerline/segments/common/players.py#L315-L335 and it's working, returning `"playing{0}+{0}Ed Sheeran{0}Lego House{0}185"`

**Comment by ZyX-I** [comment]
What is your colorscheme? If it is solarized then you need to define at least `player` highlight group.

**Comment by ZyX-I** [comment]
@alex88 It should not return `{0}`. It is placeholder for `status_delimiter` which is <code>-~`/=</code> and when testing apple script you should replace all `{0}` with this string.

**Comment by alex88** [comment]
@ZyX-I anyway, changing from apple script version to 
```
{
  "function": "powerline.segments.common.players.spotify_apple_script",
  "name": "player",
  "args": {
    "state_symbol": {
      "fallback":"Error!"
    }
  }
}
```

made at least the right segments showing (still no spotify info tho).

About the `{0}` I've just copy pasted that script into the apple's script editor to see if spotify was reporting correctly

**Comment by alex88** [comment]
My `config.json` is:

```
{
  "common": {
    "log_file": "~/tmuxlog",
    "log_level": "DEBUG"
  },
  "ext": {
        "vim": {
                "colorscheme": "default"
        }
  }
}
```

so it should be `default`

**Comment by ZyX-I** [comment]
> About the {0} I've just copy pasted that script into the apple's script editor to see if spotify was reporting correctly

If one of the characters in `status_delimiter` happened to become special for whatever reason then your test is not correct. You need to replace `{0}`.

**Comment by alex88** [comment]
Running again after running that python part in python console:

```
playing-~`/=Hands All Over-~`/=Maroon 5-~`/=Misery-~`/=216
```

**Comment by ZyX-I** [comment]
By the way, how long your statusline is and what is `status-right-length` global tmux option equal to? Maybe the result is just too lengthy.

**Comment by ZyX-I** [comment]
And `status-left-length`.

**Comment by ZyX-I** [comment]
(Better to check them all out by `tmux show-options -g | grep status`, maybe I will have some other ideas.)

**Comment by alex88** [comment]
```
status on
status-interval 2
status-justify left
status-keys emacs
status-left "#{?client_prefix,#[fg=colour254]#[bg=colour31]#[bold]#[noitalics]#[nounderscore],#[fg=colour16]#[bg=colour254]#[bold]#[noitalics]#[nounderscore]} #S #{?client_prefix,#[fg=colour31],#[fg=colour254]}#[bg=colour233]#[nobold] #(env \$POWERLINE_COMMAND \$POWERLINE_COMMAND_ARGS tmux left --width=`tmux display -p '#{client_width}'` -R width_adjust=`tmux show-options -g status-right-length | cut -d' ' -f2` -R pane_id=`tmux display -p '#D'`)"
status-left-length 20
status-left-style default
status-position bottom
status-right "#(env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=`tmux display -p "#D"` --width=`tmux display -p "#{client_width}"` -R width_adjust=`tmux show-options -g status-left-length | cut -d" " -f 2`)"
status-right-length 150
status-right-style default
status-style fg=colour231,bg=colour233
status-utf8 on
```

**Comment by alex88** [comment]
<img width="1440" alt="screen shot 2015-07-11 at 23 25 10" src="https://cloud.githubusercontent.com/assets/436888/8635478/1ca0bdb6-2824-11e5-8250-2cbb653c2635.png">

**Comment by ZyX-I** [comment]
Length should be OK, especially given that you have not specified the priority. But check out whether `tmux set-option -g status-right-length 250` will fix the issue (AFAIK `status-right-length` is not a hard limit, so it is not considered when calculating how many space may be taken, but if it happened to be hard limit in your tmux version… I cannot calculate how long statusline already is based on the image).

**Comment by alex88** [comment]
Nope, nothing changes

**Comment by ZyX-I** [comment]
Also are you using powerline-daemon and did you restart it after changing configuration?

**Comment by alex88** [comment]
oh, I'm using it but no, I haven't, I just exited and restarted tmux!

**Comment by alex88** [comment]
Damn it:

```
2015-07-11 23:33:07,827:ERROR:tmux:player:Exception while computing segment: get_player_status() got an unexpected keyword argument 'state_symbol'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/powerline/segment.py", line 173, in process_segment
    contents = segment['contents_func'](pl, segment_info)
  File "/usr/local/lib/python2.7/site-packages/powerline/segment.py", line 414, in <lambda>
    contents_func = lambda pl, segment_info: _contents_func(pl=pl, **args)
  File "/usr/local/lib/python2.7/site-packages/powerline/segments/common/players.py", line 46, in __call__
    func_stats = self.get_player_status(**kwargs)
TypeError: get_player_status() got an unexpected keyword argument 'state_symbol'
```

**Comment by ZyX-I** [comment]
@alex88 Restarting tmux is normally not needed. In case powerline bindings were updated you only need `powerline-config tmux setup` (except when there are *huge* updates). But automatic configuration reloading performed by daemon has two flaws:

1. Python modules used by powerline are not automatically reloaded on update. (Module reloading is in any case dangerous operation.)
2. New configuration files do not get automatically loaded (only changes to existing files do).
3. Sometimes changes to existing files also fail to load.

**Comment by ZyX-I** [comment]
@alex88 Because argument is named in plural form, you are using singular.

**Comment by alex88** [comment]
Wait, that wasn't the issue, it was about an incomplete `state_symbol` object in config I was trying to use, reverted an now no errors about player:

```
2015-07-11 23:34:50,811:DEBUG:tmux:Using libuv-based watcher
2015-07-11 23:34:52,769:INFO:tmux:WeatherSegment:Location returned by freegeoip is Introbio,Lombardy,IT
2015-07-11 23:34:54,188:ERROR:tmux:battery:Failed to connect to system bus: org.freedesktop.DBus.Error.NoMemory: Not enough memory
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/powerline/segments/common/bat.py", line 22, in _get_battery
    bus = dbus.SystemBus()
  File "/usr/local/lib/python2.7/site-packages/dbus/_dbus.py", line 194, in __new__
    private=private)
  File "/usr/local/lib/python2.7/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/local/lib/python2.7/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
DBusException: org.freedesktop.DBus.Error.NoMemory: Not enough memory
2015-07-11 23:34:54,189:DEBUG:tmux:battery:Not using /sys/class/power_supply: no directory
2015-07-11 23:34:54,189:INFO:tmux:battery:Using dumb “which” which only checks for file in /usr/bin
2015-07-11 23:34:54,189:DEBUG:tmux:battery:Using pmset
2015-07-11 23:34:55,432:INFO:tmux:WeatherSegment:Location returned by freegeoip is Introbio,Lombardy,IT
2015-07-11 23:34:57,245:ERROR:tmux:battery:Failed to connect to system bus: org.freedesktop.DBus.Error.NoMemory: Not enough memory
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/powerline/segments/common/bat.py", line 22, in _get_battery
    bus = dbus.SystemBus()
  File "/usr/local/lib/python2.7/site-packages/dbus/_dbus.py", line 194, in __new__
    private=private)
  File "/usr/local/lib/python2.7/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/local/lib/python2.7/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
DBusException: org.freedesktop.DBus.Error.NoMemory: Not enough memory
2015-07-11 23:34:57,246:DEBUG:tmux:battery:Not using /sys/class/power_supply: no directory
2015-07-11 23:34:57,246:INFO:tmux:battery:Using dumb “which” which only checks for file in /usr/bin
2015-07-11 23:34:57,246:DEBUG:tmux:battery:Using pmset
```

**Comment by alex88** [comment]
Anyway, I've killed daemon and on start that's the only thing I get in debug. Nothing else

**Comment by alex88** [comment]
Btw, added a log line before https://github.com/powerline/powerline/blob/2fa7c3cfc8023a927e44975514b7da4d5ac6e57e/powerline/segments/common/players.py#L346 and it's returning, so it doesn't return `None` as before conditions

**Comment by ZyX-I** [comment]
@alex88 NoMemory dbus error looks unrelated, but *very* suspicious.

What if you apply

```Patch
diff --git a/powerline/segments/common/players.py b/powerline/segments/common/players.py
index 1e03af9..e041dd4 100644
--- a/powerline/segments/common/players.py
+++ b/powerline/segments/common/players.py
@@ -336,11 +336,14 @@ class SpotifyAppleScriptPlayerSegment(PlayerSegment):
 		'''.format(status_delimiter)
 
 		spotify = asrun(pl, ascript)
+		pl.debug('Player status: {0!r}', spotify)
 		if not asrun:
 			return None
 
 		spotify_status = spotify.split(status_delimiter)
+		pl.debug('Player status, split: {0!r}', spotify_status)
 		state = _convert_state(spotify_status[0])
+		pl.debug('Player state: {0!r}', state)
 		if state == 'stop':
 			return None
 		return {
```

and restart daemon (note: to restart you only need `powerline-daemon --replace`, killing is not needed).

**Comment by alex88** [comment]
Sec, let me try

**Comment by ZyX-I** [comment]
This should add some DEBUG lines to the log.

**Comment by alex88** [comment]
```
2015-07-11 23:41:33,588:DEBUG:tmux:player:Player status: u'paused-~`/=My Head Is An Animal-~`/=Of Monsters And Men-~`/=Little Talks-~`/=267'
2015-07-11 23:41:33,589:DEBUG:tmux:player:Player status, split: [u'paused', u'My Head Is An Animal', u'Of Monsters And Men', u'Little Talks', u'267']
2015-07-11 23:41:33,589:DEBUG:tmux:player:Player state: u'pause'
```

**Comment by ZyX-I** [comment]
It looks like everything is fine. Last would be checking before the very return:

```Patch
diff --git a/powerline/segments/common/players.py b/powerline/segments/common/players.py
index 1e03af9..5161112 100644
--- a/powerline/segments/common/players.py
+++ b/powerline/segments/common/players.py
@@ -48,6 +48,7 @@ class PlayerSegment(Segment):
 			return None
 		stats.update(func_stats)
 		stats['state_symbol'] = state_symbols.get(stats['state'])
+		pl.debug('Resulting stats: {0!r}, format: {1!r}', stats, format)
 		return [{
 			'contents': format.format(**stats),
 			'highlight_groups': ['player_' + (stats['state'] or 'fallback'), 'player'],
```

**Comment by alex88** [comment]
```
2015-07-11 23:47:05,704:ERROR:tmux:player:Exception while computing segment: global name 'pl' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/powerline/segment.py", line 173, in process_segment
    contents = segment['contents_func'](pl, segment_info)
  File "/usr/local/lib/python2.7/site-packages/powerline/segment.py", line 414, in <lambda>
    contents_func = lambda pl, segment_info: _contents_func(pl=pl, **args)
  File "/usr/local/lib/python2.7/site-packages/powerline/segments/common/players.py", line 51, in __call__
    pl.debug('Resulting stats: {0!r}, format: {1!r}', stats, format)
NameError: global name 'pl' is not defined
```

**Comment by ZyX-I** [comment]
Err, use `kwargs['pl']`.

(Since I expect everything to be fine here as well, please also check the output of `powerline tmux right` and `powerline-render tmux right`.)

**Comment by alex88** [comment]
Log:

```
2015-07-11 23:48:26,971:DEBUG:tmux:player:Resulting stats: {u'album': u'My Head Is An Animal', u'title': u'Little Talks', u'artist': u'Of Monsters And Men', u'elapsed': None, u'state': u'pause', u'total': u'4:27', u'state_symbol': u'\u25ae\u25ae'}, format: u'{state_symbol} {artist} - {title} ({total})'
```

Output (picture since github mess with chars):

<img width="1440" alt="screen shot 2015-07-11 at 23 49 47" src="https://cloud.githubusercontent.com/assets/436888/8635541/8ca01e60-2827-11e5-9910-d53ea54943ea.png">

**Comment by alex88** [comment]
With `spotify_dbus` I get the `Exception while computing segment: org.freedesktop.DBus.Error.NoMemory: Not enough memory` error as well as the battery segment.

**Comment by alex88** [comment]
Font is Inconsolata for powerline, tmux config is:

```
# set window split
bind-key v split-window -h
bind-key b split-window

# Ctrl-a as prexix as in screen
set-option -g prefix C-a

# Allows for faster key repetition
set -s escape-time 0

# Allows us to use C-a a <command> to send commands to a TMUX session inside
# another TMUX session
bind-key a send-prefix

# hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key C command-prompt -p "Name of new window: " "new-window -n '%%'"

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Add powerline
run-shell "powerline-daemon -q"
source-file /usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf

set -g default-terminal "screen-256color"

if-shell "[ -f ~/.tmux.local.conf ]" 'source ~/.tmux_local.conf'
```

**Comment by ZyX-I** [comment]
You see: rendered output does contain player segment (I should’ve really started with this question). So it may be one of tmux bugs similar to one of the reported prior to this (I already got such strange error once: everything is fine in powerline, but tmux refuses to display).

Can you do the following checks:

1. Make sure that after `tmux set-option -g status-right "$(powerline-render tmux right)"` nothing is still displayed (from this point you really can go to tmux bug tracker with new `status-right` option contents because `status-right` will contain nothing powerline-specific).
2. Set option to `"$(powerline-render --config-override ext.tmux.top_theme=ascii tmux right)"` (should use only ASCII characters, except for characters inside artist and title) (check that problem is not with unicode characters).
3. Set option to `"$(powerline-render --config-override ext.tmux.top_theme=ascii --theme-override default.segments.right='[{"function":"powerline.segments.common.players.spotify_apple_script","name":"player"}]' tmux right)"` (should use only one segment for output) (check that problem is not with the number of `#[]` tmux options).
4. Set option to `"$(powerline-render --config-override ext.tmux.top_theme=ascii --theme-override default.segments.right='[{"function":"powerline.segments.common.players.spotify_apple_script","name":"player","args":{"format":"{state_symbol}"}}]' tmux right)"` (should use only one segment and also only state symbol inside the segment) (check that problem is not with the `#[]` tmux options that precede the player segment).

**Comment by ZyX-I** [comment]
I hope I have not made any mistakes when writing arguments to powerline-render. Since I have no spotify, and, especially, no Mac OS X, I have not tested anything.

**Comment by ZyX-I** [comment]
(Note: to restore automatically updating status line you need just `powerline-config tmux setup`.)

**Comment by alex88** [comment]
Just looking at the screenshot, even when right segment was there, I wasn't able to see network speed informations, also, just tested that removing spotify makes the right segment show for a second or two and disappear again.
Tested again with just `spotify_apple_script` and without network speeds, still no right segments, seems those causes problems.
Now I'm going to try yours 4 steps

**Comment by alex88** [comment]
1) Yes, nothing is shows, tried with dummy text and it's shown
2) `tmux set-option -g status-right "$(powerline-render --config-override ext.tmux.top_theme=ascii tmux right)"` renders just fine
3) Shown correctly as in the previous step
4) Shown correctly again

**Comment by ZyX-I** [comment]
@alex88 So you may add `"tmux": {"top_theme": "ascii"}` near `"vim"` to your config.json and report the problem to tmux bug tracker. Apparently it is something with unicode characters.

If you need more control copy `{powerline repository}/powerline/config_files/themes/powerline.json` to `~/.config/powerline/themes/my.json` and start replacing unicode characters inside. Use `"top_theme": "my"` in place of `"top_theme": "ascii"` in this case.

By the way, do you know how tmux actually calculates its statusline width? Also what is your tmux version?

**Comment by ZyX-I** [comment]
And, last check: what was the locale in the place from which you first started tmux?

**Comment by alex88** [comment]
About the statusline width, no idea, tmux version is 2.0.
Locale
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by ZyX-I** [comment]
@alex88 It is from where? I know that somebody start tmux from their desktop shortcuts (using something like `konsole -e tmux` (of course, equivalent for the used terminal)) which have weird environment settings.

You may check it by using `tmux show-environment -g` and searching for `LANG` and `LC_` variables in the output. (If there are none of them it is equivalent to LANG=C AFAIK.) But theoretically somebody may modify environment after server was started.

**Comment by alex88** [comment]
Anyway, I've just tested with this config:


```
      {
        "function": "powerline.segments.common.players.spotify_apple_script",
        "name": "player",
        "args": {
                "state_symbols": {
                    "fallback": "f",
                    "play":     "p",
                    "pause":    "p",
                    "stop":     "s"
                }
            }
      },
```

to remove the unicode chars from the spotify segment, but still, no right bar.

Removing the segment however, makes the right segments visible again.

**Comment by alex88** [comment]
@ZyX-I I run tmux at the end of my `.zshrc` which is started by my login shell opened from iTerm,

```
if [ "$TMUX" = "" ]; then tmux; fi
```

about `tmux show-environment -g`

```
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
LC_CTYPE=UTF-8
```

**Comment by alex88** [comment]
@ZyX-I wait, issue is the length, just tried to run the update part manually copy pasting the output of `powerline-render tmux right` and trimming some chars at the end worked

**Comment by ZyX-I** [comment]
// @alex88 I would use `exec tmux` in this case. Also note that you will not be able to use `zsh -ic '…'` for running commands using interactive mode anywhere, but inside tmux with such code. Also `[[ -z $TMUX ]]` or `! [[ $TMUX ]]` is faster in zsh (`[[` has its own parsing rules, and, though both `[[` and `[` are built-ins `[[` is normally (always?) faster for some reason).

What if you use `"format"` argument that results in less characters: e.g. `"{state_symbol} {artist:.7} - {title:.10} ({total})"`?

**Comment by ZyX-I** [comment]
(This truncates artist to 7 unicode codepoints, title to 10.)

**Comment by ZyX-I** [comment]
@alex88 BTW, check `{command to output status string} | sed 's/#\[[^]]*\]//g' | wc -c` for failing and working strings. Also check `{command to output status string} | sed 's/#\[[^]]*\]//g;s/././g' | wc -c` (first should output amount of bytes, second amount of unicode codepoints, assuming your sed does support UTF-8).

**Comment by alex88** [comment]
I've uploaded a couple screenshots to show the issue:

<img width="1440" alt="screen shot 2015-07-12 at 00 32 43" src="https://cloud.githubusercontent.com/assets/436888/8635640/d8c9bcfa-282d-11e5-9a49-f8b159ac2847.png">
<img width="1440" alt="screen shot 2015-07-12 at 00 32 59" src="https://cloud.githubusercontent.com/assets/436888/8635641/d8cad0c2-282d-11e5-8395-c807567ce226.png">
<img width="1440" alt="screen shot 2015-07-12 at 00 33 31" src="https://cloud.githubusercontent.com/assets/436888/8635642/d8cc1234-282d-11e5-9995-db9497f66a03.png">
<img width="1440" alt="screen shot 2015-07-12 at 00 33 50" src="https://cloud.githubusercontent.com/assets/436888/8635643/d8ce25d8-282d-11e5-9261-5bbc09fba51b.png">
![Uploading Screen Shot 2015-07-12 at 00.34.14.png…]()

as you can see, copy pasting full message doesn't work, removing the last part (hostname), works, writing another string works for some chars and if it gets longer makes it disappear.
Also, seems that `tmux show-options -g` truncates the right status.

Btw, now trying with that different format string and those 2 commands

**Comment by ZyX-I** [comment]
And compare result with `tmux show-option -g status-right-length` and with `tmux display -p "#{client_width}"` (in case you have only one pane this must be equivalent to `echo $COLUMNS` or `stty size | cut -d' ' -f2`).

**Comment by ZyX-I** [comment]
Note: `{command to output status string}` should be `echo -n` in case you use `echo`. `wc -c` counts NL as a character.

**Comment by ZyX-I** [comment]
And `echo -En` does not work in some other shells.

**Comment by alex88** [comment]
```
$ powerline-render tmux right | sed 's/#\[[^]]*\]//g' | wc -c
170
$ powerline-render tmux right | sed 's/#\[[^]]*\]//g;s/././g' | wc -c
126
$ tmux show-option -g status-right-length
status-right-length 550
$ tmux display -p "#{client_width}"
238
$ echo $COLUMNS
238
```

**Comment by ZyX-I** [comment]
Note: last screenshot came here as `[Uploading Screen Shot 2015-07-12 at 00.34.14.png…]()`.

**Comment by alex88** [comment]
Already reuploaded

**Comment by ZyX-I** [comment]
@alex88 There is nothing more I can do, but you can go to tmux bug tracker with

1. Failing status string.
2. Working status string.
3. Description of what you did (== truncate) to make it work.
4. All lengths (I expected 4: you did not give working ones here; or failing ones).

Also how do `powerline-render --config-override ext.tmux.top_theme=ascii tmux right` lengths compare to `powerline-render tmux right` lengths and your manually constructed working lengths?

**Comment by alex88** [comment]
About 4, you're talking about https://github.com/powerline/powerline/issues/1410#issuecomment-120665559 ? Since with ascii all worked, maybe it's because unicode is longer and so can't stay in tmux right status.

I'll open an issue there, thanks a lot!

**Comment by ZyX-I** [comment]
@alex88 With ascii it would be 6. No, I meant the string with your manual edits from https://github.com/powerline/powerline/issues/1410#issuecomment-120666387 that is working.

**Comment by alex88** [comment]
Oh it's just the full status bar, without the last part (the hostname), if I remove the hostname and its unicode char it's working, if I add back again some text it works for the first chars and if I add more it disappear again.

**Comment by ZyX-I** [comment]
@alex88 Is not the byte length of the status line with the first chars 150? I have no idea why this number was chosen by @Lokaltog, (8f055473acb1ba96374f4a2b430b00136d721e13), but 170 bytes in full powerline-render output is rather promising.

**Comment by alex88** [comment]
Seems that after 165 bytes of status the right bar disappear.
