### ISSUE TITLE
tmux line "hovers" when full-screen in OS X

### ISSUE THREAD

**Issue by OJFord** [powerline/powerline#1411]
With `tmux` running in Terminal.app, powerline hovers - by roughly it's own height - above the bottom of the screen when full screen.

The effect is not present at any non-full-screen height of Terminal while resizing.

Using OS X 10.11 (Beta) and Terminal 2.6; I can verify if also present on 10.10 later.

**Comment by ZyX-I** [comment]
Powerline does not choose where statusline is displayed. If you think it is a bug you need to go to tmux or Terminal.app bug tracker.

But I think this is normal behaviour in case Terminal.app height is not enough to display the additional line: font height has fixed width and it has no choice, but to have a blank space, it will have a blank space.
