### ISSUE TITLE
Tmux right side only visible for first 3 windows

### ISSUE THREAD

**Issue by rkennedy** [powerline/powerline#1412]
When I first start tmux, with no prior sessions, the right side of the status bar appears as normal (with uptime, time, server name, etc.). However, after I add three additional windows (for a total of four), the Powerline data changes as follows:

* If `powerline-daemon` **is** running, then the right side of the status bar changes to the first line of the powerline-daemon usage message: `usage: powerline-daemon [-h] [-r MODULE] [-w WIDTH] [--last-exit-code INT]`.
* If `powerline-daemon` **is not** running, then the right side of the status bar becomes blank.

If I kill or start powerline-daemon while inside a tmux session, the status bar will adjust to the corresponding appearance after a moment.

This is not an issue of *how many* tmux windows I have. If, after creating new windows, I switch back to one of the first three windows, the status bar goes back to normal. Switching back to window 4+, the status bar goes wrong again.

This is not an issue of the window number. If I destroy window 1 (where the status bar was correct), and then create another window, that new window will be numbered 1, but the status bar won't be correct for it. I suspect this is because the "pane ID" always increases; although window numbers get re-used, pane IDs do not.

The tmux window count applies across sessions, so if I "use up" the correctly working windows in one session, disconnect from that session, and create a new session, *all* the windows in the new session will have the wrong status bar.

Killing the tmux server (as by exiting all sessions) and restarting it makes new windows have the right status bar, but only the first three windows again.

If I run the tmux command `run-shell 'powerline tmux right'`, the output appears correct. Likewise if I run <code>env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=\`tmux display -p "#D"\`</code>, which is what's configured in *bindings/tmux/powerline-base.conf*. (In my environment, `POWERLINE_COMMAND` is simply `powerline`, and `POWERLINE_COMMAND_ARGS`.)

I'm using Powerline 2.2 installed with `pip3 install powerline-status` under Python 3.4 and Tmux 2.0.

What else can I do to investigate this problem?

**Comment by ZyX-I** [comment]
Can you set POWERLINE_COMMAND to the path to the wrapper script which saves argv, calls powerline and duplicates its output to a file? E.g. something like

```Sh
#!/bin/sh
printf 'argv:' >> /tmp/powerline-args
printf '%s\0 \0' "$@" >> /tmp/powerline-args
printf '\n' >> /tmp/powerline-args
printf 'Output for %s' "$*" >> /tmp/powerline-out
powerline "$@" 2>&1 | tee -a /tmp/powerline-out
```

and post the result here? I have no idea what this bug could be.

// Also, please enable logging using `{"common": {"log_level": "DEBUG", "log_file": "/tmp/powerline-log"}}` in `~/.config/powerline/config.json`, just in case something will appear there.

**Comment by rkennedy** [comment]
I did as you suggested, and it was illuminating. The *powerline-args* file looks like this as I create four windows and then destroy them all again:

```
argv:tmux right -R pane_id=%0 --width=265 -R width_adjust=20
argv:tmux right -R pane_id=%0 --width=265 -R width_adjust=20
argv:tmux right -R pane_id=%1 --width=265 -R width_adjust=20
argv:tmux right -R pane_id=%2 --width=265 -R width_adjust=20
argv:tmux right -R pane_id= %3 --width=265 -R width_adjust=20
argv:tmux right -R pane_id=%2 --width=265 -R width_adjust=20
argv:tmux right -R pane_id=%1 --width=265 -R width_adjust=20
argv:tmux right -R pane_id=%0 --width=265 -R width_adjust=20
```

Notice there's a space before `%3`. The contents of *powerline-out* corresponding to that %3 run are therefore not surprising:

```
Output for tmux right -R pane_id= %3 --width=265 -R width_adjust=20
usage: powerline-render [-h] [-r MODULE] [-w WIDTH] [--last-exit-code INT]
                        [--last-pipe-status LIST] [--jobnum INT]
                        [-c KEY.KEY=VALUE] [-t THEME.KEY.KEY=VALUE]
                        [-R KEY=VAL] [-p PATH] [--socket ADDRESS]
                        ext {left,right,above,aboveleft}
powerline-render: error: unrecognized arguments: %3
```

(The *powerline-log* file seems uninteresting, consisting of nothing but messages like this: `2015-07-17 17:07:56,358:DEBUG:tmux:watcher:Trying to use inotify watcher`.)

I haven't changed anything in the *bindings/tmux* directory, so the Powerline command that tmux runs is some variant of <code>... -R pane_id=\`tmux display -p "#D"\`</code>, where there's no space.

I've tried running `tmux display -p "#D"` in various contexts within a tmux session, and I couldn't observe any leading whitespace; the output was always a percent sign, a digit, and a newline, in that order.

I can't find where the space might be coming from.

**Comment by ZyX-I** [comment]
@rkennedy I have added a workaround (#1415), but I think that you should additionally report the problem to tmux bug tracker because tmux should not output space in first place.

I personally was unable to reproduce the issue.

**Comment by rkennedy** [comment]
I'll file something against tmux soon. I left one comment on your change, but it otherwise looks like a sound solution. Thanks for your help and your prompt response!
