### ISSUE TITLE
powerline-daemon usage replaces the dynamic tmux Powerline status

### ISSUE THREAD

**Issue by cviner** [powerline/powerline#1421]
This issue is analogous to issue #960, except that instead of a different ```powerline-daemon``` usage message repeatedly printing within bash, the different usage string prints within the ```tmux``` status line and the prompt often gets an additional red segment (refer to the below screenshot). The usage message is: ```usage: powerline-daemon [-h] [-r MODULE] [-w WIDTH] [--last-exit-code INT]```. Changing directories within a problematic tmux session often yields multiple: ```failed to connect to server``` errors. Detaching from such a session and attempting to re-attach, yields: ```no sessions```. It appears that this issue is causing my entire tmux server to crash.

Tmux ```powerline-daemon``` error:
![image](https://cloud.githubusercontent.com/assets/10501947/8971988/bdcd43c8-3623-11e5-897b-9e0f088b1047.png)

Initially valid tmux state for comparison (please ignore the dotted line; it is an artifact of my screenshot application):
![image](https://cloud.githubusercontent.com/assets/10501947/8972011/ea0f4134-3623-11e5-9653-ab829c32faa1.png)

I am using the current release of Powerline, installed only via pip 7.10. Every other tested aspect of the Powerline status setup is working in my configuration (bash prompt, IPython, PDB, and Vim). Tmux works with Powerline fine, except for this problem. As in issue #960, Powerline works correctly in Tmux for a while (as shown above) and only eventually has this error, at which point it never works correctly for that session.

Once the error does occur, it also seems to affect various plugins. For example, I can usually do ```prefix + X``` (shift + x) to kill my current session without detaching tmux (via the [tmux sessionist plugin](https://github.com/tmux-plugins/tmux-sessionist)). However, after this error occurs in a session, attempting to do so results in an error. I assume that this is due to the tmux server connection going down.

The directory returned by ```python -c 'import powerline; print(powerline.__file__)``` is consistent with the directory prefixes used in both my bash and tmux configurations.

-------------------
Relevant environment variables, echoed from a tmux session:

-------------------
```
$PROMPT_COMMAND
```

```
_powerline_set_prompt
history -a; 
_powerline_tmux_set_pwd
```
-------------------
```
$PS1
```
```
\[^[[0;38;5;231;48;5;31;1m\] cviner \[^[[0;38;5;31;48;5;240;22m\] \[^[[0;38;5;250;48;5;240m\]~ \[^[[0;38;5;245;48;5;240;22m\] \[^[[0;38;5;250;48;5;240m\]cytomod \[^[[0;38;5;245;48;5;240;22m\] \[^[[0;38;5;250;48;5;240m\]experiments \[^[[0;38;5;245;48;5;240;22m\] \[^[[0;38;5;252;48;5;240;1m\]linked-2015-07-29-MEME-ChIP-test \[^[[0;38;5;240;49;22m\] \[^[[0m\]
```
-------------------
```
$POWERLINE_COMMAND
```
```
powerline
```
-------------------
```type _powerline_set_prompt``` returns:
```
_powerline_set_prompt is a function
_powerline_set_prompt ()
{
    local last_exit_code=$?;
    local jobnum="$(jobs -p|wc -l)";
    PS1="$(_powerline_prompt aboveleft $last_exit_code $jobnum)";
    if test -n "$POWERLINE_SHELL_CONTINUATION$POWERLINE_BASH_CONTINUATION"; then
        PS2="$(_powerline_local_prompt left -r.bash $last_exit_code $jobnum continuation)";
    fi;
    if test -n "$POWERLINE_SHELL_SELECT$POWERLINE_BASH_SELECT"; then
        PS3="$(_powerline_local_prompt left '' $last_exit_code $jobnum select)";
    fi;
    return $last_exit_code
}
```
------------------------------------
My ```.tmux.conf``` reads:

```
#------------------------------------------
set -g @tpm_plugins '               \
  tmux-plugins/tpm                  \
  tmux-plugins/tmux-sensible        \
  tmux-plugins/tmux-logging         \
  tmux-plugins/tmux-resurrect       \
  tmux-plugins/tmux-pain-control    \
  tmux-plugins/tmux-sessionist     \
'

set -g history-limit 1000000


set -g @resurrect-save 'E'
set -g @resurrect-restore 'R'
# for vim
set -g @resurrect-strategy-vim 'session'
# for neovim
# set -g @resurrect-strategy-nvim 'session'

# mousmocil --list)" teamocile scrolling support
# From: https://gist.github.com/simme/1297707
set-option -g mouse-select-pane on
set-option -g mouse-select-window on
set-window-option -g mode-mouse on

#From: http://superuser.com/a/395273
set-window-option -g xterm-keys on

# pane movement; From: http://unix.stackexchange.com/a/14301
bind-key < command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key > command-prompt -p "send pane to:"  "join-pane -t '%%'"

# Tmux statusline Powerline config
# From: https://powerline.readthedocs.org/en/master/usage/other.html#tmux-statusline
run-shell "powerline-daemon -q"
source "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
#------------------------------------------
```

**Comment by ZyX-I** [comment]
Can you do the following:

1. Check if running `powerline-config tmux setup` in tmux fixes the issue.
2. Run `powerline-lint` and check all of the errors.
3. Check which POWERLINE_\* variables are defined in the tmux session (`env | grep '^POWERLINE_`).
4. Check whether updating to latest develop (`pip uninstall powerline-status && pip git+git://github.com/powerline/powerline` if you have non-develop version) fixes the issue. Must do `powerline-daemon --replace` before this.
5. Check whether `powerline-daemon --replace` alone fixes the issue.
6. Add a script wrapper:

    ```Shell
    #!/bin/sh
    printf "<<%s>>\n" "$@" >> /tmp/powerline-args
    powerline "$@" 2>&1 | tee -a /tmp/powerline-output
    ```

    . Usage: put this into some file (lets name it `/path/powerline-wrapper.sh`), use `chmod u+x /path/powerline-wrapper.sh` and do `tmux set-environment -g POWERLINE_COMMAND /path/powerline-wrapper.sh`.

    After doing this please show what is located in /tmp/powerline-args and /tmp/powerline-output.
7. Add `{"common": {"log_level": "DEBUG", "log_file": "/tmp/powerline-log"}}` to `~/.config/powerline/config.json` and post the logs here from `/tmp/powerline-log`. Additionally needs `powerline-daemon --replace`.

**Comment by cviner** [comment]
Thanks for this follow-up.

I have not been able to reproduce this issue recently, despite not having altered any configuration, but will do the above if and when I encounter it again.

I can say that (2) (i.e. I made sure that ```powerline-lint``` did not return any errors) and (5) don't solve the issue because I tried both of those before reporting this.

**Comment by ZyX-I** [comment]
@cviner Except for the red segment this may be another instance ofa #1412. Depends on what exactly is a reason for this behaviour.

If you are using bash then red segment is most likely the result of somebody messed up the PROMPT_COMMAND. Specifically PROMPT_COMMAND must contain `_powerline_set_prompt` as its first command run. Note: it is absolutely fine if it is *not* the first command, but previous command *does* preserve the exit status. I.e. it must be something like the following function:

```Shell
cool_prompt_command() {
    local last_exit_status=$?
    # Some other actions
    return $last_exit_status
}
```

**Comment by cviner** [comment]
That is useful information; thank you. I have noticed that I still get the red segment on one system (that for which I reported this issue on, but not on other systems I thought I had configured identically).

I will compare their PROMPT_COMMANDs.

**Comment by ZyX-I** [comment]
Theoretically this may also be background jobs counter: I saw some shell plugins that run background jobs in PROMPT_COMMAND (or it was zsh and precmd?). By default it is orange though, but your user color is also not default.

This is more likely if tmux messed up the colors: jobs counter is light yellow on darker orange background. If tmux thought that terminal emulator does not support true color then it may display this segment in the closest colors from 4-bit palette, and that does not contain flavours of orange, but does contain red color. Though it contains yellow, and this should be closer to powerline yellow variant then red.

**Comment by ZyX-I** [comment]
Last exit status segment should appear if last program exited with non-zero: e.g. run `false`.

Background jobs counter should appear e.g. when you use `echo Test | less`, then `<C-z>` to suspend the less (note: less should be configured not to exit when it has not too long input, there is such an option).

**Comment by ZyX-I** [comment]
(Last exit status should be white on red, though both colors are not in the 4-bit pallette.)
