### ISSUE TITLE
Enabling tabline (or equivalent) using Powerline in vim

### ISSUE THREAD

**Issue by fgimian** [powerline/powerline#1422]
Hey there, thanks so much for your great project :smile: 

I have read the documentation several times and it mentions tabline is enabled for vim when using powerline.  I've tried installinrg the tabline plugin for vim to no avail, any idea what I'm missing?

**Airline**: notice that you can see a list of open files at the top of the screen

![screen shot 2015-07-31 at 8 27 11 am](https://cloud.githubusercontent.com/assets/1811813/8996798/4556e084-375e-11e5-92d3-8e2a44b378cd.png)

**Powerline**: as you can see, that file list is not present in powerline

![screen shot 2015-07-31 at 8 27 36 am](https://cloud.githubusercontent.com/assets/1811813/8996802/537168ba-375e-11e5-95e5-8a35e73251b6.png)

Thanks in advance :smile: 
Fotis

**Comment by ZyX-I** [comment]
Tabline presense is controlled by Vim `showtabline` option. Powerline is not setting *any* `show*` options on its own, it is up for user to decide whether they will be shown. Note that currently tabline with buffer list has performance problems for some reason.

**Comment by fgimian** [comment]
Thanks for your reply @ZyX-I, I'll try it out tonight! :smile:
