### ISSUE TITLE
Spotify Segment list Index Out of range (Using OS X)

### ISSUE THREAD

**Issue by inet-pwnZ** [powerline/powerline#1427]
Using OS X 10.10.1 iTerm2
Spotify Version : 1.0.11.134.ga37df67b
Spotify Segment not working using 
powerline.segments.common.players.spotify and powerline.segments.common.players.spotify_apple_script
Issue : IndexError: list index out of range
Screenshot :
![Screenshot :]
(http://i.imgur.com/N8jRB7J.png)
Dedicated Code to Error line :
![Dedicated Code to Error line :]
(http://i.imgur.com/x6HzrQ9.png)
sadly im not that python savvy but i know that list index out of range has to do if some try to grab for example a [6] but it doesn't exist

**Comment by ZyX-I** [comment]
Add `print(spotify_status)` just after a line this variable is defined in and check again.

Also I would rather suggest to either run `powerline-daemon` or specify `log_file`. If you were using daemon then traceback would go to *its* stderr and not clients (here client is tmux statusline). If you specified `log_file` then traceback would go to the specified file. It needs to be specified in `~/.config/powerline/config.json`/`common` dictionary.

Also note “62:66: execution error: An error of type -10810 has occurred. (-10810)”. Most likely this line describes the cause: some error in apple script runner. But I have not Mac OS X or spotify and do not know how to debug this.

---

Also when trying the alternative use `spotify_dbus` and `spotify_apple_script`. *Not* `spotify` and something else: depending on the environment `spotify` will be the shortcut to either dbus or apple_script variants.

**Comment by ZyX-I** [comment]
Though given that `spotify_dbus` has preference *if* dbus bindings are available to try `spotify_dbus` you need to install Python bindings to dbus.

**Comment by inet-pwnZ** [comment]
about the dbus thing i have it installed but i get this error
![error]
(http://i.imgur.com/2yCp4rt.png)

**Comment by ZyX-I** [comment]
@inet-pwnZ `dbus*` commands are *completely* irrelevant. They only indicate that you have some dbus-related stuff. You need `dbus` *Python* module. It may be installed via `pip install dbus-python`.

`~/.config/powerline/config.json` is a configuration file that must contain JSON dictionary. `common` is a name of the dictionary inside the top-level dictionary. `log_file` is a name of the key inside the `common` dictionary which specifies the log file.

Stderr means [stderr](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_.28stderr.29).

And you definitely are *not* running powerline-daemon. If you were you would not get such errors in tmux.

**Comment by inet-pwnZ** [comment]
![error]
(http://i.imgur.com/bSgZYiH.png)
```
pip install dbus-python                                                                                                                                                      1
Collecting dbus-python
  Using cached dbus-python-0.84.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 18, in <module>
    IOError: [Errno 2] No such file or directory: '/private/var/folders/rb/_bqnvv314hn2570b97z6ng500000gn/T/pip-build-SVOvp8/dbus-python/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rb/_bqnvv314hn2570b97z6ng500000gn/T/pip-build-SVOvp8/dbus-python
```

**Comment by ZyX-I** [comment]
I do not know why pip does not work: maybe you need `--local` after `install`.

Why did not you do

> Add print(spotify_status) just after a line this variable is defined in and check again.

. If problem is something like “spotify is not running” dbus will not help you.

**Comment by inet-pwnZ** [comment]
i did check my second post edit2

**Comment by ZyX-I** [comment]
> i did check my second post edit2

*just after a line this variable is defined*. Line 473 does not look like I was describing. In fact I have 469 lines in this file.

Valid line is after line 342 on your second screenshot.

**Comment by inet-pwnZ** [comment]
```
342		spotify_status = spotify.split(status_delimiter)
343		print(spotify_status)
```
getting
[u''] on tux right side
powerline tmux right has no error output

**Comment by ZyX-I** [comment]
It is strange that you get `u''`: I would expect this only if you use `print(repr(spotify_status))` in place of `print(spotify_status)`. Can you check this variant?

Also can you copy the whole apple script script (https://github.com/ZyX-I/powerline/blob/11c1e07b1220453120602aafd250ae2cfcbdf007/powerline/segments/common/players.py#L315-L335) to some file and run `osascript /path/to/the/file` and post the output here?

**Comment by inet-pwnZ** [comment]
print(repr(spotify_status)) output (same error)
```
[u'']
```
apple script output
```
osascript test.py
test.py:61:65: execution error: An error of type -10810 has occurred. (-10810)
```

**Comment by ZyX-I** [comment]
What does `test.py` contain? `61:65` looks rather strange because I would expect line and column numbers there, but script does not have more then sixty lines. Though you previously got `62:66`, so I think these are byte offsets. In this case it marks word `name` in phrase `name of every process`.

Am I right that script

```
tell application "System Events"
    set pl to (name of every process)
end tell
```

emits error `{file name}:48:52: execution error: An error of type -10810 has occurred. (-10810)`?

**Comment by inet-pwnZ** [comment]
its just that wired because i had some huge indenting in the file like 3 tabs on every line i used as you marked L315-335 that contains
```
			tell application "System Events"
				set process_list to (name of every process)
			end tell
			if process_list contains "Spotify" then
				tell application "Spotify"
					if player state is playing or player state is paused then
						set track_name to name of current track
						set artist_name to artist of current track
						set album_name to album of current track
						set track_length to duration of current track
						set now_playing to "" & player state & "{0}" & album_name & "{0}" & artist_name & "{0}" & track_name & "{0}" & track_length
						return now_playing
					else
						return player state
					end if
				end tell
			else
				return "stopped"
			end if
```

but i also did

```
tell application "System Events"
				set process_list to (name of every process)
			end tell
```

but it has the same outcome

**Comment by ZyX-I** [comment]
@inet-pwnZ Indentation should not matter. If I am correct about byte offsets then indentation should alter byte offset in the error and that’s all.

Currently I am trying to construct a minimal failing example (block of code in the previous my comment) so that you will go to osascript bug tracker with something much more specific then “powerline is not working”. Since I have no Mac OS X I cannot help more.

**Comment by inet-pwnZ** [comment]
Anyways i appreciate your help
about the dbus installation problem i think i will figure by myself

thx !

**Comment by inet-pwnZ** [comment]
i got dbus-python installed now
now i get this error
![error]
(http://i.imgur.com/lDOlOY6.png)

**Comment by ZyX-I** [comment]
Are you sure that spotify is installed correctly at all?

I saw `NoMemory` errors reported by other users, but have no idea how to fix them. Especially if they mean something other then “system has no free memory” (I doubt this is the case, dbus connections do not take too much memory).

**Comment by inet-pwnZ** [comment]
Well i have an open spotify window + sound i can navigate in the window
looks working to me dunno maybe something corrupted in the backend
i can try a reinstall but i don't think this is gonna help

**Comment by algoni** [comment]
The Index out of range error magically fixes itself when a similar AppleScript command is run elsewhere:
![tmux-spotify](https://cloud.githubusercontent.com/assets/2066504/9846823/6812184e-5add-11e5-815c-fdd6ffb86557.gif)

The statusline will then work properly until restart, so I'd assume the problem is not in powerline itself.

**Comment by inet-pwnZ** [comment]
thx for that workaround

**Comment by algoni** [comment]
This was due to an osascript bug in OS X.

Upgrading to OSX 10.10.5 fixed the issue for me permanently, without the need for the workaround.
