### ISSUE TITLE
How can I uninstall powerline?

### ISSUE THREAD

**Issue by eduOS** [powerline/powerline#1428]
I've installed powerline on my Ubuntu by running `sudo pip install --user git+git://github.com/powerline/powerline`, but I find it's too overwhelming for me as a novice to use such an integrated tool, so I thought vim-airline could be a better fit for me. I've searched through this repo and the linked documentory but failed to find any pointer. And I've tried `pip uninstall powerline` and 'pip uninstall --user git+git://github.com/powerline/powerline', and both didn't work. 

Sorry for asking such an unfriendly question. Thanks.

**Comment by ZyX-I** [comment]
1. PyPI package is named `powerline-status`. You need to uninstall it.
2. You do not have permissions to uninstall powerline-status if you installed it with `sudo` until you use `sudo`. Why do you think it is necessary?
