### ISSUE TITLE
bash prompt issues

### ISSUE THREAD

**Issue by jonlorusso** [powerline/powerline#1429]
This may have been addressed in a previous/closed issue, but I couldn't find anything with a set of appropriate searches, so here goes.  I use powerline for my bash promptlocally, and on a development server I ssh into.  Locally it works just fine, but the prompt does not display correctly at all on the remote server.  The fact that it seems to work locally suggests (at least to me) that it is not an issue with my terminal emulator (urxvt), or fonts.

The prompt seems to overwrite itself, my input appears in column 2 on top of the prompt.  Disabling segments seems to alter this behavior somewhat, though I cannot lock down which segments are specifically causing issues.  

Some potentially relevant details:

localhost:
```
    $ uname -r
    4.1.5-1-ARCH

    $ bash --version
    GNU bash, version 4.3.39(1)-release (x86_64-unknown-linux-gnu)
```

remote server:
```
    $ uname -v
    #1 SMP Debian 3.2.57-3+deb7u1    
    
    $ bash --version
    GNU bash, version 4.2.37(1)-release (x86_64-pc-linux-gnu)
```

**Comment by ZyX-I** [comment]
1. Can you reproduce the issue with

        % bash --norc --noprofile -i
        %% source /path/to/powerline/bindings/bash/powerline.sh

    ?
2. What does `locale` output?
3. Are you using daemon?
4. If you are how do you launch it (also what is the locale there)?
5. How did you install powerline and what is its version? (In case of pip version may be obtained by using `pip show powerline-status`.)

**Comment by jonlorusso** [comment]
* Can you reproduce the issue with?  Yes, same result.

- My locale:
```
    $ locale
    LANG=en_US.UTF-8
    LANGUAGE=
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=
```

* Tried with and without daemon. Same issue in both.
- (same locale as above)
```
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
```
- Installed via pip:
```
powerline-status          - The ultimate statusline/prompt utility.
  INSTALLED: 2.2 (latest)
```

**Comment by ZyX-I** [comment]
Are there any differences between `echo "$PS1" | hexdump -C` output (assuming the same working directory)?

**Comment by jonlorusso** [comment]
Not sure exactly what you mean, but here's the output:

    00000000  24 28 5f 70 6f 77 65 72  6c 69 6e 65 5f 70 72 6f  |$(_powerline_pro|
    00000010  6d 70 74 20 61 62 6f 76  65 6c 65 66 74 20 24 3f  |mpt aboveleft $?|
    00000020  29 0a                                             |).|
    00000022

**Comment by ZyX-I** [comment]
@jonlorusso You are not using bash bindings. This PS1 value is from generic (non-bash, non-zsh and non-fish) POSIX shell bindings. Note: to setup powerline you *must* use `…/bash/powerline.sh`, *not* `…/shell/powerline.sh`.

**Comment by ZyX-I** [comment]
And I meant differences between output in failing and not failing system. Output should be something like

```
00000000  5c 5b 1b 5b 30 3b 33 38  3b 35 3b 32 33 31 3b 34  |\[.[0;38;5;231;4|
00000010  38 3b 35 3b 33 31 3b 31  6d 5c 5d c2 a0 7a 79 78  |8;5;31;1m\]..zyx|
00000020  c2 a0 5c 5b 1b 5b 30 3b  33 38 3b 35 3b 33 31 3b  |..\[.[0;38;5;31;|
00000030  34 38 3b 35 3b 32 34 30  3b 32 32 6d 5c 5d ee 82  |48;5;240;22m\]..|
00000040  b0 c2 a0 5c 5b 1b 5b 30  3b 33 38 3b 35 3b 32 35  |...\[.[0;38;5;25|
00000050  30 3b 34 38 3b 35 3b 32  34 30 6d 5c 5d e2 80 a6  |0;48;5;240m\]...|
00000060  2f 5c 5b 1b 5b 30 3b 33  38 3b 35 3b 32 35 30 3b  |/\[.[0;38;5;250;|
00000070  34 38 3b 35 3b 32 34 30  6d 5c 5d 50 72 6f 6a 2f  |48;5;240m\]Proj/|
00000080  5c 5b 1b 5b 30 3b 33 38  3b 35 3b 32 35 30 3b 34  |\[.[0;38;5;250;4|
00000090  38 3b 35 3b 32 34 30 6d  5c 5d 63 2f 5c 5b 1b 5b  |8;5;240m\]c/\[.[|
000000a0  30 3b 33 38 3b 35 3b 32  35 32 3b 34 38 3b 35 3b  |0;38;5;252;48;5;|
000000b0  32 34 30 3b 31 6d 5c 5d  7a 73 68 c2 a0 5c 5b 1b  |240;1m\]zsh..\[.|
000000c0  5b 30 3b 33 38 3b 35 3b  32 34 30 3b 34 39 3b 32  |[0;38;5;240;49;2|
000000d0  32 6d 5c 5d ee 82 b0 c2  a0 5c 5b 1b 5b 30 6d 5c  |2m\].....\[.[0m\|
000000e0  5d 0a                                             |].|
000000e2
```

**Comment by jonlorusso** [comment]
Thanks!!
