### ISSUE TITLE
Can't get MPD and cpu_load_percent status to work with tmux

### ISSUE THREAD

**Issue by bookletchoir** [powerline/powerline#1437]
First, for the music status bar, my mpd setup in ```~/.config/powerline/themes/tmux/default.json``` looks like this
```json
{
    "function": "powerline.segments.common.players.mpd",
    "name": "player",
    "args": {
        "host": "my_password@localhost",
        "port": 2856
    }
},
```
I have ```mpc``` and ```python2-mpd``` package installed, and I can get mpd status from mpc by ```mpc status --host=my_password@localhost --port=2856```.

But with powerline, it doesn't seems to work.

Second, for the ```cpu_load_percent``` status, my setup is
```json
{
    "function": "powerline.segments.common.sys.cpu_load_percent"
},
````
But it doesn't appear either.

Other segments work file to me.
Am I missing something?

**Comment by ZyX-I** [comment]
1. Have you restarted daemon after adding this to configuration?
2. Note that for cpu_load_percent you need psutil PyPI package.
3. What does

        python -c 'from powerline.segments.common.players import mpd; from powerline import get_fallback_logger; print(mpd(pl=get_fallback_logger(), host="my_password@localhost", port=2856))'

    print?

**Comment by bookletchoir** [comment]
1. Yes, I've restarted the daemon, tmux and/or anything related to.
2. My mistake, I've installed ```psutils``` instead of ```python2-psutil```, so it didn't work.
3. Got this log
``` bash
➜  ~  python2 -c 'from powerline.segments.common.players import mpd; from powerline import get_fallback_logger; print(mpd(pl=get_fallback_logger(), host="my_password@localhost", port=2856))'                                            
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/powerline/segments/common/players.py", line 46, in __call__
    func_stats = self.get_player_status(**kwargs)
  File "/usr/lib/python2.7/site-packages/powerline/segments/common/players.py", line 191, in get_player_status
    client.connect(host, port)
  File "/usr/lib/python2.7/site-packages/mpd.py", line 413, in connect
    self._sock = self._connect_tcp(host, port)
  File "/usr/lib/python2.7/site-packages/mpd.py", line 392, in _connect_tcp
    flags):
socket.gaierror: [Errno -2] Name or service not known
```

I'm using the ```python2-powerline-git``` package from AUR.

**Comment by ZyX-I** [comment]
#1439 should fix it. I guess so would uninstalling python-mpd2.

**Comment by bookletchoir** [comment]
Fixed. Thanks.
