### ISSUE TITLE
Using powerline inside of tmux causes the shell commands to overwrite itself

### ISSUE THREAD

**Issue by 0xFN89** [powerline/powerline#1441]
When I use powerline outside of tmux everything is working as usual the shell prompt is working fine but when I use it inside of a tmux session the problem arises the commands start overwriting themselves. I don't know if this has anything to do  with the .tmux.conf file . here is the screenshot 

![screenshot from 2015-08-31 10 45 08](https://cloud.githubusercontent.com/assets/10919848/9572479/fe94bd78-4fcd-11e5-98fe-4fd0371d1ebf.png)

I was typing sudo 'somecommand ' and it started overwriting itself

**Comment by ZyX-I** [comment]
What shell are you using it in and how exactly do you source powerline?

(Also what is the powerline version? I do not remember recent reports about wrong colors: you shouldn’t be getting green in the middle of the statusline. Rerunning `powerline-config tmux setup` normally fixes this.)

**Comment by ZyX-I** [comment]
This behaviour is normal if you use powerline in zsh or bash, but use file `…/bindings/shell/powerline.sh`: …/shell/… file is for less advanced POSIX shells.

**Comment by ZyX-I** [comment]
And you should be getting this behaviour also outside of tmux, just type longer commands. I usually just hold `t` for testing, typing `ttttttttttttttttttttttttttt…` until it either fills the whole line and wraps as expected or start from the beginning unexpectedly.

**Comment by 0xFN89** [comment]
Thanks a lot for the reply and `powerline-config tmux setup` fixed the green color , do I have to run it always before running the terminal or can I put it somewhere like bashrc or tmux.conf? 

I am using bash shell and I source powerline by putting in bashrc this line : `/.local/...../bash/powerline.sh

**Comment by 0xFN89** [comment]
I installed powerline just 2 days ago so this must be the latest version. What was causing the powerline to render the wrong colors ?

**Comment by 0xFN89** [comment]
Its fixed , I don't know how? This is really really weird , like seeing a ghost in front of you when you wake up . I added `export PATH=path_to_bin_in_lib` and then commented it in bashrc . Then I restarted the computer and BAM!  the problem is solved.

**Comment by ZyX-I** [comment]
> Thanks a lot for the reply and powerline-config tmux setup fixed the green color , do I have to run it always before running the terminal or can I put it somewhere like bashrc or tmux.conf?

This command is run by tmux via `powerline.conf` file. The problem is that it sometimes does not fully work. I suspect that problem is asynchronous nature of access to tmux server from `powerline-config` script.

**Comment by bulldozier** [comment]
I have seen this happen when there are unicode characters in the prompt (which powerline uses for spaces and triangles), and the locale does not support them (such as the "C" locale). Make sure that "locale" shows utf8 or similar, and that glibc was built with the correct locale.
