### ISSUE TITLE
Powerline extends to a second line when using Vim and iTerm2

### ISSUE THREAD

**Issue by zhongwei-z** [powerline/powerline#1444]
When opening Vim in iTerm2, powerline is incomplete in displaying all the infomation, and extends to another line.
![screen shot 2015-09-09 at 3 18 43 pm](https://cloud.githubusercontent.com/assets/9145357/9755647/2fcc5e7a-5706-11e5-924a-f4f116a80cd4.png)
This issue appeared right after I installed iTerm2, zsh, and oh-my-zsh. In Terminal.app, powerline is normal. Any ideas?

**Comment by ZyX-I** [comment]
You nee to make sure that `&ambiwidth` Vim option has correct value, identical to the similar iTerm2 option. If this is false Vim cannot know width of the status line and thus cannot truncate correctly, same problem applies to powerline.

Note that any kind of multiline statusline is a Vim issue (or your Vim configuration). Normally if powerline for some reason produced too long status line Vim will simply truncate it. It cannot do this only when it has computed statusline width wrongly.

**Comment by ZyX-I** [comment]
And do not ask where in the similiar iTerm2 option. I know that there is one, but I have no OS X.
