### ISSUE TITLE
weather segment key error

### ISSUE THREAD

**Issue by atomi** [powerline/powerline#1445]
Generally the weather is displayed correctly but every little while I randomly get an ERROR

![screenshot from 2015-09-09 21 07 47](https://cloud.githubusercontent.com/assets/83137/9779980/584e3fc2-5737-11e5-9fd4-3ee946d657d1.png)

```:tmux:WeatherSegment:Yahoo returned malformed or unexpected response: '{"query":{"count":1,"created...```

**Comment by ZyX-I** [comment]
Use daemon or set log file in configuration so that errors are not printed to stderr. I cannot do anything with yahoo returning invalid responses.

**Comment by atomi** [comment]
@ZyX-I Is there a way to suppress those errors in log? In 3 days my log file grow almost 20 Mb.

**Comment by ZyX-I** [comment]
@atomi When you use daemon adjacent same errors from one segments are suppressed. Otherwise log to `/dev/null` or set higher log_level.

**Comment by atomi** [comment]
@ZyX-I Super helpful thanks!
