### ISSUE TITLE
powerline vim status bar does not show unless Syntastic displays its error box

### ISSUE THREAD

**Issue by laebshade** [powerline/powerline#1446]
Powerline vim status bar does not show unless Syntastic displays its error box.

<img width="820" alt="screenshot 2015-09-11 14 24 06" src="https://cloud.githubusercontent.com/assets/4237425/9822942/5f6b7ec2-5891-11e5-8737-a276e733fb5b.png">

<img width="817" alt="screenshot 2015-09-11 14 24 28" src="https://cloud.githubusercontent.com/assets/4237425/9822950/62531e7e-5891-11e5-8ada-1da18ed83b7a.png">

I suspect Powerline vim is rendering offscreen and Syntastic is forcing it to render on-screen. 

Any ideas?

**Comment by ZyX-I** [comment]
*Vim* **by default** does not display status line unless there is more then one window. See `:h 'laststatus'`.

**Comment by laebshade** [comment]
I had no idea.  That fixed it.  Thank you!

**Comment by ZyX-I** [comment]
@laebshade This is described in troubleshooting.

**Comment by laebshade** [comment]
I didn't see it, probably due it not being in the table of contents at the
top of the page.  I see it now.
