### ISSUE TITLE
Provide a systemd service for powerline-daemon

### ISSUE THREAD

**Issue by DoctorJellyface** [powerline/powerline#1447]
It would greatly simplify setting it up for, especially on Archlinux. Thanks.

**Comment by ZyX-I** [comment]
If you want you may create a PR which adds systemd service. I am not using systemd and am not going to.

**Comment by DoctorJellyface** [comment]
On it. May I reopen?

**Comment by DoctorJellyface** [comment]
OK, so does the daemon need to be run as the user or can it be run as root?

**Comment by ZyX-I** [comment]
@DoctorJellyface It needs to be run as user.

**Comment by DoctorJellyface** [comment]
OK, mostly done. Where should the service go?

**Comment by ZyX-I** [comment]
I do not know what exactly is “service”. If it is config file then probably to `powerline/dist/systemd/powerline.[conf?]`.

**Comment by DoctorJellyface** [comment]
Well, a systemd service is basically a `.desktop` like file that goes into (in this case) `/usr/lib/systemd/user/powerline-daemon.service`. It contains a few lines telling systemd how to launch/handle it, and some user stuff as where the documentation is and the description.

**Comment by ZyX-I** [comment]
@DoctorJellyface Yes, put it to `powerline/dist/systemd/powerline-daemon.service`.

**Comment by DoctorJellyface** [comment]
Does the daemon make a PID file?

**Comment by DoctorJellyface** [comment]
Nevermind, I set it to foreground.
