### ISSUE TITLE
Not able to get VIM to use powerline installed via pip

### ISSUE THREAD

**Issue by jamesrobb** [powerline/powerline#1450]
Hello,

I have been following the instructions as per:
https://powerline.readthedocs.org/en/latest/usage/other.html#vim-statusline

However, I am unable to get it to work. The new powerline status line doesn't show up in vim (though I am able to get it to work in bash).

I tried opening up an ipython shell and running:
    
    from powerline.vim import setup

and I get this:

    ImportError: No module named vim

I assume this is the root of my troubles, but I don't know where to begin in fixing this issue.

How can one proceed?

**Comment by ZyX-I** [comment]
How did you install powerline?

**Comment by ZyX-I** [comment]
> I tried opening up an ipython shell and running:

This is ueseless action. Powerline needs `vim` module which is defined *inside vim executable*. This *cannot* be root of your troubles, IPython may not have this module.

**Comment by ZyX-I** [comment]
And I guess this is the usual `laststatus` problem. Powerline is not going to show up if Vim status line is not showing up, and by default this only happens if there is more then one window.

**Comment by jamesrobb** [comment]
ZyZX-I

You are correct, that was the problem. Though now I see the powerline bar, but the colours for the different modes don't seem to show up as they once did. Regardless of what mode I am in, the powerline bar remains black and white.

Am I missing something else obvious?

**Comment by ZyX-I** [comment]
@jamesrobb `&t_Co` must be 256 or `&guicolors` must be on and terminal must accept true color (latter requires custom patch). If `&t_Co` option is not 256 then you have invalid $TERM setting. In shells powerline does not bother checking how many colors terminal supports, so it will work as long as terminal is able to parse sequences that were emitted. In Vim Vim does the checks and does not let colors with too high numbers through.

**Comment by jamesrobb** [comment]
Right, works now. Thanks!
