### ISSUE TITLE
Documentation: urxvt and patched fonts

### ISSUE THREAD

**Issue by timp3289** [powerline/powerline#1455]
Hi,
Apologies if this is the wrong place.
The documentation, here, http://powerline.readthedocs.org/en/latest/installation.html#patched-fonts indicates that patched fonts don't work on urxvt. Reading elsewhere, and by personal experience, the opposite is true: the usual (fontconfig) method doesn't work, but installing a patched font does.

Edit: previously had wrong url

**Comment by ZyX-I** [comment]
The page you referenced does not say anything about urxvt. I also do not see this in troubleshooting.

**Comment by timp3289** [comment]
Sorry, linked the wrong page:
http://powerline.readthedocs.org/en/latest/installation.html#patched-fonts

**Comment by ZyX-I** [comment]
Though no, AFAIR in this section it was meant what is described in troubleshooting:

> If you’re using rxvt-unicode make sure that it’s compiled with the --enable-unicode3 flag.

Do not know how this is handled in other distributions, but rxvt-unicode ebuild in Gentoo uses --enable-unicode3 only if unicode3 USE flag is present.
