### ISSUE TITLE
i3 lemonbar with workspace info

### ISSUE THREAD

**Issue by kaatish** [powerline/powerline#1457]
Is there any way to display the available workspaces and highlight the current or action required workspaces?

**Comment by S0lll0s** [comment]
All of this is available with the default segments: https://github.com/powerline/powerline/blob/develop/powerline/segments/i3wm.py

**Comment by S0lll0s** [comment]
...and now also in the documentation, where it belongs: http://powerline.readthedocs.org/en/develop/configuration/segments/i3wm.html
