### ISSUE TITLE
integer: command not found

### ISSUE THREAD

**Issue by sachevl** [powerline/powerline#1460]
Cannot integrate into zsh on OS X due to the following error

```
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh: line 21: integer: command not found
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh: line 29: syntax error near unexpected token `_powerline_tmux_setenv'
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh: line 29: `		function -g _powerline_tmux_setenv() {'
```

**Comment by catbaron-** [comment]
I met the same error for the reason that I missed the "." when I add 
`
. /dir/to/powerilne//powerline/bindings/zsh/powerline.zsh
`
to my .zshrc file.
But new errors after I fixed this mistake. So I have turned to another powerline tool and good luck to you.

**Comment by ZyX-I** [comment]
I am wondering what is your zsh version. I have never seen zsh without `integer` built-in.

**Comment by sachevl** [comment]
@catbaron- thank you. The problem was caused by missing dot. After I had some issues, because the line was not before `source`. The following config worked for me.

```sh
powerline-daemon -q
 . /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh

source $ZSH/oh-my-zsh.sh
```
