### ISSUE TITLE
Keep MPD Connection alive in now_playing segment

### ISSUE THREAD

**Issue by S0lll0s** [powerline/powerline#1468]
The now_playing segment creates a new MPD connection on every rendering pass:

![](http://i.imgur.com/b4c1iiq.png?1)
as you can see, a new connection is spawned twice a second (mopidy is a mpd server).

I don't know the actual performance impact but it seems pretty "stupid" to me.

**Comment by ZyX-I** [comment]
Such decision leaves code simple and more robust: I would not only need to keep open connection, but also handle cases when connection is lost for whatever reason. Thus this behaviour is not going to change until somebody actually does benchmarks.

Also note that I am not using mpd (as well as other players) which makes modifying code by me much more error-prone.

**Comment by S0lll0s** [comment]
I think that could be handled rather easily with something like:

    def new_connection():
      ...
    def connection_closed(conn):
      ....

    ....
      global connection
      if not connection or connection_closed(connection):
        connection = new_connection()

**Comment by ZyX-I** [comment]
@S0lll0s In any case this is more code for no real reason. Which also is not going to work for users that are not using daemon.
