### ISSUE TITLE
OS X- 'int' object has no attribute 'lstrip' in right statusbar.

### ISSUE THREAD

**Issue by dafstone** [powerline/powerline#1470]
Hi - 

My powerline status has been working well for some time under el capitan (since install a couple of weeks back) but as of this morning I'm now getting:

`'int object has not attribute 'lstrip' where my right hand statusbar should be.  

I recently updated a couple of pip modules as I was chasing another problem, including psutil.  (This was previously at 3.1.1 ) and my statusbar is now broken. I'm not 100% sure this is the cause though, as I've also been updating a few other things. I rolled back to 3.1.1 but still no luck.

I also run weekly brew updates, I also recently updated to el capitan.  

Love to find the cause of this, or get some guidance on troubleshooting.

**Comment by ZyX-I** [comment]
Right hand status bar of what? If this is tmux, check out the output of `powerline-daemon --foreground --replace & {sleep 2; powerline tmux right ; powerline-daemon --kill}`. You will need to start powerline-daemon again after this, better setting `log_file` `common` option in `${XDG_CONFIG_HOME:-$HOME/.config}/powerline/config.json` (e.g. by placing `{"common":{"log_file":"/tmp/powerline.log"}}` there): after this operation you will be able to see most of the exceptions in the log without needing to restart daemon in foreground.

**Comment by dafstone** [comment]
Yes tmux.  Sorry, can't believe I didn't mention that.

Thanks for the quick reply - I'll give that a try now and see what I see.

**Comment by sdval** [comment]
@ZyX-I : following your troubleshooting step above, I receive the following:

```
Traceback (most recent call last):
  File "/Users/anthony/Library/Python/2.7/lib/python/site-packages/powerline/__init__.py", line 760, in render
    return self.renderer.render(*args, **kwargs)
  File "/Users/anthony/Library/Python/2.7/lib/python/site-packages/powerline/renderers/tmux.py", line 39, in render
    return super(TmuxRenderer, self).render(width=width, segment_info=segment_info, **kwargs)
  File "/Users/anthony/Library/Python/2.7/lib/python/site-packages/powerline/renderer.py", line 297, in render
    segment_info=self.get_segment_info(segment_info, mode),
  File "/Users/anthony/Library/Python/2.7/lib/python/site-packages/powerline/renderers/tmux.py", line 66, in get_segment_info
    varname = 'TMUX_PWD_' + r['pane_id'].lstrip('% ')
AttributeError: 'int' object has no attribute 'strip'
```

**Comment by dafstone** [comment]
Same here:

```
powerline-daemon --foreground --replace & {sleep 2; powerline tmux right ; powerline-daemon --kill}
[1] 15223
2015-10-19 13:25:45,149:ERROR:tmux:powerline:Failed to render: 'int' object has no attribute 'lstrip'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/powerline/__init__.py", line 760, in render
    return self.renderer.render(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/powerline/renderers/tmux.py", line 39, in render
    return super(TmuxRenderer, self).render(width=width, segment_info=segment_info, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/powerline/renderer.py", line 297, in render
    segment_info=self.get_segment_info(segment_info, mode),
  File "/usr/local/lib/python2.7/site-packages/powerline/renderers/tmux.py", line 66, in get_segment_info
    varname = 'TMUX_PWD_' + r['pane_id'].lstrip('%')
AttributeError: 'int' object has no attribute 'lstrip'
```

As a note - this is with psutil-3.2.2.  

However - I've discovered that if I downgrade to psutil-3.1.1 with pip, I no longer get this error with the troubleshooting step from above.  Though even after I kill powerline I still get it in the status bar.  Perhaps it's cached somewhere?

**Comment by dafstone** [comment]
So interestingly although I can make the above error appear and dissappear by upgrading and downgrading psutil, I can't make the original issue dissapear with this troubleshooting step.

I notice that even after the `powerline-deamon` has been killed:

`/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /usr/local/bin/powerline-render tmux right -R pane_id=0 --width=238 -R width_adjust=20`

Is still in my process list.  Is this where the error is originating?

**Comment by sdval** [comment]
I was on 3.1.1, and for testing sake I just upgraded to 3.2.2 and I'm receiving the same error.

@dafstone -- tried to catch the daemon in my process list, but it's behaving as expected

```
$  ps aux | grep powerline
asandoval       31432   0.0  0.0  2434836    772 s001  S+   12:53PM   0:00.00 grep powerline
asandoval       31242   0.0  0.1  2484908  11416   ??  S    12:52PM   0:00.11 /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /usr/local/bin/powerline-daemon
$  powerline-daemon --kill
Kill command sent to daemon, if it does not die in a couple of seconds use kill to kill it
$  ps aux | grep powerline
31445   0.0  0.0  2434836    784 s001  S+   12:53PM   0:00.00 grep powerline
$  powerline-daemon
$  ps aux | grep powerline
31461   0.0  0.0  2434836    768 s001  R+   12:54PM   0:00.00 grep powerline
31453   0.0  0.1  2483204  10416   ??  S    12:53PM   0:00.05 /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /usr/local/bin/powerline-daemon
$  tmux new-session -s local # error still appears in right status pane
[exited]
```

**Comment by ZyX-I** [comment]
What tmux version? It looks like `tmux display -p '#D'` no longer outputs `%` in the front.

**Comment by dafstone** [comment]
Good thought there - version 2.1, which also just got an update.

**Comment by sdval** [comment]
I also just upgraded to 2.1. - there was a horrible bug with tmux/el-capitan that just got resolved over the weekend. 

```
$ tmux -V
tmux 2.1
$ t tmux display -p '#D'
%0
```

**Comment by jaredbonobos** [comment]
Hey all, i managed to fix it on my computer by doing this:

vi +66 "/Users/username/Library/Python/2.7/lib/python/site-packages/powerline/renderers/tmux.py"

change this:
varname = 'TMUX_PWD_' + r['pane_id'].lstrip('% ')

to this:

varname = 'TMUX_PWD_' + str(r['pane_id']).lstrip('% ')

**Comment by ZyX-I** [comment]
@sdval If `tmux display -p '#D'` outputs `%0` then you should not see this problem. But if you “just” upgraded tmux this does not mean you are *actually* using this version: you need to restart server.

**Comment by sdval** [comment]
+1 @jaredbonobos -- that did the trick! my terminal looks incredible again, thanks guys!

@ZyX-I - awesome project. keep up the good work!

**Comment by dafstone** [comment]
+1 @jaredbonobos - working here also.  Thanks - look forward to this patch coming downstream!

**Comment by mhartington** [comment]
I'm still seeing this after a fresh install of 2.3.
When I reload the config, it flashes for a second then displays the error.

<img width="649" alt="screen shot 2015-12-21 at 10 04 19 am" src="https://cloud.githubusercontent.com/assets/2835826/11933506/46b7d32a-a7ca-11e5-944b-c8765a55a757.png">


```
zsh
osx 10.11.2
powerline-status 2.3
tmux 2.1
```

Please let me know what other information you may need

**Comment by jaredmichaelwilliams** [comment]
@mhartington https://github.com/powerline/powerline/issues/1470#issuecomment-149306665

**Comment by mhartington** [comment]
yes, changed that and still have the error

**Comment by ZyX-I** [comment]
@mhartington Can you read the very first *comment* on this issue? It clearly says what information you need to provide. Also if you *were able to do* changes described in that comment then you clearly have outdated version. And do not forget to restart daemon after any update.

**Comment by NHDaly** [comment]
I'm seeing the same thing, and I am also on

```
zsh
osx 10.11.2
powerline-status 2.3
tmux 2.1
```
I installed `powerline` through homebrew.

When I try printing `tmux display -p '#D'`, I get `%24`, not `%0`.


BUT, then when I ran `powerline-daemon --foreground --replace & {sleep 2; powerline tmux right ; powerline-daemon --kill}` to get diagnostic information, among other things, it printed `2016-01-20 01:20:59,491:WARNING:tmux:uptime:Unable to get uptime. You should install psutil module` and then *started working*. Why would this start it working?

Also, why isn't `psutil` installed as part of the brew installation if it's a dependency?

**Comment by ZyX-I** [comment]
@NHDaly It is *optional* dependency. Needed only for some segments. In any case any questions like this should be directed to *brew package maintainers*, not here. I and this repository has nothing to do with brew package.

**Comment by NHDaly** [comment]
Got it. Thank you!

**Comment by erikw** [comment]
I still have this problem with `'int' object has no attribute 'lstrip'`


Line 66 of `$POWERLINE_ROOT/renderers/tmux.py` already looks like

```python
varname = 'TMUX_PWD_' + str(r['pane_id'])
```

**System:**
Powerline: `2.5`, python3 version, installed with pip3.
Tmux: `2.3`
Python: `3.5.2`
Terminal emulator: iTerm `3.012`
OS: macOS Sierra 10.12.1

**Comment by ZyX-I** [comment]
@erikw This patch can’t be correct, check line 53.

**Comment by ZyX-I** [comment]
I do not see how `pane_id` may be both “'int' object” and instance of `bytes` or `unicode` (which is `str` on Python-3). Code is not actually going to work properly if it is Python-3 and pane_id is `bytes`, but argparse should not leave bytes in renderer_arg, as well as mergeargs or parsedotval, and it definitely cannot produce error regarding 'int' object.

**Comment by erikw** [comment]
Indeed it looks very strange! How do I run this in a debug-mode to take a closer look? Would be nice to set a `pdb` breakpoint.

**Comment by ZyX-I** [comment]
@erikw Check tmux `status*` options, there should be two which run powerline in `#(`: `tmux show-options -g | grep '#('`. Contents of `#()` may as well be run inside a shell running inside tmux, `$POWERLINE_COMMAND` should be `powerline-render` (not in a running tmux session, for testing): this is a Python script, `powerline` is not.

**Comment by erikw** [comment]
`$POWERLINE_COMMAND` for me is 

```bash
$ echo $POWERLINE_COMMAND  
powerline
```

Is that wrong you mean? :O

**Comment by ZyX-I** [comment]
I mean that if you can reproduce the problem with POWERLINE_COMMAND set to `powerline-render` then it will be easier to change to run under pdb. `powerline` will use powerline daemon if it is launched and in any case is a program which will use other process to do actual rendering.

Try catching what arguments powerline is actually run with: using either strace on tmux (need to do something to avoid truncating `execve` argument, but this variant is stable) or `ps -C powerline -o cmd=` (you need to be lucky, or just use `while ! ps -C powerline -o cmd= ; do done | cat`: this works for me; note that this way determining which space is a part of argument and which space is an argument separator will require checking original expression).

**Comment by ZyX-I** [comment]
With exact arguments catching error inside zsh should be easier.

**Comment by erikw** [comment]
Ha! I found it the problem, sort of. I was using `$ locate powerline` and noticed that there was a an older python2 version of powerline installed too on this system. Once I got rid of that one the problems went away! :)
