### ISSUE TITLE
ERROR:tmux:powerline:Failed to render: 'int' object has no attribute 'lstrip'

### ISSUE THREAD

**Issue by andrew222** [powerline/powerline#1473]
You can reproduce the error wih this env
mac os x 10.11
tmux 2.1
python 2.7
powerline 2.2

**Comment by andrew222** [comment]
Sorry I found it was fixed in v2.3

**Comment by erikw** [comment]
I still have this in powerline `2.5`.

**Comment by nether-cat** [comment]
I have this issue too in v2.5 just like @erikw

**Comment by erikw** [comment]
@nether-cat The solution for me was to completely remove all my powerlin configuration files and copy the new templates. The bug was due to some old issue with these configuration files.

**Comment by nether-cat** [comment]
I even did that. But thanks to your reply I doubled checked what I had done and I realized, that I had not killed the powerline-daemon after doing that. It's working now :)
