### ISSUE TITLE
tmux error : "unsupported operand type(s) for -=: 'int' and 'unicode'"

### ISSUE THREAD

**Issue by Swatto** [powerline/powerline#1474]
After an upgrade of the package using `pip`, I have an issue with the tmux statusline but the vim one works nicely. Without any kind of modification of basic installation and with version2.1.0 of tmux, it puts me this message in the right part of the statusline :

```
unsupported operand type(s) for -=: 'int' and 'unicode'
```

Here's the code of my `.tmux.conf` if it could help to detect the issue:

```
run-shell "powerline-daemon -q"

# use UTF8
set -g utf8
set-window-option -g utf8 on

set-option -g default-command "reattach-to-user-namespace -l bash"
# make tmux display things in 256 colors
set -g default-terminal "screen-256color"

set -g history-limit 50000
set -g display-time 4000

# set Ctrl-a as the default prefix key combination
# and unbind C-b to free it up
set -g prefix C-a
unbind C-b

# use send-prefix to pass C-a through to application
bind C-a send-prefix

# shorten command delay
set -sg escape-time 1

# set window and pane index to 1 (0 by default)
set-option -g base-index 1
setw -g pane-base-index 1

# reload ~/.tmux.conf using PREFIX r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# use PREFIX | to split window horizontally and PREFIX - to split vertically
bind | split-window -h
bind - split-window -v

# use shortcut to kill pane and window
bind j kill-pane
bind k kill-window

# Make the current window the first window
bind T swap-window -t 1

# -----------------------
# Status Bar
# -----------------------
set-option -g status on                # turn the status bar on
source "/usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"
```

**Comment by ZyX-I** [comment]
Check out the full error in daemon log. If you have not setup one (key `"log_file"` in `"common"` dictionary in `~/.config/powerline/config.json`) use

    powerline-daemon --replace --foreground & { sleep 2 ; tmux refresh -S ; powerline-daemon --replace }

: this will restart daemon, attached to foreground (so that log will be given to stderr), redraw tmux statusline and restart daemon again, in background.

**Comment by Swatto** [comment]
The command to replace the daemon fix my issue. Thanks !
