### ISSUE TITLE
icons not displaying locally but ok when ssh somewhere else

### ISSUE THREAD

**Issue by nbalonso** [powerline/powerline#1475]
I am trying to figure out what is wrong with my workstation because since the upgrade to OSX El Capitan the icons don't show up.

The funny thing is that they are not working locally. If I ssh into another box they show up fine.

At the same time, they work on my laptop running the same settings, but if I ssh into my workstations they still don't show. 

An image might explain better what I am seeing:
![bash](https://cloud.githubusercontent.com/assets/1116445/10675368/7bdc1944-7908-11e5-9152-37bb80161921.png)

I don't believe it is a problem with powerline itself, but I'd like some directions

**Comment by ZyX-I** [comment]
Please refer to the documentation of the hostname segment.

**Comment by ZyX-I** [comment]
Though you rather need source code. It depends on the presence of SSH_CLIENT variable, or the configuration option.

**Comment by nbalonso** [comment]
sitting on the workstation and opening iTerm, the icons are still not showing. So I don't see how this can be related to the ssh_client variable

**Comment by ZyX-I** [comment]
SSH_CLIENT environment variable presence. This segment does not show up if you are not inside an ssh session, which is detected using  this variable.

**Comment by ZyX-I** [comment]
Or you may tell it to show always.

**Comment by nbalonso** [comment]
I know that. 

I am sorry if I'm not explaining myself well. What I'd like to know is why, in that particular host that happens to be my workstation, the icons are not rendering. 

Eg. in the screenshot the lock icon doesn't show up and an H is shown instead. Same thing for the arrows, git branch... I know is not iTerm, not the config (using defaults) and not the fonts.

**Comment by ZyX-I** [comment]
This means that you have non-unicode locale. Powerline automatically degrades to ascii-only theme if  locale is not UTF-8. Locale can be seen using `locale` command.

**Comment by nbalonso** [comment]
Thanks. 

Executing `locale` returns the same thing in a working machine and in the non-working one, but I'll try to find what else can be wrong about the locale.

```
bash-3.2$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="en_IE.UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
bash-3.2$
```

**Comment by ZyX-I** [comment]
There are too many `C` in locale. Most of the “variables” need to be `en_IE.UTF-8` here (I am not really sure which of them are used in each case).

**Comment by nbalonso** [comment]
having this in the bash_profile and sourcing it, sets everything to US UTF-8; yet the icons still replaced by letter. 

I'll keep digging.

```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by ZyX-I** [comment]
@nbalonso If you are using daemon any change to locale setup is useless until you restart a daemon. `powerline-daemon` is always using the locale from the environment it was started in.

**Comment by nbalonso** [comment]
@ZyX-I that was it. Reloading the daemon now that the locales are set and it's back to normal.

Thanks a mil
