### ISSUE TITLE
Powerline-daemon complain about usage in tmux.

### ISSUE THREAD

**Issue by GuillaumeSeren** [powerline/powerline#1476]
Hey there,
I use powerline for my tmux status bar, and it has partly broken since last week, this is the issue:

I use 3 sessions at the same time on my laptop (main, mail, irc) but after the first main is launched, the others get a error message in the status bar "usage: powerline-daemon [-h] [-r MODULE] [-w WIDTH] [--last-exit-code INT]".
The erreur message did not show up on the fist launched session.

I use:
tmux: v2.1
powerline: v2.2-2

My tmux.conf minified:
```
run-shell "powerline-daemon -r"
source "/usr/share/powerline/bindings/tmux/powerline.conf"
set -g @tpm_plugins '            \
  tmux-plugins/tpm               \
  tmux-plugins/tmux-sensible     \
  tmux-plugins/tmux-copycat      \
  tmux-plugins/tmux-resurrect    \
  tmux-plugins/tmux-continuum    \
  tmux-plugins/tmux-yank         \
  seebi/tmux-colors-solarized    \
'
run-shell '~/.tmux/plugins/tpm/tpm'
```
Did someone have an idea ?

**Comment by ZyX-I** [comment]
I do not know what exactly may result in *this* error, but tmux-2.1 and powerline-2.2 cannot be used together. You either need to downgrade tmux or update powerline (also what is `-2` in version?).

Also it is bad idea to use `run-shell "powerline-daemon --replace"` in configuration: this will kill and replace daemon when not necessary (prereq: powerline-daemon needs to be launched prior to tmux server started, otherwise this is harmless). Use `--quiet`.

After updating powerline do not forget to restart daemon (this is where `--replace` is needed).

**Comment by GuillaumeSeren** [comment]
@ZyX-I Hello and thank you for your answer.
> 'mux-2.1 and powerline-2.2 cannot be used together'
Yes I will test that, but it may be an error of the maintener who upgrade powerline and did not notice that tmux needed to be upgraded too.

> '(also what is -2 in version?)'
It is a sub-version in the package specific to debian, details here:
https://packages.debian.org/sid/powerline

> 'bad idea to run-shell "powerline-daemon --replace" (...) Use --quiet'
Yes I keep a test in the pasted config, it is my bad, I use -q outside of the test (all the time).

Maybe it come from the package dependency tmux 2.1 with powerline 2.2 I will open a ticket on the BTS to find out.

**Comment by ZyX-I** [comment]
> Yes I will test that, but it may be an error of the maintener who upgrade powerline and did not notice that tmux needed to be upgraded too.

New powerline (2.3) can be used with all tmux versions, up to `2.1` (BTW, tmux developers love to break things). It is tmux update that makes powerline update be needed.

**Comment by GuillaumeSeren** [comment]
@ZyX-I 
Ok I will notice that to the debian maintener.

The behavior is still strange because the 2 first session are launch by my ~/.xsessionrc work without bug, and the third I launch it after get the bug.

**Comment by GuillaumeSeren** [comment]
Quoting Nikolai Aleksandrovich Pavlov (2015-10-24 18:48:44)
> New powerline (2.3) can be used with all tmux versions, up to 2.1 (BTW, tmux
> developers love to break things). It is tmux update that makes powerline update
> be needed.
I open a issue on Debian BTS,
I'll give some feedback when it get fixed.

**Comment by GuillaumeSeren** [comment]
Hey,
the Debian maintainer upgrade powerline to the v2.3, 
and that fix the problem, thank you for helping !

Guillaume.
