### ISSUE TITLE
OSX El Capitan destroyed my powerline

### ISSUE THREAD

**Issue by ejamroz** [powerline/powerline#1478]
I had powerline installed for use within both vim and zsh and everything worked well, that is until I installed OSX El Capitan. Now when I open .zsh I get:
```
zsh: no such file or directory: /usr/local/lib/python2.7/site-packages/scripts/powerline
zsh: no such file or directory: /usr/local/lib/python2.7/site-packages/scripts/powerline
```
and when I try to use vim, I get:
```
An error occurred while importing powerline package.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Error detected while processing /Users/ejam/.vimrc:
line   17:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named powerline.vim
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'powerline_setup' is not defined
line   19:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'powerline_setup' is not defined
```
Needless to say, powerline is no longer working in either place. I have poured a few hours into this already, and nothing is seeming to work. I have tried reinstalling vim, python, and powerline with no success. Below are the details:

Running OSX 10.11.1
Python: 2.7.10

Both python and vim were installed via homebrew using: 
```
brew install python
brew install vim --env-std --override-system-vim
```
Powerline was installed via python:
```
pip install powerline-status
```
Added to .zshrc:
```
source /usr/local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh
```
Added to .vimrc
```
 source /usr/local/lib/python2.7/site-packages/powerline/bindings/vim/plugin/powerline.vim
 python from powerline.vim import setup as powerline_setup
 python powerline_setup()
 python del powerline_setup
```
${PATH}:
```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/usr/local/sbin
```
Output from within vim (:python import sys; print(sys.path)):
```
['/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/pytho
n2.7', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Version
s/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.
10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/
Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/site-packages', '/Library/Python/2.7/site-packages', '_vim_path_', '/usr/local/lib/python2.7/site-packages']
```
Any help would be much appreciated!

**Comment by ZyX-I** [comment]
It looks like your setup is correct. I have no OSX, so can’t say more, but there are no obvious errors (it is strange though that `/usr/local/lib/python2.7/site-packages` is the last directory is `sys.path` list).

Though there is one thing:

```
 source /usr/local/lib/python2.7/site-packages/powerline/bindings/vim/plugin/powerline.vim
 python from powerline.vim import setup as powerline_setup
 python powerline_setup()
 python del powerline_setup
```

initializes powerline *twice*. You need to either use first or last three lines, but not both. This is not going to harm (and lead to your errors) AFAIK, but this is not correct.

**Comment by ejamroz** [comment]
There in lies my pickle, from everything I can see, it is set up correctly.. hence the frustration.
Yeah those last three lines are from some issues I had with the initial install about a year ago, I should have deleted them after I got it all working, and will do so now.

**Comment by ZyX-I** [comment]
@ejamroz Thow there is a question: AFAIK OSX has two pythons: system one and brew one. Which of them `pip` is using?

**Comment by ejamroz** [comment]
Well, not knowing exactly how to figure that out, here is what I came up with.
Brew python version: 2.7.10
Brew pip -V output:
```
pip 7.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
```
which python:
```
/usr/local/bin/python
```
Not quite sure how to get more info than that...

**Comment by ejamroz** [comment]
So, after more investigation I have a couple questions. Where is the command 'powerline' suppose to live? I think this could be a problem
```
which powerline
powerline not found
```

**Comment by ZyX-I** [comment]
@ejamroz It is supposed to live somewhere in `$PATH`. There are no more restrictions. (And I do not have OSX, so can’t say where pip should install it, especially given that I know about two pythons and different installation paths for them.)

**Comment by ejamroz** [comment]
I added 
```
 export POWERLINE_CONFIG_COMMAND=powerline-config
 export POWERLINE_COMMAND=powerline
```
to my .zshrc and now when I try to open I get the error
```
Traceback (most recent call last):
  File "/usr/local/bin/powerline", line 11, in <module>
    from powerline.shell import ShellPowerline, get_argparser, finish_args  # NOQA
ImportError: No module named powerline.shell
Traceback (most recent call last):
  File "/usr/local/bin/powerline", line 11, in <module>
    from powerline.shell import ShellPowerline, get_argparser, finish_args  # NOQA
ImportError: No module named powerline.shell
```
and when I try to open vim 
```
Error detected while processing /Users/ejam/.vimrc:
line   17:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named powerline.vim
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'powerline_setup' is not defined
line   19:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'powerline_setup' is not defined
Press ENTER or type command to continue
```
The output from powerline-lint
```
Traceback (most recent call last):
  File "/usr/local/bin/powerline-lint", line 5, in <module>
    from powerline.lint import check
ImportError: No module named powerline.lint
Traceback (most recent call last):
  File "/usr/local/bin/powerline", line 11, in <module>
    from powerline.shell import ShellPowerline, get_argparser, finish_args  # NOQA
ImportError: No module named powerline.shell
Traceback (most recent call last):
  File "/usr/local/bin/powerline", line 11, in <module>
    from powerline.shell import ShellPowerline, get_argparser, finish_args  # NOQA
ImportError: No module named powerline.shell
```
Now, I am not too well versed in python, but looking at those line numbers within /urs/local/bin/powerline I see 
```
 from powerline.shell import ShellPowerline, get_argparser, finish_args
```
Does the from call assume that powerline.shell is in the same directory as this file or does 'from' default to a different location?

**Comment by ZyX-I** [comment]
> Does the from call assume that powerline.shell is in the same directory as this file or does 'from' default to a different location?

It does not assume anything. `from module import attributes` is a way to say “import module, take its attributes and assign this attributes to locals() with the same name”. Import uses `sys.path` just like any other import.

**Comment by ejamroz** [comment]
So, I am not sure if this is the "proper" fix, but I just got it all working again by modifying /usr/local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh
I changed the behaviour of variable POWERLINE_CONFIG_COMMAND:
```
if test -z "${POWERLINE_CONFIG_COMMAND}" ; then
     if which powerline-config >/dev/null ; then
         POWERLINE_CONFIG_COMMAND=powerline-config
     else
         POWERLINE_CONFIG_COMMAND="/usr/local/bin/powerline-config"
         #POWERLINE_CONFIG_COMMAND="$_POWERLINE_SOURCED:h:h:h:h/scripts/powerline-config"
     fi
 fi
```

**Comment by ZyX-I** [comment]
@ejamroz What’s the point in modifying `POWERLINE_CONFIG_COMMAND` *there* if you can add the necessary export in your zshrc before you source powerline bindings?

**Comment by ejamroz** [comment]
You know when you're right, you're right. I added the necessary exports. Thank you so much for your help through this process, I really do appreciate it. I love the use of powerline and am quite happy to have it back.

**Comment by ShawnLinLoveLife** [comment]
@ejamroz Hi, could you please tell me how you export it? Thanks in advance

**Comment by ejamroz** [comment]
Add:
export POWERLINE_CONFIG_COMMAND="/usr/local/bin/powerline-config"
export POWERLINE_COMMAND=powerline

to your shell rc file before the source calls for powerline. Be it .bashrc
or .zshrc, or whatever you use.

Hope this helps
