### ISSUE TITLE
tries to install scripts to ${PYTHONHOME}/bin on OS X (outside of $PATH)

### ISSUE THREAD

**Issue by claviola** [powerline/powerline#1479]
I can't come up with a way to make pip install on a proper location such as ~/bin or /usr/local/bin, so I guess the workaround for now is to either symlink from that directory or add it to my $PATH.

Everything I'm using is coming from MacPorts except for Powerline itself, which is the current Git version. OS X is current (El Capitan).

Here's a partial verbose output of pip showing the issue:

```
    byte-compiling /Users/carlos/Library/Python/2.7/lib/python/site-packages/powerline/theme.py to theme.pyc
    byte-compiling /Users/carlos/Library/Python/2.7/lib/python/site-packages/powerline/vim.py to vim.pyc
    running install_data
    creating /Users/carlos/Library/Python/2.7/bin
    copying scripts/powerline -> /Users/carlos/Library/Python/2.7/bin
    running install_egg_info
    Copying powerline_status.egg-info to /Users/carlos/Library/Python/2.7/lib/python/site-packages/powerline_status-2.3.dev9999+git.fc6c3d94741baa77cc75e86510fda88bafe8b9ec-py2.7.egg-info
    running install_scripts
    copying build/scripts-2.7/powerline-config -> /Users/carlos/Library/Python/2.7/bin
    copying build/scripts-2.7/powerline-daemon -> /Users/carlos/Library/Python/2.7/bin
    copying build/scripts-2.7/powerline-lint -> /Users/carlos/Library/Python/2.7/bin
    copying build/scripts-2.7/powerline-render -> /Users/carlos/Library/Python/2.7/bin
    changing mode of /Users/carlos/Library/Python/2.7/bin/powerline-config to 755
    changing mode of /Users/carlos/Library/Python/2.7/bin/powerline-daemon to 755
    changing mode of /Users/carlos/Library/Python/2.7/bin/powerline-lint to 755
    changing mode of /Users/carlos/Library/Python/2.7/bin/powerline-render to 755
    writing list of installed files to '/var/folders/j2/pfmcwmg15rdby4qc549mggs00000gp/T/pip-liwFQ2-record/install-record.txt'
  Removing source in /var/folders/j2/pfmcwmg15rdby4qc549mggs00000gp/T/pip-HkHkJA-build
Successfully installed powerline-status
Cleaning up...
```

**Comment by ZyX-I** [comment]
It is installed to that location because I use

    data_files=(None if can_use_scripts else (('bin', ['scripts/powerline']),)),

`setuptools.setup` argument because `setuptools` does not support “script” which is an ELF binary (other scripts are installed using `scripts=…` argument).

Note: “does not support ‘script’ which is an ELF binary” means “depending on setuptools version, either *silently* messes up with newline characters inside or simply crashes due to ‘script’ not being a valid executable”. If you know how to workaround this you are welcome to run a PR.

**Comment by claviola** [comment]
I understand the limitation, but perhaps it should be documented somewhere. I was a bit mystified as to how I had to install these helper scripts like ```powerline-config``` referenced in the installation guide as they were nowhere to be found in my $PATH, and without running pip in verbose mode you're none the wiser.

**Comment by ZyX-I** [comment]
@claviola Can you verify that workaround in #1480 works?

**Comment by claviola** [comment]
Only when I get back to my OS X box on Tuesday. I'll confirm as soon as possible, though.

**Comment by claviola** [comment]
Doesn't seem to work for me yet, the message isn't displayed.

```
$ pip install --user git+https://github.com/ZyX-I/powerline.git@fix-osx-script-install
Collecting git+https://github.com/ZyX-I/powerline.git@fix-osx-script-install
  Cloning https://github.com/ZyX-I/powerline.git (to fix-osx-script-install) to /var/folders/j2/pfmcwmg15rdby4qc549mggs00000gp/T/pip-ckoAyl-build
Installing collected packages: powerline-status
  Running setup.py install for powerline-status
Successfully installed powerline-status-2.3.dev9999+git.1947eb7e60beadcdd3f8f248ddd8924fdab59a05
```

**Comment by ZyX-I** [comment]
@claviola `pip` redirects/overwrites `sys.stdout` AFAIK: I see indented messages without requisting indentation. Don’t check messages, I do not know rules for suppressing them, check the intended result.

**Comment by claviola** [comment]
@ZyX-I sorry, I did not really understand what you meant about indented messages, do you mean my output? If so, I did that on purpose, I'm sorry. What I understood from your code is that you added a warning about where the binaries would be installed, right? But if pip overwrites `sys.stdout`, then how do I test if this is working?

**Comment by ZyX-I** [comment]
@claviola No, this is a debug message. I fixed the path, so it should install to the same directory other scripts go.

**Comment by claviola** [comment]
@ZyX-I Ah, right. In the meantime I asked on the macports IRC channel and they told me it was a deliberate decision to install scripts in that directory instead of a system-wide directory to prevent the same package in other installed python versions from "winning" by being installed first. At least this issue should be some form of documentation should someone stumble upon it as well.
