### ISSUE TITLE
powerline-tmux turns black after few keystrokes

### ISSUE THREAD

**Issue by fedemp** [powerline/powerline#148]
I've reinstalled powerline using latest commit 7022b47ed984d11474b1aa5721099620cc20956c and now tmux will turn into a black bar after I start typing. When it starts it shows the left prompt as expected.

I had to remove `"colorscheme": "default"` or `"theme": "default"` from the `tmux` section in config.json. Removing any of those two lines fixes the issue.

I'm using zsh 5 on Ubuntu 12.10 and powerline was installed under a python2.7 directory.

**Comment by Dynasty9** [comment]
+1 I've had the same problem
