### ISSUE TITLE
I can't add any segment to right side of ipython

### ISSUE THREAD

**Issue by sassanh** [powerline/powerline#1481]
I added this for test to my ipython theme (in.json):

    "right": [
      {
        "function": "powerline.segments.common.time.date",
        "args": {
          "format": "%Y-%m-%d %H:%M:%S"
        },
        "priority": 100
      }
    ]

but it's not working, nothing is shown on the right hand side of ipython.

though my changes to "left" list apply immediately.

**Comment by ZyX-I** [comment]
Powerline is using program own capabilities. Readline used by IPython does not support right prompts.
