### ISSUE TITLE
Duplicate virtual environment prompt with conda

### ISSUE THREAD

**Issue by ethanluoyc** [powerline/powerline#1487]
I am using conda for managing python packages. However I noticed that when I change to a conda environment there will appear duplicate virtual env prompt, illustrated below:
![image](https://cloud.githubusercontent.com/assets/6040760/11021446/5e733bcc-867c-11e5-8769-6b2e4afb02db.png)

However, sourcing the .zshrc file agains seems to fix it, but I cannot do this manually every time.

**Comment by ZyX-I** [comment]
You need to configure `activate` script to not prepend `(data)` to your prompt. It is none of the powerline issue.

**Comment by sbusch** [comment]
As a reference for others having this problem: http://conda.pydata.org/docs/config.html#change-command-prompt-changeps1
