### ISSUE TITLE
Tmux 2.1 compatibility

### ISSUE THREAD

**Issue by ricpelo** [powerline/powerline#1488]
I tried it, but I'm unable to get powerline working with tmux 2.1, so I must be stuck in 1.9.

**Comment by ZyX-I** [comment]
Ref #1471.

**Comment by ZyX-I** [comment]
And you *must* describe what exactly does not work. This issue is INVALID and completely not helpful: if I do not need this information this means that I already know what is the problem and will fix it without your issue. If I do need this information it is absent.

**Comment by fdelacruz** [comment]
Well for me powerline simply ignores my tmux.conf

**Comment by ZyX-I** [comment]
@fdelacruz How does it ignore `tmux.conf`? It cannot possibly do this because powerline is setup there, *not* powerline sets up tmux, including sourcing `tmux.conf`.

**Comment by fdelacruz** [comment]
Hi, I apologise, I just needed to make the powerline executables folder available in my path.
A simple `export PATH="/Users/fdelacruz/Library/Python/2.7/bin:$PATH"` seems to do the trick.
![tmux](https://cloud.githubusercontent.com/assets/148098/11373523/b9dde41e-92a0-11e5-9cd0-8c46bb96fd17.jpg)

**Comment by axltxl** [comment]
I've been kind of pulling my hair on this thing, I'm using tmux `HEAD` and my powerline broke as soon as I installed it. **Apparently `set -g status-utf8` is the offending configuration directive in tmux** since it does not seem to be present at all (not even mentioned in its man pages). I'm still gathering information about this since `tmux`'s changelog does not state this option to have been deprecated. Long story short, below is my testimony under `tmux -2 -u`:

```bash
powerline-config tmux setup                                                            ~/.dotfiles
unknown option: status-utf8
Traceback (most recent call last):
  File "/usr/local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/usr/local/lib/python2.7/dist-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/powerline/bindings/config.py", line 212, in tmux_setup
    source_tmux_files(pl, args, tmux_version=tmux_version, source_tmux_file=stf)
  File "/usr/local/lib/python2.7/dist-packages/powerline/bindings/config.py", line 74, in source_tmux_files
    source_tmux_file(os.path.join(TMUX_CONFIG_DIRECTORY, 'powerline-base.conf'))
  File "/usr/local/lib/python2.7/dist-packages/powerline/bindings/config.py", line 199, in source_tmux_file_nosource
    run_tmux_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/powerline/bindings/tmux/__init__.py", line 32, in run_tmux_command
    _run_tmux(subprocess.check_call, args)
  File "/usr/local/lib/python2.7/dist-packages/powerline/bindings/tmux/__init__.py", line 27, in _run_tmux
    return runner([get_tmux_executable_name()] + list(args))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'tmux', 'set', '-g', 'status-utf8', 'on']' returned non-zero exit status 1
```
I will continue to follow this, I think guys at the IRC channel could give a thorough statement on this one. Should this be the issue, no one using `tmux 2.1+` would achieve to see its powerline working. I hope this helps. Maybe `tmux` uses UTF-8 by default, who knows? ... Thanks.

Cheers :wine_glass:

**Comment by ZyX-I** [comment]
@axltxl You may be sure that at least tmux-2.1 from https://github.com/powerline/deps works. It is tmux checked out from git (using tag `2.1`) and compiled by https://github.com/powerline/bot-ci on travis.

**Comment by axltxl** [comment]
Yep!, you're right!, I have compiled `tmux` at `2.1` and it worked flawlessly and playing by the rules. Anyways, I think it's good for you to know that *maybe* new version of `tmux` wouldn't work with `powerline`. Thanks for your enlightenment!. 

Cheers :wine_glass:

**Comment by ZyX-I** [comment]
@axltxl If this was an issue with `master` branch then I should say that it is not supported. They sometimes break things which get fixed afterwards, and it would also be rather hard to correctly verify that `master` branch works with powerline.
