### ISSUE TITLE
git status shows as dirty when ignored files exist

### ISSUE THREAD

**Issue by jsjohnst** [powerline/powerline#1492]
The purpose of adding something to `.gitignore` is for them to be *ignored* by anything related to git. As such, I don't understand why Powerline shows the git repo as dirty when there are ignored files. Happy to submit a patch, but I wanted to understand the logic behind this first in case there was a use case I didn't think of.

**Comment by ZyX-I** [comment]
It *does not* show that repo is dirty when there are ignored files. I also do not see anything like this in the code.

**Comment by ZyX-I** [comment]
Note: if you saw `I` in repository status this has *absolutely* nothing to do with ignored files, it means “has changes in _I_ndex”.

**Comment by jsjohnst** [comment]
https://github.com/powerline/powerline/blob/develop/powerline/lib/vcs/git.py#L118
https://github.com/powerline/powerline/blob/develop/powerline/lib/vcs/git.py#L177

So want to change your statement there?

**Comment by ZyX-I** [comment]
@jsjohnst Do you see `if path`? This is *file* status, `status_colors` is *repository* status.

**Comment by ZyX-I** [comment]
And I am not going to ignore “ignored” *file* status.

**Comment by jsjohnst** [comment]
Ok, so if I remove --ignored (or make a comparable change in the pygit2 block), the repo shows as clean when there are ignored files. So either you are wrong or are not communicating the point you are trying to make.

**Comment by jsjohnst** [comment]
Also, the repo status I am talking about is the one for a bash prompt, so it's definitely not on a file basis.

**Comment by ZyX-I** [comment]
@jsjohnst Here is the simple script:

```Sh
git init repo
cd repo
export POWERLINE_THEME_OVERRIDES="default_leftonly.segment_data.branch.args.status_colors=true"
export POWERLINE_CONFIG_OVERRIDES="ext.shell.theme=default_leftonly"
export POWERLINE_CONFIG_PATHS="$HOME/.vam/powerline/powerline/config_files"
powerline shell left ; echo
echo test > .gitignore
powerline shell left ; echo
git add .gitignore
git commit .gitignore -m 'Test'
powerline shell left ; echo
touch test
powerline shell left ; echo
cd ..
rm -rf repo
```

. It shows repository as dirty as expected only once: after “echo test > .gitignore”. After adding ignored “test” file repository is still  not dirty.

**Comment by jsjohnst** [comment]
@ZyX-I Here's an example to show what I mean... 
<img width="738" alt="image 2015-11-15 at 6 44 16 pm" src="https://cloud.githubusercontent.com/assets/5507/11171876/087cfe5e-8bc9-11e5-8707-74db193f152b.png">

**Comment by ZyX-I** [comment]
@jsjohnst Without a script to reproduce the issue I cannot do anything. The code which handles ignored files is not getting triggered by using `status_colors` and I have no idea why you see changes to it doing anything.

**Comment by ZyX-I** [comment]
Also most of time such issues indicate that powerline did not pick some change (it is *especially* the problem on OS X because pyuv-based filesystem watcher occasionally misses some events even on linux, and I have no idea why), this should be solved by restarting powerline daemon (if you use it, if you don’t you should not have this kind of problem at all; though I can hardly understand how can use powerline as a shell prompt without a daemon because it is pretty slow in this case).

**Comment by jsjohnst** [comment]
@ZyX-I Ok, so that last comment helped. If I kill and restart the power line daemon, then it works just fine. So the issue is that daemon is missing events.
