### ISSUE TITLE
Tmux uptime segment missing

### ISSUE THREAD

**Issue by fdelacruz** [powerline/powerline#1504]
No errors, just the tmux uptime segment quietly missing. 
I do have psutil installed. I've tried both 3.x and to 2.x to no avail.
![shot3](https://cloud.githubusercontent.com/assets/148098/11399900/233a7b86-9358-11e5-9121-4c405f2c1742.jpg)

**Comment by itsachen** [comment]
@fdelacruz I'm experiencing this as well, did you manage to find a solution?

**Comment by s-ol** [comment]
@itsachen in the default tmux config `uptime` has a priority of `50`, is there even enough space to show it?

**Comment by itsachen** [comment]
Yes - I even tested by removing the priority attribute in the config as well.

**Comment by BlitzKraft** [comment]
What other segments do you have enabled? 

Even with the priority removed, powerline hides segments when there is not enough screen width.

**Comment by itsachen** [comment]
Strangely enough restarting my computer restored the missing segments
