### ISSUE TITLE
environment variables set as tmux segments never update value

### ISSUE THREAD

**Issue by sheriferson** [powerline/powerline#1505]
I tried to set a couple of environment variables as tmux segments. Example:

```
{
  "function": "powerline.segments.common.env.environment",
    "args": {
      "variable": "tnumAll"
    }
 },
```

The variable does show up with the correct value in the correct location when I start a tmux session, but then it never changes even though the environment variable does change. I've confirmed this by typing `echo $tnumAll` and getting the correct value that differs from the one displayed in powerline bar in tmux. I have to close the session and start a new one to see the new values.

By contrast, setting this environment variable as a shell segment works as expected. With every new prompt line, the value displayed is the current one.

I tried looking around for similar reports but didn't find anything, so I'm not sure if this is expected behaviour, or if I'm missing some customization trick, or if it's a bug.

I'm seeing thing with:
powerline: 2.3
tmux: 2.1 (installed with Homebrew)
and iTerm 2.1.4 (latest stable) on OS X 10.11.1

**Comment by ZyX-I** [comment]
Environment variables are taken from the tmux *server* context. But even if they were taken from client (BTW, I have no idea how you can get environment variable from client) shell process running as the client children has *nothing* to do with its parent (except that they are by default copied from the parent at the very start, which I am not sure is the case) and cannot affect its environment.

This is *not* a bug, this is how things work in \*nix world. Child environment variable changes never affect its parent, not to mention environment of the child (tmux client) [of the child]* (optional, e.g. hilite: nothing can prevent you from running shell not directly by tmux, but by other shell or a program like hilite) of the child (shell)

**Comment by ZyX-I** [comment]
If you need to alter tmux server environment variables use `tmux set-environment [-g]`. In shell this will appear only when you create next tmux client instance with the shell.

**Comment by sheriferson** [comment]
Thanks for your response.
