### ISSUE TITLE
unknown option: status-utf8

### ISSUE THREAD

**Issue by itdev-gozaru** [powerline/powerline#1509]
error occurs:
 subprocess.CalledProcessError: Command '[u'tmux', 'set', '-g', 'status-utf8', 'on']' returned non-zero exit status 1

status-utf8 option is removed in latest tmux.

**Comment by ZyX-I** [comment]
Latest version is 2.1 and it does contain this option. VCS version is not supported.

**Comment by ZyX-I** [comment]
Though there is another reason to drop this option: powerline does not output *UTF-8*, it uses *whatever the locale encoding is*. So it will be dropped. But this issue is still INVALID.
