### ISSUE TITLE
Ctrlp's search field disappears using Powerline

### ISSUE THREAD

**Issue by KevinSjoberg** [powerline/powerline#1511]
When using CtrlP to navigate between files, the search field disappears when using Powerline. See the video below for a demonstration of the problem.

http://d.pr/i/10iwp/2PhkvJGN

Powerline installed via `pip`:

    ---
    Metadata-Version: 2.0
    Name: powerline-status
    Version: 2.3
    Summary: The ultimate statusline/prompt utility.
    Home-page: https://github.com/powerline/powerline
    Author: Kim Silkebaekken
    Author-email: kim.silkebaekken+vim@gmail.com
    License: MIT
    Location: /usr/local/lib/python2.7/site-packages
    Requires:

Vim installed via `brew`:

    vim: stable 7.4.963, HEAD
    Vi "workalike" with many additional features
    http://www.vim.org/
    Conflicts with: ex-vi
    /usr/local/Cellar/vim/7.4.963 (1620 files, 29M) *
        Built from source with: --override-system-vi --with-lua --with-luajit
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/vim.rb

I'm using iTerm2 (2.1.4) on OS X (10.11.2). The video was taken within tmux (tmux 2.1). As you can see, as I type, the search field flickers but eventually the text disappears. Doing the same thing outside tmux result in the same problem, except now the whole screen flickers.

**Comment by ZyX-I** [comment]
Unable to reproduce this with

    vim -N -u NORC -i NONE --cmd 'set rtp=~/.vam/ctrlp,~/.vam/powerline/powerline/bindings/vim' readme.md

(commit b40119a18704a3f346e4c5e3cb6bb33f2610f2d8) and then typing `<C-p>` and some search term.
