### ISSUE TITLE
External IP segment causes entire status line to fail if unable to connect

### ISSUE THREAD

**Issue by bacondropped** [powerline/powerline#1512]
If Internet connection is down, or powerline is unable to resolve given URL, or any other network-based exception occurs during the call of `_external_ip(query_url)` in `segments/common/net.py`, that function raises an unhandled exception which causes entire powerline to display that exception.

From the user perspective, displaying a concise error message instead, something like `No connection` or disabling the segment altogether would provide a smoother user experience. I'm submitting a pull request which implements this behavior.

**Comment by ZyX-I** [comment]
Where and what exactly do you see? Exceptions are already caught and logged, but if you are not redirecting log (there is configuration option for this) and are not using daemon you will see the exception in tmux.

**Comment by ZyX-I** [comment]
I have added `raise ValueError` to the `_external_ip` function and the resulting exception is caught and logged as expected.
