### ISSUE TITLE
A lot of space between the cursor and the arrow with Fish shell

### ISSUE THREAD

**Issue by daudich** [powerline/powerline#1514]
Even if there is an error the space remains. If I `cd` into a directory the space doubles. Hitting return doesn't help either.
I am using Elementary OS.

![screenshot from 2016-01-02 03 17 55](https://cloud.githubusercontent.com/assets/2798620/12073781/74c1d1e2-b0ff-11e5-9b3b-7278ac169189.png)

**Comment by ZyX-I** [comment]
Fish versions less then 2.1 are not supported. Also if you use true colors in fish, this is not supported as well (in both cases fish is unable to detect sequences used to color prompt, but non-true-color sequences detection was fixed in 2.1 and true color was not at all AFAIK).
