### ISSUE TITLE
Tmux powerline status bar reverting after using source command

### ISSUE THREAD

**Issue by paanvaannd** [powerline/powerline#1516]
After configuring Powerline to work with tmux as stated in the documentation, the status bar looks as follows regularly even though I have configured some extra information to show there:

<img width="570" alt="tmux_powerline_regular" src="https://cloud.githubusercontent.com/assets/16567134/12131098/b49a8bde-b3dd-11e5-8350-b0c01388621c.png">

After running the "tmux source" command, the screen flutters and looks like the following, almost as desired, for about half a second before reverting to the state in the first image:

<img width="570" alt="tmux_powerline_issue" src="https://cloud.githubusercontent.com/assets/16567134/12131124/e0a22cc8-b3dd-11e5-8079-0a40ef1e2a27.png">

The following is my .tmux.conf file as a plaintext document:
[paanvaannd.tmux.conf.txt](https://github.com/powerline/powerline/files/79230/paanvaannd.tmux.conf.txt)

Machine info:
Retina MacBook early 2013, OS X El Capitan, using iTerm2 v2.1.4

**Comment by ZyX-I** [comment]
You have set `status-right` option which is controlled by powerline. If you need information that powerline does not show, you should configure powerline, *not* mess with `status-right` option.
