### ISSUE TITLE
[Powerline] Display full file path in Powerline for Vim?

### ISSUE THREAD

**Issue by phongvcao** [powerline/powerline#1518]
Hi,

I just want to know how to show full file path in Powerline for Vim? I mean normally without Powerline I would add something like the following to my `.vimrc` to show the full file path:

```vim
set statusline+=%F
```

However, in Powerline for Vim, only the file name is displayed (for example, `./.vimrc` when I open `.vimrc` from my home directory). How can I display the full file path in Vim with Powerline?

**Comment by ZyX-I** [comment]
For questions there is mailing list. You need to read powerline.segments.vim.file_directory segment documentation.
