### ISSUE TITLE
How to display output of arbitrary shell command in powerline segment?

### ISSUE THREAD

**Issue by jottr** [powerline/powerline#1519]
I would like to display the free disk space in a segment.
How could I achieve this? There seems to be no existing segment for this.

**Comment by ZyX-I** [comment]
For questions there is mailing list. Read documentation regarding developing segments.

**Comment by jottr** [comment]
Will do.

**Comment by donifer** [comment]
@jottr Did you figure this out? I'm also trying to display the output of an arbitrary command and can't figure it out.
