### ISSUE TITLE
Changing edit mode in multiline zsh prompt causes redraw in the wrong place

### ISSUE THREAD

**Issue by alh84001** [powerline/powerline#1529]
I configured a multiline zsh prompt (3 lines, first line completely empty), and there is one thing that is quite annoying. When changing edit mode (I use vi mappings), the prompt gets redrawn in such a way that current command entry line jumps two lines up, to where the prompts initial first line was drawn.

![mode](https://cloud.githubusercontent.com/assets/2332355/13031005/17561d9e-d2bd-11e5-82c4-b6d4b2b971a9.gif)

**Comment by ZyX-I** [comment]
How did you configure zsh prompt?

**Comment by alh84001** [comment]
Here is my ~/.config/powerline/themes/shell/default.json

[shell_default.json.txt](https://github.com/powerline/powerline/files/129476/shell_default.json.txt)

**Comment by ZyX-I** [comment]
I am unable to reproduce this using

    POWERLINE_CONFIG_OVERRIDES=ext.shell.theme=alh84001 zsh -f  # Run zsh using your theme saved to ~/.config/powerline/themes/shell/alh84001.json
    bindkey -v
    source /path/to/powerline/powerline/bindings/zsh/powerline.zsh

, also with `POWERLINE_NO_ZSH_ZPYTHON=1`. Zsh version is 5.1.1.

What is your zsh version?

**Comment by ZyX-I** [comment]
Also are you able to reproduce this using my sequence (you should not need setting POWERLINE_CONFIG_OVERRIDES, I meant with `zsh -f`).

**Comment by ZyX-I** [comment]
And can you reproduce this bug using

    zsh -f
    setopt promptsubst
    zle-keymap-select() {
        MODE=$KEYMAP[1]
        zle reset-prompt
    }
    zle -N zle-keymap-select
    bindkey -v
    MODE=u
    PS1=$'\n~\n$MODE>> '

and then switching modes (note: this is not a code that may show correct mode always, this is not its purpose)? If yes and your zsh version is not outdated then you should go to zsh mailing list because it is not a powerline bug.

**Comment by alh84001** [comment]
Loading with `zsh -f`, I couldn't repro the issue. I still haven't try the second command set.

My zsh is the one which ships with El Capitan
    
    % zsh --version
    zsh 5.0.8 (x86_64-apple-darwin15.0)

**Comment by ZyX-I** [comment]
@alh84001 There should be something conflicting then. Note that powerline keeps widgets that were run at zle-keymap-select and runs them. You may check what is that previous widget (if any) by investigating $_POWERLINE_SAVE_WIDGET

**Comment by ZyX-I** [comment]
Also something may be bound to `reset-prompt` widget. What is bound to `reset-prompt` may be checked by running `zle -l -L reset-prompt`.

**Comment by ZyX-I** [comment]
I have empty (unset) $_POWERLINE_SAVE_WIDGET and _zsh_highlight_widget_reset-prompt bound to reset-prompt widget and this works fine.

**Comment by alh84001** [comment]
This is the output on my system.

     ❯❯❯ zle -l -L reset-prompt
    zle -N reset-prompt _zsh_highlight_widget_reset-prompt
    
     ~
     ❯❯❯ echo $_POWERLINE_SAVE_WIDGET
    _powerline_save_zle-keymap-select


When running using `zsh -f`, both of these return nothing.

**Comment by ZyX-I** [comment]
@alh84001 Reset-prompt widget should be fine. But you need to do something so that $_POWERLINE_SAVE_WIDGET is empty if I am not mistaking (set it to empty and check to confirm).

Based on the contents of $_POWERLINE_SAVE_WIDGET I may say that you additionally have `_powerline_save_zle-keymap-select` function which contains two commands: `emulate -L zsh` and `zle-keymap-select $@`; and you have a function `zle-keymap-select` which is suspected to interfere. Function contents may be obtained by running `whence -f $function_name`.

**Comment by ZyX-I** [comment]
I do not know how to determine where `zle-keymap-select` function and old widget was defined.

**Comment by alh84001** [comment]
Well this is interesting. I unset the $_POWERLINE_SAVE_WIDGET var and this almost causes the issue to disappear. Now when I enter vicmd mode, it behaves correct, but returning to viins mode, still causes redraw in the wrong place.

This is a bit over my head with regards to zsh, as I started using it only recently, but I'll keep poking around, and tweak the zpresto config. Thanks for all the help.
