### ISSUE TITLE
PowerLine is not working with Root

### ISSUE THREAD

**Issue by udara-u3** [powerline/powerline#1530]
![terminal](https://cloud.githubusercontent.com/assets/12265797/13044905/0c0b106a-d3ea-11e5-86df-05b50e784300.png)

I'm using Elementary Os, PowerLine is only working for Local user, when I logged in to Root, It's disappeared.

**Comment by ZyX-I** [comment]
Root is a different user with a different $HOME and thus different location of configuration files. Your user configuration is not supposed to work unless you made it work explicitly (e.g. by symlinking).

**Comment by djap96** [comment]
Hello, any guide to do this for linux noobies?

**Comment by ZyX-I** [comment]
@djap96 Root is more or less the same user as your own one. There is nothing special in configuring shell there, configure it like your primary user.

**Comment by finix14** [comment]
Adding these three lines in ~root/.bashrc solved the problem 
```
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/share/powerline/bindings/bash/powerline.sh
```

**Comment by christianbueno1** [comment]
yes , ok, it is fine to know that. thanks @ZyX-I
