### ISSUE TITLE
Direct X rendering and Windows

### ISSUE THREAD

**Issue by Sharlock93** [powerline/powerline#1533]
I found that using direct X to render the fonts will produce a much better result, I posted the results over at airlines, but I'm gonna copy paste them here, mostly because it will help to generate more accurate powerline symbols.

(I didn't find any topics on these in the issues, so I made one)
We know that the status bar even after font patching on windows will still is not perfect like you see on MacVim, so did a little searching, and I found that vim has rendering support for Direct X which is much better than the current rendering using GDI, but your vim has to support it, after a few tests, I have the following results:

Without Direct X (Status Bar)
![Status Bar Old](http://puu.sh/n8Ac8/ea6b69485e.png)

With Direct X (Status Bar)
![Status Bar New] (http://puu.sh/n8Ahw/caf5ff0f9a.png)

Without Direct X (Unicode Symbols from the Help)
![Unicode Sym old](http://puu.sh/n8Ae7/5dae6e1298.png)

With Direct X (Unicode Symbols from help)
![Unicode Sym New](http://puu.sh/n8AjA/4f4cc9a9fa.png)

Without Direct X (Powerline Symbols)
![Powerline sym old](http://puu.sh/n8Af5/26832dd4b0.png) 

With Direct X (Powerline Symbols)
![PowerLIne symbols New](http://puu.sh/n8Ako/5257a276c4.png)

This is the Vim I used: [Vim x64 with Direct X](https://bintray.com/veegee/generic/vim_x64/7.4.1403/view)
Thanks to Veegee we have the latest vim with Direct X enabled.

Also once you have Direct X support, you have to turn it on like the following:

    set encoding=utf-8   
    set rop=type:directx,gamma:1.0,contrast:0.5,level:1,geom:1,renmode:4,taamode:1

all of those options are adjustable, after a few tests, those worked for me, you can change them for yourself, but the last 3 options (geom, renmode, taamode) those I got the best result using those values.

I think with a few modifications to the font patching, we could get a much better result.
One disadvantage I noticed is it slows down vim a bit, not a lot, but noticeable.

So tell me what you think.

**Comment by ZyX-I** [comment]
I do not see what is an issue: you want documentation update or what? Also modifications to the font patching should be discussed in font patcher repository (not sure though whether anybody actually maintains it).
