### ISSUE TITLE
vcs.branch segment does not appear in tmux

### ISSUE THREAD

**Issue by cody-somerville** [powerline/powerline#1535]
I attempted to add the vcs.branch segment to powerline in tmux but it does not appear when I change my working directory to a directory containing a git repository.

Interestingly enough, if I source /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh to enable the bash powerline in a tmux session then the branch segment starts working as expected in the tmux statusline.

I have powerline 2.3 installed from pypi.

Here is my powerline config:

```Diff
diff -Nur /usr/local/lib/python2.7/dist-packages/powerline/config_files/themes/tmux/default.json /home/cody-somerville/.config/powerline/themes/tmux/default.json
--- /usr/local/lib/python2.7/dist-packages/powerline/config_files/themes/tmux/default.json      2016-02-21 21:17:15.000000000 -0700
+++ /home/cody-somerville/.config/powerline/themes/tmux/default.json    2016-02-27 11:52:22.650562594 -0700
@@ -1,7 +1,20 @@
 {
+       "segment_data": {
+               "branch" : {
+                       "before": " ",
+                       "args": {
+                               "status_colors": true
+                       }
+               }
+       },
        "segments": {
                "right": [
                        {
+                               "name": "branch",
+                               "function": "powerline.segments.common.vcs.branch",
+                               "priority": 50
+                       },
+                       {
                                "function": "powerline.segments.common.sys.uptime",
                                "priority": 50
                        },
```

Here is my tmux configuration:

```
set-option -g history-limit 5000
run-shell "powerline-daemon -q"
source "/usr/local/lib/python2.7/dist-packages/powerline/bindings/tmux/powerline.conf"
```

**Comment by ZyX-I** [comment]
Tmux statusline is being evaluated in the context of the tmux server, powerline does not and cannot know what is the current working directory of the *client*. Shell bindings contain code that exports this data, as well as code that sets up prompt, and these codes are *separate* and can be disabled. By default they are both enabled. See `components` key in documentation in configuration reference page.

**Comment by rfkrocktk** [comment]
Can we update the documentation to make this more clear in the components?

**Comment by ZyX-I** [comment]
@rfkrocktk  ead3ff33f3b2984f16892e1fff0c494209b51b01

**Comment by rfkrocktk** [comment]
@ZyX-I Excellent work, it's now very clear how to do what I need/want it to do!
