### ISSUE TITLE
tmux quirky status line

### ISSUE THREAD

**Issue by rjrobinson** [powerline/powerline#1538]
Having an issue with tmux. I set it up as per the instructions on the site yet when I load it up, I get the status bar that stacks on top of each other. as well as an error within my prompt. It is non-existant. I had to ctrl-c and I get these errors. 
![Image1](https://dl.dropboxusercontent.com/u/9377605/Screen%20Shot%202016-03-02%20at%2011.35.18%20AM.png)

**Comment by rjrobinson** [comment]
tmux.conf 
```
  1 unbind C-b
  2 set -g prefix C-s
  3 set -g default-terminal "screen-256color"
  4
  5 source "/usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"
```

**Comment by rjrobinson** [comment]
And in regular shell im getting some overflow to the next line. 
![image2](https://dl.dropboxusercontent.com/u/9377605/Screen%20Shot%202016-03-02%20at%2012.30.26%20PM.png)

**Comment by ZyX-I** [comment]
Powerline does not alter tmux window width, it only tells tmux *what* to show, not *where*. If tmux thinks that terminal is wider then it actually is (which leads to wrapping and thus that effect of “stacking” status lines) then it is tmux bug. You should get the same problem even if you set `status-left` and `status-right` options to something that has nothing to do with powerline.

Though there is another possibility: tmux determines terminal width correctly, but it is not able to correctly determine *powerline characters* width. Problem here is that some terminal emulators have equivalent to Vim’s `&ambiwidth` option: it determines whether characters with “ambiguous” east asian width property should be considered single or doublewidth. All software which does not have `&ambiwidth` option equivalent considers them single-wide and you should configure your terminal emulator same. But if that is your problem then you should get gaps like between arrow and `master` branch in the last screenshot near *all* arrows.

In any case this is not a powerline issue. You should first try to find the ambiwidth option and if terminal does not have it or it is set to “single” report to tmux bug tracker. If you are using iTerm then I should say it *does* have this option.

**Comment by rjrobinson** [comment]
Oh. awesome... is it in the preferences?

**Comment by rjrobinson** [comment]
Never mind. Totally fixed it. Thanks for all the help!

**Comment by avocadoras** [comment]
woah. that fixed it for me too
