### ISSUE TITLE
Daemon not used by awesome binding 

### ISSUE THREAD

**Issue by michelesr** [powerline/powerline#1539]
I'm using the binding for awesome WM and when inspecting powerline daemon system calls with `strace` I  can't see any activity at all (while I seen activity from tmux binding for example).

Given that I'm using the same segments that i use in tmux, I should see a similar activity (for example fopen() for battery related `/proc/` files).

**Comment by ZyX-I** [comment]
There is no reason awesome bindings should use daemon. Daemon is used only when there is no other way to keep single Python interpreter instance running.

**Comment by michelesr** [comment]
Got it.
