### ISSUE TITLE
Issue with konsole and zsh

### ISSUE THREAD

**Issue by vinaychandra** [powerline/powerline#1541]
I am using zsh with Konsole and this is what I am seeing when I run tmux.
![snapshot1](https://cloud.githubusercontent.com/assets/5670927/13626590/61ae0840-e5e9-11e5-9654-9f9597abfe01.png)

Instead of seeing the arrow symbols and other font, I am just seeing a vertical line. What should be done so that it looks like in the screenshot

**Comment by ZyX-I** [comment]
You need to run tmux server (or powerline-daemon in case you are using daemon) with unicode locale. With other locales it will fall back to ASCII-only symbols.
