### ISSUE TITLE
Powerline/zsh extremely slow in git repos with large file counts

### ISSUE THREAD

**Issue by ttrmw** [powerline/powerline#1543]
Hey,

I'm finding zsh with powerline takes a long time to finish commands such as `ls`, `cd` in git repos with high file counts.. Is this a known issue? 

For example, the following project:

https://github.com/shakacode/react-webpack-rails-tutorial

Once npm install is run on this, the directory and its subdirectories will contain around 32000 files. The vast majority are `.gitignore`d, but the presence of so many files in a git repo seems to be the deciding factor for the massive slow downs I'm seeing: Powerline/zsh are really speedy in the root directory, and in repos with a low file count. In rbenv's gem installation paths, eg `$HOME/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.2`, or just generally under `$/.rbenv` (190~k files) things slow down heavily, but in a normal rails project everything is fine.

In the above project, the `client/node_modules` directory is the main offender, containing 29000 of the 32000 files. Note however that the problem is still exhibited in subdirectories outside of `node_modules`, eg `:/app/models`.

**Comment by ttrmw** [comment]
Note that running zsh without powerline fixes this. Untested with bash/powerline but can do so if it'd be helpful!

**Comment by ZyX-I** [comment]
You need to run the powerline daemon, otherwise it will be slow even without any repositories. Though not all people consider that slow.

**Comment by ttrmw** [comment]
That fixed it utterly. 

I couldn't find any mention of this outside of the FAQ section in the docs - would it be worth adding to the installation instructions? Happy to PR if it would be helpful!

**Comment by ZyX-I** [comment]
This is in docs/source/usage/shell-prompts.rst, also tips-and-tricks.rst. It should not be in the installation instructions, they do not contain even configuration necessary to use shell bindings.

**Comment by ttrmw** [comment]
True, my mistake - been a while since I followed the docs. Fair to say I must have skipped over that bit. Thank you! :grin:
