### ISSUE TITLE
powerline.segments.common.players.mpd: {elapsed} format is None

### ISSUE THREAD

**Issue by ncoop** [powerline/powerline#1550]
Music Player Daemon: 0.19.9
Powerline: powerline-2.3-1.fc23.src.rpm
tmux: 2.1

I am using the MPD segment with tmux. I tried dumping out all the valid format items for the player:

`~/.config/powerline/config.json`

```
{
	"common": {
		"log_file": "/tmp/powerline.log",
		"log_level": "DEBUG"
	},
	"ext": {
		"shell": {
			"colorscheme": "default",
			"theme": "default_leftonly",
			"local_themes": {
				"continuation": "continuation",
				"select": "select"
			}
		},
		"tmux": {
			"theme": "mpd"
		}
	}
}
```

`~/.config/powerline/themes/tmux/mpd.json`
```
{
	"segments": {
		"right": [
			{
				"function": "powerline.segments.common.players.mpd",
				"name": "player",
				"args": {"format": "{state_symbol} {album} {artist} {title} {elapsed} {total}"},
				"priority": 70
			},
			{
				"function": "powerline.segments.common.sys.uptime",
				"priority": 50
			},
			{
				"function": "powerline.segments.common.net.hostname"
			}
		]
	}
}
```

Everything looks OK during playback except {elapsed} always evaluates to None. The log shows nothing unusual.

**Comment by ZyX-I** [comment]
Do you have python bindings for mpd installed (i.e. python-mpd or python-mpd2)? If yes, what are their versions?

**Comment by ZyX-I** [comment]
Though I guess it is exactly the problem: you do not have these bindings and `MpdPlayerSegment` does not support `elapsed` without them. I checked the documentation of `mpc` and it appears that `elapsed` is not supported because `mpc` (0.27) does not support it, not because it *did* not support or author of the bindings missed something.

**Comment by ncoop** [comment]
OK, I have installed python-mpd 0.3.0
However, `elapsed` is now always `0:00`

**Comment by ncoop** [comment]
@ZyX-I: Applied your change and it works. Thank you.

**Comment by ncoop** [comment]
Want to point out that you can parse out the elapsed time from the second to last line of MPC's output, if `current` is not passed. It's hacky though, and an upstream fix would be better.
