### ISSUE TITLE
Powerline with tmux causes high CPU usage in tmux.

### ISSUE THREAD

**Issue by bedge** [powerline/powerline#1564]
Removed items from .tmux.conf and kept restarting tmux until I saw the CPU usage drop. Usage remained high until I removed:

> source /usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf

Started a few months ago, just finally lost patience with everything being so damn slow and started tracking it down.

Tried with and without the powerline -daemon with no change.

![screen shot 2016-04-04 at 3 40 58 pm](https://cloud.githubusercontent.com/assets/499317/14272762/b4645766-faba-11e5-9f92-9ebba00c0915.png)

> %> pip show powerline
> ---
> Metadata-Version: 1.0
> Name: Powerline
> Version: beta
> Summary: The ultimate statusline/prompt utility.
> Home-page: https://github.com/Lokaltog/powerline
> Author: Kim Silkebaekken
> Author-email: kim.silkebaekken+vim@gmail.com
> License: UNKNOWN
> Location: /usr/local/lib/python2.7/site-packages
> Requires:
> Classifiers:
> 

> 
> 
> %> brew info tmux
> tmux: stable 2.1 (bottled), HEAD
> Terminal multiplexer
> https://tmux.github.io/
> /usr/local/Cellar/tmux/1.9a (16 files, 599.2K)
>   Poured from bottle
> /usr/local/Cellar/tmux/2.0 (16 files, 620.6K)
>   Poured from bottle
> /usr/local/Cellar/tmux/2.1 (15 files, 648.8K) *
>   Poured from bottle
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tmux.rb
> ==> Dependencies
> Build: pkg-config ✔
> Required: libevent ✔
> ==> Caveats
> Example configuration has been installed to:
>   /usr/local/opt/tmux/share/tmux
> 
> Bash completion has been installed t

**Comment by ZyX-I** [comment]
I cannot reproduce this and I also do not think that this is powerline bug. Powerline has its own process(es) which may consume CPU, tmux only receives strings like `#[fg=colour233,bg=default,nobold,noitalics,nounderscore] …`. If receiving such string causes CPU usage go high, this is tmux bug.

**Comment by ZyX-I** [comment]
And pip package is named `powerline-status` which cannot have version `beta` at all. Most likely you are using *very* outdated version of powerline.

**Comment by bedge** [comment]
Understood, and thanks for the info.

Apologies for the package name error. Will followup with tmux.

The powerline vs powerline-status was a big help. I set this up years ago and it's been working flawlessly until this CPU thing came up.
