### ISSUE TITLE
only show vim tabline with more than one buffer or tab

### ISSUE THREAD

**Issue by dffischer** [powerline/powerline#1570]
I recently discovered that powerline can not only list tabs, but also buffers in vim - an extremely useful feature to me. But I found a detail that could be improved upon.

Currently, I can set vim's `showtabline` to `2`, showing it always, or to `1` showing it only when multiple tabs are open. I miss a setting to only show it when there is more than one tab or buffer open. As vim normally does not list buffers there at all, this is maybe an issue to powerline and not vim itself.

I do not know enough of vim to script when the tabbar should appear, but I found that its Python interface seems to have structures able to count both, as `:help python-tabpages` and `:help python-buffers` tell.

**Comment by ZyX-I** [comment]
You can probably construct something based on `Buf*` autocommands. But powerline does not ever control *when* statusline/tabline is shown, it controls only *what* is shown there, so this enhancement cannot be in the core.
