### ISSUE TITLE
Symbol colors are off in iTerm2

### ISSUE THREAD

**Issue by mixinmax** [powerline/powerline#1572]
Here's a screenshot of powerline in iTerm2 with patched fonts:

![screen shot 2016-04-16 at 11 17 47 am 1](https://cloud.githubusercontent.com/assets/866856/14581847/06f14576-03c5-11e6-8c25-bd5e14423cf3.png)

The symbols colors are off and I can't seem to get them to be the same color. I made sure that the contrast was correctly set in iTerm2. Any ideas?

**Comment by ZyX-I** [comment]
This is not about contrast. I usually see such problems when some kind of transparency is enabled.

Base problem is that grey at `colorschemes` is background color. Grey at arrow is foreground color. They may be actually different colors for various reasons, most common is transparency (background may be transparent, foreground may not). Maybe this will be fixed if you set config.json/common/term_truecolor to true (for testing you may do this by using `export POWERLINE_CONFIG_OVERRIDES=common.term_truecolor=true`, then restarting daemon if you use it), but if problem is exactly transparency this is not going to help.

**Comment by ZyX-I** [comment]
In any case this is not a powerline issue, so I am closing it. But this does not mean I will stop responding.

**Comment by mixinmax** [comment]
Thanks for the help - it was transparency in iTerm2. I removed it and set a background image instead.
