### ISSUE TITLE
tmux statusbar is outdated : "unknown option: status-utf8"

### ISSUE THREAD

**Issue by s0r00t** [powerline/powerline#1573]
Today's tmux update broke the Powerline statusbar : 
`tmux set -g status-utf8 on` is no longer valid. 
Tmux returns `unknown option: status-utf8`.

**Comment by ZyX-I** [comment]
It was already fixed. You must update powerline.

**Comment by s0r00t** [comment]
Sorry for the dupe then. I had updated before posting : guess i did before the update was pushed.

**Comment by ZyX-I** [comment]
@s0r00t It was long since fixed. But I do not remember whether fix is in any release version.

**Comment by s0r00t** [comment]
I am using latest pip(3) package. The fix is not present there.

**Comment by ZyX-I** [comment]
#1510
