### ISSUE TITLE
tmux: powerline doesn't integrate because of removed configuration opition

### ISSUE THREAD

**Issue by dcbaker** [powerline/powerline#1575]
When I start tmux I get the basic green status bar, even with the most minimal configuration possible:

```conf
source /usr/lib64/python3.5/site-packages/powerline/bindings/tmux/powerline.conf
```

When I run powerline-config tmux setup I get the following error:
```
unknown option: status-utf8
Traceback (most recent call last):
  ...
subprocess.CalledProcessError: Command '['tmux', 'set', '-g', 'status-utf8', 'on']' returned non-zero exit status 1
```

The traceback itself isn't very useful, but the stderr output of tmux is, looking at the tmux documentation, seting "status-utf8" has been unnecessary since the 1.0 release, it's auto-detected. When this was filed as a bug against tmux the advice was to remove the option (https://github.com/tmux/tmux/issues/230#), and I can confirm that for me (with tmux 2.2) removing that options from powerline-base.conf indeed fixes the issue and tmux+powerline works as expected.

I don't know how you want to handle this. I'd be happy to send a pull request to remove the configuration option, the documentation seems to suggest that it is safe to do so and it does fix my system with tmux 2.2, where it seems the option is not just deprecated by removed.

**Comment by ZyX-I** [comment]
This was already fixed in develop. Do use search.
