### ISSUE TITLE
What do double question marks mean?

### ISSUE THREAD

**Issue by pkasarski** [powerline/powerline#1577]
I tried the documentation but couldn't find this anywhere.

![image](https://cloud.githubusercontent.com/assets/1276286/14688616/1f7d1d8a-0709-11e6-859d-6c0d4e433ed7.png)

Would like to know what the two red question marks represent. Sometimes I also see just a single one.

**Comment by ZyX-I** [comment]
These statuses are directly from `git status --porcelain`, you need to check there. Specifically this one means that file is not tracked.

Questions should go to the mailing list, this is issue tracker.
