### ISSUE TITLE
New to powerline and needs some help

### ISSUE THREAD

**Issue by lxynox** [powerline/powerline#1582]
I am fairly new to powerline. I am using plugin 'vim-airline' for vim and really like it so i want to change my Terminal prompt look to be the same/similar.

I am using OSX EI Captain. After went through all the installation process on official-doc, my Bash prompt doesn't look as anticipated.

I put following into my bash_profile.
```bash
export PIP_INSTALL_HOME=/usr/local/lib/python2.7/site-packages(using brew install python)
powerline -daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. $PIP_INSTALL_HOME/powerline/bindings/bash/powerline.sh 
```

And here is how my bash prompt looks
<img width="675" alt="screen shot 2016-04-23 at 2 44 59 pm" src="https://cloud.githubusercontent.com/assets/10333817/14763383/fe6b1a4c-0961-11e6-8783-9d2e070bf396.png">

And my $PROMPT_COMMAND =
> powerline_set_prompt update_terminal_cwd

I just don't know how to approach this, thanks for any help!

**Comment by ZyX-I** [comment]
`$VAR=…` is no a valid way to assign variable in bash, you must use `VAR=`. String `(using brew install python)` should not be there. You have space after `powerline` so valid command `powerline-daemon -q` was turned into invalid call of `powerline`.

**Comment by ZyX-I** [comment]
And I guess you need to install powerline font or use different theme.

**Comment by lxynox** [comment]
Sorry for any confusions on described above. I updated them to be more accurate.

To change the font/theme i use, should i touch the `$powerline_root/powerline/config_files`, cause i don't find any detailed instruction here: http://powerline.readthedocs.org/en/master/installation/osx.html

**Comment by ZyX-I** [comment]
@lxynox Documentation that describes installation is the wrong source of information for configuration, there is a dedicated piece of documentation (configuration/reference, you need config.json/common/default_top_theme). You cannot change font by configuring powerline, powerline only outputs UTF-8 sequences for terminal to display. There is documentation regarding font installation somewhere.

**Comment by lxynox** [comment]
That also what i'm think, thank your for help 😀
