### ISSUE TITLE
[cygwin] powerline-config tmux setup consumes all available RAM

### ISSUE THREAD

**Issue by dutchgecko** [powerline/powerline#1590]
I recently had to reinstall my cygwin setup due to a hard drive failure. My binaries have been reinstalled, but my home directory was stored on a different drive and has remained intact. 

I have powerline installed from git (the stable version in pip has some kind of binary incompatibility). It works correctly for my shell and for vim, however since reinstalling it is now working incorrectly for tmux.

Upon running the command `powerline-config tmux setup` the computer becomes unresponsive, and task manager informs me that in just a few seconds powerline is consuming over 6GB of system memory. A few seconds later the cygwin process  and its subprocesses are killed by Windows.

Since my home environment hasn't changed I can only assume that a change in powerline since the last time I checked the repository out is the cause.

**Comment by ZyX-I** [comment]
What exactly consumes 6 GiB? `powerline-config tmux setup` only reads a few configuration files and runs a number of `tmux …` commands and I did not change anything which may consume 6 GiB.

Also saying about a change in powerline is useless unless you used `git bisect` to actually find out what change is responsible for this. You did not even provide “bad” and “good” commits.

**Comment by dutchgecko** [comment]
My apologies, I was rather assertive in my statements and further investigation shows that I've completely missed the mark.

I checked out some older tags of the develop branch and going back to 2.2 all of them exhibit the same behaviour. I'm pretty sure that I was using either 2.2 or 2.3 successfully before so the problem appears to lie with tmux.

The process which consumes the memory is the tmux process itself. It briefly hangs with the following data showing in the status bar:

![http://i.imgur.com/2r5XzeB.png](http://i.imgur.com/2r5XzeB.png)

I've since found that simply executing `tmux display -p "%0"` will cause the memory-consuming behaviour. Is the `%0` meant to be expanded to something, or is this a legitimate command which tmux is executing incorrectly?

Small note, I was running a customised powerline configuration but have since removed it, so this is occurring with the stock configuration.

**Comment by ZyX-I** [comment]
`tmux display` normally receives `#D`, not `%0`, it appears that they changed the place where `#…` is expanded. In any case this change should be harmless: `display -p '%0'` command means displaying `%0` literally without doing any computations at all: the only special character in format string is `#`.

**Comment by dutchgecko** [comment]
In the various tmux binding files the parameter given to the command is still `#D`, so it's not clear to me why this is being expanded into `%0` before the command is called. Calling `display -p '#D'` from the command line works correctly.

**Comment by ZyX-I** [comment]
I have tmux-2.1 and here it receives what is expected, not `%0`. This is basically why `tmux display` call is present in the first place.

**Comment by dutchgecko** [comment]
Further testing has showed that the problem does not occur with tmux 2.1 (and indeed that the variables are being expanded correctly). Therefore I'm going to close this issue and discuss it further with tmux.
