### ISSUE TITLE
Mode-dependent highlighting color issue

### ISSUE THREAD

**Issue by zachliu** [powerline/powerline#1591]
Re-sizing your window can mess up with the colors:
![p1](https://cloud.githubusercontent.com/assets/14293802/15084632/bf8f2d72-13a2-11e6-8892-46165443745b.png)
INSERT becomes green...
![p2](https://cloud.githubusercontent.com/assets/14293802/15084635/c3ae0162-13a2-11e6-8312-ca37b010a1cf.png)

**Comment by ZyX-I** [comment]
Which Vim version and terminal (window = Vim window or terminal window? if Vim then terminal is irrelevant)? Also can you reproduce starting with `vim -u NONE -i NONE`?

Also what powerline version and what is your user configuration?

**Comment by ZyX-I** [comment]
Better first answer the last question. I guess the answer is “no own configuration” which means that you are not using powerline: ![./ before file name](http://img-fotki.yandex.ru/get/47043/9151298.6/0_bd6e9_a9dcdf37_orig.png): note `./` before file name with default configuration. https://github.com/Lokaltog/vim-powerline is not supported.

**Comment by zachliu** [comment]
My bad. I just realized I was using airline instead of powerline. I'm so so sorry.
