### ISSUE TITLE
ZSH ImportError: No module named 'powerline' - Ubuntu 16.04

### ISSUE THREAD

**Issue by pierolenzo** [powerline/powerline#1595]
hi,
my zsh output

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'powerline'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '_powerline_setup' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '_powerline_setup' is not defined
Traceback (most recent call last):                                              
  File "<string>", line 1, in <module>
NameError: name '_powerline' is not defined

this is my config in .zshrc
POWERLINE_CONFIG_COMMAND=/home/piero/.local/bin/powerline-config
source /home/piero/.local/lib/python2.7/site-packages/powerline_status-2.4-py2.7.egg/powerline/bindings/zsh/powerline.zsh

My python path
python -c "import sys; import os; print(sys.path)"
['', '/home/piero/.local/lib/python2.7/site-packages/powerline_status-2.4-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/piero/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/FontTools', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2']

install dir
piero@piero-laptop:~% ls -lrta /home/piero/.local/lib/python2.7/site-packages/powerline_status-2.4-py2.7.egg 
total 20
drwx------ 21 piero piero 4096 mag 11 16:26 ..
drwxrwxr-x  3 piero piero 4096 mag 11 16:26 EGG-INFO
drwxrwxr-x  2 piero piero 4096 mag 11 16:26 bin
drwxrwxr-x  5 piero piero 4096 mag 11 16:26 .
drwxrwxr-x 13 piero piero 4096 mag 11 16:26 powerline

i defined POWERLINE_CONFIG_COMMAND because initially I had this error
/home/piero/.local/lib/python2.7/site-packages/powerline_status-2.4-py2.7.egg/powerline/bindings/zsh/powerline.zsh:200: no such file or directory: /home/piero/.local/lib/python2.7/site-packages/powerline_status-2.4-py2.7.egg/scripts/powerline-config
/home/piero/.local/lib/python2.7/site-packages/powerline_status-2.4-py2.7.egg/powerline/bindings/zsh/powerline.zsh:204: no such file or directory: /home/piero/.local/lib/python2.7/site-packages/powerline_status-2.4-py2.7.egg/scripts/powerline-config

thanks for your support

**Comment by ZyX-I** [comment]
Are you using `zpython` zsh module? You need to install powerline for the same Python version zpython was compiled with, check it with `zpython import sys; print(sys.version_info)`. Or define `POWERLINE_NO_ZSH_ZPYTHON` to 1 before sourcing powerline.zsh.

**Comment by ZyX-I** [comment]
Also with zpython `python -c "import sys; import os; print(sys.path)"` is not a correct command to check such things, use `zpython` in place `python -c`.

**Comment by pierolenzo** [comment]
bingo :)
i have compiled zpython with python3.5 but powerline on python 2.7
many thanks

**Comment by pierolenzo** [comment]
i used
`cmake .. -DZSH_REPOSITORY=/usr/include/zsh/ -DPYTHON_INCLUDE_DIR=/usr/include/python2.7/`

in the file /build/CMakeFiles/zpython.dir/build.make
i made some change, at row 61,39
`include/zsh/zsh.mdh: /usr/include/zsh/Src/zsh.mdh`
become
`include/zsh/zsh.mdh: /usr/include/zsh/zsh.mdh`

and row 63,45
`    ../process_zsh_header.sh /usr/include/zsh//Src/zsh.mdh /home/piero/Repositor    y/zpython/build/include/zsh/zsh.mdh`
become
 `   ../process_zsh_header.sh /usr/include/zsh//zsh.mdh /home/piero/Repositor    y/zpython/build/include/zsh/zsh.mdh`

**Comment by ZyX-I** [comment]
@pierolenzo You missed -DPYTHON_LIBRARY=/path/to/libpython2.7.so. And -DZSH_REPOSITORY=/usr/include/zsh is the wrong thing to do: -DZSH_REPOSITORY is for the case when you compiled zsh yourself and left sources (not cleaned: with temporary files from `make`!) somewhere.

**Comment by herculan0** [comment]
Solve this by putting in my ~/.vimrc:

```
let $PYTHONPATH='/usr/lib/python3.8/site-packages'
set laststatus=2

```

Don't have the error anymore.
