### ISSUE TITLE
Glyphs using rxvt-unicode

### ISSUE THREAD

**Issue by lukas-123** [powerline/powerline#1597]
Hello,
I am using rxvt-unicode compiled with unicode3 and 256color with zsh as my shell. The font I use is Inconsolata. I installed powerline with apt-get and tried to use `Inconsolata for Powerline` that comes with the Installation. 
When is use this font with `URxvt.font: xft:Inconsolata for Powerline:size=15` the result is the following: 
![default](https://cloud.githubusercontent.com/assets/11629114/15213243/566cd274-1846-11e6-8413-96d473a835fc.png)

When I use the patched font installed in `~/.fonts/` as `Inconsolata for Powerline patched` the result looks like this:
![patched](https://cloud.githubusercontent.com/assets/11629114/15213269/80370426-1846-11e6-95db-e78f15007143.png)

For other terminals `Inconsolata for Powerline` works though (gnome-terminal, xfce4-terminal).

EDIT: Some clarification.

**Comment by ZyX-I** [comment]
This is not the powerline issue, fonts have their own repository. Though it is better to first ask rxvt-unicode devs if in most terminals this works fine (in any case fonts repository is mostly unmaintained AFAIK).
