### ISSUE TITLE
Poweline isn't installing the bash bindings.

### ISSUE THREAD

**Issue by Tekkkz** [powerline/powerline#1600]
I have cloned the git repo, I run setup.py build && setup.py install, but bash bindings aren't intsalled?

Why?
How to fix that?

**Comment by BlitzKraft** [comment]
Did you modify your bashrc as mentioned [here](http://powerline.readthedocs.io/en/master/usage/shell-prompts.html) ?

**Comment by Tekkkz** [comment]
Yes, but my problem is not that it isn't running. My problem is, that setup.py install ISN'T installing the bash bindings. Following error at source .bashrc:

/usr/lib/python3.5/site-packages/powerline/bindings/bash/powerline.sh: No such file or directory

**Comment by ZyX-I** [comment]
You are not supposed to use `setup.py` directly. I have no idea why it is not installed, but you should use `pip`.

And package name is not `powerline`, it is `powerline-status`. I guess using pip will not change anything, but you supplied incorrect path: in my case `setup.py build && setup.py install` installs these bindings, but it installs them to ~/.virtenvs/test/lib/python2.7/site-packages/powerline_status-2.3.dev9999_git.f0b820bd7529a80fd800ff3d097712d473db0708-py2.7.egg/powerline/bindings/bash. And using python3.4 for the virtual env (do not have 3.5) does not really change anything regarding directory name.
