### ISSUE TITLE
`poweline-daemon` seems to corrupt rendering after restart

### ISSUE THREAD

**Issue by asfaltboy** [powerline/powerline#1602]
The status line rendered well up to a restart. After restarting my machine, and starting a new terminal session, the separators seem incorrect, and continues to be so until I issue `powerline-daemon --kill`. Here's a screen to explain:

![screen shot 2016-05-18 at 09 30 08](https://cloud.githubusercontent.com/assets/321520/15350894/69055ba0-1cdc-11e6-8ac2-f70e9526cc68.png)

Here is my installation location
```
pip show powerline-status
---
Metadata-Version: 1.1
Name: powerline-status
Version: 2.4
Summary: The ultimate statusline/prompt utility.
Home-page: https://github.com/powerline/powerline
Author: Kim Silkebaekken
Author-email: kim.silkebaekken+vim@gmail.com
License: MIT
Location: /Users/pavel/.local/lib/python2.7/site-packages
Requires:
Classifiers:
  Development Status :: 5 - Production/Stable
  Environment :: Console
  Environment :: Plugins
  Intended Audience :: End Users/Desktop
  License :: OSI Approved :: MIT License
  Natural Language :: English
  Operating System :: Microsoft :: Windows
  Operating System :: POSIX
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3.2
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: Implementation :: CPython
  Programming Language :: Python :: Implementation :: PyPy
```

Notes:
1. I have no local customizations.
2. I recently upgraded to iTerm2 Version 3 Beta (Build 2.9.20160510), but this issue occurs also in "vanilla OSX Terminal" app as well.

Please let me know if you need more info and I'll edit the issue to include it.

**Comment by BlitzKraft** [comment]
I can confirm this but I don't know how to cause it or what causes it. 

Even vim and tmux are affected by it. Sometimes restarting the powerline daemon works and sometimes I have to kill the daemon and restart my tmux session. 

I am on linux mint 17.1, tmux 2.1. Powerline version 2.2.dev9999.

**Comment by ZyX-I** [comment]
You must run your daemon with a UTF-8 locale. If you run it with non-UTF-8 locale it will assume that all its clients have same non-UTF-8 locale and thus disable fancy characters. Separators are correct for this case.

This should also be fixed by `--restart` from a UTF-8 locale, not `--kill`.

**Comment by asfaltboy** [comment]
Thanks @ZyX-I , I'll assume [this is the related doc entry](http://powerline.readthedocs.io/en/master/troubleshooting/osx.html?highlight=LANG#i-cant-see-any-fancy-symbols-whats-wrong), and since my current (working) environment contains `LANG=en_GB.UTF-8` , I'm going to try explicitly set `LC_` and `LANG` variables prior to running daemon in my `~/.bash_profile`. I'll report back if any issues persist.

**Comment by ZyX-I** [comment]
@asfaltboy Setting them in `~/.bash_profile` is usually not correct. My distro expects setting locale in `/etc/env.d/99locale`, modifying which then needs `env-update` which will collect environment from `/etc/env.d` into `/etc/profile.env` which is sourced by `/etc/profile`.

**Comment by asfaltboy** [comment]
That is very informative, I did not know that `LANG` variables may have cascading consequences.

[This helpful SE answer](http://apple.stackexchange.com/a/23175/58743) claims that the "Terminal" app configuration decides whether and which system locale environment variables are set on startup.

My best guess to what happened to us, is that after a system "restore" (dehybernation of sorts), the terminal app has not set the locale vars.
This should be confirmed by [running `locale` command](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/locale.1.html) when the issue reoccurs to someone.

If the variables are not set to `**.UTF-8` then we should probably advise in the docs to set the `LANG/LC_` variables in some way. And so far the only solutions I see suggested is using the `bash_profile` ... perhaps a OSX superuser can suggest a better way?

Coincidentally, the "Troubleshooting on OS X" section suggests to "Consult your Linux distro’s documentation for information about setting these variables correctly."; however, OSX is **not** a Linux distro - docs need to be fixed here as well.

**Comment by asfaltboy** [comment]
**Update:** Just encountered the issue again, and the `locale` command output seems legit:
```bash
pavel ~  locale
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL="en_GB.UTF-8"
```

This can only mean that the daemon was started in another "terminal" session outside of my current iTerm, and *before* the locale was set to the correct values; unfortunately, it is not plain to see what process the daemon was started from:

```bash
 pavel  ~  ps awux | grep powerline
pavel            1856   0.0  0.1  2510280  12148   ??  S     8:47am   0:00.29 /Users/pavel/.pyenv/versions/2.7.11/bin/python2.7 /Users/pavel/.local/bin/powerline-daemon -q
pavel            4965   0.0  0.0  2434840    732 s000  R+    9:36am   0:00.00 grep powerline
 pavel  ~  pstree -p 1856
-+= 00001 root /sbin/launchd
 \--- 01856 pavel /Users/pavel/.pyenv/versions/2.7.11/bin/python2.7 /Users/pavel/.local/bin/powerline-daemon -q
 pavel  ~  /Users/pavel/.local/bin/powerline-daemon --restart
usage: powerline-daemon [-h] [--quiet] [--socket SOCKET] [--kill]
                        [--foreground] [--replace]
powerline-daemon: error: unrecognized arguments: --restart
 pavel  ~  /Users/pavel/.local/bin/powerline-daemon --replace
Kill command sent to daemon, waiting for daemon to exit, press Ctrl-C to terminate wait and exit
 pavel  ~  ps awux | grep powerline
pavel            5252   0.0  0.0  2434840    788 s000  S+    9:37am   0:00.00 grep powerline
pavel            5156   0.0  0.1  2491080  10832   ??  S     9:37am   0:00.07 /Users/pavel/.pyenv/versions/2.7.11/bin/python2.7 /Users/pavel/.local/bin/powerline-daemon --replace
 pavel  ~  pstree -p 5156
-+= 00001 root /sbin/launchd
 \--- 05156 pavel /Users/pavel/.pyenv/versions/2.7.11/bin/python2.7 /Users/pavel/.local/bin/powerline-daemon --replace
```

By the way, we can see the command to restart the daemon is ` --replace` rather than `--restart` as mentioned above. I guess I'll have to use this for now, until a better solution comes along.
