### ISSUE TITLE
Tmux left side priority

### ISSUE THREAD

**Issue by aiguofer** [powerline/powerline#1606]
Whenever I don't have enough width, I'd like for my right side components to disappear before it shrinks the left side. I tried setting the right side components' priority to something near 1000 but that still doesn't seem to work.

Is this a bug or intended behavior, and if it's intended, is there a way to change this behavior?

**Comment by ZyX-I** [comment]
Most of the “segments” contained on the left side are controlled by tmux and powerline only describes how they look like, but not actually compute them. What *is* controlled by powerline is listed in the theme file (you may see that there is no left side there).

Even worse, left and right segments are computed with two distinct calls, so total occupied width is hard to determine correctly even if all segments were controlled by powerline.

So it is not intended behaviour, but neither it is a bug: it is simply the way I know to provide this functionality. If you know how to change this, PR is welcome.
