### ISSUE TITLE
Problem with 4-byte symbol output

### ISSUE THREAD

**Issue by xrEngine512** [powerline/powerline#1608]
I wanted to add a symbol to segment output. I didn't found proper way to do this, so I edited ExternalIpSegment.render in net.py file by adding symbol to ip:
`return [{'contents': u"\U0001F310" + ip, 'divider_highlight_group': 'background:divider'}]`
symbol properly appears, but this happens:
![screenshot_20160605_023636](https://cloud.githubusercontent.com/assets/13075253/15802761/70d247ce-2ac6-11e6-94d8-113d5b20e6b5.png)
Every update it's growing. When I add 2-byte or ascii symbol everything is ok. Using tmux.

**Comment by ZyX-I** [comment]
Editing Python file is not a proper way to add a symbol, there is `before` key for this. But in any case this will not help: powerline controls “what” is shown, “where” and “when” is controlled by tmux. You need to post this issue to tmux bug tracker, but before try to update it if tmux is not the most recent version.
