### ISSUE TITLE
Powerline seems not worked well with zsh and "ZLE_RPROMPT_INDENT=0".

### ISSUE THREAD

**Issue by lixiaoyan** [powerline/powerline#1620]
![screenshot from 2016-07-19 01-00-56](https://cloud.githubusercontent.com/assets/1610614/16923934/549fd408-4d4f-11e6-8c77-982d06a88415.png)

OS: Arch Linux
zsh version: zsh 5.2 (x86_64-unknown-linux-gnu)
powerline version: powerline-status (2.5) from pip

**Comment by ZyX-I** [comment]
Powerline does not control where prompt is shown or where cursor is located, it just tells zsh what prompt to show. You should report this bug to the zsh mailing list, not here.

**Comment by ZyX-I** [comment]
If reporting to zsh mailing list you must also include your terminal emulator and its version. Also note that zsh help explicitly states that terminal may not handle this correctly.
