### ISSUE TITLE
'auto' watcher exception loop

### ISSUE THREAD

**Issue by asonawalla** [powerline/powerline#1622]
When `TreeWatcher.get_watcher` is called and watcher_type is set to `auto`, exceptions that are handled with try/except keep getting hit over and over again.

Specifically, I'm running into an inotify `DirTooLarge` in my main git repo, and the time/resources spent trying to return an `INotifyTreeWatcher` each time are wasteful.

I think it would be beneficial to reset `self.watcher_type` based on the first successful initialized watcher when we init `TreeWatcher` with `watcher_type=auto`

**Comment by ZyX-I** [comment]
Whether or not creating watcher is successfull depends on system settings, filesystem directory is on and directory contents, and everything in the list may change at any time. So if creating INotifyTreeWatcher watcher was not successfull once, it may be successfull the other time.

Also watchers are already cached, it should not create watcher twice for one directory.

**Comment by ZyX-I** [comment]
If you see it creating watcher constantly then you probably are not using daemon, in which case any kind of caching you suggest is completely useless: Python interpreter and powerline are restarted each time you check the prompt.
