### ISSUE TITLE
Error when using a lister to show workspaces

### ISSUE THREAD

**Issue by Lagertonne** [powerline/powerline#1623]
I tried to use powerline with i3 + lemonbar. But when trying to show the workspaces with the "powerline.segments.i3wm.workspaces"-function, the not-focused workspaces are shown in a list without spaces and not as segments. So I tried to use the powerline.listers.i3wm.workspace_lister with the following code:
`{ name": "i3 workspaces",
"function": "powerline.listers.i3wm.workspace_lister" }
`
But after that, some cryptic xml-style stuff is shown in the bar and the following error is written to the console:

> 2016-07-20 02:29:39,854:ERROR:wm:i3 Workspaces:Failed to compute segment contents: coercing to str: need a bytes-like object, generator found
> Traceback (most recent call last):
>  File "/usr/lib/python3.5/site-packages/powerline/theme.py", line 161, in get_segments
>    ) + segment['after']
>  File "/usr/lib/python3.5/site-packages/powerline/lib/unicode.py", line 41, in u
>    unicode(s, 'utf-8')
>TypeError: coercing to str: need a bytes-like object, generator found

The message in the bar isn't fully shown, just something like
`<generator object workspace_lister.<locals>.<genexpr> at 0x7f58...>`

EDIT: I start the bar with the following command:
`python <path-to-lemonbar-binding>/powerline-lemonbar.py --i3 --height 16 -- -f "DejaVu Sans Mono for Powerline:size=10"`

**Comment by Lagertonne** [comment]
So I fixed this by adding 
`"segments": [ { "function": "workspace" } ]`
to the lister-segment. Now it's working as expected :)

**Comment by ZyX-I** [comment]
@Lagertonne Lister is a special kind of segment and you neither specified segment type nor specified subsegments so your configuration is not supposed to work. Also `"name"` is useless for listers.

See `powerline/config_files/themes/vim/tabline.json` for an example.
