### ISSUE TITLE
segment comes closer to prompt, moves in closer farther up the directory tree I go

### ISSUE THREAD

**Issue by turbopascalwiz** [powerline/powerline#1624]
I have a few computers with powerline on it, and have been running powerline for a long while now, no issues until recently when I moved one of my computers over to an AMD/FM2+ system. I have tried chrooting and rebuilding my environment from scratch to see if I had some sort of config issue, borrowing config and powerline environment from a working computer (other). And I have had no luck. It's been a while since I dug through powerline to try and follow how the segment horizontal offset is calculated. Right now I am at the point where this issue might be more effectively solved by bringing this up here since it might be something obvious I haven't laid my hands on.

Symptoms, under ZSH V 5.0.8 and 5.2 when ever there is a segment displayed (right side, be it VCS or an error of sorts) it is offset inward towards the prompt. It seems to shift in a few spaces every time I go in to another folder (further in to the tree). The cursor then goes back about 5-8 places in to the PS1, so it gets confused with the user name, and looks fairly ugly. Anyways, there is no issue with BASH, as it only occurs when a segment shows up, and then the cursor is misplaced.

If this sounds like an obvious issue or there are a few files I can look at in order to get some sort of start on troubleshooting I would appreciate it. Again, it's been a while since I dug through this, so I am kind of rusty on the organization/implementation. Right now I put powerline in a dot folder under any given user, and make the appropriate links and zshrc configs to get the daemon running. Gentoo, 64 bit, python 2.7.10 / 3.4.3

I am running some plugins right now (ZSH). I will continue to investigate my zshrc just to see if I can see anything that changes anything.

**Comment by ZyX-I** [comment]
I could not say that I understand without screenshots. But note that powerline only tells zsh what to show in prompt, where to place the prompt is the zsh’s decision. You may see such bugs if zsh understanding of how much display cells a symbol occupies is different from terminal emulator’s one.

**Comment by turbopascalwiz** [comment]
Yeah, it was hard to figure out, I ended up dumping the file system and just copying over another one, and rebuilding the configs, and the problem went away. 

However, I did try with multiple terminal emulators, and they all screwed it up, weird bug somewhere. Thanks for your time. I will do a better job tracking down the next issue.
