### ISSUE TITLE
Virtualenv Title is not centered

### ISSUE THREAD

**Issue by DrBomb** [powerline/powerline#1626]
I'm using Konsole, the VIM statusline shows fine, but when a virtualenv is activated the name is oddly offset from the center:

![model1](https://cloud.githubusercontent.com/assets/6021771/17075450/9205c72a-5061-11e6-8158-ab4621adf6c1.png)

**Comment by ZyX-I** [comment]
Powerline is not drawing the prompt, it only tells zsh what to draw and zsh will pass this to the terminal emulator. I cannot do anything with how terminal emulator draws glyphs. You may fix your problem by configuring powerline to use another symbol, but I cannot do anything with how currently used symbol is drawn.
