### ISSUE TITLE
 powerline-daemon is not running when start tmux

### ISSUE THREAD

**Issue by cpanato** [powerline/powerline#1630]
When I start tmux looks like the  powerline-daemon is not running, and when I start it manually it works

my tmux.conf (I tried with run-shell and only with run)
```
run-shell 'powerline-daemon -q'

source /usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf
set -g default-terminal "screen-256color"

# scrollback size
set -g history-limit 10000

# set first window to index 1 (not 0) to map more to the keyboard layout
set -g base-index 1
setw -g pane-base-index 1

# pass through xterm keys
set -g xterm-keys on


#binding Ctrl+a
set-option -g prefix C-a
bind-key C-a last-window
bind-key z setw synchronize-panes
set -g base-index 1
# Activity monitoring
setw -g monitor-activity on
set -g visual-activity on

bind-key C command-prompt -p "Name of new window: " "new-window -n '%%'"

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config tmux reloaded..."

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Setup 'e' to begin selection as in Vim
bind-key -t vi-copy e begin-selection
bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -t vi-copy Enter
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

```

**Comment by ZyX-I** [comment]
What do you mean by “tmux looks like the powerline-daemon is not running”?

**Comment by cpanato** [comment]
now its running.

however the left side looks like is missing something

![screen shot 2016-08-04 at 08 48 50](https://cloud.githubusercontent.com/assets/4115580/17392938/db596436-5a20-11e6-92e2-c277e5c415b2.png)

**Comment by ZyX-I** [comment]
I cannot do anything with the gap between white and blue segment if I want to continue using standard tmux facicilities (controlling left side directly and determining what to output by querying tmux has a number of downsides, including things like #1502 which sometimes pops up not at startup (depends on system load, mostly pops up when tmux stayed long unused probably having something to do with moving something to swap)). You can only configure your colorscheme to have blue segment have the same background color as the gap (you need to adjust `window:current` highlight group).
