### ISSUE TITLE
Hidden external IP segment (in tmux) does not join the surrounding segments properly.

### ISSUE THREAD

**Issue by BlitzKraft** [powerline/powerline#1631]
Here is what I am referring to:
![2016-08-08-181803_474x61_scrot](https://cloud.githubusercontent.com/assets/6516167/17501660/a956cbb8-5d95-11e6-9e1d-468cbdb65d62.png)

This is the left most part of my tmux status bar. The segments are tmux session name, external IP and email count. Due to limited width on my monitor, the IP segment is  not shown. That is expected. However, the join between the two remaining segments is what I have the issue with. 

My tmux version is 2.1; 

powerline-status Version: 2.2.dev9999-git.44b2f91729a4c45099d0efe2b14fd02b8a7676e1

On a bigger monitor, it shows all three segments without a hitch. The separators between the IP and mail work fine. And if there is no new email, the IP segment shows up properly, with the hard divider.

**Comment by ZyX-I** [comment]
It is tmux what decides where to place segments which represent tmux windows, powerline job ends on telling tmux how they should look like. I cannot do anything with that space.
