### ISSUE TITLE
Setting up bash prompt inside tmux causes a "sessions should be nested with care" error

### ISSUE THREAD

**Issue by MadWombat** [powerline/powerline#1637]
I have bash prompt setup in my .bash_profile using the following
```
if [ $TERM == 'xterm-256color' -o $TERM == 'screen-256color' ]; then
    if alias | grep -q tmux; then
        unalias tmux
    fi
    if [ -z $TMUX ]; then
        powerline-daemon -q
    fi
    POWERLINE_BASH_CONTINUATION=1
    POWERLINE_BASH_SELECT=1
    source /usr/local/lib/python3.5/site-packages/powerline/bindings/bash/powerline.sh
fi

alias tmux='tmux new -A -s wombat'
```

I have tmux status line configured using 
```
source "/usr/local/lib/python3.5/site-packages/powerline/bindings/tmux/powerline.conf"
```

Every time I start tmux, I get "sessions should be nested with care" error. It seems to be caused by the source command, if I remove it, I don't get the error, but I don't get the prompt either. If I run the source command from command line in a new bash window, I don't get the error.

**Comment by ZyX-I** [comment]
Apparently bash reparses `$(…)` and <code>`…`</code> contents each time (zsh does the same thing though). Don’t create such destructive aliases: I can write code that is not touched by this specific problem, but if I will protect against every possible way to shoot oneself into the foot code resulting code will look like a crap.

**Comment by MadWombat** [comment]
The alias is there to connect to an existing session if there is one or create a new one. If there is a better way to do the same thing, I will gladly get rid of the alias. I am not sure what I should do with $TMUX_PANE, should I use it instead of $TMUX?

**Comment by ZyX-I** [comment]
@MadWombat You should not define `tmux` alias, choose better name. You are not supposed to do anything with $TMUX_PANE or $TMUX, I just found that I can avoid using `$(tmux display -p '#D')` because tmux already exports $TMUX_PANE.

**Comment by MadWombat** [comment]
Ah, I see. You are using $(...) and the alias gets reset even though I unset it in the outer shell. Renamed the alias to `screen` and all is well :)

Quick question, can I run powerline-daemon once or should I run it for every shell?

**Comment by ZyX-I** [comment]
@MadWombat You need to run it once for each user, lasts until you kill it, it crashes (rather unlikely AFAIK) or computer is shut down. `-q` in `powerline-daemon` call allows you to run it multiple times without getting errors if daemon was already launched.

Though when you update you will have to restart it.
