### ISSUE TITLE
In fish shell, No prompt until manually calling powerline-setup. 

### ISSUE THREAD

**Issue by tommyjcarpenter** [powerline/powerline#1639]
I am using fish version 2.3.1. 

I do not get the powerline prompt until I call powerline-setup. I tried putting powerline-setup at the top of my fish prompt but that does not do anything. Please let me know what information you need. 

Here is a screenshot. I do three things in that prompt:
1 start a new terminal
2 cd into a directory: you can see powerline not activated at this point
3) setup, then you can see it activated. 
http://imgur.com/a/WjaEG

**Comment by ZyX-I** [comment]
Powerline prompt is not supposed to appear until you call `powerline-setup`. You are supposed to call `powerline-setup` in `config.fish`. I have no idea why you are trying to put `powerline-setup` “at the top of your fish prompt” (and what do you mean by “putting at the top”). In any case I cannot say what you are doing wrong without seeing your configuration file.

**Comment by tommyjcarpenter** [comment]
I meant powerline-setup is in my fish.conf (meant conf, not prompt). It
doesn't do anything. I tried re putting it at the bottom, also doesn't do
anything. It only works when called manually.

**Comment by tommyjcarpenter** [comment]
Here is the relevent portion  of my fish config 👍 
```
 
       set -gx PATH ~/Library/Python/2.7/lib/python/site-packages/scripts $PATH
       set -xg theme_nerd_fonts yes
       set fish_function_path $fish_function_path "~/Library/Python/2.7/lib/python/site-packages/powerline/bindings/fish"
       source ~/Library/Python/2.7/lib/python/site-packages/powerline/bindings/fish/powerline-setup.fish
          powerline-setup
```

The last line here does not do anything, as shown in the screenshot.

**Comment by ZyX-I** [comment]
@tommyjcarpenter 

1. You are not supposed to `source` anything.
2. `~/` is not going to work. Normally path `"~/Library/Python/2.7/lib/python/site-packages/powerline/bindings/fish"` means literally `./~/Library/Python/2.7/lib/python/site-packages/powerline/bindings/fish`, `~/` is not expanded in double quotes. This is OK in first statement because there are no quotes, but by using `""` you explicitly told fish that you do not need some operations, including `~/` expansion.

   You may check that this works as I said yourself by running `fish` using `strace -e open,stat -o /tmp/fish.strace fish`, this will show you lots of entries like

        stat("~/.vam/powerline/powerline/bindings/fish/set.fish", 0x7ffded2eb9b0) = -1 ENOENT (No such file or directory)

    Note: `stat()` syscall *does not* expand `~/`, it is shell (and some other apps that copied this behaviour because it is convenient) own feature.

I have just

    set fish_function_path "$HOME/.vam/powerline/powerline/bindings/fish" $fish_function_path
    powerline-setup

in my `config.fish` (basically because I am not using fish, I am testing powerline there): note `$HOME`, not `~/`.

> The path addings work because powerline-setup gets defined.

`powerline-setup` gets defined because you are running `source`, path additions have nothing to do with this.

--

Though I am not sure that fixing these issues is enough: before you ran `powerline-setup` fish has prompt that is neither powerline nor default (at least, not 2.2.0 default). And `theme_nerd_fonts` looks like an option for https://github.com/oh-my-fish/theme-bobthefish (though prompt also does not look like bobthefish). If you have other prompt plugins you must disable them, don’t ask me how: I am not using OM? packs or any shell plugin managers generally (oh-my-zsh has very bad reputation in `#zsh` on freenode and I have no reasons not to trust people there), not to mention I am not using fish except for testing.

**Comment by tommyjcarpenter** [comment]
These changes kept the current functionality with less stuff,  but did not work. 

Conf now just

       #powerline and fish theme working
       #set -gx PATH ~/Library/Python/2.7/lib/python/site-packages/scripts $PATH
       #set -xg theme_nerd_fonts yes
       set fish_function_path $fish_function_path "$HOME/Library/Python/2.7/lib/python/site-packages/powerline/bindings/fish"
       #source ~/Library/Python/2.7/lib/python/site-packages/powerline/bindings/fish/powerline-setup.fish
       powerline-setup

but same issue as screenshot. This is fish 2.3.0 as indicated in my post, not 2.2.0. When you say "default" the prompt is based on the fish theme.

**Comment by ZyX-I** [comment]
Normally at this point I would request running shell with `-x`. If I am not mistaking, fish equivalent is running fish with `fish -i -d 10`, though this thing is way too verbose.

**Comment by tommyjcarpenter** [comment]
@ZyX-I can you send me a documentation link to what you are talking about?

**Comment by ZyX-I** [comment]
@tommyjcarpenter Documentation link to what? `-x` just makes POSIX shell print every command it runs.

**Comment by tommyjcarpenter** [comment]
@ZyX-I do you want the output of fish -i -d 10? It is gigantic.

**Comment by ZyX-I** [comment]
You have other ideas to determine what is redefining `fish_prompt`?

**Comment by tommyjcarpenter** [comment]
@ZyX-I I ran the command `fish -i -d 10 > log2.txt 2>&1`. It never returned but after the file log2.txt stopped updating, I uploaded it here: http://s000.tinyupload.com/index.php?file_id=08011898378459767541

**Comment by sheriferson** [comment]
@tommyjcarpenter Just a thought: [you said](https://github.com/powerline/powerline/issues/1639#issuecomment-240694107) you had this in `fish.conf`, but as far as I know the configuration file for fish has to be called `config.fish`, full path being `~/.config/fish/config.fish`. Could the problem be the file name? I googled and found no reference to a file called `fish.conf`.

That said, I might have missed some evidence in the comments that _something_ in that file is working (if so, I don't see it), or you could have just written `fish.conf` for expediency.

**Comment by ZyX-I** [comment]
Something is clearly working: without update to fish_function_path `powerline-setup` could not possibly work. Based on the log, it looks like something is overwriting fish_prompt (which was already suspected), but it does not show clearly what overrides it. Except that it looks like it is using default prompt, and I still cannot reproduce the issue including on latest 2.4.0.

**Comment by ZyX-I** [comment]
Neither on 2.4.0 or 2.3.1 releases.

**Comment by ZyX-I** [comment]
I suspect that fish universal variables are involved in the problem.

Can you reproduce the issue with the minimal configuration: $XDG_CONFIG_HOME set to /tmp/cfghome, configuration in /tmp/cfghome/fish/config.fish; $XDG_DATA_HOME, $XDG_CONFIG_DIRS, $XDG_CACHE_HOME set to /tmp/emptydir; $XDG_DATA_DIRS set to /usr/share (or where are runtime files installed?).

**Comment by tommyjcarpenter** [comment]
I do not know how to easily to that. On my mac `/tmp/cfghome` is not even a directory. However, I did try to remove all global variables in my fish config (I had a few set -xgs) and that didn't help.

**Comment by tommyjcarpenter** [comment]
If it helps, this is not tied to iterm2. This also happens to me in `terminal` (default mac app).

**Comment by tommyjcarpenter** [comment]
I have "solved" this issue by having iterm2 always inject "powerline-setup" into each new terminal window that is opened.

**Comment by ZyX-I** [comment]
@tommyjcarpenter Of course, it is not. To have clean configuration you will need to create needed directories yourself. And fish has universal variables which are shared among instances via other means, *not* configuration file, this makes changes tricky: at least, you need to drop the file they use to share these variables; at most, you need to first kill all fish instances and only then drop the file. Feature is unique among shells and I wish they never had it.

**Comment by tommyjcarpenter** [comment]
OK, so this morning I confirmed this is *not a Mac OS* issue and also not a *terminal* issue. I have the exact same problem on Arch Linux, using the official AUR Arch package `python-powerline-git`. Everything installs correctly, but not matter how many times or where `powerline-setup` exists in my config, nothing shows until I call that manually. This is in two completely different terminals on a different Operating system with a minimal fish config file.

**Comment by ZyX-I** [comment]
@tommyjcarpenter I still need steps from scratch or with empty configuration. It is not reproducible here, but I am not actively using fish and constantly drop its universal variables. If that is because some universal variable exists in your setup then no matter where you move powerline-setup in your configuration as long as universal variable provokes some action from fish runtime the problem will persist.

And did you try to drop file with universal variables?

**Comment by ZyX-I** [comment]
Though it is strange: “standard” way to create prompt is creating ~/.config/fish/functions/fish_prompt.fish. This file does neither trigger your problem. Still are you using something like oh-my-fish?

**Comment by tommyjcarpenter** [comment]
I have not tried your steps yet as it's a lot of work to create all these env variables to a path that does not exist etc. Probably giving up at this point.

I used to use oh-my-fish, now I use fisherman, it's replacement.

**Comment by ZyX-I** [comment]
@tommyjcarpenter Still a question about dropping universal variables (whether you did this). I guess that OMF/fisherman uses some configuration to select the prompt and does not expect that prompt is controlled by something else (if latter is the case, cleaning universal variables would not help: they would use something default). I would suggest to ask at their issue tracker/IRC channel.

**Comment by tommyjcarpenter** [comment]
I removed all -xg from my config file, had no global variables in my conf, rebooted my system, tried again, same result. Not sure what else you're asking.

**Comment by ZyX-I** [comment]
@tommyjcarpenter Universal variables do not *live* in your configuration file, even though you may *define* them there. Neither they will disappear after reboot. They used to live in `~/.config/fish/fishd.$(hostname)` (with fish-2.4.0 they do), but I know that fish has an issue to move them to more XDG-compliant location.

**Comment by tommyjcarpenter** [comment]
OK, then I'm not sure what is being asked of me.

**Comment by ZyX-I** [comment]
Remove that file and rerun fish. If fisherman has some default and defines prompt always this will not work, if it defines prompt only if some variable is present this should fix the issue.

Note: better do that not from fish and with all fish instances killed: existing fish instances should not create the file again from their memory.

**Comment by tommyjcarpenter** [comment]
Remove which file, this one? /.config/fish/fishd.$(hostname)

**Comment by ZyX-I** [comment]
Yes. Maybe back up it (`mv ~/.config/fish/fishd.$(hostname){,.bak}`), if you are willing to determine which variable causes the problems in case there is one.

**Comment by tommyjcarpenter** [comment]
That worked but didn't work for your purposes. Getting rid of that file blew my whole prompt away so I get a completely empty screen when a new terminal opens. However, I *still* do not see anything until I type `powerline-setup`.

```
  powerline-setup
 tommy  ~ 
```
I don't even get a tilda or anything as you can see, powerline-setup was the first thing I typed in my new shell.

**Comment by tommyjcarpenter** [comment]
There was a `SET fish_greeting: some stuff` in there.

**Comment by ZyX-I** [comment]
This is rather strange, if I have neither configuration file (which only has two lines that work with powerline) nor universal variables I see default prompt (greeting also disappears). If I get rid of only universal variables I see no greeting, but powerline is fine (greeting is removed though and I have “test: Missing argument at index 2” coming from unknown location, maybe something to do with fish key bindings: `$fish_key_bindings` may be found in that file).

And what plugins do you use with fisherman? Specifically have you any prompt plugins installed?

**Comment by tommyjcarpenter** [comment]
I use metro, bobthefish (these are  themes) and z (a movement plugin). I'll try again later (on phone right now) because I only removed the host name file, I didn't try removing both files at once.

**Comment by ZyX-I** [comment]
@tommyjcarpenter bobthefish looks like exactly what should not be there, is not it the prompt plugin?! I already asked to disable that in https://github.com/powerline/powerline/issues/1639#issuecomment-240767678. As well as other prompt plugins.

How could you expect *three* prompt plugins to work together? There is only one prompt.

**Comment by tommyjcarpenter** [comment]
This is not the (or the only) issue, because on my Arch box it is brand new and I don't even have fisherman installed. And I don't have any fisherman plugins installed there. And I observe identical behavior. I haven't been home to try the universal variable thing on my arch box though. 

Regardless later on my Mac I will try blowing away all fisher plugins and re trying. 

My takeaway is that this is all very fragile and not worth the effort for eye candy. This is more hassle than it's worth.

**Comment by tommyjcarpenter** [comment]
This is "fragile" because the conflicts/dependencies are not explicit. When I installed metro, it deactivated bobthefish. So I know there is a conflict there. But nothing in the system indicates that there is a conflict with powerline. Something should detect "hey you can't have all of these things". 

Arch package management is normally very good at this. When you install a package (like pipeline) it checks for a big list of known conflicts before letting  you install. As I said I do not have fisherman on my arch box, just citing an example. 

On Mac however where there is no built in package manager, it appears you can install multiple conflicting packages and nothing complains. Not a fan of that. I use homebrew when I can. But the powerline installation page doesn't list brew as an option for Mac.

**Comment by ZyX-I** [comment]
This is strange because I cannot reproduce the problem on my Gentoo with a clean installation to `~/.local-fish`. I see the only relevant difference between “minimal configuration” from your https://github.com/powerline/powerline/issues/1639#issuecomment-240903403 and my https://github.com/powerline/powerline/issues/1639#issuecomment-240767678 comments which is “I have powerline path first in fish_function_path, you have it last”. But it should not cause problems like this: that variable is only modified to add `powerline-setup` function and it will be available in both variants.

BTW, I have an interesting idea: what if you add `fish_prompt.fish` near `powerline-setup.fish` with the contents

```fish
function fish_prompt
    powerline-setup
    fish_prompt  # powerline-setup redefines fish_prompt function
end
```

and make path to powerline first in fish_function_path?

**Comment by tommyjcarpenter** [comment]
I have done all of your suggestions (I think) and it is still not working.

1) I removed metro and bob:
```
~ fisher ls
getopts z
~
```

2) My powerline fish setup is the very first function in my function path:
```
~ echo $fish_function_path
/Users/tommy/Library/Python/2.7/lib/python/site-packages/powerline/bindings/fish/ /Users/tommy/.config/fish/functions /usr/local/Cellar/fish/2.5.0/etc/fish/functions /usr/local/share/fish/vendor_functions.d /usr/local/Cellar/fish/2.5.0/share/fish/functions
~
```
3) I have added 
```
function fish_prompt
    powerline-setup
    fish_prompt  # powerline-setup redefines fish_prompt function
end
```
into my fish config near the end of my config. 

Calling `powerline-setup` is still the only way to get the prompt to appear. Tested in iterm2 and terminal.

**Comment by ZyX-I** [comment]
@tommyjcarpenter Can you confirm that if you place `fish_prompt` right after `powerline_setup` in your `config.fish` then you see that prompt, though obviously once? Regardless of the answer I will have to ask you to ask on some channel from https://github.com/fish-shell/fish-shell#contact-us because I cannot reproduce the issue locally, have not found an answer in the trace you provided and have actually no idea how to debug that further as I am not using fish. People there should at least have an idea what may be behind overwriting `fish_prompt` function.

**Comment by tommyjcarpenter** [comment]
OK, I have this working. I did a complete reinstall and blew away my whole fish, fisherman, and config. Then slowly pieced back stuff. Whatever problem I had (on mac) is solved, so closing this.
