### ISSUE TITLE
VCS branch segment doesnt highlight properly if a powerline-daemon is running

### ISSUE THREAD

**Issue by prasanthkrishnan** [powerline/powerline#1644]
![screen shot 2016-09-08 at 1 47 42 am](https://cloud.githubusercontent.com/assets/6378815/18343030/658a9df4-7566-11e6-9669-c3715b7fece6.png)

**Comment by nrobert13** [comment]
Hey, 

I cannot get it working without the daemon either, on ubuntu 18.04.

Added the following to my bashrc:

```
      powerline-daemon -q
      POWERLINE_BASH_CONTINUATION=1
      POWERLINE_BASH_SELECT=1
      . ~/powerline/powerline/bindings/bash/powerline.sh
```

but the branch is always gray, doesn't matter what status the git has.
using the default_leftonly theme and enabled the status_colors in the vcs branch segment:
in powerline/config_files/themes/shell/default_leftonly.json
```
			{
				"function": "powerline.segments.common.vcs.branch",
				"priority": 40,
				"args": {
					"status_colors": true
				}
			},
```

tried the master and the develop branches.

**Comment by ZyX-I** [comment]
Does it has something in log? To see the log you need to either run daemon with `--foreground` argument (will occupy the shell it was run in) or configure log file location in common section.

**Comment by nrobert13** [comment]
it seems I misinterpreted the doku and did the theme config in `powerline/config_files/themes/shell/default_leftonly.json` instead of `~/.config/powerline/themes/shell/default_leftonly.json`, moved the json over to the .config, and it works. thanks.
