### ISSUE TITLE
powerline status overflow in iterm2

### ISSUE THREAD

**Issue by hellojas** [powerline/powerline#1649]
<img width="1105" alt="screen shot 2016-09-19 at 1 13 46 pm" src="https://cloud.githubusercontent.com/assets/1888003/18650740/8500d9f0-7e7b-11e6-8b2e-659e729bef24.png">

Hi, 

Have a overflow on the status into the second line no matter the size of the terminal. 
Wondering if any has had this problem, if it is a problem with powerline installation, iterm2 settings or possibly themes?

I have tried a different themes, and I have installed [powerline fonts ](https://github.com/powerline/fonts) and changed it in iterm2's profile settings. 

Thanks!

**Comment by ZyX-I** [comment]
This looks like a difference between zsh’s understanding of how wide a character is (powerline characters are *1* display cell wide) and iterm2’s (it clearl looks like 2 cells). AFAIR there is a setting in iterm2 which controls how wide characters with ambigious width are.

In any case this is not a powerline bug, powerline controls what to show, not where and how large gap should be left between end of left and start of right prompts.
