### ISSUE TITLE
Powerline for Zsh not connecting to daemon

### ISSUE THREAD

**Issue by zeorin** [powerline/powerline#1650]
My powerline prompt in Zsh does not seem to be connecting to the daemon.

```
% cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

```
% zsh --version
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
```

```
% pip show powerline-status | grep '^Version'
Version: 2.5
```

```
% file ~/.local/bin/powerline
/home/xandor/.local/bin/powerline: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=ae4f0504ed8a97f976490efd936f45a11b4fd61a, not stripped
```

`powerline-daemon` is started by Tmux (which is run before Zsh); `.tmux.conf`:
```
PATH="$HOME/.local/bin:$PATH"
run-shell "powerline-daemon -q"
run-shell 'tmux source-file "$(python -m site --user-site)/powerline/bindings/tmux/powerline.conf"'
```

Relevant part of `.zshrc`:
```
PATH="$HOME/.local/bin:$PATH"
source "$(python -m site --user-site)/powerline/bindings/zsh/powerline.zsh"
```

(`PATH` is exported later in `.zshrc`. Incidentally I'm actually adding `$HOME/.local/bin` to `PATH` only once because the setting in `.tmux.conf` is necessary for Powerline to work for Tmux, but it doesn't export to the shell env, which is exactly the behaviour I want).

`~/.config/powerline/config.json`:
```
{
	"common": {
		"term_truecolor": false
	},
	"ext": {
		"shell": {
			"colorscheme": "solarized",
			"theme": "default",
			"local_themes": {
				"continuation": "continuation",
				"select": "select"
			}
		},
		"tmux": {
			"colorscheme": "solarized",
			"theme": "default"
		}
	}
}
```

I'm using `libzpython`. Contrary to the README of zpython, debian-based OSs do have the correct headers in the `zsh-dev` package to be able to build. I built it against Python 2.7 (using `cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so && make && sudo make install`).

I've been struggling with the performance of Powerline for Zsh on my Ubuntu box for a little while, wondering what the problem was. I edited `~/.local/bin/powerline-daemon` to print some statements in the `do_run` function. When I then ran `powerline-daemon --foreground` (after killing it first), there is no output from the shell client. Tmux client was definitely connected, lots of activity indicated by my added print statements. When I removed the powerline bindings from `.tmux.conf` and again looked for activity from the shell, there was simply no output from `powerline-daemon`, indicating no connections from any clients.

I'm not using Powerline for any other software at the moment.

Please advise :-).

**Comment by ZyX-I** [comment]
Zsh with libzpython is not supposed to connect to the daemon, in this case powerline is executed inside zsh process. If you want to use exactly daemon you should first disable usage of libzpython via POWERLINE_NO_ZSH_ZPYTHON environment variable (set to 1), if you want to run cPython profiler you will have to alter `powerline.bindings.zsh` module.

Debian-based OSes have correct headers starting from some point (absense of headers was reported by me to their bug tracker and fixed, but I forgot that I mentioned this in README).

Closing this issue because problem in topic is not a problem.

**Comment by zeorin** [comment]
Ah OK. Thanks for clearing that up. I didn't understand from the docs that they were mutually exclusive. The docs mention both options side-by-side.

FWIW zpython seems to be slightly faster than the daemon mode for Zsh Powerline (I didn't actually profile that, just by feel). I'll keep using the daemon for Tmux, though.
