### ISSUE TITLE
IPython not working

### ISSUE THREAD

**Issue by sebastiandev** [powerline/powerline#1651]
Here's the error when entering ipython:

> Python 3.5.1 (default, Aug  9 2016, 15:35:51) 
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 4.2.0 -- An enhanced Interactive Python.
> ?         -> Introduction and overview of IPython's features.
> %quickref -> Quick reference.
> help      -> Python's own help system.
> object?   -> Details about 'object', use 'object??' for extra details.
> 2016-09-28 20:33:59,568:ERROR:ipython:powerline:Failed to import attr renderer from module powerline.renderers.ipython: module 'powerline.renderers.ipython' has no attribute 'renderer'
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/powerline/**init**.py", line 382, in get_module_attr
>     return getattr(**import**(module, fromlist=(attr,)), attr)
> AttributeError: module 'powerline.renderers.ipython' has no attribute 'renderer'
> 2016-09-28 20:33:59,569:ERROR:ipython:powerline:Failed to create renderer: Failed to obtain renderer
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/powerline/**init**.py", line 842, in update_renderer
>     self.create_renderer(**cr_kwargs)
>   File "/usr/lib/python3.5/site-packages/powerline/**init**.py", line 666, in create_renderer
>     raise ImportError('Failed to obtain renderer')
> ImportError: Failed to obtain renderer
> 2016-09-28 20:33:59,569:ERROR:ipython:powerline:Failed to render: Failed to obtain renderer
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/powerline/**init**.py", line 859, in render
>     self.update_renderer()
>   File "/usr/lib/python3.5/site-packages/powerline/**init**.py", line 842, in update_renderer
>     self.create_renderer(**cr_kwargs)
>   File "/usr/lib/python3.5/site-packages/powerline/**init**.py", line 666, in create_renderer
>     raise ImportError('Failed to obtain renderer')
> ImportError: Failed to obtain renderer

Here's powerline config for ipython:

``` json
"ext": {
                "ipython": {
                        "colorscheme": "default",
                        "theme": "in",
                        "local_themes": {
                                "rewrite": "rewrite",
                                "out": "out",
                                "in2": "in2"
                        }
                },
```

Here's the ipython_config.py:

``` python
c = get_config()
c.InteractiveShellApp.extensions = [
    'powerline.bindings.ipython.post_0_11'

]
```

**Comment by ZyX-I** [comment]
Unable to reproduce with IPython-4.2.0 in virtualenv on latest develop. Is this issue still applicable?

**Comment by sebastiandev** [comment]
well... i guess not. I'll notify again if find anything. thanks!
