### ISSUE TITLE
spotify_dbus not working but spotify_apple_script works

### ISSUE THREAD

**Issue by rohithvsm** [powerline/powerline#1655]
Hi,
I love using powerline with zsh, tmux and vim and I have spent a lot of time customizing it. Thank you!
I am having trouble getting spotify segment to work for me. spotify_dbus does not work for me, where spotify_apple_script works. spotify_apple_script makes my vim very slow and I can't use it on my Linux machines. Please help me. Below is the snippet where I have showcased the problem.

```
$ # Environment: Mac OSX
$ uname && sw_vers -productVersion
Darwin
10.11.6

$ # All pre-requisites installed
$ brew info dbus
dbus: stable 1.10.8 (bottled), devel 1.11.4, HEAD
Message bus system, providing inter-application communication
==> Caveats
To have launchd start dbus now and restart at login:
  brew services start dbus
 $ ps aux | grep "[d]bus"
rohithvsm       18445   0.0  0.0  2454632   2212   ??  S     5:20PM   0:00.02 /usr/local/Cellar/dbus/1.10.8/bin/dbus-daemon --nofork --session
$ pip show dbus-python
Version: 1.2.4
Summary: Python bindings for libdbus
Location: /usr/local/lib/python2.7/site-packages
$ python -c 'import dbus; print dbus.__version__'
1.2.4

$ python
>>> from powerline.segments.common.players import spotify_dbus
>>> from powerline import get_fallback_logger
>>> # spotify_dbus returns None
>>> print spotify_dbus(pl=get_fallback_logger())
None
>>> from powerline.segments.common.players import spotify_apple_script
>>> # spotify_apple_script works
>>> print spotify_apple_script(pl=get_fallback_logger())
[{u'contents': u'~ Black Sabbath - Sabbath Bloody Sabbath (5783:20)', u'highlight_groups': [u'player_pause', u'player']}]
```

**Comment by ZyX-I** [comment]
Are you sure that spotify_dbus *should* work at all? I.e. whether spotify exports its interface via dbus on Mac OS?

I also would say it is better to ask about `_get_dbus_player_status` function with the code it is called by in SpotifyDbusPlayerSegment in spotify issue tracker, these are pretty self-contained: I have neither Mac OS, nor any players to work with, so determining what is the problem would take much time.

Also note that player status segments were really ever designed for use in tmux, Vim has a habit of redrawing statusline on every user action and Vim+python AFAIR was reported to have some issues with threading and multiprocessing modules (though I do not remember having enough problems with them myself to ban completely like it was done for all segments used in Vim by default).

---

Some debugging information may be obtained by using

    python -mtrace -t <(echo 'from powerline.segments.common.players import spotify_dbus; spotify_dbus(pl=None)')

(note: output is going to be very lengthy).

**Comment by rohithvsm** [comment]
Thanks for your response. I will try a little more debugging with SpotifyDbusPlayerSegment and post back here.

**Comment by rohithvsm** [comment]
I wasn't able to gather much information from the debugging information. You can close it if you feel dbus module was not meant for MacOS.
