### ISSUE TITLE
Gnome Terminal 3.22 keeps scrolling the base line

### ISSUE THREAD

**Issue by burningTyger** [powerline/powerline#1656]
I just upgraded to Gnome 3.22 on Arch and this is what happens:

![screenshot from 2016-10-12 14-46-01](https://cloud.githubusercontent.com/assets/263378/19310585/2293b8ce-908b-11e6-9d69-c305143822f7.png)

Let me know what else you need or if I need to report this over at GNOME.

**Comment by burningTyger** [comment]
Is this maybe a tmux issue?

**Comment by ZyX-I** [comment]
Duplicate of #1652.

**Comment by mrmodolo** [comment]
I'm having the same problem! I tested with gnome-terminal and xfce4-terminal! My distribution is Arch
