### ISSUE TITLE
pip install didn't include vim bindings

### ISSUE THREAD

**Issue by jdfoote** [powerline/powerline#1659]
I followed the install instructions on Ubuntu 16.04. Powerline is working fine in bash, but when I tried to install in vim, it isn't working - I just see a blank white line:
![powerline](https://cloud.githubusercontent.com/assets/452218/19525380/6477f1fa-95e6-11e6-9425-813ee2cec33f.png)

I looked, and my /usr/share/powerline/bindings directory does not have a vim/ subdirectory.

Is there a reason that wouldn't be installed?

**Comment by ZyX-I** [comment]
Which install instructions? `pip` is not supposed to install *anything* to /usr/share AFAIK, only system package manager for externally maintained powerline packages is normally instructed to install there. `pip` installs somewhere like `{PREFIX}/lib/python{major}.{minor}/site-packages/…`.

**Comment by jdfoote** [comment]
Hmmm... I was just using pip, and things were definitely installed to /usr/share.

I uninstalled, and reinstalled using pip install --user powerline-status, and changed my vimrc first line to 
set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/

Now all is working well. Thanks!
