### ISSUE TITLE
Powerline in tmux gets scrolled up by gnome-terminal

### ISSUE THREAD

**Issue by jadeaffenjaeger** [powerline/powerline#1660]
When opening tmux with powerline in gnome-terminal, powerline shows up for a split second and disappears again. Then after approximately 5 seconds, the command line disappears and powerlines updates get scrolled up across the screen in 2 second intervals (see attachment)

This seems to be an issue with gnome-terminal, as it still works fine with xterm and konsole. This was caused by a recent update, assumingly in gnome or python, as the same setup worked fine before.
![bildschirmfoto von 2016-10-19 21-58-30](https://cloud.githubusercontent.com/assets/15603149/19535431/e8028998-9647-11e6-9610-733f7bba1414.png)

**Comment by ZyX-I** [comment]
#1652
