### ISSUE TITLE
Error show name when completed

### ISSUE THREAD

**Issue by thanhdong1234** [powerline/powerline#1662]
After I completed the installation then it fails like this. I used the python 3.4. Help Me !!
![error](https://cloud.githubusercontent.com/assets/16979197/19621508/a0de1faa-98bd-11e6-9d41-19df939bce1a.png)

**Comment by s-ol** [comment]
(how) have you installed the fonts?

**Comment by thanhdong1234** [comment]
i not install font in bash on win 10. hic. You know??

**Comment by s-ol** [comment]
@thanhdong1234 you need to install a font and make your terminal use it. [See the docs](http://powerline.readthedocs.io/en/master/installation.html#fonts-installation).
