### ISSUE TITLE
tmux freezes when running with powerline.

### ISSUE THREAD

**Issue by symbolix** [powerline/powerline#1668]
I am on **OSX 10.11.6 (El Capitan)**. Using **tmux 2.4** inside **iTerm2**, with **powerline 2.5**.

After a very short time tmux would freeze when running with powerline enabled. It freezes and dies so bad, that I have to kill the process.

I can see some ghosts tmux processes appearing:
<img width="200" alt="tmux_dead" src="https://cloud.githubusercontent.com/assets/474655/19807364/a6da3d22-9d17-11e6-9f6c-ae36abe22a90.png">

On the other hand, when I disable powerline, everything is just fine no matter how much I push tmux (many new sessions, new windows, new panes etc.).

I have the following line to enable powerline in my .tmux.conf:
```
run-shell "powerline-daemon -q"
source "/Users/me/opt/Darwin64/powerline/powerline/bindings/tmux/powerline.conf"
```

Any ideas?

**Comment by symbolix** [comment]
Ok, I have a bit more information here:

Is it possible that powerline invokes `tmux` for some reason? On my system, since I am testing tmux 2.4 right now, it is symlinked as `tmux2.4`, so in order to run the latest tmux on my system, I type `tmux2.4`.

However, I still have tmux 1.9a and that is still running as `tmux`. So those ghosts process that pop up and kill my tmux seem to be listed as **tmux 1.9a**.

So at some point, something is attempting to launch **tmux** with the command **tmux** which is the old version. And then everything dies.

**Comment by symbolix** [comment]
Once I have upgraded the alias for tmux 2.4 to be `tmux` and the old tmux 1.9a to be `tmux1.9`. Things are working. I will run couple of more tests and hopefully close this issue.

**Comment by symbolix** [comment]
All good.

**Comment by ZyX-I** [comment]
`powerline` indeed invokes tmux. AFAIR with default configuration the only place where this is done is the main configuration file which makes tmux run powerline-config which in turn will run tmux multiple times to feed it with appropriate configuration.
