### ISSUE TITLE
Mercurial branches are no longer shown

### ISSUE THREAD

**Issue by QuLogic** [powerline/powerline#1675]
I'm not sure at what point it stopped working, but git branches are fine while mercurial branches are not shown. I removed my custom config just to be sure; can't verify in bash because it doesn't have a right side view, but in vim, the same thing occurs where the branch is missing in mercurial repos.

Currently using powerline 2.5 from Fedora repos and mercurial 3.7.3.

**Comment by QuLogic** [comment]
Oh, hah, of course, Fedora uses Python 3 for powerline and mercurial is still stuck on 2.7. I guess there's no way to workaround?

**Comment by jleaders** [comment]
Do you think this is related?

https://superuser.com/questions/1214370/powerline-status-makes-zsh-hg-mercurial-branch-info-disappear-from-the-prompt
```

hg --version                                   
Mercurial Distributed SCM (version 3.9.1)

python --version
Python 2.7.12+
```
