### ISSUE TITLE
Branch symbol show error

### ISSUE THREAD

**Issue by XiaochenCui** [powerline/powerline#1677]
vim: 7.4
os: ubuntu 16.04

The branch symbol show error like this:
![](https://lh3.googleusercontent.com/vR-Z8IvAUKaDszt4gbT-0O2mSS-tvvPuyiPXdCn7aDq5kLH38JXpNZr-ozFYgdo54jax0c73dg-DHB1gayzeFkM_QJrqd4Ug5HHs347mL8Y3szktB4mltFSaE2Hj_PJCzclazDgvHHRUL3U1iXYFe3fh82CSx32CMZOrQOR8__LZoL7Ud9aZJoYzR4oL5NmK6S6W0ZpZpbNiHhrg7IG3C4Qag55qqhB1GtkYQInIYIgwxbLmhjA6kEgca07awn3XzetbUU7FzRwxkXZDV6aH7c3MCIYD-MuubyY1N4-IASzt7gQh22EYpmPZUXxMDkkee-C-BAxRpiG3i4nRLAalzO7LGGP6Ucg5pTLYGugzR7AQr68-35TYsYRbdNDUAhIZ4IrriCxINQ-6JooJdAZBnJ4iC9APIj9NFHWufPbiyV28KKK_b-HHCDPyOxOrUyl6ioO0Gw-Atp6uo51p6GbczKUd6vs9lYe8MBqDH_bpUKFJJn_xkH76BP501D2cWAtfat8nDxqkmfv4lQFnJ5f8scvfO9Xo_Ad1rqskivHr4AA_WjORMSpc0ITWvwmoAutcCmPBV1edxNbq_kWy2ACKL4xuN9veu6l0MahOxx0z0TU6mzjj=w375-h17-no)

**Comment by ZyX-I** [comment]
This looks like you are not using a patched font and branch symbol happened to occupy a code point which was also occupied by other symbol from other (non-PowerlineSymbols) font. If this is true I cannot do anything with this, using private use area does not allow reserving code points just for one use; you can fix the issue by either removing font(s) with offending glyph, using a patched font or determining how (and if) fontconfig may be configured to look for fallback glyphs first in PowerlineSymbols and only then anywhere else (I guess this may be only a matter of changing `10` in `10-powerline-symbols.conf` to some smaller integer).
