### ISSUE TITLE
Tmux status line is duplicated once every second

### ISSUE THREAD

**Issue by bendavis78** [powerline/powerline#1679]
Using tmux 2.3, powerline 2.5. As soon as I start tmux, the status line starts duplicating, stacking on itself about once every second.

![image](https://cloud.githubusercontent.com/assets/324392/20156657/e5113662-a696-11e6-8ff0-644f9dfe09c9.png)

**Comment by BlitzKraft** [comment]
In the words of @ZyX-I :

> Duplicate of #1652. Also see #1502.
