### ISSUE TITLE
Statusline not showing in iTerm with tmux -CC

### ISSUE THREAD

**Issue by ddauer** [powerline/powerline#1680]
On macOS 10.12.1 with iTerm 3.0.12, the powerline statusbar works fine in vim as well as tmux 2.3 (both from homebrew).

However, when starting tmux with `tmux -CC`, I get a new window with only the bash promt and not the statusbar. Any ideas why this is not working?

**Comment by ZyX-I** [comment]
`tmux -CC` starts control mode. I do not know how you see anything here (it is supposed to be used with some application which parses the output and you have not stated you use anything like this), but in `CONTROL MODE` section there are no notifications for specifically status lines and apparently it is not sending `%output` notifications for status lines. If you think it should it is better ask tmux bug tracker, I have never used control mode.
