### ISSUE TITLE
Arrows don't appear in prompt. Directories separated by "|" instead.

### ISSUE THREAD

**Issue by finix14** [powerline/powerline#1684]
I have installed all the patched fonts, and selected ubuntu mono for powerline in terminal as the custom font. UTF-8 is the encoding and using gnome terminal. Here's the screenshot http://i.imgur.com/FenWUXi.png
Have this in my bashrc:

```
 if [ -f /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh ]; then
             source /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh
fi
```
Please help.

**Comment by ZyX-I** [comment]
This looks like if you have non-unicode locale (if you are using daemon then non-unicode locale in whatever place you launched it).

**Comment by finix14** [comment]
I think it's already Unicode. http://i.imgur.com/sCmEKa9.png
I suspect it might be my $PS1  variable.. 
It's \[\] itachi \[\] \[\]~ \[\]| \[\]bash \[\] \[\]
http://i.imgur.com/0MHukFT.png
Thanks

**Comment by finix14** [comment]
Thanks a tonne mate. Finally got it working :+1:  :sob:
Updated my locale to UTF-8. It was english India previously.
Output of `locale` now reads
```LANG=en_US.UTF-8
LANGUAGE=en.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
