### ISSUE TITLE
Powerline not loaded in pre-compiled MacVim

### ISSUE THREAD

**Issue by justinmayer** [powerline/powerline#1687]
It would be nice to be able to use MacVim + Powerline without installing Xcode, but I have never been able to figure out whether that's possible, and if so, how to make that happen.

The only way I have ever been able to use Powerline with MacVim is by installing Xcode and then compiling MacVim with Homebrew via the [method outlined in the Powerline docs](https://powerline.readthedocs.io/en/latest/installation/osx.html#vim-installation). I have tried `brew cask install macvim` as well as downloading directly from the [MacVim releases page](https://github.com/macvim-dev/macvim/releases), but the Powerline status bar never loads when using those instances of MacVim.

I guess my question is... why? What are the pre-built MacVim applications missing? Conversely, what is it about compiling MacVim via Homebrew that allows Powerline to function properly?

**Comment by ZyX-I** [comment]
You need python support, this is the only requirement put on Vim. Vim’s python support is (not) added at compile time.
