### ISSUE TITLE
Not visible in Vim unless multiple windows are open

### ISSUE THREAD

**Issue by qwertystop** [powerline/powerline#1688]
Title says it all. Powerline is normally non-present (The status line with -- INSERT -- or the last typed command is still there), but when I have multiple windows open (whether vertically or horizontally split, and whether it's multiples of the same buffer or multiple buffers), it shows up under all of them as it should.

I can provide configuration information as necessary but don't want to just dump a wall of everything on you. This is a terminal Vim, not running in a GUI; version is 7.4, compiled with Python 3 support. OS is Mint. I vaguely recall an issue like this a while ago when I was setting up on a previous system, but can't seem to find anything on it now, so that's just a vague assurance that it's probably solvable?

**Comment by ZyX-I** [comment]
This is not a bug, `:h 'laststatus'`.

**Comment by bennypowers** [comment]
This should be added to the docs.

**Comment by qwertystop** [comment]
Agreed there. Default behavior, not obviously intended functionality, not obviously configurable, and you only need to do it once per Vim install so it's easy to forget about by the next time you need it.
