### ISSUE TITLE
Uninstall powerline

### ISSUE THREAD

**Issue by olibchr** [powerline/powerline#1691]
There is no information whatsoever on how to remove powerline. I installed it with the install.sh and it screwed up my bash_profile for some reason. It is common curtesy to provide a removal script and not only an install script. Is there any other way?

**Comment by ZyX-I** [comment]
Powerline does not provide any scripts to install it, it is supposed to be installed by some package manager (pip, easy_install or system package manager) which also naturally handles the removal (installation script does not do any automatic edits to any configuration files). If you installed powerline with `install.sh` then you need to go to the maintainer of `install.sh`, not here.
