### ISSUE TITLE
Unable to see the conda virtual environment

### ISSUE THREAD

**Issue by drorata** [powerline/powerline#1692]
When activating a virtual environment (`source activate myenv`), I don't see an indication of the activated environment in the segments. Note I have `'virtual_env'` in the `SEGMENTS` and I have disabled `PS1` change from conda's config (`changeps1: False`).

How can I get to see the active environment?

**Comment by drorata** [comment]
I replaced 
```
env = os.getenv('VIRTUAL_ENV') or os.getenv('CONDA_ENV_PATH')
```

with 

```
env = os.getenv('VIRTUAL_ENV') or os.getenv('CONDA_ENV_PATH') or os.getenv('CONDA_DEFAULT_ENV')
```

This seems to solve the problem...

**Comment by ZyX-I** [comment]
Why this issue is here? Powerline virtualenv segment uses

```Python
	return (
		(not ignore_venv and
		 os.path.basename(segment_info['environ'].get('VIRTUAL_ENV', ''))) or
		(not ignore_conda and
		 segment_info['environ'].get('CONDA_DEFAULT_ENV', '')) or
		None)
```

and thus should not have the problem. Don’t know whether it should check CONDA_ENV_PATH, but it definitely will show virtual environment when CONDA_DEFAULT_ENV is there.

**Comment by drorata** [comment]
Sorry... I'm now to powershell (and its derivatives). The right PR should be: https://github.com/banga/powerline-shell/pull/257
