### ISSUE TITLE
strange  PROMPT in zsh

### ISSUE THREAD

**Issue by vados** [powerline/powerline#1695]
![07-12-16_21 08 03](https://cloud.githubusercontent.com/assets/1023532/21052728/12c25a78-be2f-11e6-9140-dba100c73f29.png)
zsh 5.2
Python 2.7.12
powerline-status Version: 2.4
urxvt
How to fix it ? 
thanks for the help

**Comment by ZyX-I** [comment]
What is strange? I do not see anything unexpected here if you are using vi bindings.
