### ISSUE TITLE
vim: Selecting tabs with mouse cycles tab instead of select

### ISSUE THREAD

**Issue by erikw** [powerline/powerline#1696]
If vim is configured with `set mouse=a` you can click on the tabs to select a tab. If powerline is enabled in vim, then a click on any tab will instead cycle to the next tab, like `gt` in normal mode, instead of selecting the clicked tab.

**System:**
Powerline: `2.5`, python3 version, installed with pip3.
Vim: `8.0`
Python: `3.5.2`
Terminal emulator: iTerm `3.012`
OS: macOS Sierra 10.12.1

Very annoying :-)

**Comment by ZyX-I** [comment]
Duplicate of https://github.com/powerline/powerline/issues/1353.

**Comment by erikw** [comment]
@ZyX-I that issue is closed though, can you reopen it?

**Comment by ZyX-I** [comment]
@erikw Relevant patches are already merged and should work. Are you using default configuration or have copied it somewhere at some older version?

**Comment by ZyX-I** [comment]
It was merged in powerline-2.2.

**Comment by erikw** [comment]
Ahh it was outdated config files. Now it works. Thanks :)
