### ISSUE TITLE
bash prompt looks rectangle 

### ISSUE THREAD

**Issue by shyamjos** [powerline/powerline#1697]
Bash prompt looks different (rectangle ), How can I change it to arrow ?
![bash](https://cloud.githubusercontent.com/assets/3982702/21292067/8aa61012-c51d-11e6-87b3-96b0ca30e214.png)

but looks fine in vim 
![vim](https://cloud.githubusercontent.com/assets/3982702/21292065/7d3de8c8-c51d-11e6-913e-acf2f61c1570.png)

PS: already using inconsolata  for powerline

**Comment by ZyX-I** [comment]
This means that you have non-unicode locale (most likely, non-unicode locale at the point where you started powerline-daemon).

**Comment by joe247** [comment]
I too have the same problem how do I rectify...?
![Screenshot from 2019-12-26 10-44-43](https://user-images.githubusercontent.com/38415384/71459298-ce873300-27cc-11ea-8ede-4424a41c4726.png)

**Comment by PH111P** [comment]
@joe247, it looks like you're not using a correct font. Try using one of the patched powerline fonts.

**Comment by joe247** [comment]
Thanks! It's working now... I'm using [SourceCodePro.](https://fonts.google.com/specimen/Source+Code+Pro)...
![Screenshot from 2019-12-31 13-18-49](https://user-images.githubusercontent.com/38415384/71614345-180ebe00-2bd1-11ea-9838-0c64f75f33d9.png)
