### ISSUE TITLE
Trailing 2 at the end of directory address

### ISSUE THREAD

**Issue by varundey** [powerline/powerline#1703]
Powerline works perfectly for me except that I am getting a trailing '2' at the end like the one shown in the screenshot
![screenshot from 2017-01-11 12-16-26](https://cloud.githubusercontent.com/assets/9202135/21838519/5f337bd4-d7f8-11e6-9186-d97ffc7186fc.png)

This appeared when there was an error installing some other package and has been persistent since then. I have tried reinstalling powerline and there is no sign of this number 2 anywhere in my .bashrc file

**Comment by ZyX-I** [comment]
This is a number of background jobs: [jobnum](https://github.com/powerline/powerline/blob/d53695a3fd244d6ceb9607c7407b098eba32e5e7/powerline/config_files/themes/shell/default_leftonly.json#L24-L27) segment. You may check `jobs` output to determine what are these two jobs.

**Comment by varundey** [comment]
`jobs` give me an empty result as there are no stopped jobs in the background. Just to confirm it, I kept .bashrc in background jobs and the number changed to 3. As soon as I closed the bashrc, the number changed back to 2
![screenshot from 2017-01-11 14-24-54](https://cloud.githubusercontent.com/assets/9202135/21842009/da23ff82-d80a-11e6-849b-0721a7f60d2c.png)
Also, just to clarify, I rebooted my system just to make sure there aren't any jobs running

**Comment by ZyX-I** [comment]
@varundey Powerline actually uses `jobs -p` for bash. Though I never heard of a way to make `jobs` output different from `jobs -p`. Can you check the output of

    jobs -p
    jobs -p | wc -l
    echo "$(jobs -p)"
    echo "$(jobs -p | wc -l)"

?

**Comment by varundey** [comment]
yup. I guess both are same
![screenshot from 2017-01-11 14-48-33](https://cloud.githubusercontent.com/assets/9202135/21842524/343e7720-d80d-11e6-882e-daea721bbf46.png)

**Comment by ZyX-I** [comment]
Looks like something like https://github.com/powerline/powerline/issues/749#issuecomment-32706539: there *are* jobs, but they are spawned by something in PROMPT_COMMAND and successfully exit before you execute the new command.

**Comment by varundey** [comment]
I don't think I understand the thread as I don't have the `z` package installed, but AFAICT there are no explicitly mentioned PROMPT_COMMAND in .bashrc

**Comment by ZyX-I** [comment]
@varundey It does not mean that you don’t source something which alters PROMPT_COMMAND somewhere. You should check PROMPT_COMMAND value, not bashrc.

**Comment by varundey** [comment]
sorry for the noob comment. here is the output with the command

```sh
$ echo $PROMPT_COMMAND
pre_prompt_command; _powerline_set_prompt

```

**Comment by ZyX-I** [comment]
@varundey This means that `pre_prompt_command` runs two jobs which quickly disappear. Powerline should be the first.

**Comment by varundey** [comment]
```sh
$ export PROMPT_COMMAND=_powerline_set_prompt
```
does the trick for the current terminal window. However when I add this line in my bashrc file, there's no change. What am I doing wrong?

**Comment by ZyX-I** [comment]
@varundey There is a reason why pre_prompt_command appears. You need to (re)move this reason (remove it or move so that at the end powerline command appears first). Using `bash -i -x` may give a hint.

**Comment by ZyX-I** [comment]
Given its name (specifically “prompt” in the name of the offending function) I guess that you have some other prompt plugin installed.

**Comment by varundey** [comment]
I just did a `$ unset pre_prompt_command` and the number changed to 1 for the current terminal window but now a `pre_prompt_command: command not found` message follows me everywhere right after I execute a command. Guess I have to dig deeper into it. Thanks for all the help :+1:
