### ISSUE TITLE
Wrong cursor position in termite

### ISSUE THREAD

**Issue by lrvick** [powerline/powerline#1705]
Exact replica of: https://github.com/powerline/powerline/issues/845

Using latest python 3.6 and powerline 2.5 with latest Hack font.

Oddly in any terminal other than termite (such as urxvt) gets corrupted attempting to render with the same font.

My complete dotfiles are available here for reference: https://github.com/lrvick/dotfiles

Termite:
![](http://i.imgur.com/fpWSrOy.png)

urxvt:
![](http://i.imgur.com/gTfh0cD.png)

**Comment by ZyX-I** [comment]
Powerline only tells zsh what to draw, deciding where to position cursor is zsh job. The image looks like zsh for some reason thinking that some characters (I guess, powerline dividers) are wider then they actually are. Given that zsh is right when in urxvt I guess that you have a problem with locale: zsh operates in a 8-bit locale (what you see there looks like UTF-8 characters interpreted as latin1), powerline assumes unicode one. Termite also assumes unicode, but urxvt somehow figures right locale out (you did run it from termite so it inherits locale settings, did not you?). Check `locale` output.

I do not know how this situation appeared, but powerline itself cannot make zsh measure prompt leght right.

**Comment by lrvick** [comment]
@ZyX-I fixing up my locales and all is well. Sorry about that!

**Comment by link3904** [comment]
@lrvick Hey how did you end up fixing locales to solve the problem?

**Comment by link3904** [comment]
Problem Solved.

For people who don't know how to fix locale settings, make sure the locale you're using (i.e. en_US.UTF-8) is un-commented in `/etc/locale.gen`. After that, run `locale-gen` again and check your `locale` output too see if there are still errors. Restart your terminal and problem should be solved!
