### ISSUE TITLE
Short prompt

### ISSUE THREAD

**Issue by sebelk** [powerline/powerline#1707]
Hi, 

I use powerline-2.5-3.fc25.x86_64 and powerline-fonts-2.5-3.fc25.x86_64.

How can I do to make prompt show the basename of the current working directory, and not the full path of it?

Thanks in advance!

**Comment by s-ol** [comment]
by reading the docs and configuring powerline.
See [themes](http://powerline.readthedocs.io/en/master/configuration/reference.html#themes) and [the reference of the `cwd` segment](http://powerline.readthedocs.io/en/master/configuration/segments/shell.html#powerline.segments.shell.cwd).
