### ISSUE TITLE
Suppress whitespace when tmux status line is filled

### ISSUE THREAD

**Issue by Paschalis** [powerline/powerline#1708]
As you can see in the following example, there is too much white space taking up screen space, which could have been used to display more windows instead:

![screen shot 2017-01-24 at 22 57 51](https://cloud.githubusercontent.com/assets/1271164/22266469/d949ca6e-e288-11e6-9e57-d80d76f5d076.png)

The only variable that I've found in the configs that removes some space is the 'spaces' variable in `themes/powerline.json`, which removes a single space from everywhere if set to `0`.

For example, I don't want the space between the window id and the divider, and not so much space between the window name and the next window.

BTW, thanks for the nice plugin! 👍

Cheers,
Paschalis

**Comment by ZyX-I** [comment]
These “segments” are controlled by tmux, powerline only tells tmux how they should look like: it does not even know how many of them there are there. I can’t suppress spaces there without spawning other problems.
