### ISSUE TITLE
invalid syntax while installing from pip3

### ISSUE THREAD

**Issue by Alirezaies** [powerline/powerline#1711]
Hello, I'm facing error while trying to install it with pip3

    Collecting powerline
      Downloading powerline-0.2.4.zip (79kB)
        100% |████████████████████████████████| 81kB 50kB/s
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-ieu0zabf/powerline/setup.py", line 27
            zip_safe = False,
            ^
        SyntaxError: keyword argument repeated

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ieu0zabf/powerline/

**Comment by ZyX-I** [comment]
You are installing powerline pip package, it has nothing to do with powerline from this repository. You must use `powerline-status` instead.
