### ISSUE TITLE
Vim : mode update

### ISSUE THREAD

**Issue by hutou** [powerline/powerline#1713]
Mode remains set to "Normal" when typing r to replace one char (should be set to "Replace", I think ?)

**Comment by ZyX-I** [comment]
1. “Replace” mode is what you will see when typing `R` (*upper case* R), `r` is different.
2. `r` does not start any mode. It is incomplete built-in command.
3. Typing `r` does not trigger statusline redraw.
4. AFAIK “pending input for incomplete normal mode command” “mode” is not exposed anywhere, as well as part of the incomplete command. It may be shown by Vim with some settings, but it is not available from VimL.

So I cannot do anything to change current behaviour.
