### ISSUE TITLE
Any way to show OPERATOR in Vim statusline when in operator pending mode?

### ISSUE THREAD

**Issue by trusktr** [powerline/powerline#1718]
Is it possible?

**Comment by ZyX-I** [comment]
Vim does not trigger statusline update in this mode. I cannot do anything with this.

**Comment by ZyX-I** [comment]
Though no, it does trigger update. It either does not provide proper `mode()` output or happens to trigger update before entering this mode.

**Comment by ZyX-I** [comment]
If you want to check this yourself, I use the following command for checking when statusline updates are triggered:

```Shell
vim -u NONE -i NONE -N --cmd 'let &stl="%{execute(\"let g:cnt=get(g:, \\\"cnt\\\", 0) + 1|unsilent echon g:cnt\").\"m:\".mode(1)}"' --cmd 'set ls=2'
```
