### ISSUE TITLE
I cannot change the segment of powerline for tmux

### ISSUE THREAD

**Issue by wsbky** [powerline/powerline#1724]
#1724

I cannot change the segments of powerline for tmux. I cannot change the segments even editing the original source.  

please refer  
  
[bindings/tmux/powerline.conf](https://github.com/wsbky/setting-files/blob/master/powerline/bindings/tmux/powerline.conf)  
[config_files/config.json](https://github.com/wsbky/setting-files/blob/master/powerline/config_files/config.json)  
[config_files/themes/tmux/custom.json](https://github.com/wsbky/setting-files/blob/master/powerline/config_files/themes/tmux/custom.json)

**Comment by ZyX-I** [comment]
You must restart daemon after changing settings.

**Comment by wsbky** [comment]
Thanks!

**Comment by wsbky** [comment]
I cannot change the segment which returns vcs.branch even after I restart powerline-daemon with the option r.
