### ISSUE TITLE
How to set colour scheme for one particular occurrence of a segment?

### ISSUE THREAD

**Issue by user501254** [powerline/powerline#1725]
I have something like this in my shell config file:

```JSON
{
	"segments": {
		"above": [
			{
				"left": [
					{
						"function": "powerline.segments.shell.mode"
					},
					{
						"function": "powerline.segments.common.net.hostname",
						"priority": 10
					},
					{
						"function": "powerline.segments.common.env.user",
						"priority": 30
					},
					{
						"function": "powerline.segments.common.env.virtualenv",
						"priority": 50
					},
					{
						"function": "powerline.segments.shell.cwd",
						"priority": 10,
						"args": {
							"use_path_separator": true
						}
					},
					{
						"function": "powerline.segments.shell.jobnum",
						"priority": 20
					}
				]
			}
		],
		"left": [
			{
				"function": "powerline.segments.shell.mode"
			},
			{
				"function": "powerline.segments.common.time.date",
				"name": "fake_newline",
				"draw_hard_divider": false,
				"args": {
					"format": "$ "
				}
			}
		],
		"right": [
			{
				"function": "powerline.segments.shell.last_pipe_status",
				"priority": 10
			},
			{
				"function": "powerline.segments.common.vcs.stash",
				"priority": 50
			},
			{
				"function": "powerline.segments.common.vcs.branch",
				"priority": 40
			},
			{
				"function": "powerline.segments.common.time.date"
			},
			{
				"function": "powerline.segments.common.time.date",
				"args": {
					"format": "%H:%M:%S %A",
					"istime": true
				}
			}
		]
	}
}
```

I want to set different colours for only the 1st occurrence of `powerline.segments.common.time.date`.
How can I do this?

**Comment by ZyX-I** [comment]
You need to name the segment and assign color for this name. Similar to assigning colors for [player segment](https://powerline.readthedocs.io/en/latest/configuration/segments/common.html#module-powerline.segments.common.players): I could not rely on `function` key there because there are many player segments which need same coloring.

And for questions there is mailing list, issue tracker is for bugs or feature requests.

**Comment by user501254** [comment]
Sorry, but I did assign `"name": "fake_newline"` as visible in the above snippet and assigned it custom colours but there was no change.

**Comment by ZyX-I** [comment]
@user501254 Mistaken, this is for themes only. It is impossible to make separate highlighting for function segments.

**Comment by user501254** [comment]
@ZyX-I Would it be viable to add such a feature?

**Comment by ZyX-I** [comment]
I can hardly call including one segment more then once a common request: the single date date segment which actually is expected to be used separately as date and time already has a workaround that makes it possible to highlight date and time differently.

You can relatively easy workaround this now: just create a copy of the segment (or segment which is a filtering proxy for another one) which returns different `highlight_groups` in subsegments. You don’t even need to fork the upstream for this: powerline is fine with segments stored in any importable module.
