### ISSUE TITLE
Powerline daemon AWOL.

### ISSUE THREAD

**Issue by jimthree** [powerline/powerline#1726]
Hi Folks.

I've had all sorts of woes getting power line installed on my Mac OS X 10.11.  Using the `pip install powerline-status` I found that the scripts and configs weren't installed, and I had to go grab them from github and install them myself.  Now i've done that, Powerline is working, but it's pretty slow (in iTerm).  I suspect it's because it's not using `powerline-daemon`. It doesn't seem to exist on my system, so I assume it was another thing that wasn't included in the pip install.  Problem is that I don't know where to get it from, and even if I did, i'm not sure how to run it.  Is it enough to just call `powerline-daemon -q` from `.bash_profile`?

**Comment by ZyX-I** [comment]
Yes, it is enough. But you are doing something wrong, `pip install` *does* install configuration and scripts, you need to fix this. How exactly do you check that it does not?

And WTF is AWOL?

**Comment by ZyX-I** [comment]
`powerline-daemon` itself is part of the scripts so I do not know how you can “grab scripts from github” and miss `scripts/powerline-daemon`, it is not hiding anywhere unlike `powerline` which is client; normally a compiled binary built by `setup.py` and thus not present on github, though there are two alternatives in `client/` which are less and far less performant.
