### ISSUE TITLE
tmux master branch version issue

### ISSUE THREAD

**Issue by Chris-Bee** [powerline/powerline#1727]
Hello,
when compiling the tmux from source (master branch). tmux -V shows "master" as the version number. This causes "source .powerline/powerline/bindings/tmux/powerline.conf" to fail. If I checkout the latest tag of tmux so that tmux -V shows a version number e.g. 2.3 - "source .powerline/powerline/bindings/tmux/powerline.conf" works fine.

**Comment by BlitzKraft** [comment]
I had the same issue. when I checked out master. I changed the file in `bindings/tmux/__init__.py` to hard code the version info for now. 

```
Line 76: version_string = "tmux 2.3"
```

This fixed it. Excepting that, I don't think there is much that can be done from powerline.

**Comment by s-ol** [comment]
@BlitzKraft: well, sane behaviour would be to expect tmux to be of the latest supported version if it reports `master`.

**Comment by Chris-Bee** [comment]
@s-ol That makes the most sense. Can anybody do it and just do a pull request?
