### ISSUE TITLE
Help， Mac os powerline  like square why  ?

### ISSUE THREAD

**Issue by toplinuxsir** [powerline/powerline#1728]
As below a picture , become square :
![image](https://cloud.githubusercontent.com/assets/1111353/23252759/f6127db4-f9ec-11e6-9f3a-46c3e018dd4b.png)

**Comment by ZyX-I** [comment]
You are running powerline (or powerline-daemon) from non-unicode locale. Note that if you use powerline-daemon it only matters which locale it had at the point daemon was launched, *not* which locale shell has now. To check locale use `locale` command.
