### ISSUE TITLE
MacOS Sierra Iterm2 tmux -2 new-session

### ISSUE THREAD

**Issue by AcidScorpion** [powerline/powerline#1731]
After upgrade to latest MacOS version I've got issue, when during remote connection (MacOS client -> Linux server) didn't started tmux with powerline. Just usual tmux (green bottom line). With Linux clients no such problems. Connection to already running tmux with powerline is OK.
During connection, running bash script:
```bash
TMUX="/usr/bin/tmux"
POWERLINE_CONF="$HOME/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"

$TMUX -2 attach || \
$TMUX -2 new-session -s "$(hostname -s)" -n "$(hostname -s)" \; source "$POWERLINE_CONF"
```
Any advice and suggestions will be greatly appreciated

Update:
https://powerline.readthedocs.io/en/master/troubleshooting.html#in-tmux-there-is-a-green-bar-in-place-of-powerline
Done already and it worked with previous MacOS version

**Comment by ZyX-I** [comment]
Your script is not going to source powerline if tmux server was not created by this script. Did you try sourcing `powerline.conf` in an existing session?

**Comment by AcidScorpion** [comment]
How I can do that? Tried some ways, but seems, doesn't work for me.

**Comment by ZyX-I** [comment]
@AcidScorpion Usually it is easier just to run `powerline-config tmux setup` from the shell inside tmux: in any case `powerline.conf` does exactly this. Also it may show some errors if they occurred.

**Comment by AcidScorpion** [comment]
Thanks! That is really help!

so, `powerline-config tmux setup` shows me next error:
```
Traceback (most recent call last):
  File "/home/acid/.local/bin/powerline-config", line 6, in <module>
    from powerline.commands.config import get_argparser
  File "/home/acid/.local/lib/python2.7/site-packages/powerline/commands/config.py", line 6, in <module>
    import powerline.bindings.config as config
  File "/home/acid/.local/lib/python2.7/site-packages/powerline/bindings/config.py", line 19, in <module>
    from powerline.commands.main import finish_args
  File "/home/acid/.local/lib/python2.7/site-packages/powerline/commands/main.py", line 17, in <module>
    encoding = get_preferred_arguments_encoding()
  File "/home/acid/.local/lib/python2.7/site-packages/powerline/lib/encoding.py", line 89, in get_preferred_arguments_encoding
    locale.getdefaultlocale()[1]
  File "/usr/lib64/python2.7/locale.py", line 511, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib64/python2.7/locale.py", line 443, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```
Which gave me a clue about some issue with locale configuration on my Mac. So, in my .profiles was only
`export LANG=en_GB.UTF-8`

I added as additional
`export LC_ALL=en_GB.UTF-8`

After that, such issue has been fixed.
Case closed :)

**Comment by ZyX-I** [comment]
Always thought `LANG` should be enough: I personally do not have `LC_ALL` defined (Gentoo linux). But I saw `locale` output from other Mac OS users and they seem to have that defined pretty often.
