### ISSUE TITLE
Git clone/pull/push causing powerline failure

### ISSUE THREAD

**Issue by keawade** [powerline/powerline#1737]
Every time I run the command `git clone`, `git pull`, or `git push` my terminal's output get's turned into what look like the underlying character codes.

![powershell_powerline_git_failure](https://cloud.githubusercontent.com/assets/7308850/23819998/a2abc0c4-05d4-11e7-90ce-19b53fb9a5d2.PNG)

I'm using HyperTerm but have verified that this occurs even in regular PowerShell.

![powershell_powerline_git_failure_ps](https://cloud.githubusercontent.com/assets/7308850/23820014/fc6b9b16-05d4-11e7-851a-8a9ff6c5c121.PNG)

**Comment by ZyX-I** [comment]
Powerline does not support powershell. Also it uses more lengthy versions of escape codes then what are used here. So I think that you are using some other project.
