### ISSUE TITLE
Complains about missing powerline.conf

### ISSUE THREAD

**Issue by binarykitchen** [powerline/powerline#1739]
Each time I SSH into my server, I am seeing this one error

![selection_001](https://cloud.githubusercontent.com/assets/177641/23831052/ee932266-077d-11e7-8371-a8df4a06ea06.png)

And then I am just seeing this plain theme where powerline and sorin theme are missing
![selection_003](https://cloud.githubusercontent.com/assets/177641/23831059/0fbe0ae6-077e-11e7-8258-69e18f51366a.png)

Any clues what this could be?

**Comment by s-ol** [comment]
Well does the the not exist? If so, you will need to change your `.tmux.conf` to point to where your `bindings/tmux/powerline.conf` really is.

**Comment by ZyX-I** [comment]
The error is pretty descriptive: the file is not there. You do not have powerline installed or do not have it installed to that location, you need to install powerline or point to the correct location.

**Comment by binarykitchen** [comment]
ah, right, that was the problem - thanks!
