### ISSUE TITLE
Incorrect glyphicons on Ubuntu 16.04

### ISSUE THREAD

**Issue by koxu1996** [powerline/powerline#1742]
I installed powerline and fonts using fontconfig method, but glyphicons are not correct:
- gnome terminal (a little too height arrows)
![gnome](http://i.imgur.com/M4AGmjP.png)
- guake (a little too height arrows)
![guake](http://i.imgur.com/2JFSLfu.png)
- xterm (no glyphicons)
![xterm](http://i.imgur.com/U8CoHZG.png)

I also tried installing patched fonts, but nothing helped. I can provide logs, system info or something else.

**Comment by ZyX-I** [comment]
Patched fonts are maintained in https://github.com/powerline/fonts and that should’ve fixed xterm. Though it is known that if font was patched only by fontpatcher without manual adjustments it may be unideal. If patched font did not fix xterm (you should at least see the same problem as in other terminals) then it means you misconfigured something (better also review whether you did use patched font, it does not replace the original). Fontconfig method cannot really be correct for all fonts and all configurations at once.

**Comment by koxu1996** [comment]
I don't really care about xterm, but that's how it look like in other terminals after patching:
- gnome (too small arrows)
![gnome](http://i.imgur.com/y2XHHXi.png)
- guake (too small arrows)
![guake](http://i.imgur.com/mA5oLAX.png)

What should I do?

**Comment by ZyX-I** [comment]
It is exactly patching? First, look whether font was already altered, maybe you just need to install it. Official repository is https://github.com/powerline/fonts, though I think that there may be other places.

If it was not, `fontforge` is able to edit fonts. I never actually used it to do this: using terminus (bitmap font) with bitmap font patcher you may just use any image editor; if I am not mistaking I was using gimp. It would be good to submit PR to the fonts repository afterwards.

**Comment by koxu1996** [comment]
I installed patched fonts from official repository and font is altered.

**Comment by ZyX-I** [comment]
@koxu1996 Patched fonts are maintained there. I guess that either your setup is rather different from the setup of whoever added the patched font, or patched font was never altered manually, only by font patcher, and it is just as “not universal” as fontconfig variant.

**Comment by koxu1996** [comment]
Now I got nearly ideal glyphicons using this pull request https://github.com/powerline/fontpatcher/pull/12.

**Comment by ZyX-I** [comment]
@koxu1996 I do not understand what is going on there, never developed that fontpatcher. So I can’t merge the PR.

**Comment by iamsubhranil** [comment]
@ZyX-I same issue with 16.10

**Comment by koxu1996** [comment]
Powerline is useless on Ubuntu.
