### ISSUE TITLE
ubuntu 16.04  a red bar on the left of the status line

### ISSUE THREAD

**Issue by Barmus** [powerline/powerline#1745]
Hi,I'm using terminal Vim in ubuntu 16.04 ,After I have installed  this plugin through Vundle . Every times i open vim i find a red block on the most left side of the status line. it looks werid . would you be so kind to help me out with this? Thanks a lot .
![image](https://cloud.githubusercontent.com/assets/8174987/24347787/1eaaae94-130c-11e7-9a13-438f7317a9b2.png)

**Comment by ZyX-I** [comment]
What is your configuration and where is the line you used to install powerline?

**Comment by Barmus** [comment]
I have no configuration code for it ,but  I used to use it in ubuntu 14.04 (still with no configuration ) and it works fine . Recently I updated my system to ubuntu 16.04 , and this problem emerged .  By the way , the line I used to install this plugin is  **Plugin 'Lokaltog/vim-powerline'.**

**Comment by ZyX-I** [comment]
Lokaltog/vim-powerline is outdated and no longer maintained.

**Comment by ZyX-I** [comment]
And it is not what you see in this repository.

**Comment by Barmus** [comment]
Okay I got it , Thanks a lot .
