### ISSUE TITLE
Hard divider color isn't set correctly?

### ISSUE THREAD

**Issue by liavkoren** [powerline/powerline#1747]
<img width="298" alt="screen shot 2017-04-01 at 5 21 22 pm" src="https://cloud.githubusercontent.com/assets/5854101/24582536/d9532e46-16ff-11e7-99fb-5ab0bd6ed52f.png">

AFAICT, per the docs, hard divider color should be set by the segment to the left. 

- I've upgraded to the newest version of powerline:
```
$  pip freeze | ag powerline-status
powerline-status==2.5.2
```
- My colorscheme is:
```json
{
	"name": "Default color scheme for shell prompts",
	"groups": {
		"hostname":         { "fg": "brightyellow", "bg": "mediumorange", "attrs": [] },
		"environment":      { "fg": "white", "bg": "darkestgreen", "attrs": [] },
		"mode":             { "fg": "darkestgreen", "bg": "brightgreen", "attrs": ["bold"] },
		"attached_clients": { "fg": "white", "bg": "darkestgreen", "attrs": [] },
		"critical:failure": { "fg": "white", "bg": "darkestgreen", "attrs": [] },
		"critical:success": { "fg": "white", "bg": "darkestgreen", "attrs": [] },
        "virtualenv":       { "fg": "green", "bg": "brightorange", "attrs": [] },
        "cwd":              { "fg": "gray70", "bg": "gray70", "attrs": [] },
        "cwd:divider":      { "fg": "gray70", "bg": "gray70", "attrs": [] },
        "cwd:current_folder":{ "fg": "gray70", "bg": "gray70", "attrs": [] },
        "branch":           { "fg": "white", "bg": "gray10", "attrs": [] },
        "branch_dirty":     { "fg": "white", "bg": "gray10", "attrs": [] },
        "branch_clean":     { "fg": "white", "bg": "gray10", "attrs": [] },
        "branch:divider":   { "fg": "gray10", "bg": "gray10", "attrs": [] },
        "jobnum":           { "fg": "white", "bg": "darkestgreen", "attrs": [] },
        "information:priority":	{ "fg": "white", "bg": "darkestgreen", "attrs": [] }
	},
	"mode_translations": {
		"vicmd": {
			"groups": {
				"mode": {"fg": "darkestcyan", "bg": "white", "attrs": ["bold"]}
			}
		}
	}
}
```
I've tried adding, eg, a `virtualenv:divider` line, but that doesn't change anything. 
The output from `powerline-lint` all [seems unrelated](https://gist.github.com/liavkoren/f47f77a7e828a2b32868e1fc7f699a48) (and prior to upgrading, I cleared all the powerline-lint errors, and that didn't make a difference, either.)

I'm pretty sure I'm just doing something wrong in the config, rather than this being a bug, but I have no idea what to do next, and I've even looked through the source code quickly. 

Thanks!

**Comment by ZyX-I** [comment]
Can you show `powerline shell left` and copy `powerline shell left | cat -v` outputs?

**Comment by ZyX-I** [comment]
I am pretty sure you will have hard time intentionally breaking config like this. I.e. I myself have no idea how you can get this result with configuration. The main reasoning behind question above is to check that problem with colors is *powerline* problem and not some problem with terminal: it may appear that in `cat -v` output there are no sequence to reset the color to black and yet color is reset.

Also note that cwd:divider in your config makes character invisible (gray70 fg + gray70 bg), but it is black.

Additionally: cwd and cwd:current_folder also should be invisible: gray70 + gray70. Maybe your terminal somehow protects you from invisible characters?

And branch colors do not match: requested white fg, black on screenshot. Actually except for the rightmost triangle there are no non-black foregrounds.

**Comment by ZyX-I** [comment]
What are the truncated leftmost triangles?

**Comment by liavkoren** [comment]
Ah, okay, this is interesting. My normal term is iterm2, but I opened terminal.app, and got a prompt that matched the colors defined above, looking like this:

<img width="464" alt="screen shot 2017-04-01 at 9 30 07 pm" src="https://cloud.githubusercontent.com/assets/5854101/24583734/6f81a2c2-1722-11e7-8966-8abb9e0ebb34.png">

*Then I edited my colorscheme, to try and fix the invisible text, but **that** now has no effect:*

```json
...
        "virtualenv":       { "fg": "black", "bg": "brightorange", "attrs": [] },
        "cwd":              { "fg": "black", "bg": "gray70", "attrs": [] },
        "cwd:divider":      { "fg": "black", "bg": "gray70", "attrs": [] },
        "cwd:current_folder":{ "fg": "black", "bg": "gray70", "attrs": [] },
        "branch":           { "fg": "black", "bg": "gray10", "attrs": [] },
...
```
<img width="680" alt="screen shot 2017-04-01 at 9 33 02 pm" src="https://cloud.githubusercontent.com/assets/5854101/24583740/d95978fa-1722-11e7-9f10-331c75cc4ffe.png">

`$ powershell shell left` give:
```
^[[0;38;5;231;48;5;74mÂ âM-^SM-^TÂ Â vmportalÂ ^[[0;38;5;74;48;5;240;22mîM-^B°Â ^[[0;38;5;250;48;5;240m~Â ^[[0;38;5;245;48;5;240;22mîM-^B±Â ^[[0;38;5;250;48;5;240mdevÂ ^[[0;38;5;245;48;5;240;22mîM-^B±Â ^[[0;38;5;252;48;5;240;1mvmportalÂ ^[[0;38;5;240;48;5;236;22mîM-^B°Â ^[[0;38;5;220;48;5;236mîM-^B Â stagingÂ ^[[0;38;5;236;49;22mîM-^B°Â ^[[0m
```

[I actually don't know exactly what the little triangles at the left are. They're red if there was a non-zero exit from previous command or I ctrl-c'd something.]

**Comment by ZyX-I** [comment]
If you are using powerline-daemon you may not get changes until you restart it. There is some automatic reloading functionality, but it is mostly working only in tests for whatever reason.

The fact that colors of your prompt do not match those from `powerline shell left` is rather strange. Also powerline has no left triangles feature.

Based on what I see in `cat -v` output this is neither powerline nor your configuration issue, check settings of iterm2: colors from cat -v do not match colors from the screenshot.

**Comment by ZyX-I** [comment]
Most likely both left triangles and `[` on the left in terminal.app are from some Mac OS-specific bash plugin, powerline tries keeping non-prompt plugins working.

**Comment by liavkoren** [comment]
I rebooted, got the expected powerline in terminal.app, no change in iterm2. I've tried changing the [iterm2 color schemes](http://iterm2colorschemes.com/) but those don't make a difference. Do you know how I access the iterm color settings?

**Comment by ZyX-I** [comment]
And to restart daemon you need `powerline-daemon --replace`, rebooting is an overkill.

**Comment by liavkoren** [comment]
Thanks for your help! 👍 : )

**Comment by ZyX-I** [comment]
Found a setting?

**Comment by liavkoren** [comment]
No, not yet, but it's clearly something wrong with iterm.

**Comment by liavkoren** [comment]
Ah. It was the "minimum contrast" slider?!
