### ISSUE TITLE
Shell arrow/branch icons issue on OS X 10.12.4

### ISSUE THREAD

**Issue by clamey** [powerline/powerline#1748]
After updating to OS X 10.12.4, the shell arrow/branch icons were replaced with 'BR' and '|'.

I removed ~/.config/powerline with no effect.  Here is the output of powerline-lint and locale:

```
 clamey  ~  ls ~/.config/powerline
ls: /Users/clamey/.config/powerline: No such file or directory
 clamey  ~  powerline-lint -p ~/.config/powerline -p /usr/local/lib/python2.7/site-packages/powerline/config_files
 clamey  ~  locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

Happens on iTerm 3.0.15 and Terminal 2.7.2.

Screenshot of Terminal

![powerline-issue](https://cloud.githubusercontent.com/assets/1063046/24765039/960dac3a-1ab3-11e7-9f5b-a9702b00b4b1.png)

Iterm settings (Non-ASCII same as ASCII set)

![iterm-settings](https://cloud.githubusercontent.com/assets/1063046/24765116/da3e9194-1ab3-11e7-9aea-e1f0f56e7e14.png)

**Comment by ZyX-I** [comment]
You have run powerline-daemon (if you are using it) or the shell itself in non-unicode environment. You need to make sure that `locale` is unicode at the point where daemon is run and in the shell.

**Comment by ZyX-I** [comment]
Since locale is unicode, I assume you are using daemon. Check locale *there*.

**Comment by ZyX-I** [comment]
`powerline-daemon --replace` from a shell where you checked locale should fix the issue for one session.

**Comment by clamey** [comment]
```powerline-daemon --replace``` fixed it, thanks.  The powerline daemon started before locale was set to UTF-8.  Nothing to do with 10.12.4, sorry for the misdirection.
