### ISSUE TITLE
Is there a way someone could donate money to this project or the people maintaining it?

### ISSUE THREAD

**Issue by sheriferson** [powerline/powerline#1753]
Powerline is extremely useful to me. It drastically improves my terminal workflow and environment, and as I can see from the number of stars and number of open and closed issues, it does for many others.

Is there a way someone could donate some money to this project or the maintainer(s) (especially @ZyX-I) to show thanks and to keep it going?

(Edit: if there isn't, thoughts about adding a link or donate button to the README?)

**Comment by ZyX-I** [comment]
I know only that @Lokaltog has set up bountysource, but it looks like it is not working any more. I was not going to set up something like this: powerline is not top priority and maintained less actively by me then I could, mostly spending time on Neovim.

Also generally there is mailing list for question while issue tracker is for issues.
