### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by essank** [powerline/powerline#1756]
I installed powerline but I got this error every time I open the terminal
```
-bash: /Library/Python/2.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh: No such file or directory
```

How I can fix this problem?

**Comment by ZyX-I** [comment]
You need to source the file at the location you installed powerline to, this error means that you are using incorrect location.

**Comment by essank** [comment]
I wrote this command 
```
which powerline
``` 
and I got nothing! How to delete it?

**Comment by ZyX-I** [comment]
To delete what? I do not know how you installed powerline in first place. Neither powerline itself nor any packages I am aware of do anything to enable powerline in bash during installation, normally you install powerline and edit the bashrc yourself and thus know how to undo edits.

**Comment by essank** [comment]
what I did is that:
```
pip install --user powerline-status
pip install --user git+git://github.com/powerline/powerline
```

**Comment by ZyX-I** [comment]
That should not yield `-bash: /Library/Python/2.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh: No such file or directory`, `setup.py` is maintained here and it does not do anything to any user configuration.

When using pip you may get information about where it is installed by using `pip show powerline-status | grep Location`. To get `which powerline` working you need to find where pip installs executable, usually that is the same as location, but `lib/.*` replaced with `bin` (e.g. `/home/zyx/.local/lib64/python2.7/site-packages` reported as Location changed to `/home/zyx/.local/bin`).

**Comment by ZyX-I** [comment]
Pip removes packages via `pip uninstall powerline-status`.

**Comment by essank** [comment]
I tried 
```
pip uninstall powerline-status
```
and still same error

**Comment by ZyX-I** [comment]
@essank As I said setup.py does not do anything to your configuration. So there is no reason error will disappear, you need to undo what you did to your bashrc.

**Comment by ZyX-I** [comment]
Most likely you have something like `. /Library…` or `source /Library…` there.
