### ISSUE TITLE
the internal_ip segment doesn't work in tmux

### ISSUE THREAD

**Issue by BowenWang** [powerline/powerline#1763]
Hi!
I just install the powerline and all the python packages needed(including netifaces), 
when I configure the powerline, all other segments work fine, but the internal_ip segment isn't displayed, by the way, the external_ip is working fine

Bowen

**Comment by BowenWang** [comment]
I think the 
powerline.segments.common.vcs.branch
powerline.segments.common.vcs.stash
are not working either.

By the way, this is my default.json file
[default3.txt](https://github.com/powerline/powerline/files/967486/default3.txt)

**Comment by ZyX-I** [comment]
Branch, stash and whatever segments that need state of the shell are not supposed to work unless you set up powerline in shell (not necessary prompt, but you must activate at least tmux part of the shell bindings). internal_ip may need explicitly specifying network interface if it was not detected.

**Comment by BowenWang** [comment]
Thanks, all the problems solved now. 
Another question is that I also want to configure on the vim, I follow the instruction on the website, but when I open Vim after configuration, it seems no change. By the way, I am using spf13 vim configuration.

**Comment by ZyX-I** [comment]
@BowenWang Did you set `&laststatus` option? Powerline does not alters when Vim displays status line, it only alters what it displays in the status line.
