### ISSUE TITLE
Vim `<C-x>` triggers powerline mode change.

### ISSUE THREAD

**Issue by MrMino** [powerline/powerline#1767]
### Steps to reproduce ###
1. Open vim (`$> vim`)
2. Initiate insert mode (push `i`)
3. Push `<C-x>` (`Ctrl+x`)

### Expected behavior ###
1. After opening, powerline shows colors related to normal mode
2. After pushing `i`, powerline switches to insert mode colors
3. After pushing `<C-x>`, powerline stays with insert mode colors

### Observed behavior ###
...
3. Powerline trips up, doesn't show the "mode" block, and goes back to normal mode colors

This causes flickering when using YouCompleteMe (and probably other Omnicomplete style plugins).

**Comment by MrMino** [comment]
Also, mine shows "KeyError: 'ix' in vim's messages.

**Comment by ZyX-I** [comment]
You need to update, correct behaviour *is* changing mode, but new configuration (in develop at least) is so that colors are for insert mode and mode block shows different thing.

**Comment by ZyX-I** [comment]
Looks like there are quite a number of fixes that are not in the latest release.

**Comment by MrMino** [comment]
I just updated it to the latest python3 pip package (`2.5.2`). Problem still persists, even after purging all files from `site-packages`.

**Comment by ZyX-I** [comment]
@MrMino It is not in any release yet.

**Comment by ZyX-I** [comment]
Should be in 2.6.

**Comment by MrMino** [comment]
K, moded package locally myself. Thanks :).

**Comment by ZyX-I** [comment]
2.6 should be available to pip now (and at the time of the previous comment).

**Comment by MrMino** [comment]
Oh wow, nice. Thank you.
