### ISSUE TITLE
Windows 10 Subsystem for Linux - render error

### ISSUE THREAD

**Issue by bschley** [powerline/powerline#1772]
I installed the Windows Subsystem for Linux together with powerline.

![bashscreenshot](https://cloud.githubusercontent.com/assets/3937642/26081875/2a787732-39cd-11e7-937d-a7f5048d1790.png)

![vimscreenshot](https://cloud.githubusercontent.com/assets/3937642/26081960/9142c846-39cd-11e7-85bb-92349aef799c.png)

As you can see, I have question marks next to every box which was rendered... Do you have a solution for it or its a general problem?

Cheers

**Comment by ZyX-I** [comment]
You need to install one of the powerline fonts (preferably patched as I am very unsure that fontconfig fallback will work) and direct the application to use it. Do not know how exactly you could do this. Or simply use top_theme which does not use powerline characters.

In any case this is not a powerline issue: powerline works just fine, just you don’t have necessary glyphs in your font.

**Comment by bschley** [comment]
Yeah was not a powerline issue.

I fixed it. Windows Subsystem for Linux user have to install a font and then reboot the system. After the reboot they have to start the "Bash on Ubuntu on Windows" and then they have to select the font for the console.

**Comment by Juddd** [comment]
Could you tell me your detailed steps about how to install *Powerline* successfully in *Windows 10 Subsystem for Linux*?I thinks that can help some people(include me of course).This is my suitation.And you can see this is my current bash prompt..

![](http://i.stack.imgur.com/SYcGG.png)

**Comment by Juddd** [comment]
Done.Thanks anyway.
