### ISSUE TITLE
Android Environment

### ISSUE THREAD

**Issue by duyu** [powerline/powerline#1774]
Hi,
I'm new to this cool stuff. It actually looks great but I ran into this weird issue very quickly as I'm an Android developer.
After I typed "lunch" command in my Android project, the powerline seems stopped working, the "path" in prompt does not change at all.
It seems like there's some variable defining conflicts, but I'm not sure.
Anybody could help on this one?

Thank you!

**Comment by ZyX-I** [comment]
This looks like

1. You are using bash. You need to provide some details like this.
2. `lunch` command is actually a bash function.
3. In place of being sane and appending things like `$'\nneeded-command'` to `$PROMPT_COMMAND` `lunch` overwrites `$PROMPT_COMMAND` (zsh has saner way of handling such hooks and additionally I can use `$()` in prompt in zsh, so `lunch` are less likely to cause such issues).

If this is true I can do nothing about this. You can source powerline bindings script again after running `lunch`, but this is really a thing `lunch` authors must fix.

**Comment by ZyX-I** [comment]
I think I have found what you meant by “lunch” command and it is exactly what described: lunch [is running](https://android.googlesource.com/platform/build/+/master/envsetup.sh#620) set_stuff_for_environment, which [runs](https://android.googlesource.com/platform/build/+/master/envsetup.sh#289), which  incorrectly [sets](https://android.googlesource.com/platform/build/+/master/envsetup.sh#312) `PROMPT_COMMAND` while best practices tell doing something like [this](https://github.com/powerline/powerline/blob/develop/powerline/bindings/bash/powerline.sh#L86): appending or prepending to `PROMPT_COMMAND` in place of strictly setting it. Though it [allows](https://android.googlesource.com/platform/build/+/master/envsetup.sh#307) omitting the behaviour, still it is a bug which could easily be avoided.

**Comment by ZyX-I** [comment]
If you are going to report that note that I am bothering with `local last_exit_code=$? … return $last_exit_code` when prepending for a reason and they should also be doing this if they choose to prepend their command and not append: it allows things which care about what was the last exit code (like powerline which displays it) receive it even if they happened to be setup before `lunch` was run.

**Comment by duyu** [comment]
Thanks for your specific answer on this!

I also read the source code of [envsetup.sh](https://github.com/android/platform_build/blob/master/envsetup.sh), it turns out there's actually a designed way to solve my issue. 
```shell
 function settitle()
{
    if [ "$STAY_OFF_MY_LAWN" = "" ]; then
        local arch=$(gettargetarch)
        local product=$TARGET_PRODUCT
        local variant=$TARGET_BUILD_VARIANT
        local apps=$TARGET_BUILD_APPS
        if [ -z "$apps" ]; then
            export PROMPT_COMMAND="echo -ne \"\033]0;[${arch}-${product}-${variant}] ${USER}@${HOSTNAME}: ${PWD}\007\""
        else
            export PROMPT_COMMAND="echo -ne \"\033]0;[$arch $apps $variant] ${USER}@${HOSTNAME}: ${PWD}\007\""
        fi
    fi
}
```
I could just set `STAY_OFF_MY_LAWN` in my environment to get around of this issue.
Although I still don't understand why Android is trying to changing the `PROMPT_COMMAND`, and actually the modified `PROMPT_COMMAND` is outputing empty in my test.

**Comment by ZyX-I** [comment]
@duyu Function name is pretty descriptive. It is not “empty”, it is a way to command terminal emulator do something (set title in this case), of course emulator does what it was told to (or simply ignores if you e.g. configured it to ignore titles set like this) and not displays anything on screen. And as I said they should be *appending* to `PROMPT_COMMAND`, not *setting* it, if you are fine without `lunch` adjusting your terminal title that does not mean that code that sets up adjusting terminal title does not contain a bug.

**Comment by duyu** [comment]
@ZyX-I Thanks for your explanation, I've filed a bug to google, let's see what they come back with.
