### ISSUE TITLE
finish_args() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by Ava1onDragoN** [powerline/powerline#1780]
I can't make bash show powerline correctly on Ubuntu 17.04. But I get the Ubuntu 16.04.2 LTS work.

I followed the tutorial https://www.tecmint.com/powerline-adds-powerful-statuslines-and-prompts-to-vim-and-bash/. 

After I put this in .bashrc, it shows finish_args() takes at least 3 arguments (2 given).
if [ -f `which powerline-daemon` ]; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  . ~/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh
fi

**Comment by ZyX-I** [comment]
It looks like you also have two powerline installations, one of which has very old bug. If you are installing powerline using pip make sure it is not installed via system package manager, or for other Python version, or with pip, but for root and not your user.

**Comment by Ava1onDragoN** [comment]
I removed them and reinstalled powerline by root. It works great! 
Thanks for the help.

**Comment by Beanocean** [comment]
I installed powerline-status2.6 on Mac OS using the `pip-9.0.1` provided by the system. When I execute `tmux`, The status bar shows as follow:
<img width="1280" alt="screen shot 2017-09-11 at 15 47 31" src="https://user-images.githubusercontent.com/5241291/30260141-f5c0fbb0-9708-11e7-924b-c6c7204fc4c6.png">

**Comment by ZyX-I** [comment]
@Beanocean The answer does not change, remove all powerline installations except the single most recent one. Cannot say how to deal with protection. I am wondering though, why this problem is common on Mac OS, maybe something like brew having packaged only outdated version?

**Comment by Beanocean** [comment]
@ZyX-I Thanks for your reminder. I installed an old version Powerline by using brew-installed python whose library files was not removed automatically after my uninstallation. After cleaning them up, It works.

**Comment by felixbuenemann** [comment]
A likely cause of this problem is that you previously installed powerline with pip without the `--user` switch and then tried to update with the `--user` switch as listed in the docs (or vice versa).

The easiest fix is to run `pip uninstall powerline-status` twice and then reinstall either with `--user` or globally.

**Comment by samumist** [comment]
@Beanocean I run into a similar problem. I have uninstalled all the powerline/powerline-status I could find. But still have the finish_args problem after reinstall powerline-status with the `--user` flag. my old version powerline was installed with brew. 
I just couldn't find those library files aforementioned. Would you please advice?

**Comment by Beanocean** [comment]
@samumist I can't reproduce the error, but as advice, I think you can try to find the powerline-status in the paths like `/Users/xx/Library/Python/2.7/site-packages/powerline` or `/usr/local/lib/python2.7/site-packages/powerline`. Or try to use the shell command: `locate powerline`

**Comment by dylon** [comment]
It is worth noting that if you have the powerline-daemon running in the background, you must restart it post-upgrade.
