### ISSUE TITLE
 powerline symbol at 0x00A0 not displayed in GVim but works in ViM

### ISSUE THREAD

**Issue by imranmunshi** [powerline/powerline#1781]
I am using Arch Linux and installed powerline, powerline-vim and powerline-fonts from the official repositories.
Everything works except for GVim where the glyphs at 0x00A0 are not displayed in GVim but are properly displayed in ViM. I use ViM under gnome-terminal with ttf-inconsolata, same font is used in GVim.

**Comment by ZyX-I** [comment]
What glyphs at 0x00A0? I can guess that gnome-terminal takes them from fallback font and gvim is not using fallback, but not sure (“is not using fallback” should be meaning “generally cannot use fallbacks”). In any case, this is not a powerline issue.
