### ISSUE TITLE
Support for awesome4+

### ISSUE THREAD

**Issue by martingabelmann** [powerline/powerline#1784]
I already tried it. One just hast to replace   ``awful.util.spawn_with_shell`` with ``awful.spawn.with_shell`` in the `powerline.lua`.

**Comment by crimsonknave** [comment]
Note: my widget did not appear when it was the last in the list as suggested in the doc. Everything worked once I moved it after the layoutbox.

**Comment by martingabelmann** [comment]
I also experience this on some of my machines (only on newer hardware). Having a look in the output/log of awesome it seem like that the powerline daemon is not running/ready when `powerline wm.awesome` is invoked, it says: `powerline-render: error: WM bindings must be used with daemon only`. However, restarting aweseome makes the powerline appearing.   
My quickfix is to not load the powerline module but create the powerline_widget widget and run the two commands manually (the daemon on top and the powerline at the bottom of rc.lua) instead.  
  
Im not sure what causes this since running `powerline-daemon -k;powerline-daemon -q;powerline wm.awesome` directly in the shell works.
