### ISSUE TITLE
Fail to start the powerline.sh

### ISSUE THREAD

**Issue by Juddd** [powerline/powerline#1791]
As you see,I have install the powerline successfully

![](http://i.stack.imgur.com/WJXll.png)

But I cannot start the powerline.sh.

![](http://i.stack.imgur.com/pWdcS.png)

Could you give some advice for this error?

**Comment by ZyX-I** [comment]
You need to install `argparse`. Given that https://pypi.python.org/pypi/argparse it should be installable by `pip`, starting from Python 2.7 it is a part of the standard library. You are highly recommended to update Python though, 2.6 is long since unmaintained.

**Comment by Juddd** [comment]
Thanks,I just don't know how to update the python..

**Comment by Juddd** [comment]
Thanks,it is normal after I have install that `argparse`.
