### ISSUE TITLE
powerline doesn't work for zsh on Arch Linux

### ISSUE THREAD

**Issue by khoi-nguyen** [powerline/powerline#1797]
Hi,

I have the following lines in my .zshrc

    powerline-daemon -q
    . /usr/lib/python3.6/site-packages/powerline/bindings/zsh/powerline.zsh

but they don't seem to do anything. Can anyone help me please?

**Comment by ZyX-I** [comment]
Start with running this code surrounded by `set -x` and `set +x`, this should show you a trace.

**Comment by khoi-nguyen** [comment]
Thanks, that helped me.

It was conflicting with a zsh module.
