### ISSUE TITLE
Sourcing zsh binding gives error

### ISSUE THREAD

**Issue by michaeldel** [powerline/powerline#1802]
Sourcing Powerline's _zsh_ binding does not work and provides a missing argument error like so:

```zsh
$ . /usr/lib/python3.6/site-packages/powerline/bindings/zsh/powerline.zsh
finish_args() missing 1 required positional argument: 'args'
```
Here are some more information about my powerline installation
```
pip show powerline-status                      (07-13 15:46)
Name: powerline-status
Version: 2.6.dev9999-git.b-8d577b59584c51c643495f5173da5b8a04806236-
Summary: The ultimate statusline/prompt utility.
Home-page: https://github.com/powerline/powerline
Author: Kim Silkebaekken
Author-email: kim.silkebaekken+vim@gmail.com
License: MIT
Location: /usr/lib/python3.6/site-packages
Requires: 
```
I found this previous issue which was about a similar error https://github.com/powerline/powerline/issues/1766 and thus uninstalled my Python 2.7 version of Powerline, but the errors still remains.

**Comment by ZyX-I** [comment]
After uninstalling some version you also need to kill the daemon.
