### ISSUE TITLE
Powerline statusline loses its colours in Vim when `:w` is used

### ISSUE THREAD

**Issue by BBagTP** [powerline/powerline#1807]
`vim --version` output:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
```
Using the powerline theme for vim, here is how the theme is called:
```
set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/
set laststatus=2
```

Each time I use `:w` to write to a file, my powerline statusline goes from looking like this:
![image](https://user-images.githubusercontent.com/29816026/28464049-ddabd66e-6e66-11e7-89af-9efa9a9713fc.png)

...to looking like this: 
![image](https://user-images.githubusercontent.com/29816026/28464067-f9577080-6e66-11e7-96f3-c037ffa8232f.png)

If I use `so %` to re-source the .vimrc file in the same session, the statusline colours return as normal (until `:w` is used again)

Doing some research, if I use `:verbose set statusline?`, it outputs `statusline=%!py3eval('powerline.statusline(1)')`. Seems like somewhere the powerline theme is calling to set the `statusline` param to `1`, as opposed to the value of `2` like it should be to have it persist. 

I realise this may not be a powerline theme issue, so please close if necessary (I have also posted this in the Vim issues thread)

**Comment by ZyX-I** [comment]
@BBagTP I see no reason for this parameter to be 2, it is *window identifier* (powerline-specific, introduced before Vim got window identifiers it has now), it has absolutely nothing to do with persistency of any kind. The issue looks like you are calling `highlight clear` during `:write` (i.e. in some BufWrite\* autocommand), possibly by running `:colorscheme`, and what is worse you are doing that without `nested` flag meaning that `powerline.reset_highlight()` called as `Colorscheme` autocommand for this purpose (to force powerline reinitialize colors when colorschemes are changed) is not actually called.

If I am right about some colorscheme switcher I would suggest to get rid of whatever switches colorschemes as it is known that some colorschemes cannot be switched to from some other colorschemes without making some highlight groups cleared, and it is pretty much useless to switch from one colorscheme to the same colorscheme, meaning that whatever does the switching will have to fight such bugs. Or, at least, make it switch colorschemes at autocommand.

**Comment by BBagTP** [comment]
I'm not sure where I found this information, but I read that the only way for the powerline statusline to display is to use `set statusline=2`. See below, I tried using `set statusline=1` and the powerline statusline disappears:
![image](https://user-images.githubusercontent.com/29816026/28486835-241c8b76-6eca-11e7-8ed5-8fbd36b79386.png)

As far as using a colorscheme switcher; I'm not using a switcher, but I am using the ['flattened' solarized colorscheme](https://github.com/romainl/flattened) as I couldn't get the [original Solarized theme](http://ethanschoonover.com/solarized) to work properly (background colours weren't working properly).

Besides the two points I think I addressed in this post, I'm not sure what else you are talking about (I'm not well-versed with vim's config or powerline's config), so a simpler explanation might help me to give you the information you need.

**Comment by BBagTP** [comment]
I just realised that my `verbose set statusline?` is useless, as it's not investigating the parameter that we're interested in. 
Instead, if I use `verbose set laststatus?`, the output is `Last set from ~/.vimrc`, which tells me the issue must be somewhere in my vim config.

**Comment by ZyX-I** [comment]
@BBagTP Your colorscheme contains `hi clear` which clears out colors. And since you do not have `nested` (`:h autocmd-nested`) `ColorScheme` event set up by powerline to fix exactly this issue is not launched. In any case, this is not powerline issue.

**Comment by ZyX-I** [comment]
@BBagTP And the line in question is resourcing files with last path component equal to `.vimrc` (*not* your vimrc, *any* file which happens to meet the requirements, not necessary located in `$HOME`) after you write it. If you comment and restart Vim (or have something in the vimrc which will delete the autocmd on sourcing nevertheless) it is no longer resourced, so next time you do `:w` again autocmd is not launched and you do not see the issue.
