### ISSUE TITLE
PWD freeze.

### ISSUE THREAD

**Issue by demonguy** [powerline/powerline#1808]
When i'm using powerline(installed from pip, powerline-status 2.6), i found sometimes my current working directory will freeze no matter where i `cd` to

 cy  ~  Documents  Sources  A7  cd /home/cy
 cy  ~  Documents  Sources  A7  

I'm not sure what log i should give. So if you need anything else to debug this problem, feel free to tell me.
Thanks

**Comment by ZyX-I** [comment]
It looks like

1. You are using bash.
2. Something is overriding PROMPT_COMMAND so that it no longer contains powerline calls.

E.g. it is known that android SDK scripts are doing this (#1774).

**Comment by demonguy** [comment]
You're right, i'm an Android developer.
After checking, it is overriding by android script after using "lunch" command.
I will check original issue thread and figure out what to do. Thanks
