### ISSUE TITLE
Custom Segments

### ISSUE THREAD

**Issue by ggascoigne** [powerline/powerline#1809]
I know that I can write custom Segments by simply forking the powerline repo, but is there an easy way to put Segments on the python path and see them loaded?  I've tried putting a segment in /Users/ggp/Library/Python/2.7/lib/python/site-packages/mypackage but I can't seem to get anything loaded.

Is this even correct or is there a better way.

**Comment by ZyX-I** [comment]
It does not matter where you put a segment, it just needs to be importable. But nothing would be loaded, you need to have custom configuration.

In any case, this is not the issue. For questions there is mailing list.

**Comment by ggascoigne** [comment]
That's fair enough, but I spent ages trying to work out where support for this is, there's no reference to a mailing list anywhere in the repo that I can find.  So where is it?

**Comment by ggascoigne** [comment]
ok, found it, in the readme and not the docs, and it's a forum not a mailing list (which is why my search failed to find it.

Sorry bout that.

**Comment by ZyX-I** [comment]
Google groups is a mailing list with a web interface, may be used as a forum, though interface sucks and I almost never use it.
