### ISSUE TITLE
lemonbar stacks on one monitor when using two monitors

### ISSUE THREAD

**Issue by cranndarach** [powerline/powerline#1819]
Hello, I'm having an issue with powerline-lemonbar when I use two monitors, where rather than displaying one bar per output, it stacks both of the bars on one.

Specifically, this only happens when one monitor is configured to be above/below the other, i.e., 
```bash
xrandr --output VGA1 --above LVDS1
``` 
results in two stacked bars on VGA1 and none on LVDS1, whereas 
```bash
xrandr --output VGA1 --left-of LVDS1
``` 
results in the expected configuration.

Even when they stack, it's clear that they're still getting information about which output they should appear on. The widths are correct for the intended output (one will be smaller than the other), and I added a `print(bars)` statement to `powerline/bindings/lemonbar/powerline-lemonbar.py`, and the output was: 
```
[('LVDS1', <subprocess.Popen object at 0x7fed4a053978>, 273.2), ('VGA1', <subprocess.Popen object at 0x7fed4a05eac8>, 384.0)]
```

I'm using powerline 2.6, i3-gaps 4.13 (for Manjaro), lemonbar-xft-clicky 0.r214.a2fad82, and python 3.6.

Thank you!

**Comment by s-ol** [comment]
hey @cranndarach, this is a situation I didn't have in mind when writing powerline-lemonbar originally, but it should be an easy fix.

Try changing [`powerline-lemonbary.py:25`](
https://github.com/powerline/powerline/blob/develop/powerline/bindings/lemonbar/powerline-lemonbar.py#L25) like this and please report back with the results.

```diff
--- a   2017-08-15 21:01:04.719551911 +0200
+++ b   2017-08-15 21:01:23.898828663 +0200
@@ -22,7 +22,7 @@
        bars = []

        for screen in get_connected_xrandr_outputs(powerline.pl):
-               command = [args.bar_command, '-g', '{0}x{1}+{2}'.format(screen['width'], args.height, screen['x'])] + args.args[1:]
+               command = [args.bar_command, '-g', '{0}x{1}+{2}+{3}'.format(screen['width'], args.height, screen['x'], screen['y'])] + args.args[1:]
                process = subprocess.Popen(command, stdin=subprocess.PIPE)
                bars.append((screen['name'], process, int(screen['width']) / 5))
```

**Comment by cranndarach** [comment]
That worked perfectly, thank you!
