### ISSUE TITLE
For a day it worked fine, now its broken

### ISSUE THREAD

**Issue by ar0ra1** [powerline/powerline#1822]
![terminalpower](https://user-images.githubusercontent.com/20777462/29534631-4c9b8c1a-86d4-11e7-9a45-c85a0607520a.png)

I tried re-installing, no help!

**Comment by s-ol** [comment]
this is a misconfigured terminal using a font without powerline chars. Maybe you changed but didn't save your font settings in the profile settings.

**Comment by ar0ra1** [comment]
changed the font back to system default. Still not working!

**Comment by ar0ra1** [comment]
any solution to this now ?
finish_args() takes at least 3 arguments (2 given)

**Comment by ZyX-I** [comment]
@ar0ra1 The `finish_args` problem is known to pop up only if you have two incompatible powerline versions installed, normally via different means (e.g. pip and brew installation); in this case you must unistall one. “System default” font is highly unlikely to contain powerline characters, you need to install a patched font from https://github.com/powerline/fonts and use it.

**Comment by ar0ra1** [comment]
i am using only powerline fonts
and i installed powerline using pip only.

**Comment by ZyX-I** [comment]
You may have tried to install it much earlier, long enough ago to forget: I do not change even the internal API often.

**Comment by ar0ra1** [comment]
I installed Elementary Os last week 
Anyway,
Is there a way to completely remove all the old files of powerline that might exist 
and then i do a fresh install ?

**Comment by ZyX-I** [comment]
No, there generally *can’t* be such a way. You need to inspect your setup and check which package belongs `$(which powerline-render)` file and which package belongs `$(python -c 'import powerline.commands.main as pcm ; print(pcm.__file__)')` file, with the error you see either `powerline-render` or `powerline-daemon` are expected to have different version.

**Comment by ar0ra1** [comment]
i deleted all.
Re-installed using pip
changed the font to pre patched for terminal
Working fine as of now
----
Can you clarify one thing?
The first time i installed it
i never used the pre patched font and still it worked fine for a day 
how ? Why did it work in the first place?

**Comment by ZyX-I** [comment]
@ar0ra1 If I knew why I would say that. I do not have elementary OS and you never mentioned even the terminal emulator name. Not that it would help much, everything I know about configuration of different terminal emulators suggests that it can only change due to some user action or due to an update, and latter is very much unlikely because most terminal emulators are very stable.

**Comment by ZyX-I** [comment]
Without a pre-patched font it may work by using PowerlineSymbols.otf assuming emulator uses font rendering library which supports fallback fonts. But `pip` installs neither PowerlineSymbols.otf nor fontconfig configuration file which is required for fontconfig (one of the most used font rendering libraries) to recognize the fallback.

**Comment by ar0ra1** [comment]
I did install the PowerlineSymbols.otf

I came across powerline while browsing this site and found this link :
https://www.tecmint.com/powerline-adds-powerful-statuslines-and-prompts-to-vim-and-bash/

Followed everything mentioned there.
