### ISSUE TITLE
external_ip segment hangs the shell because of network timeout

### ISSUE THREAD

**Issue by erikw** [powerline/powerline#1825]
Helluu!

I experience that the segment `external_ip` is not working good if there is no Internet connection -- it hangs the powerline-daemon for 10 seconds.

# The setup
I have configured correctly powerline for `tmux` and for `zsh`. The cofiguration for tmux uses the `external_ip` segment. 

# The problem
When no internet connection is available, the IP segment at

`/usr/lib/python3.6/site-packages/powerline/segments/common/net.py:_external_ip()`

uses 

`/usr/lib/python3.6/site-packages/powerline/lib/url.py:urllib_read()`

which in turn uses 

```python
urlopen(timeout=10)
```

What now happens is that the powerline-daemon freezes for 10 seconds. If you during this time create a new shell, it will hang too as the powerline daemon is busy. If you press enter in an open shell, it hangs too, as the shell status can't be printed either (uses powerline).

Maybe add a configuration parameter cold be added to `external_ip` to set the network timout setting to something lower than 10s? 

What do you think? 

Having shells freezing because of no Internet connection is simply not good!

**Comment by ZyX-I** [comment]
It will not hang the shell if you set `update_first` argument of `external_ip` to `false`. The argument defaults to true, it forces updating at first call and is needed to not receive bugs like “need to move cursor in Vim to get network load information”, at a cost of slower startup obviously.

**Comment by erikw** [comment]
Aha there you go. However,  `false` as a default value sounds sounder too me, if cost is shells that hangs in case of no Internet-connection.

**Comment by ZyX-I** [comment]
@erikw This will make a bunch of segments empty at startup. Also “no internet connection” yields different result, I would normally receive one of “some status from the provider, with the redirect” (not for https obviously, but https is not used for external_ip by default), that would even be faster then regular reply (provider is closer), “no route to host”, immediately, or “could not resolve host …”, immediately as well.
