### ISSUE TITLE
Prefixing or appending items to powerline prompt

### ISSUE THREAD

**Issue by envintus** [powerline/powerline#1826]
This is a simple question and after looking through the documentation I still cannot figure it out for myself. All I'd like to do is determine how to prefix or append characters to the powerline prompt. Specifically after all of my segments I'd like a space to separate the last segment and the commands I'm typing. I've tried "after" in various places in the themes, like I said after reviewing the docs, but cannot figure it out. I do have my dividers/arrows disabled, so each segment is a "rectangle".

Apologies if this is not the appropriate venue for this type of question, but any help would be appreciated.

**Comment by s-ol** [comment]
you can add a segment with

    {
      "type": "string",
      "contents": "asdasd",
      "highlighting_groups": ["group"],
    },

see the reference: https://powerline.readthedocs.io/en/master/configuration/reference.html (in the chunk on Themes)

**Comment by ZyX-I** [comment]
There is mailing list for questions mentioned in README. Specifically existence of the space before the cursor is controlled by `outer_padding` theme option which is one by default (so you should already have one space).
