### ISSUE TITLE
iTunes Segment not working

### ISSUE THREAD

**Issue by danielnehrig** [powerline/powerline#1829]
System OSX 10.12.6 sierra
Terminal iTerm
tmux right length is 500
This is the pip install of powerline-status

Spotify is working fine
iTunes not at all

Theme
```
{
	"segments": {
		"right": [
      {
        "function": "powerline.segments.common.players.itunes",
        "name": "player"
      },
			{
				"function": "powerline.segments.common.sys.uptime",
				"priority": 50
			},
			{
				"function": "powerline.segments.common.sys.system_load",
				"priority": 50
			},
			{
				"function": "powerline.segments.common.time.date"
			},
			{
				"function": "powerline.segments.common.time.date",
				"name": "time",
				"args": {
					"format": "%H:%M",
					"istime": true
				}
			},
			{
				"function": "powerline.segments.common.net.hostname"
			}
		]
	}
}
```
powerline-lint
```
error while checking theme (key /segments/right/list item 0/function)
found highlight groups list (player_fallback, player) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/dnehrig/Library/Python/2.7/lib/python/site-packages/powerline/config_files/themes/tmux/default.json", line 5, column 56:
     ... werline.segments.common.players.itunes",
                                         ^

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player_fallback not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight groups list (player_play, player) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/dnehrig/Library/Python/2.7/lib/python/site-packages/powerline/config_files/themes/tmux/default.json", line 5, column 56:
     ... werline.segments.common.players.itunes",
                                         ^

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player_play not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight groups list (player_pause, player) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/dnehrig/Library/Python/2.7/lib/python/site-packages/powerline/config_files/themes/tmux/default.json", line 5, column 56:
     ... werline.segments.common.players.itunes",
                                         ^

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player_pause not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight groups list (player_stop, player) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/dnehrig/Library/Python/2.7/lib/python/site-packages/powerline/config_files/themes/tmux/default.json", line 5, column 56:
     ... werline.segments.common.players.itunes",
                                         ^

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player_stop not defined in the following colorschemes: default, solarized

Error while checking theme (key /segments/right/list item 0/function)
found highlight group player not defined in the following colorschemes: solarized
```
powerline tmux right
```
powerline tmux right
#[fg=colour233,bg=default,nobold,noitalics,nounderscore] #[fg=colour247,bg=colour233,nobold,noitalics,nounderscore] ↑  14m 54s#[fg=colour241,bg=colour233,nobold,noitalics,nounderscore] #[fg=colour2,bg=colour233,nobold,noitalics,nounderscore] 1.9 #[fg=colour2,bg=colour233,nobold,noitalics,nounderscore]1.5 #[fg=colour2,bg=colour233,nobold,noitalics,nounderscore]1.1#[fg=colour236,bg=colour233,nobold,noitalics,nounderscore] #[fg=colour247,bg=colour236,nobold,noitalics,nounderscore] 2017-09-09#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore] #[fg=colour252,bg=colour236,bold,noitalics,nounderscore] 18:10#[fg=colour252,bg=colour236,nobold,noitalics,nounderscore] #[fg=colour16,bg=colour252,bold,noitalics,nounderscore]  admins-MBP.local %
```

**Comment by ZyX-I** [comment]
The `powerline-lint` explains that right in the first message: you added a segment, but you did not define highlighting for it.

And do not edit anything in powerline/config_files, it is default configuration which must not be touched, or all your changes will be overwritten on update. User configuration is to be stored in `${XDG_CONFIG_HOME:-$HOME/.config}/powerline`.

**Comment by ZyX-I** [comment]
Though no, `player` highlight is defined in `default` colorscheme (but not in solarized), only auxilary groups are missing. And you would not get spotify working if that was the case.

**Comment by ZyX-I** [comment]
You need to run daemon in the foreground and check its stderr (or define a file to store logs in and check that): `powerline-daemon --foreground --replace`. If log will not explain the problem then I am not of much help: no macos here.

**Comment by ZyX-I** [comment]
Note about configuration file location is still valid, never edit files managed by package manager.

**Comment by ZyX-I** [comment]
You may check what `osascript` does if piped with a script [used by powerline](https://github.com/powerline/powerline/blob/d0d0644e3c8965769fe5c52f84a30c21ea0db2dd/powerline/segments/common/players.py#L486-L502) if there will be nothing in a log (most likely case). Script is pretty self-explanatory.

**Comment by inet-pwnZ** [comment]
I used a local config before I edited the config inside the package just for testing had the same results.
as I said Spotify was working fine I can provide screenshots for the other stuff I'll test stuff out and report back tomorrow thanks for the reply

**Comment by inet-pwnZ** [comment]
ok i fixed the powerline-lint issues with the color scheme
still not properly working though

**Comment by inet-pwnZ** [comment]
i tested the apple script inside players.py which gives a valid output
```
osascript a.scpt
                                                                                                                                        │Letdown{0}nothing,nowhere.{0}Letdown - Single{0}46,742000579834{0}279,325988769531{0}playing
```

**Comment by inet-pwnZ** [comment]
Ok I got it working now
i tailed my tmuxlog
and debuged the issue on a float that had a comma instead of a dot inside

if wanted I can make a pull request with missing thumbing for players and
for the players.py

**Comment by ZyX-I** [comment]
So osascript follows locale settings when printing floats - right? Can it be told to use different locale right in the script or it needs to be passed LC_\* variables? (Teaching powerline to recognize different decimal point character does not look like the right variant: who knows what other unexpected differences locale may yield.)

**Comment by ZyX-I** [comment]
Missing theme highlight would PR would be welcome.

**Comment by danielnehrig** [comment]
![Bildschirmfoto 2019-05-06 um 12 41 30](https://user-images.githubusercontent.com/4050749/57220613-4b765a00-6ffc-11e9-826b-7308d7953a26.png)

just want to point out that this is still not fixed in the repo

**Comment by danielnehrig** [comment]
site note my Mac is installed in German 
and in German floats are represented with a , instead of a dot .
my fix I had back then was
changing lines 533 and 534 in players.py like so

		total = _convert_seconds(now_playing[4].replace(',', '.'))
		elapsed = _convert_seconds(now_playing[3].replace(',', '.'))
