### ISSUE TITLE
what's meaning of `ST 1[2][3]`

### ISSUE THREAD

**Issue by jacinzhang** [powerline/powerline#1833]
![image](https://user-images.githubusercontent.com/9859965/30573282-9311cbec-9cb8-11e7-9e45-fc8063ad341c.png)
I don't know what's meaning of `ST 1` beside git branch on the right.

**Comment by j-f1** [comment]
That’s the `git` [stash](https://git-scm.com/book/en/v2/Git-Tools-Stashing-and-Cleaning) count.
