### ISSUE TITLE
Issue with the Powerline bar

### ISSUE THREAD

**Issue by matze9194** [powerline/powerline#1837]
<img width="789" alt="issue" src="https://user-images.githubusercontent.com/24566968/30882759-58297072-a30a-11e7-95ec-8bcd4810102b.png">

Has anyone a suggestion for the red lines in the pictures ??
 It is not supposed that "Big Bang" an "64?" is standing there. 
I haven't made any costum configuration yet. 
It would be nice when somebody could help me because Iam not a specialist in this area :D

**Comment by ZyX-I** [comment]
This is a bug tracker, not a place for usage questions. And if you have not made custom configuration, then it definitely is not powerline as I already stated, this repository does not contain the only shell plugin which makes use of powerline arrow glyphs in existence.

Also whatever you are seeing there is by no means a default bash, zsh or whatever shell you are using prompt, so you *must* have a custom configuration at least of the shell itself, if not powerline.
