### ISSUE TITLE
Help with enabling segments

### ISSUE THREAD

**Issue by ar0ra1** [powerline/powerline#1841]
I am very beginner at this stuff, I would like to know how to enable/show the battery/weather segment.
I tried going through the documentation, did some stackoverflow searches. 
Every time i end up creating too many errors
Would be really helpful if you could spare some minutes of your time explaining the process

![powerline](https://user-images.githubusercontent.com/20777462/31068398-5d5f23de-a747-11e7-97d6-c120d6f98bcf.png)

**Comment by ZyX-I** [comment]
This is the issue tracker, for usage questions you need to go to the mailing list mentioned in README.
