### ISSUE TITLE
Bash prompt no longer uses > as the separator 

### ISSUE THREAD

**Issue by Guzzii** [powerline/powerline#1842]
Similar to the issue [https://github.com/powerline/powerline/issues/1697](url). The behavior change happened inside one bash session. Here is `locale` returns:
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```
Both Terminal and iTerm2 changed. Feel free to let me know if other information would be helpful to identify the issue. Thank you.

**Comment by ZyX-I** [comment]
As it was said there, it is a locale problem, *most likely locale you run daemon in*. You should be able to resolve the issue by running `powerline-daemon --replace` in a unicode locale, if this repeats find a place where daemon is run from.

**Comment by Guzzii** [comment]
`powerline-daemon --replace` worked. Thanks @ZyX-I !

**Comment by banerjeesamrat** [comment]
Still doesn't work for me even after using powerline-daemon --replace

![image](https://user-images.githubusercontent.com/31121849/31495937-054c0dc4-af49-11e7-93aa-dd80e1ffab19.png)

**Comment by ZyX-I** [comment]
`powerline-daemon --replace` is utterly useless if you have not yet setup locale to be a unicode one. You need to first check what `locale` returns what OP did.

**Comment by Mukundan314** [comment]
`powerline-daemon --replace` dosen't work
locale returned me:
`
LANG=en_IN
LANGUAGE=en_IN:en
LC_CTYPE="en_IN"
LC_NUMERIC="en_IN"
LC_TIME="en_IN"
LC_COLLATE="en_IN"
LC_MONETARY="en_IN"
LC_MESSAGES="en_IN"
LC_PAPER="en_IN"
LC_NAME="en_IN"
LC_ADDRESS="en_IN"
LC_TELEPHONE="en_IN"
LC_MEASUREMENT="en_IN"
LC_IDENTIFICATION="en_IN"
LC_ALL=
`

**Comment by ZyX-I** [comment]
@Mukundan314 See that there is no mention of UTF-8 in the locale output. OP has the example of the correct variant, though with different language.

**Comment by ZyX-I** [comment]
@Mukundan314 @banerjeesamrat What `locale` returns is determined after environment variables. Setting just LANG should be enough unless other are defined by some software. It is best to find where it could be set in /etc: e.g. Gentoo has that in /etc/env.d/99locale, where files from /etc/env.d are merged into a single file /etc/profile.env by env-update which is then sourced by /etc/profile and /etc/zsh/zprofile which are startup files used by shells. Next options are configuring your terminal emulator to set up those variables and setting them in a bashrc as a last resort.

**Comment by Mukundan314** [comment]
thanks @ZyX-I doing `sudo update-locale LANG=en_US.UTF-8` worked
