### ISSUE TITLE
Errors when switched to root

### ISSUE THREAD

**Issue by ar0ra1** [powerline/powerline#1843]
_powerline_set_prompt: command not found
__vte_prompt_command: command not found

I get these errors when switch to su

**Comment by ZyX-I** [comment]
You haev installed powerline for your user only, it is not going to work without /home/akash/.local/bin in your $PATH and it looks like you do not have your bashrc put it there.

Also __vte_prompt_command has nothing to do with powerline.

**Comment by ar0ra1** [comment]
Never Mind issue #652 helped me

This is shown in my weather widget-
STORM 24°C
The documentation states -
icons (dict) – dict for overriding default icons, e.g. {'heavy_snow' : u'❆'}

Are these unicode characters provided by default ?
If yes, how to enable them
