### ISSUE TITLE
bash + tmux will hold a ridiculous number of open file handles

### ISSUE THREAD

**Issue by samueldaniel** [powerline/powerline#1848]
I set up powerline for bash and tmux. I started using it at work but immediately noticed that everything would slow to a crawl when opening a new tmux pane. If I continued to work and opened maybe one or two other panes, tmux would eventually hang and complain about too many open files.

I looked at lsof for my user in a few scenarios:
1) no powerline shell and no powerline tmux
```
plain shell:
$ lsof | grep sdaniel | wc -l
67
plain shell + plain tmux (1 pane):
$ lsof | grep sdaniel | wc -l
143
plain shell + plain tmux (2 pane):
$ lsof | grep sdaniel | wc -l
165
plain shell + plain tmux (4 pane):
$ lsof | grep sdaniel | wc -l
209
plain shell + plain tmux (8 pane):
$ lsof | grep sdaniel | wc -l
297
```
2) powerline shell and no powerline tmux
```
shell:
  lsof | grep sdaniel | wc -l
100
shell + plain tmux (1 pane):
 lsof | grep sdaniel | wc -l
176
shell + plain tmux (2 pane):
 lsof | grep sdaniel | wc -l
198
shell + plain tmux (4 pane):
 lsof | grep sdaniel | wc -l
242
shell + plain tmux (8 pane):
  lsof | grep sdaniel | wc -l
330
```
3) powerline shell and powerline tmux
```
shell + tmux (1 pane):
 lsof | grep sdaniel | wc -l
220
shell + tmux (2 pane):
 lsof | grep sdaniel | wc -l
302
shell + tmux (4 pane):
 lsof | grep sdaniel | wc -l
436
shell + tmux (8 pane):
 lsof | grep sdaniel | wc -l
704
shell + tmux (8 pane, 1st window) (1 pane, 2nd window):
 lsof | grep sdaniel | wc -l
876
shell + tmux (8 pane, 1st window) (8 pane, 2nd window):
 lsof | grep sdaniel | wc -l
1312
```
During the course of my day to day development, I will routinely have 3 to 8 tmux windows open, each with anywhere from 2 to 6 panes open (vims, shells, tailing logs, etc.). Powerline's behavior in this situation seems...not ideal to me...

To the point: my issue is that using powerline shell and powerline tmux is preventing me from getting any work done because tmux crashes complaining about too many open files!

**Comment by ZyX-I** [comment]
Correct me if I am wrong, but

1. these handles all point to pipes
2. you are using mercurial and frequently enter mercurial repositories
3. the issue does not exist on develop

? This looks like #1757.

**Comment by samueldaniel** [comment]
1) most handles point to directories - my home directory specifically
2) i frequently enter *large* git repos - and i use the git shell segment
3) i am using develop

**Comment by ZyX-I** [comment]
Do not know why it would want to point to home directory, but the only other thought is that these handles are somehow needed for watchers. Are you using powerline-daemon and are you on linux?

**Comment by samueldaniel** [comment]
Yes, I am using the daemon and running on linux (ubuntu 12.04)

**Comment by ZyX-I** [comment]
It is strange because the only thing my powerline-daemon needs (i.e. what is in its /proc/{pid}/fd) are two inotify watchers, one or two sockets, /dev/urandom and a pipe. Client should only open that socket and nothing else.

**Comment by ZyX-I** [comment]
Can you check a diff between those cases?
