### ISSUE TITLE
vim powerline python errors mac os sierra

### ISSUE THREAD

**Issue by laur1s** [powerline/powerline#1856]
I  tried to install powerline to my vim by adding

`python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup`

to my ~/.vimrc. However I get errors. `
line   13:
E319: Sorry, the command is not available in this version: python3 from powerline.vim import setup as powerline_setup
line   14:
E319: Sorry, the command is not available in this version: python3 powerline_setup()
line   15:
E319: Sorry, the command is not available in this version: python3 del powerline_setup
Press ENTER or type command to continue
`

I am expecting that vim might invoke apple's python and not python3 which I have installed using anaconda. How can I fix that?

**Comment by ZyX-I** [comment]
You need to use `:python` if you need to invoke `:python`. With this setup variant (as opposing to using `powerline/bindings/vim/plugin/powerline.vim`) you are responsible for invoking of the correct command and if you invoked wrong command it is issue in *your* code, *no powerline code was run yet*.
