### ISSUE TITLE
No vim binding when installed via apt in Ubuntu 17.10

### ISSUE THREAD

**Issue by zh2018** [powerline/powerline#1857]
Running Ubuntu 17.10 and installed powerline from the Ubuntu repos:
`sudo apt install powerline`
Edited my .bashrc and .tmux.conf and powerline is working as expected. However, when I edited my vimrc to add powerline it wouldn't work. After some searching I see there is nothing for vim in /usr/share/powerline/bindings

Is this a bug or am I missing something?

**Comment by ZyX-I** [comment]
You need to list package contents and search for `powerline.vim` there. But ubuntu packages are not maintained here, so if it indeed does not contain `powerline.vim` and not just placed it elsewhere then you need to file a bug to the maintainer. In any case alternative method which calls `:python` directly should be working fine.

**Comment by Beren-G** [comment]
For those here from Google, add the following to `~/.vimrc`

```
set rtp+=/usr/share/vim/addons/
set laststatus=2
set t_Co=256
```
