### ISSUE TITLE
Bash Powerline not showing git branch info, but vi is working correctly.

### ISSUE THREAD

**Issue by felixgao** [powerline/powerline#186]
![Screen Shot 2013-02-06 at 5 35 17 PM](https://f.cloud.github.com/assets/1153820/134213/ab25f820-70c6-11e2-95cf-d6284069d9c4.png)
but if I do vi set.py I do see git branch info
![Screen Shot 2013-02-06 at 5 36 12 PM](https://f.cloud.github.com/assets/1153820/134217/cc68cfee-70c6-11e2-926f-2f78a0107ea8.png)

in my vimrc i have the following
. /Users/felix/Personalization/powerline/powerline/bindings/bash/powerline.sh

running iterm2 1.0.0.20130204-nightly on OSX 10.8.2

also if someone can tell me how to add server info to my prompt that would be great.

**Comment by DanielGGordon** [comment]
@danieltdt that documentation is confusing. I can't figure out which file to change (and what to change)

**Comment by Ihsahn** [comment]
Either modify main config.json or make a local copy (into ~/.config/powerline) and change shell->theme from "*default*" to "*default_leftonly*"

**Comment by DanielGGordon** [comment]
thanx!

**Comment by den-is** [comment]
I have followed all the steps but still have this problem on Fedora 23:
powerline-status (2.3) installed with pip2 (python 2.7.10)
have both pygit2 (0.22.1) for python2 and python3
created user config in ~/.config/powerline/config.json which works coz i can see that it applies colorscheme. but git still doesn't work
```shell
{
  "common": {
    "term_truecolor": false
  },
  "ext": {
    "ipython": {
      "colorscheme": "default",
      "theme": "in",
      "local_themes": {
        "rewrite": "rewrite",
        "out": "out",
        "in2": "in2"
      }
    },
    "shell": {
      "colorscheme": "solarized",
      "theme": "default_leftonly",
      "local_themes": {
        "continuation": "continuation",
        "select": "select"
      }
    },
    "tmux": {
      "colorscheme": "default",
      "theme": "default"
    }
  }
}
```

Edited main config .json in powerline install root/config_files - still nothing.

**Comment by xenithorb** [comment]
For the people from google: 

```bash
mkdir -p ~/.config/powerline
cat <<-'EOF' > ~/.config/powerline/config.json
{
    "ext": {
        "shell": {
            "theme": "default_leftonly"
        }
    }
}
EOF
powerline-daemon --replace 
```
This works because configs are merged

**Comment by marcioAlmada** [comment]
I agree that the documentation for customization managed to be verbose and confusing at the same time. I still have no idea where is `powerline_root` on my setup.

@xenithorb worked for me btw ^^

**Comment by meffect** [comment]
Are you saying there a master config.json of sorts? And `~/.config/powerline/config.json` overrides matching keys?

The docs I was reading dont seem to efficaciously educate the json schema

**Comment by meffect** [comment]
I found some language on a website after googling for more info. I think this is how it's supposed to be done to get the user started with the base/defaults. Then can edit as needed

I happen to install with pip --user , so my bits are in ~/.local/
```
$>mkdir -p ~/.config/powerline && cp -R ~/.local/lib/python3.5/site-packages/powerline/config_files/* ~/.config/powerline/ && cd ~/.config/powerline && ls -alF --color=auto
```

**Comment by crewshin** [comment]
This was the command that I needed.

`powerline-daemon --replace`

Thanks @xenithorb

**Comment by briner** [comment]
Hi,

Is there a way to get extra information on git. I'd love to know if:

- my repo needs some commit.
- my git needs to be pushed on the origin.

I've seen this https://github.com/jaspernbrouwer/powerline-gitstatus#installation and I was wondering if such things already exist or not in powerline ?

**Comment by ZyX-I** [comment]
No, you would need to use third-party modules like the one you mentioned.

**Comment by Yossarian0916** [comment]
Besides `powerline`, you should also`pip install powerline-gitstatus` , if you'd like to show git prompt in terminal. I also found a useful [post](https://medium.freecodecamp.org/jazz-up-your-bash-terminal-a-step-by-step-guide-with-pictures-80267554cb22) on Medium for your problem. Although this tutorial is based on macOS, but I've tested his method on my Ubuntu18.04 and it worked! Hope this will help you.

**Comment by ojtibi** [comment]
Apologies, what's the reason behind using the `default_leftonly` theme? Why isn't it the "real" default theme in the first place?

**Comment by gugol2** [comment]
I had trouble installing `powerline-gitstatus` with `apt install` in Ubuntu 18.04, maybe the repo is not maintained anymore. I didn't try to install it with `pip` though.

**Comment by gugol2** [comment]
Another thing... in my .bashrc file I only added:

```
if [ -f /usr/share/powerline/bindings/bash/powerline.sh ]; then
source /usr/share/powerline/bindings/bash/powerline.sh
fi
```
Nothing about the daemon and this stuff:
```
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
```
My questions are:
-Do I have to add those lines to my .bashrc file?
-Should I `apt remove powerline` and install it with `pip`?

**Comment by digitalformula** [comment]
> Another thing... in my .bashrc file I only added:
> 
> ```
> if [ -f /usr/share/powerline/bindings/bash/powerline.sh ]; then
> source /usr/share/powerline/bindings/bash/powerline.sh
> fi
> ```
> 
> Nothing about the daemon and this stuff:
> 
> ```
> powerline-daemon -q
> POWERLINE_BASH_CONTINUATION=1
> POWERLINE_BASH_SELECT=1
> ```
> 
> My questions are:
> -Do I have to add those lines to my .bashrc file as well?
> -Should I `apt remove powerline` and install it with `pip`?

I installed Powerline-status using pip3:

    pip3 install powerline-status
    pip3 install powerline-gitstatus

Created these directories:

    ~/.config/powerline
    ~/.config/powerline/themes/shell
    ~/.config/powerline/colorschemes

And created these files based on various comments above:

    ~/.config/powerline/colorschemes/default.json
    ~/.config/powerline/themes/shell/default.json
    ~/.config/powerline/config.json

Now my Konsole looks like this:

![powerline](https://user-images.githubusercontent.com/423229/80700462-20481d00-8b21-11ea-9a7c-b7846d17802b.png)
