### ISSUE TITLE
Missing space when using bash in tmux with battery

### ISSUE THREAD

**Issue by bewing** [powerline/powerline#1861]
Noticed that when I am using tmux, with bash as my shell, and the battery segment in my bash powerline, if I have power connected, there is a missing space at the end of the powerline.

If I'm not using tmux (bash only), no problem with power connected or disconnected, but inside tmux, if power is connected, commands entered are overlapping the final arrow.

Configs:
config.json:
```json
{
    "common": {
        "log_file": "/tmp/powerline.log"
    },
    "ext": {
        "shell": {
            "theme": "multi_leftonly",
            "colorscheme": "solarized"
        },
        "tmux": {
            "colorscheme": "solarized"
        }
    }
}
```
themes/shell/multi_leftonly.json
```json
{
        "segments": {
        "above": [
            {
                "left": [
                    {
                        "function": "powerline.segments.common.net.hostname",
                        "priority": 10
                    },
                    {
                        "function": "powerline.segments.common.bat.battery",
                        "priority": 10
                    },
                    {
                        "function": "powerline.segments.common.env.user",
                        "priority": 30
                    },
                    {
                        "function": "powerline.segments.shell.cwd",
                        "priority": 10
                    },
                    {
                        "function": "powerline.segments.shell.jobnum",
                        "priority": 20
                    },
                    {
                        "function": "powerline.segments.shell.last_status",
                        "priority": 10
                    }
                ]
            }
        ],
                "left": [
                        {
                                "function": "powerline.segments.common.env.virtu                                                                                                         alenv",
                                "priority": 50
                        },
            {
                "function": "powerline_gitstatus.gitstatus",
                "priority": 40
            }
                ]
        }
}
```
colorschemes/solarized.json:
```
{
  "groups": {
    "gitstatus":                 { "fg": "solarized:base1",           "bg": "solarized:base02", "attrs": [] },
    "gitstatus_branch":          { "fg": "solarized:base1",           "bg": "solarized:base02", "attrs": [] },
    "gitstatus_branch_clean":    { "fg": "solarized:base1", "bg": "solarized:base02", "attrs": [] },
    "gitstatus_branch_dirty":    { "fg": "solarized:yellow", "bg": "solarized:base02", "attrs": [] },
    "gitstatus_branch_detached": { "fg": "solarized:magenta",    "bg": "solarized:base02", "attrs": [] },
    "gitstatus_tag":             { "fg": "solarized:cyan",        "bg": "solarized:base02", "attrs": [] },
    "gitstatus_behind":          { "fg": "solarized:base2",          "bg": "solarized:base02", "attrs": [] },
    "gitstatus_ahead":           { "fg": "solarized:base2",          "bg": "solarized:base02", "attrs": [] },
    "gitstatus_staged":          { "fg": "solarized:green",           "bg": "solarized:base02", "attrs": [] },
    "gitstatus_unmerged":        { "fg": "solarized:red",       "bg": "solarized:base02", "attrs": [] },
    "gitstatus_changed":         { "fg": "solarized:orange",    "bg": "solarized:base02", "attrs": [] },
    "gitstatus_untracked":       { "fg": "solarized:yellow", "bg": "solarized:base02", "attrs": [] },
    "gitstatus_stashed":         { "fg": "solarized:blue",        "bg": "solarized:base02", "attrs": [] },
    "gitstatus:divider":         { "fg": "solarized:base1",           "bg": "solarized:base02", "attrs": [] },
    "battery":                   { "fg": "solarized:base1",           "bg": "solarized:base02", "attrs": [] }
  }
}
```

This is using the latest source 6be991c571e6abc333d5ed1e5884e60e16ec2eed

![bash-power-conn](https://user-images.githubusercontent.com/4759896/33224828-4297f11e-d133-11e7-8afb-2e030d2ad4eb.PNG)
![bash-power-disconn](https://user-images.githubusercontent.com/4759896/33224830-44d3b3dc-d133-11e7-9bac-060168aea155.PNG)
![tmux-power-conn](https://user-images.githubusercontent.com/4759896/33224832-47e1f318-d133-11e7-8bf0-41c942012d75.PNG)
![tmux-power-disconn](https://user-images.githubusercontent.com/4759896/33224833-4b3ecc2a-d133-11e7-9c8e-cf9bc57537e5.PNG)

I do not notice this on my Macbook with the same config using the last pypi release

**Comment by ZyX-I** [comment]
This looks like the usual problem with miscalculated character widths: notice the space before `99`? Such things happen when different parts of the system responsible for drawing characters have different idea regarding how wide the character is (typically some think about one display cell, some about two; all possible values are zero, one and two). The chain here is pretty long:

- powerline - uses width calculations to skip some segments if there is not enough space. Should not cause problems under most circumstances even if it miscalculates, except for the cases “vim statusline” and “above line which is supposed to be exactly one screen wide” (you do not have a filler, so this is not the case).
- Shell - needs to know where to position cursor. If it causes problems you should see that definitely in cases when you do autocompletion or move cursor in a long jumps (e.g. to start and end). In other cases too, but these should be definite.
- Tmux - needs to know where to wrap and where to draw pane separator. Any problems would not normally be noticed if there are no wraps and no panes.
- Terminal emulator - needs to place characters and things like cursor in a grid. Miscalculation may result in a wide number of problems, which also depend on how exactly these characters are then drawn.
- Font rendering library - need to actually draw the greed on screen. It is hard to tell whether it or terminal emulator is the root of the problem: such libraries may be used in a different fashion, also some terminal emulators have their own font rendering libraries and there are not many people understanding what is going on in complicated scenarios.

Note that here powerline is the lowest layer, and least significant. Unless you can confirm with `hexdump` that space is actually not there there is nothing I can do: I do not know any sane way to automatically detect issues on the two highest layers.

**Comment by ZyX-I** [comment]
You may want to make battery use different character which does not cause any issues with your setup, by configuring online/offline arguments of the segment.
