### ISSUE TITLE
Powerline ignores the term_truecolor setting for tmux statusline

### ISSUE THREAD

**Issue by kmoschcau** [powerline/powerline#1863]
Hi,
I have an odd little case where powerline seems to ignore the "term_truecolor" global setting just for the tmux statusline. This happens even though my terminal and tmux are perfectly capable of using truecolor.
I have configured powerline to use the gruvbox theme (https://github.com/morhetz/gruvbox) for everything I use. It works everywhere except the powerline tmux statusline. It's probably best to show some screenshots.

This shows two neovim instances inside tmux. The colors for neovim are correct, the ones for the statusline are not. The outermost elements in the statusline should have the same color as the mode element in neovim.
![selection_001](https://user-images.githubusercontent.com/9497302/33515235-95b0d108-d760-11e7-85ac-151ecb9c5b32.png)
(Disclaimer: I did not get powerline to work with neovim. Neovim just uses the plain gruvbox theme and vim-airline. It uses the same colors though. I just included this as a proof, that truecolor works inside tmux.)

This shows the same tmux instance with a terminal. As you can see again, the terminal PS1 uses the right colors.
![selection_002](https://user-images.githubusercontent.com/9497302/33515263-21ef013a-d761-11e7-9d4c-2e3ffd279a2c.png)

Here now is the main reason why I think the problem is with powerline: Before I source the powerline binding for tmux, I set up a sort of fallback in my .tmux.conf with the right colors. And look, they actually work!
![selection_003](https://user-images.githubusercontent.com/9497302/33515295-7493f224-d761-11e7-9c9e-52c369c395c4.png)

And now what makes me think that powerline ignores the "term_truecolor" setting for tmux: This is how my PS1 looks, when I set "term_truecolor" to false.
![selection_004](https://user-images.githubusercontent.com/9497302/33515323-c65c61fe-d761-11e7-91cb-ee5e00001915.png)
That looks pretty much the same to me.

The gruvbox theme provides colors for truecolor and 256 colors. I set both of them in my colors configuration for powerline. Here is my colors.json:
```json
{
  "colors": {
    "gruvbox_dark:0_bg":            [235, "282828"],
    "gruvbox_dark:8_gray":          [245, "928374"],

    "gruvbox_dark:1_dark_red":      [124, "cc241d"],
    "gruvbox_dark:9_light_red":     [167, "fb4934"],

    "gruvbox_dark:2_dark_green":    [106, "98971a"],
    "gruvbox_dark:10_light_green":  [142, "b8bb26"],

    "gruvbox_dark:3_dark_yellow":   [172, "d79921"],
    "gruvbox_dark:11_light_yellow": [214, "fabd2f"],

    "gruvbox_dark:4_dark_blue":     [66,  "458588"],
    "gruvbox_dark:12_light_blue":   [109, "83a598"],

    "gruvbox_dark:5_dark_purple":   [132, "b16286"],
    "gruvbox_dark:13_light_purple": [175, "d3869b"],

    "gruvbox_dark:6_dark_aqua":     [72,  "689d6a"],
    "gruvbox_dark:14_light_aqua":   [108, "8ec07c"],

    "gruvbox_dark:7_gray":          [246, "a89984"],
    "gruvbox_dark:15_fg":           [223, "ebdbb2"],

    "gruvbox_dark:bg0_h":           [234, "1d2021"],

    "gruvbox_dark:bg0":             [235, "282828"],
    "gruvbox_dark:bg0_s":           [236, "32302f"],

    "gruvbox_dark:bg1":             [237, "3c3836"],
    "gruvbox_dark:fg4":             [246, "a89984"],

    "gruvbox_dark:bg2":             [239, "504945"],
    "gruvbox_dark:fg3":             [248, "bdae93"],

    "gruvbox_dark:bg3":             [241, "665c54"],
    "gruvbox_dark:fg2":             [250, "d5c4a1"],

    "gruvbox_dark:bg4":             [243, "7c6f64"],
    "gruvbox_dark:fg1":             [223, "ebdbb2"],

    "gruvbox_dark:gray":            [245, "928374"],
    "gruvbox_dark:fg0":             [229, "fbf1c7"],

    "gruvbox_dark:dark_orange":     [166, "d65d0e"],
    "gruvbox_dark:light_orange":    [208, "fe8019"]
  },
  "gradients": {}
}

```

And for reference, here are my tmux color constants, that are used prior to sourcing the powerline tmux binding:
```tmux
# color constants {{{2

GRUVBOX_DARK_0_BG="#282828"
GRUVBOX_DARK_8_GRAY="#928374"

GRUVBOX_DARK_1_DARK_RED="#cc241d"
GRUVBOX_DARK_9_LIGHT_RED="#fb4934"

GRUVBOX_DARK_2_DARK_GREEN="#98971a"
GRUVBOX_DARK_10_LIGHT_GREEN="#b8bb26"

GRUVBOX_DARK_3_DARK_YELLOW="#d79921"
GRUVBOX_DARK_11_LIGHT_YELLOW="#fabd2f"

GRUVBOX_DARK_4_DARK_BLUE="#458588"
GRUVBOX_DARK_12_LIGHT_BLUE="#83a598"

GRUVBOX_DARK_5_DARK_PURPLE="#b16286"
GRUVBOX_DARK_13_LIGHT_PURPLE="#d3869b"

GRUVBOX_DARK_6_DARK_AQUA="#689d6a"
GRUVBOX_DARK_14_LIGHT_AQUA="#8ec07c"

GRUVBOX_DARK_7_GRAY="#a89984"
GRUVBOX_DARK_15_FG="#ebdbb2"

GRUVBOX_DARK_BG0_H="#1d2021"

GRUVBOX_DARK_BG0="#282828"
GRUVBOX_DARK_BG0_S="#32302f"

GRUVBOX_DARK_BG1="#3c3836"
GRUVBOX_DARK_FG4="#a89984"

GRUVBOX_DARK_BG2="#504945"
GRUVBOX_DARK_FG3="#bdae93"

GRUVBOX_DARK_BG3="#665c54"
GRUVBOX_DARK_FG2="#d5c4a1"

GRUVBOX_DARK_BG4="#7c6f64"
GRUVBOX_DARK_FG1="#ebdbb2"

GRUVBOX_DARK_GRAY="#928374"
GRUVBOX_DARK_FG0="#fbf1c7"

GRUVBOX_DARK_DARK_ORANGE="#d65d0e"
GRUVBOX_DARK_LIGHT_ORANGE="#fe8019"

# 2}}}

```

I hope this helps you guys find the bug or somebody to point out some error in my powerline config, that I overlooked so far.

**Comment by ZyX-I** [comment]
I was not aware that tmux adding support for true color also includes support to them in the status line. So powerline currently does not support them.
