### ISSUE TITLE
Q: Remove $HOSTNAME

### ISSUE THREAD

**Issue by Mamad026** [powerline/powerline#1865]
Hi there.
[I asked a question in superuser about powerline](https://superuser.com/questions/1274468/how-to-remove-hostname-in-powerline)  but I really don't know why it taken negative point & why no one answered that. In the other hand I know asking question in issue tracker is illegal but I 'm newbie & have no one to guide & answering me, so if you don't mind please let me know How can I remove $HOSTNAME (I just want full path of my current directory).
Thanks.

**Comment by ZyX-I** [comment]
There is mailing list for question, not issue tracker. Default configuration is in powerline/config_files, pieces necessary to be modified may be copied over into ~/.config/powerline and modified there.
