### ISSUE TITLE
ZSH command not found: powerline

### ISSUE THREAD

**Issue by mindfulmonk** [powerline/powerline#187]
source /home/yaro/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh
zsh: command not found: powerline  
zsh: command not found: powerline
editor-info:23: command not found: powerline
editor-info:23: command not found: powerline

It works fine in vim, but not in zsh.

I used:
pip install --user git+git://github.com/Lokaltog/powerline
to install it.

**Comment by shashwattiwari** [comment]
```
zsh: command not found: powerline-daemon
```

```
export PATH=$PATH:$HOME/Library/Python/2.7/bin
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /Users/shashwattiwari/Library/Python/2.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh
```
