### ISSUE TITLE
Doesn't show git branchs with /

### ISSUE THREAD

**Issue by DavidUser** [powerline/powerline#1871]
[![asciicast](https://user-images.githubusercontent.com/6628028/34903011-fc84640c-f80e-11e7-9736-ad3857cc8293.png)](https://asciinema.org/a/O5DhRXzOjNFxlWZIyS92K2S2r)
Works with **data-contract** but not with **feature/data-contract**.

**Comment by ZyX-I** [comment]
`feature/data-contract` is too long to be shown in your case. Powerline is supposed to leave some space for the typed command (default zero if you did not edit configuration) by removing segments with less priority, priority and how much space to spare is defined in theme configuration. As you see here there is no space on the line to show `feature/data-contract` even with zero space left for the shell command.
