### ISSUE TITLE
Ubuntu 17.10 with latest github clone gives 'finish_args() takes at least 3 arguments (2 given)'

### ISSUE THREAD

**Issue by snwiem** [powerline/powerline#1872]
I know this issue has been discussed already  and all other issues have been closed, but actually I still have the same issue mentioned in the subject using a fresh install of ubuntu 17.10.

I followed the instructions on this page
[](https://powerline.readthedocs.io/en/latest/installation.html#pip-installation)
and when I try to source 
`powerline/powerline/bindings/bash/powerline.sh`
I get
`finish_args() takes at least 3 arguments (2 given)`

**Comment by ZyX-I** [comment]
If you seen other issues then you should know that bug could only be there in case of multiple incompatible installations, you need to find the offending one and your report is absolutely not helpful on the matter. Most universal way is probably `strace`'ing `powerline-render shell left` (if it shows the error): the executable itself should belong to one place (e.g. when installed with pip it should be in ~/.local/bin), while Python modules should belong to another (e.g. when installed with system package manager they should be in /usr/lib/python…).

**Comment by snwiem** [comment]
Thanks for your reply. I'm sorry, but I see that the copied link to the documentation page is missing. Therefore the post makes no sense  for sure. The link missing is: https://powerline.readthedocs.io/en/latest/installation.html#pip-installation

As I compeletly reinstalled everything from scratch on my virtual machine now everything works as documented.

Sorry for cluttering

**Comment by ZyX-I** [comment]
@snwiem The link there is not completely missing: if you click “Edit comment” icon it is still there and repository owners can use this button just like the author of comment. The point is that while I knew you used pip to install powerline I could not search your machine for other installations, and in absense of other installations pip installation is known to work just fine.
