### ISSUE TITLE
I can’t get `exit_fail` to display

### ISSUE THREAD

**Issue by jonnybarnes** [powerline/powerline#1877]
In my theme’s json I have:
```json
"right": [
            {
                "function": "powerline.segments.shell.last_pipe_status",
                "priority": 10
            },
```
Then in my colorscheme’s json I have:
```json
        "exit_fail": {
            "fg": "gray8",
            "bg": "red",
            "attrs": []
        },
```
However everytime I run a command that returns some kind of error my powerline log gets the following added to it:
```
2018-01-25 18:48:40,360:ERROR:shell:last_pipe_status:Failed to set highlight group: 'Highlighting groups not found in colorscheme: exit_fail'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/powerline/segment.py", line 151, in set_segment_highlighting
    segment.get('gradient_level')
  File "/usr/local/lib/python3.6/site-packages/powerline/colorscheme.py", line 105, in get_highlighting
    raise KeyError('Highlighting groups not found in colorscheme: ' + ', '.join(groups))
KeyError: 'Highlighting groups not found in colorscheme: exit_fail'
```
Does anyone know whats wrong?

**Comment by ZyX-I** [comment]
I can’t help any further without context: maybe you have your `exit_fail` in the wrong position in the file or wrong file, maybe you are actually not using that colorscheme, maybe you need to restart daemon to reload configuration. In any case the first thing you should do when you have problems with config is running `powerline-lint`.

**Comment by jonnybarnes** [comment]
Yeah, `powerline-lint` is throwing up errors.

Going through it now. I got `exit_fail` to work, the output showed that it was looking for `information:critical`, so defining that then worked.

**Comment by ZyX-I** [comment]
This should mean “wrong file” then: `information:critical` is a definition of `exit_fail` in shell/__main__ colorscheme, it overrides whatever non-extension-specific colorscheme you have, but is in turn overridden by extension-specific: e.g. if you have placed exit_fail definition in colorscheme ~/.config/powerline/colorschemes/foo.json you would neet to use ~/.config/powerline/colorschemes/shell/foo.json instead.

**Comment by jonnybarnes** [comment]
Hmm, moving `foo.json` into a `shell/` subdir has made the output of `poewrline-lint` a lot shorter as I now see noe reference to vim related errors.

Its still complaining about `exit_fail` and `critical:failure` (got the wrong string before, but the `exit_fail` is displaying as I’d expect it to.

Here’s the start of the output of `powerline-lint`:

```
One of the either variants failed. Messages from the first variant:

    Error while loading groups (key /groups/exit_fail)
    'critical:failure' must be a dict instance, not str
      in "/usr/lib/python3.6/site-packages/powerline/config_files/colorschemes/shell/__main__.json", line 5, column 27:
        >--->---"exit_fail":            "critical:failure",
                                        ^

messages from the next variant:

    Error while checking group definition in colorscheme (key /groups/exit_fail)
    name critical:failure is not present anywhere in 2 shell jonny colorschemes: /home/jonny/.config/powerline/colorschemes/shell/jonny.json, /usr/lib/python3.6/site-packages/powerline/config_files/colorschemes/shell/__main__.json
      in "/usr/lib/python3.6/site-packages/powerline/config_files/colorschemes/shell/__main__.json", line 5, column 27:
        >--->---"exit_fail":            "critical:failure",
```

Given `exit_fail` displays as expected is this now an issue in `powerline-lint`?

**Comment by ZyX-I** [comment]
`powerline-lint` really expects you to define colorscheme for all extensions at once, so there may be some issues if you do otherwise.
