### ISSUE TITLE
Cursor jumps to beginning of line after typing a few chars on bash 

### ISSUE THREAD

**Issue by AlexZeitler** [powerline/powerline#1878]
My cursor jumps to the beginning of the current line after typing a few chars on bash on Ubuntu 17.10.

![image](https://user-images.githubusercontent.com/287480/35766659-79f85e92-08dc-11e8-8234-1082a19bb9cf.png)
I tried to type `ls -la` and after the space the cursor jumps to the beginning of the line (to the left of `alexzeitler`).

**Comment by ZyX-I** [comment]
Why do you think powerline has something to do with this behaviour?

**Comment by AlexZeitler** [comment]
I fixed it by using https://github.com/vincepii/ubuntu-powerline-bash to install powerline on Ubuntu 18.04.
