### ISSUE TITLE
Problem with attribute : italic in tmux

### ISSUE THREAD

**Issue by ar0ra1** [powerline/powerline#1879]
Without tmux :   
![screenshot from 2018-02-11 19-03-30](https://user-images.githubusercontent.com/20777462/36073921-4dc098ac-0f5e-11e8-966c-8193c98687a6.png)

Inside Tmux :  
![screenshot from 2018-02-11 19-03-35](https://user-images.githubusercontent.com/20777462/36073920-4d8c6a14-0f5e-11e8-88e5-786212de869a.png)

Colorscheme :  
`"information:regular":        { "fg": "black", "bg": "white", "attrs": ["italic"] },`

**Comment by ZyX-I** [comment]
Your tmux is translating italic text into inverse text. This is not a powerline bug, based on what I can find on the internet you can only hope to use some hacks like described here: https://medium.com/@dubistkomisch/how-to-actually-get-italics-and-true-colour-to-work-in-iterm-tmux-vim-9ebe55ebc2be.
