### ISSUE TITLE
strange symbols on powerline

### ISSUE THREAD

**Issue by fpusersuggest** [powerline/powerline#1888]
Hi, I have ubuntu 16.04 and I have installed powerline as usual on ubuntu:
`apt install powerline fonts-powerline`
But I have found strange symbols on powerline instead of special character on uxterm.
I works very well on other terminal like terminator or gnome-terminal. But I have to use uxterm becaus it's more light.
I have tried to install the patched fonts from github on my local home (~/.fonts) without any changes.

**Comment by ZyX-I** [comment]
You need to configure urxvt to use installed fonts, it is neither going to use fallback like other terminals nor could use font you did not configure it to use. And there is mailing list for user questions, bug tracker is for bugs.
