### ISSUE TITLE
Date segment ignoring locale

### ISSUE THREAD

**Issue by dffischer** [powerline/powerline#1891]
I strive to have powerline display the current date in my tmux status line. To do so, I included the following segment in my tmux theme configuration at `.config/powerline/themes/tmux/custom.json`

    { 
      "function": "powerline.segments.common.time.date", 
      "name": "date", 
      "args": { 
        "format": "%x" 
      } 
    }

The `%x` format specifier to python's `time.strftime` function should render the date according to the locale, which would today be `11.03.2018` in my locale `de_DE.UTF-8`. But instead, `03/11/18` appears, which looks like it was rendered in the generic `C` locale.

Testing the entry in the zsh theme yields the same result.

The installation is an Arch Linux booting systemd. Its `/etc/locale.conf` reads just

    LANG=de_DE.utf8

Running `locale` outputs

    LANG=de_DE.utf8
    LC_CTYPE="de_DE.utf8"
    LC_NUMERIC="de_DE.utf8"
    LC_TIME="de_DE.utf8"
    LC_COLLATE="de_DE.utf8"
    LC_MONETARY="de_DE.utf8"
    LC_MESSAGES="de_DE.utf8"
    LC_PAPER="de_DE.utf8"
    LC_NAME="de_DE.utf8"
    LC_ADDRESS="de_DE.utf8"
    LC_TELEPHONE="de_DE.utf8"
    LC_MEASUREMENT="de_DE.utf8"
    LC_IDENTIFICATION="de_DE.utf8"
    LC_ALL=

While experimenting with the underlying Python functions I noted that `time.strftime` output the correct format when any variant of `locale.setlocale` was called beforehand.

Is this segment intended to respect the locale? Did I miss some locale or powerline configuration to make it work?

**Comment by ZyX-I** [comment]
Segment intended to just call `strftime()`. I do not know why Python does not set LC_TIME on startup from either $LANG or $LC_TIME (tried setting explicitly), but powerline is supposed to respect Python’s understanding of the locale and not implement locale determination itself.

**Comment by ZyX-I** [comment]
(Confirmed locally on 2.7.14 and 3.5.4 from Gentoo main portage tree.)
