### ISSUE TITLE
hostname:colorize should preserve contrast

### ISSUE THREAD

**Issue by catskul** [powerline/powerline#1892]
hostname colorize sometimes produces poor contrast combinations.

We should protect against that.

**Comment by ZyX-I** [comment]
What is “hostname:colorize”? There is exactly one colorscheme group associated with `hostname` segment and it is just `hostname`. And I am not aware of any existing problems with that.

Also generally I see no sense in restricting colorschemes. First, definition of “poor contrast” is both subjectable (some people see better, other people could not distinguish certain colors) and circumstantial (unless using true colors powerline is relying on terminal colorscheme which generally can’t be queried). Second, it will slow everything down for a very minor gain: basically for making poorly written colorschemes standable. Third, there are cases when poor contrast is *exactly* what is needed, e.g. for making separators less visible. Fourth, there need to be a definition of what to do if poor contrast is detected.

**Comment by catskul** [comment]
That response feels very adversarial. Did I say something to offend you?
