### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by petrux** [powerline/powerline#1898]
Hi there,  
  
I just installed powerline for the first time and it looks like the rendering in my bash shell is a bit broken. More in detail, the arrows seem to be a bit _short_ and the junction points is a bit discontinuous (yeah, don't know how to explain better, sorry), as in the screenshot:

![powerline-calzetti](https://user-images.githubusercontent.com/401919/37838008-183ba712-2eb7-11e8-9c52-306893cc9e18.png)

Any hint on how to fix it?
Thanks.

**Comment by s-ol** [comment]
@petrux this is a problem with the fonts you are using and how your terminal is configured. Should go to powerline/fonts, where there are many issues like this: https://github.com/powerline/fonts/issues/236

Depending on your terminal emulator you can use settings like `URxvt*.letterSpace: -2` to fix it as well.

**Comment by ZyX-I** [comment]
You have not told which font you are using, but in any case there is not much I can do. First, if you are using fallback then you should switch to a patched font. Fallback *sometimes* work, but I have no idea whether it *can* be made universal at all, let alone how to make it universal. Second, if it is patched font that has problem then maybe you should repatch it yourself manually. There is a [PR](https://github.com/powerline/fontpatcher/pull/12) which *maybe* makes automatic patching results better, but I have no idea what are the possible problems and whether it actually does work for cases not matching PR’s author (and there already is at least one comment which asks for more tweaks). This is basically why it never got merged.
