### ISSUE TITLE
Powerline setup on Ubuntu 17.10 yielding script arg error

### ISSUE THREAD

**Issue by preston3271** [powerline/powerline#1899]
I am attempting to get "Powerline" plug-ins working for Ubuntu 17.10 system where I was following guides from 

> https://www.tecmint.com/powerline-adds-powerful-statuslines-and-prompts-to-vim-and-bash/

 and it producing the following script error:  

 `finish_args() takes at least 3 arguments (2 given)`

my ~/.bashrc file is setup as follows:

` # Powerline configuration`
`export TERM="screen-256color"`
`powerline-daemon -q`
`POWERLINE_BASH_CONTINUATION=1`
`POWERLINE_BASH_SELECT=1`
`. '/home/xxxxxxxxxxx1/.local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh' `

I have confirmed which powerline:
`/usr/bin/powerline`
from the /etc/fonts/conf.d:
`lrwxrwxrwx 1 root root   39 Jan 24  2017 10-powerline-symbols.conf -> ../conf.avail/10-powerline-symbols.conf`

Please advise on next troubleshooting steps.

Thanks.

**Comment by ZyX-I** [comment]
You clearly have installed two incompatible powerline versions in two locations, either `/usr/…` or `~/.local/…` installation must not exist.

**Comment by ZyX-I** [comment]
The first one should be installed by a system package manager and is expected to be more outdated. It should be possible to use some command to find which package `/usr/bin/powerline` belongs to and then remove it.
