### ISSUE TITLE
Question about Custom Colors

### ISSUE THREAD

**Issue by 0paIescent** [powerline/powerline#1906]
I may be doing things completely wrong, but let's say I wanted to make a custom color for 00C4FF, how would I go about doing this? I tried using a cterm color index but the color always came out to that of the cterm color.

**Comment by ZyX-I** [comment]
What do you mean by “custom color for 00C4FF”? Powerline uses highlight groups which refer to colorscheme “colors” which are (unless being gradients) either cterm color indexes or 2-tuples (lists with two items in JSON) with cterm color index and RGB value. There are lots of examples of both in `powerline/config_files/colors.json`. Highlight group definitions never refer to some particular color directly though, all colors need to be defined in `colors.json`.

(And there is a mailing list for usage questions.)
