### ISSUE TITLE
Describe labels and colors on the statusline

### ISSUE THREAD

**Issue by ocdC0d3r** [powerline/powerline#1912]
Hi all, this is not an issue or a bug, it's just I couldn't find any info on this.. Please correct me if I'm wrong or provide some useful docs.
![screenshot from 2018-05-22 11-16-31](https://user-images.githubusercontent.com/3659263/40353442-d1d2c7c2-5db1-11e8-9e9d-9a5621e6855f.png)

What does the orange label mean?

**Comment by ZyX-I** [comment]
You need to check your shell theme and colorscheme. *By default* segment looking like indeed shows number of jobs running. But by default neither branch segment has the color you are seeing nor it has flag with a number so you definitely have custom theme and with a custom theme and colorscheme that may be just any segment happening to need to contain `1` for whatever reason, including e.g. segment which displays last exit status.

Also there is mailing list for user questions.
