### ISSUE TITLE
FTBFS with GCC-7

### ISSUE THREAD

**Issue by daniel-baumann** [powerline/powerline#1913]
Hi,

powerline.c fails to build from source with GCC-7.

Fortunatly, Fedora already has a patch for that:
https://src.fedoraproject.org/rpms/powerline/blob/master/f/powerline-2.6-gcc7_fixes.patch

It woud be nice if you could merge it.

Regards,
Daniel

**Comment by cryptomilk** [comment]
This can be closed as fixed, see

73244eb976bae2806c70bf776497738c0bd601c8
and
924bbbe92b072a23af2e205568dc03d83fc93a76

**Comment by daniel-baumann** [comment]
Indeed, thanks ;)

Regards,
Daniel
