### ISSUE TITLE
virtualenv segment not displaying

### ISSUE THREAD

**Issue by fdelacruz** [powerline/powerline#1918]
Hi, my issue is powerline doesn't show the virtualenv. I have virtualenv and virtualenvwrapper running normally. I can load a virtualenv in a shell, and start up vim with the vim-virtualenv plugin. I know the virtualenv has loaded properly. 
1. :echo g:virtualenv_loaded returns '1'
2. :echo $VIRTUAL_ENV returns the path to my currently loaded virtual env
3. :echo g:virtualenv_name returns the name of said virtual env

Where else can I start looking?

Thanks, Francisco

**Comment by fdelacruz** [comment]
I should add that I'm running python 3 (:echo has('python3') returns '1') on vim 8.1.1. I have also installed powerline using Vundle.

**Comment by fdelacruz** [comment]
In issue #892 it was suggested to copy and edit ${XDG_CONFIG_HOME:$HOME/.config}/powerline/themes/vim/default.json. I'm looking trying to figure out how to do that right now..

**Comment by ZyX-I** [comment]
You have not posted configuration. And just as in #892 virtualenv segment was not added by default since the time issue was created. For usage questions there is mailing list.

**Comment by fdelacruz** [comment]
I added ${XDG_CONFIG_HOME:$HOME/.config}/powerline/themes/vim/default.json, but there's not a CLUE as to how to add the virtualenv configuration. It does even seem possible since these are all function calls from powerline/segments/vim/__init__.py

**Comment by ZyX-I** [comment]
Just take virtualenv segment from where it does exist: e.g. default shell theme specifies all functions with explicit module path which would work in any theme regardless of what is the default module there. Also there is full configuration reference in documentation which tells you what may be the value corresponding to the `function` key.

**Comment by fdelacruz** [comment]
Yeah,  I just added:
 


```
  {
	"function": "powerline.segments.common.env.virtualenv",
         "draw_soft_divider": false,
         "after": " ",
         "before": "ⓔ "
  },
```

to the settings in ../themes/vim/default.json. I wonder if I can just add the settings I want to add instead of bringing the entire file. Going to test that out. 
Added also the following:

`"virtualenv":`             { "fg": "solarized:base1", "bg": "solarized:base02", "attrs": [] }

to ../colorschemes/solarized.json to make it look just the way I want it.

**Comment by ZyX-I** [comment]
You can just add settings only as long as the said setting is located inside a dictionary ... inside a dictionary: dictionaries are recursively merged, overrides override user settings which override defaults. List of segments is located inside a *list* (how is merging lists supposed to work in any case?) so you can’t do it there. It is fine for user colorscheme to only contain differences with default though. Merging does not allow removing some key (internally it actually does and overrides sometimes provide this functionality, but not json AFAIR), only overriding it with another value.

**Comment by bradwood** [comment]
Ok, I'm assuming that the path it will look in is: `~/.config/powerline/themes/vim`.

I've added this into `default.json` in that folder:
```
  {
	"function": "powerline.segments.common.env.virtualenv",
         "draw_soft_divider": false,
         "after": " ",
         "before": "ⓔ "
  }
```

Python3 is fully working in vim too...

However, this doesn't seem to work... Any suggestions?

thanks

Brad
