### ISSUE TITLE
Tabline entry "tabs" at beginning of tabline

### ISSUE THREAD

**Issue by DasOhmoff** [powerline/powerline#1919]
Hi, I would like to know how to get rid of the "tabs" thing at the beginning of my tabline:

![image](https://user-images.githubusercontent.com/16063186/41510709-9547fb0c-7269-11e8-8686-f5a59f0fd8ad.png)

No matter how or where I open any tabs, it is always there

My .vimrc airline part:
```
let g:airline_extensions = ['branch', 'tabline']
let g:airline_theme = 'badwolf'
let g:airline#extensions#tabline#buffer_nr_show = 0
let g:airline#extensions#tabline#show_tab_nr = 0
```

Thank you very much.

**Comment by ZyX-I** [comment]
Powerline does not have this by default. And it is wrong to configure powerline with variables named `g:airline…`. I assume you *did not* use powerline and should ask in some resource related to airline.

Also note that powerline has mailing list for usage question and issue tracker is for bugs and feature requests. I do not know whether airline has something similar, but check before posting there.
