### ISSUE TITLE
Vim issue "undefined symbol: _PyUnicode_Ready"

### ISSUE THREAD

**Issue by m-wells** [powerline/powerline#1921]
I'm on Arch Linux and used the [python-powerline-git](https://aur.archlinux.org/packages/python-powerline-git/) to install.  Powerline is working in bash and tmux just fine but when I fire up vim I get:
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/lib/python3.6/site-packages/powerline/__init__.py", line 10, in <module>
    from powerline.colorscheme import Colorscheme
  File "/usr/lib/python3.6/site-packages/powerline/colorscheme.py", line 6, in <module>
    from powerline.lib.unicode import unicode
  File "/usr/lib/python3.6/site-packages/powerline/lib/unicode.py", line 7, in <module>
    from unicodedata import east_asian_width, combining
ImportError: /usr/lib/python3.6/lib-dynload/unicodedata.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_Ready
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/usr/lib/python3.6/site-packages/powerline/__init__.py", line 10, in <module>
    from powerline.colorscheme import Colorscheme
  File "/usr/lib/python3.6/site-packages/powerline/colorscheme.py", line 6, in <module>
    from powerline.lib.unicode import unicode
  File "/usr/lib/python3.6/site-packages/powerline/lib/unicode.py", line 7, in <module>
    from unicodedata import east_asian_width, combining
ImportError: /usr/lib/python3.6/lib-dynload/unicodedata.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_Ready
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Unable to import powerline, is it installed?
Press ENTER or type command to continue

```

**Comment by ZyX-I** [comment]
You should be getting exactly the same error by using `vim -u NONE -i NONE -N -c 'python3 from unicodedata import east_asian_width, combining'` without any powerline involved: there is some error with your Python installation, powerline does not have any C extensions, does not mess with `/usr/lib/python3.6/lib-dynload` and at the time that import occures does not alter `sys.path` at all. If this command is fine, disable powerline, restart Vim confirming that you do not have an error and type `:python3 from unicodedata import east_asian_width, combining<CR>`: if `-u NONE -i NONE` works fine, but trying to use import from a working version without powerline enabled is not then you have some problem in your configuration.

One of the common causes for such errors is difference between the version Vim was compiled with and version you are actually using. It is also possible that you have right version, but `sys.path` for the wrong one. I am not sure what exactly would be the case here though: I think error could not have occurred if you have Vim compiled with Python-3.5 and used with Python-3.6 (if it would start importing something at all it probably would not try to import from `unicodedata.cpython-36m-x86_64-linux-gnu.so`), but could if you have two Python’s with the same version, but different compilation options and have wrong `sys.path`. Check whether you have PYTHONPATH variable is defined and what Vim is linked to.

**Comment by m-wells** [comment]
Thank you for helping with this!  It indeed was my system python and doing a quick reinstall of my base python fixed the issue.
