### ISSUE TITLE
cwd segment broken inside a docker container

### ISSUE THREAD

**Issue by ntoniazzi** [powerline/powerline#1923]
Hello,
I've been using powerline for some time already, without any problem. I'm trying to use it with bash inside a docker container (debian:stretch + apt install powerline) and have something strange with the cwd segment:
![image](https://user-images.githubusercontent.com/849271/42033704-0ae07246-7ade-11e8-958c-ed62e5333145.png)
The prompt seem to be send back to the left after writing each part of the path.
For `~` and `/` (lines 1 and 2), the prompt is correct.
For `/etc` and `/etc/init.d` (lines 3 and 4), it's broken.
When I enter `powerline shell left`, the prompt is printed correctly on line 6.

I'm using gnome-terminal.
Thanks.

**Comment by ZyX-I** [comment]
I think that you have something wrong with either $TERM/terminfo (does docker container *have* necessary terminfo entries?), have incorrect terminal size inside a container (check `stty size` output, it should be the same inside and outside container) or have bash understanding character width differently then terminal emulator does (check that locale is correct first: incorrect locale will get you incorrect character widths, it is unlikely that something else is wrong here). Most likely it is a problem with width of some kind: either second or third suggestions.

**Comment by ZyX-I** [comment]
Note that if you have incorrect terminal size then you can just have basic prompt consisting of a single hash sign and type long ASCII string and you will see the problem. To check for the third possible issue you would need to type (or, rather, copy) non-breaking spaces (powerline by default uses only non-breaking spaces due to some bug I do not remember currently) and two kinds of powerline arrows.

**Comment by ntoniazzi** [comment]
Terminal size (columns and lines) was right inside Docker, the locales seemed good too. Actually, for some reasons other than that, I had to make a clean new install of the host system (Ubuntu → Fedora), and everything it working well now. I had not the opportunity to investigate more.
Thanks for your time and answers.
