### ISSUE TITLE
How could I change statusline symbols?

### ISSUE THREAD

**Issue by roachsinai** [powerline/powerline#1926]
I mean how could I use symbols like `unicode '\ue0c4'` change `>`? 

Should I change file `/home/roach/.vim/bundle/powerline/powerline/bindings/vim/plugin/powerline.vim'? What should I do, if that file is related to my question.

Which I want is like ,

![image](https://user-images.githubusercontent.com/9500049/42295578-68a79c20-801e-11e8-96fc-db70a194a4bf.png)

---

![image](https://user-images.githubusercontent.com/9500049/42295592-93e2137a-801e-11e8-8d67-d8cc2e904623.png)

I have installed the font patch.

Thanks for any help!

**Comment by ZyX-I** [comment]
You need to copy `powerline/config_files/themes/powerline.json` to `~/.config/powerline/themes/yourtheme.json`, edit it like you want and create `~/.config/powerline/config.json` with `{"common":{"default_top_theme":"yourtheme"}}`.

Note that for usage questions there is mailing list. Issue tracker is for issues.

**Comment by roachsinai** [comment]
Thanks a lot!
