### ISSUE TITLE
ImportError: Failed to obtain segment function. OSX+SystemPython2.7.15/brew python@2

### ISSUE THREAD

**Issue by avermaet** [powerline/powerline#1932]
Hi,
I want to use powerline in bash, vim and tmux. So far the setup worked, promt works, also 3rd party powerline-gitstatus works. I pip installed them, so they are latest versions.
My problem is, that the comon segment won't load. It seems like none of them. I think there has to be somethin wrong with the path, but I don't know what. Seems ok to me.

Error: when using the common segments. they are not working in 

> tmux

. Bash is fine, also vim.
![screen shot 2018-07-18 at 13 54 29](https://user-images.githubusercontent.com/41374691/42881256-2afda06c-8a97-11e8-8537-0a5519d6c6d6.png)

3rd party works fine in tmux+bash
> powerline-gitstatus
![screen shot 2018-07-18 at 13 56 01](https://user-images.githubusercontent.com/41374691/42881471-90801c12-8a97-11e8-9df3-09e6d9d4dbfa.png)

> Maybe this could have to do with the error. 
![screen shot 2018-07-18 at 13 55 09](https://user-images.githubusercontent.com/41374691/42881659-1edc3d9c-8a98-11e8-804e-68dea477f4fa.png)
but sys.path includes `/usr/local/lib/python2.7/site-packages` therefore I am clueless why the import doesn't work.

![screen shot 2018-07-18 at 14 40 07](https://user-images.githubusercontent.com/41374691/42881588-f26fbb80-8a97-11e8-9ab6-d12b61cabe83.png)

Any help would be greatly appreciated. Thanks!

 Edit: using brew installed python, python@2, vim
and I saw the troubleshoot [advice](http://powerline.readthedocs.io/en/master/troubleshooting/osx.html#i-receive-an-importerror-when-trying-to-use-powerline-on-os-x). But this isn't really helping.I also tried to configure it for pbrew installed python3.7 which resulted in the same problem.

**Comment by ZyX-I** [comment]
The attribute errors looks like if you somehow have corrupt `time` module from standard library. Normally I would say that you should have the same error if you just used `python -c 'import logging'`, but I do not really think you will: powerline is not supposed to work without `logging` at all, that is imported in `powerline/__init__.py`.

Though I spotted another problem in `sys.path`: you have `''` there and it must not ever be put there as it means “current directory” and it is not only a security risk, it being in the first position *will import `powerline.segments.common.time` in place of `time` module from Python library* as long as you `cd` to powerline/segments/common. Check your `$PYTHONPATH` first, it *must not* have any empty entries, which is any character sequence resulting in `os.environ['PYTHONPATH'].split(':')` producing an empty string in a list (that is, two colons everywhere or one colon directly at the start of at the end of the environment variable text).

**Comment by avermaet** [comment]
Hey @ZyX-I, thanks for the answer. `python -c 'import logging`works fine. About the PYTHONPATH, I never set it myself, how do you suggest I remove the empty string? Can't delete `""` in .bash_profile since I didn't set it myself. Also `echo $PYTHONPATH` is an empty line.

**Comment by ZyX-I** [comment]
It appears I forgot that Python adds that by default for whatever reason. Vim removes the entry at startup for the greater good, other applications (powerline included) do not (and removal obviously would not happen in each module, so you would not ever be able to run wthr or import logging (it does *not* work fine as long as you are in the same directory with `time.py`) from directory with `wthr.py`).

If this is what is a problem with tmux I suggest to just run `powerline-daemon` in advance from a directory with no Python files. Though I am wondering why this issue has not been hit earlier.

**Comment by avermaet** [comment]
Another thing, regarding the speed of the prompt generation. In #1653 you said, that the powerline client should be an executable C binary in the fastest case. What about the powerline-daemon, is it ok if this one is still a Python script? I got: <p> `file powerline`--> Mach-O 64bit executable<p> but `file powerline-daemon`--> "python script text executable" and therefore just normal python script. But my prompt is still relatively slow. I'd wish it would be faster due to the noticeable delay in its generation. Any  suggestions?

**Comment by ZyX-I** [comment]
Powerline-daemon has no reason to be a C binary, powerline is written in Python and daemon+C client is a workaround for slow startup. Whether or not you are using daemon delay in generation should be I/O in first place, just without daemon you will have to load Python and import lots of modules and with daemon you may only sometimes get problems with VCS repositories, especially in Mac OS where you either have slower modification-time-based watcher for file changes or have to install pyuv (which is known to miss some events).
