### ISSUE TITLE
Powerline symbols are misaligned in Hyper 2

### ISSUE THREAD

**Issue by jcklpe** [powerline/powerline#1933]
Hi. 

I'm using Hyper 2 (previously known as hyperterm). I am attempting to use the Zsh theme powerlevel9k and everything works fine except for the misalignment of the powerline fonts. I created an issue for this in the powerlevel9k repo but was told that this was more likely an issue with the powerline project itself and to post a ticket here. 

Here is what my terminal looks like:

![image](https://user-images.githubusercontent.com/9451726/43023520-c4f6e472-8c30-11e8-84d6-69cd3a79521c.png)

This issue is the same across any visual theme that I use in Hyper2. 

This is also behavior that other people have encountered in terminal and gnome term: https://github.com/bhilburn/powerlevel9k/issues/922#issuecomment-406700274

And this issue was reported in June in the font repo: https://github.com/powerline/fonts/issues/285

Is there a solution for this issue?

**Comment by BlitzKraft** [comment]
This is an issue with the font+term, not exactly powerline's. This could be likely reproduced in airline/lightline and other prompt decorators.
