### ISSUE TITLE
Usage Problem - No such file or directory

### ISSUE THREAD

**Issue by KayHS** [powerline/powerline#1943]
Hi,

After going trough the setup of powerline with zsh i get the following errors when i load my terminal up.

**~/.zshrc**
```
powerline-daemon -q
. /home/kay/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh
```

```
/home/kay/.zshrc:102: command not found: powerline-daemon
/home/kay/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh:210: no such file or directory: /home/kay/.local/lib/python2.7/site-packages/scripts/powerline-config
/home/kay/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh:214: no such file or directory: /home/kay/.local/lib/python2.7/site-packages/scripts/powerline-config
```
1. "  Powerline daemon is not run automatically by any of my bindings. It is advised to add"

 ( So i did)

2. I checked site-packages/powerline exists but scripts/powerline-config does not am i missing something.

**pip show powerline-status**

```
Name: powerline-status
Version: 2.7
Summary: The ultimate statusline/prompt utility.
Home-page: https://github.com/powerline/powerline
Author: Kim Silkebaekken
Author-email: kim.silkebaekken+vim@gmail.com
License: MIT
Location: /home/kay/.local/lib/python2.7/site-packages
Requires:
```

Im on Ubuntu 18.

**Comment by ZyX-I** [comment]
You must add the location where pip places executable files to `$PATH` before attempting to use said files. E.g. I have

```Zsh
function insert_paths()
{
    for new_path in $@ ; do
        if test -z "${path[(re)$new_path]}"; then
            path[1,0]=( "$new_path" )
        fi
    done
}

# …
insert_paths $HOME/.local/bin
```

in my zshrc, though some prefer to just make entries in `$path` unique (there is a way to use `typeset` to tell zsh that entries in array must be unique) and simply append (`path+=( $new_path )`)/prepend (example above) paths.
