### ISSUE TITLE
No syntax highlighting

### ISSUE THREAD

**Issue by steven-campbell** [powerline/powerline#1944]
After installing powerline and configuring it for vim, I lose syntax highlighting.

This is my .vimrc, which had syntax highlighting before. 
![image](https://user-images.githubusercontent.com/6538667/45722447-69c93b80-bb7a-11e8-91ec-7efee3c7e445.png)

Additionally, I do not experience any coloring issues in the shell (zsh).

**Comment by ZyX-I** [comment]
This vimrc is not configuring any syntax highlighting at all, that could work only if system vimrc was configuring something. Not sure why syntax highlighting stopped working, but I bet it would not start working again if you comment out or remove `set rtp` line. You are supposed to have `filetype plugin indent on` line (to enable filetype detection, though additionally enabling filetype plugins and indent plugins which is not strictly required) and `syntax on` line, both strictly after you finished configuring `&runtimepath`.

Also `set t_Co=256` must not be there. Vim is capable of picking this data from environment (namely `$TERM` variable) and if it picks wrong then it is the *environment* which is wrong and needs fixing: most likely switching startup `$TERM` from `xterm` to `xterm-256color` *in terminal emulator configuration* (not in shell configuration and definitely not in Vim configuration).

**Comment by steven-campbell** [comment]
Yes, my system vimrc was configuring that. Good catch.

Moved these lines to that file and it works as expected.
