### ISSUE TITLE
Player segment throws an error if the player is not installed

### ISSUE THREAD

**Issue by ocaballeror** [powerline/powerline#1946]
I was going to publish a PR, but I wanted to check first if this is something you guys would be open to change.

Right now, if you have a player segment that needs to invoke a subprocess to get the "Now playing" info and the program is not installed, an ugly error is thrown and it's displayed as a very long line in my tmux output. Since I like to sync my configuration between different machines and I don't have all the players installed in all of them, I would like to be able to hide this error.

If it's not an idea you absolutely hate, I'll gladly look into implementing it.

Edit: Screenshot for reference
![selection_078](https://user-images.githubusercontent.com/20464046/45931993-6f59c380-bf76-11e8-988e-f4b695be9932.png)

**Comment by ZyX-I** [comment]
The error must be shown once and go to the log (stderr if log file was not configured). If you see error there and see it each time then it indicates that either there is a bug (unlikely, there *is* logger header seen meaning that error was captured successfully) or you are neither using daemon nor have configured a log file: without a daemon powerline has no means to determine whether error was already shown.

**Comment by ocaballeror** [comment]
You are right, I wasn't running a daemon. I didn't know that a daemon even existed, so I guess this was all my fault.

Starting a daemon makes the error message goes away, so i'm closing this issue. Thanks for your help.
