### ISSUE TITLE
powerline/bash issues overwriting itself.

### ISSUE THREAD

**Issue by kharann** [powerline/powerline#1954]
I know that this issue most likely has been answered already, but none of the fixes i went through has worked at all. This issue has legit been driving me crazy and i hope someone here might be able to help me. Basically when the command i write in the terminal is too long it doesnt jump on the next line and keeps writing on the same line until it goes twice and then it will jump to the next \[ \] which didnt work. Also tried a bunch of other kinds of PS1 configs. 

When i have a normal PS1 Config, which i only configured to have $git$symbol. It seemed to work when the folder(too long line would jump to new line) had no relation with a git branch, but the moment i cd into a folder connected with git it would overwrite itself when command becomes too long. So maybe its something git related? im not sure. Since with powerline running it would straight up overwrite itself regardless of git symbols.

![aasd](https://user-images.githubusercontent.com/41551253/46634852-a9b88880-cb52-11e8-8e5d-ae26e9aa0a72.png)

**Comment by ZyX-I** [comment]
How exactly do you configure bash? With powerline you are not supposed to do anything to PS1 as it gets overwritten every time. Though if you have the issue with every prompt then this means that either bash failed to determine correct terminal width or there is some terminfo screwup (and by that I would normally mean that you have incorrect $TERM as I am yet to hear about a machine which has actual major error in terminfo database itself and not just shell picking wrong part of the database due to wrong $TERM).

**Comment by kharann** [comment]
```powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/share/powerline/bindings/bash/powerline.sh```

I havent really done anything to my bash script at all i believe. It came out like out o the box for some reason. I've been using termite if that helps. I dont believe its a problem with powerline tho since i tried other kind of bash scripts and i seem to have the same issue. 

Also you might be correct about the $TERM thing since this seems to be an issue with any kind of terminal, whatever its tilix, termite or konsole.Im not really sure how to fix this

**Comment by kharann** [comment]
I havent really done anything to my bash script at all i believe. It came out like out o the box for some reason. I've been using termite if that helps. I dont believe its a problem with powerline tho since i tried other kind of bash scripts and i seem to have the same issue. 

Also you might be correct about the $TERM thing since this seems to be an issue with any kind of terminal, whatever its tilix, termite or konsole.Im not really sure how to fix this

**Comment by rdkdd** [comment]
Isn't this connected to size of terminal window? If I have terminal window spread accross desktop powerline prompt is displayed correctly, while if terminal window is smaller, I get display glitches in prompt.

**Comment by ZyX-I** [comment]
@kharann Normally terminals export configured $TERM into the environment before starting any shells. While default exported $TERM in many cases does not give access to full terminal capabilities (I refer to the fact that many terminals have `xterm` as the default while you need to configure them to have `xterm-256color`), it would not cause such problems. So having problems in all of the terminals seems likely in only two causes:

1. It is indeed a terminfo database problem. Invalid entries unlikely, but the whole database missing for some reason not so.
2. You have startup script which overwrites $TERM set by terminal emulator to something else. I must say that shell configuration has no business setting $TERM, it is to be set in terminal emulator configuration.

   Note that bash has more then one configuration file, some are system-wide (though system-wide normally do not contains any bugs like that).

I would suggest to first actually check what is $TERM value and whether it matches what is expected for the terminal emulator. Consult terminal emulator documentation to make sure, but normally it is said to be `xterm` or `xterm-256color`, regardless of the extent to which terminal is *actually* compatible to xterm. For example, AFAIK konsole terminal emulator I am using now is officially supposed to work with `TERM=xterm-256color` despite the fact that ncurses package (at least on my system) does contain records for `TERM=konsole-256color` (and I myself use exactly that) and there are differences on how these emulators treat escape sequences (and `infocmp` does show differences in terminfo entries as well, though I do not know whether they are correct).

And check that you either do not have `$TERMINFO` variable or it is set to some sensible location (it should contain at least file `$TERMINFO/${TERM:0:1}/$TERM`, and normally more than that).

Then check that `stty size` correctly outputs terminal dimensions in display cells (e.g. `stty size` reporting `24 80` means that you have terminal with 24 lines and 80 columns, assuming it reports correctly). Then check that `echo $LINES $COLUMNS` outputs the same thing as `stty size`.

It might also be a good idea to install some other shell (like zsh or fish) and check whether it has the same problem.

**Comment by rdkdd** [comment]
@ZyX-I I tried what you proposed and checked dimensions.
![screenshot from 2018-10-11 09-32-00](https://user-images.githubusercontent.com/18483085/46787943-4177cb80-cd39-11e8-8357-022219255178.png)

**Comment by rdkdd** [comment]
Another thing is that if gnome-terminal is spread on whole desktop, there are some weird symbols in the path
![image](https://user-images.githubusercontent.com/18483085/46809800-920a1b80-cd6f-11e8-9c1f-3269900e7834.png)

any solution? @ZyX-I

**Comment by rdkdd** [comment]
thanks @ZyX-I .
I tried non-configured version of shell (`env -i INPUTRC=/dev/null HISTFILE= "PATH=$PATH" "TERM=$TERM" bash --norc --noprofile`) and run `powerline.sh` and it works ok. 
Here is my `locale` output:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
do you know where in my bash shell configuration could be problem?

**Comment by ZyX-I** [comment]
@rdkdd No, but you can always see everything bash is executing when running `bash -x` (well, everything until somebody runs `set +x` for some reason, but you will still see where that was run and can remove the call). I still have not much of an idea of what is causing the problem though.

**Comment by ondrejtichacek** [comment]
@rdkdd Did you finally solve the issue. I have similar problems, although using `env -i INPUTRC=/dev/null HISTFILE= "PATH=$PATH" "TERM=$TERM" bash --norc --noprofile` does not help.

**Comment by BenisonSam** [comment]
I am also facing the same issue. I have googled and have tried many things but nothing's working

**Comment by bryanmramsamy** [comment]
Same here.
I have the same issue and I don't find any fix anywhere on the internet.
Did someone find a solution by the time ?

**Comment by qoheniac** [comment]
I have a similar issue. If I continually type characters at some point the cursor will jump to the beginning of the line overwriting it but then go on until the very end of the terminal width from where it continues as expected on a new line. The unexpected first jump happens as soon as I reach a line width of 75 if I am in the home directory, 28 if I am in a subdirectory and 150 in a subsubdirectory, not depending on the length of the directory names. These numbers are from a full-screen gnome-terminal with a width of 169. If I use a smaller terminal windows this still happens but at different points. For a terminal with a width of 128 for example the jumps happen at 34, 115 (sub) and 68 (subsub).

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/35881930/zsh-powerline-prompt-disappears-with-long-command-line mentions a similar issue with powerline-bash

**Comment by qoheniac** [comment]
Ok, after living with this issue for months now, I just looked once more into my .bashrc and saw I was sourcing the script for the Busybox prompt instead of the one for Bash. I don't know why I haven't notice this before and I don't really know what more to say. Seems like I was facing a classic layer 8 error.
`¯\_(ツ)_/¯`
