### ISSUE TITLE
characters not displaying correctly in powerline status bar in tmux

### ISSUE THREAD

**Issue by wenyugu** [powerline/powerline#1957]
powerline status bar showing up strange characters in tmux. My locale outputs are
`LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"`
And my tmux.conf is shown below
<img width="254" alt="screen shot 2018-10-23 at 00 30 49" src="https://user-images.githubusercontent.com/29175668/47337793-1b1c2f00-d65b-11e8-999d-7b4c856fea4b.png">
<img width="516" alt="screen shot 2018-10-23 at 00 31 51" src="https://user-images.githubusercontent.com/29175668/47337794-1b1c2f00-d65b-11e8-817d-2cc123d1db31.png">

**Comment by wenyugu** [comment]
I found out that after I pip uninstall powerline. The status bar still remains when open tmux.

**Comment by ZyX-I** [comment]
You are missing fonts, either font files themselves or just proper configuration of terminal emulator. And tmux has client-server architecture, with server never shutting down until there are no terminals (or if you force that with `tmux kill-server`) and configuration being read only once (again possible to source configuration, but sourcing tmux.conf will not clean what is already there, only overwrite if configuration explicitly defines something).

Also note that `status-left.sh` and `status-right.sh` scripts have nothing to do with *this* powerline. I do not know where you got them and what exactly they are doing, but last two lines is all what required for powerline to work.

**Comment by wenyugu** [comment]
The problem is solved. Forgot to configure the font for my shell setting.
