### ISSUE TITLE
powerline bash binding looking for powerline-config in the wrong directory on macos

### ISSUE THREAD

**Issue by paul-tcell** [powerline/powerline#1960]
attempted to launch powerline after installing using [these instructions](https://powerline.readthedocs.io/en/latest/installation/osx.html).

```
. ./Library/Python/3.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh
```

Got this error:

```
. ./Library/Python/3.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh
-bash: ./Library/Python/3.7/lib/python/site-packages/powerline/bindings/bash/../../../scripts/powerline-config: No such file or directory
-bash: ./Library/Python/3.7/lib/python/site-packages/powerline/bindings/bash/../../../scripts/powerline-config: No such file or directory
```

seems the file is actually here: `~/Library/Python/3.7/bin/powerline-config` and not in the scripts directory.

I got it working with: `ln -s  ~/Library/Python/3.7/bin ~/Library/Python/3.7/lib/python/site-packages/powerline/bindings/bash/../../../scripts` but that seems suboptimal.

install info
```
Name: powerline-status
Version: 2.7
Summary: The ultimate statusline/prompt utility.
Home-page: https://github.com/powerline/powerline
Author: Kim Silkebaekken
Author-email: kim.silkebaekken+vim@gmail.com
License: MIT
Location: /Users/me/Library/Python/3.7/lib/python/site-packages
Requires: 
Required-by: 
```

**Comment by erichlf** [comment]
This looks related to #850

**Comment by erichlf** [comment]
Checkout this answer:
https://askubuntu.com/a/953875

**Comment by ZyX-I** [comment]
Directory `$HOME/Library/Python/3.7/bin` is supposed to be in your `$PATH`, you don’t and must not link it where you linked it as that directory is supposed to be maintained by your package manager. If it was powerline would not try to use fallbacks leading to attempting to use powerline-config from the directory you see it attempt to use.

**Comment by colinsf** [comment]
@ZyX-I why was this issue closed?  @paul-tcell's symlink was an attempt at a workaround, not the cause of the problem.

> I got it working with: ln -s ~/Library/Python/3.7/bin ~/Library/Python/3.7/lib/python/site-packages/powerline/bindings/bash/../../../scripts but that seems suboptimal.

**Comment by colinsf** [comment]
[this test](https://github.com/powerline/powerline/blob/2.7/powerline/bindings/bash/powerline.sh#L141) seems to be failing even though `$PATH` is correct in my environment
