### ISSUE TITLE
why is slower in iterm2 than in linux

### ISSUE THREAD

**Issue by liuwenru** [powerline/powerline#1961]
i have a problem  , but how can i to resolve this

in iterm2 use this it cose 
![image](https://user-images.githubusercontent.com/7694194/48065981-411f0300-e207-11e8-8cc6-9d83a3f130ba.png)
in linux ubuntu

![image](https://user-images.githubusercontent.com/7694194/48066017-5ac04a80-e207-11e8-8a3e-7f5b0452bedd.png)

 show to resolve this?

**Comment by ZyX-I** [comment]
`powerline-shell` is not one of executables of *this* powerline project. Also output of `powerline-shell` is much different from output of `powerline shell left` (specifically, escape codes) so it is obvious it is not some local alias. You need to ask where what you are using is maintained, not here.
