### ISSUE TITLE
new color

### ISSUE THREAD

**Issue by madchap** [powerline/powerline#1965]
Hi,

I am trying to add color `lime` and use it, by means of appending to file `colors.json`. This is for use with the tmux extension.

I have tried to add it directly in the colors.json provided by my `brew` install, and also in `~/.config/powerline/config_files/colors.json` for eventual merging (which would be preferred). To no avail in either case.

```
{
        "colors": {
                "lime": [10, "00ff00"]
        }
}
```

I have restarted the `powerline-daemon` and reloaded tmux config.

A `powerline-config tmux setenv` definitely returns it is not finding the key:

```
Traceback (most recent call last):
  File "/usr/local/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/usr/local/lib/python3.7/site-packages/powerline/commands/config.py", line 15, in __call__
    self.function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/powerline/bindings/config.py", line 124, in init_tmux_environment
    highlight = get_highlighting(highlight_group)
  File "/usr/local/lib/python3.7/site-packages/powerline/bindings/config.py", line 110, in get_highlighting
    return colorscheme.get_highlighting([group], None)
  File "/usr/local/lib/python3.7/site-packages/powerline/colorscheme.py", line 113, in get_highlighting
    'fg': pick_color(group_props['fg']),
KeyError: 'lime'
```

I am using the `default` theme.

Any other color in the packaged colors.json file works fine.

**Comment by ZyX-I** [comment]
Did you run `powerline-lint`? Also can you show where you are using it? I do not see anything wrong so far.

**Comment by madchap** [comment]
No error in `powerline-lint`as run in 

```
powerline-lint -p "/Users/fblaise/Library/Python/2.7/lib/python/site-packages/powerline/config_files/"
```

Usage would be in `~/.config/powerline/colorschemes/tmux/default.json`, for example:

```
 "active_window_status": {"fg": "lime",       "bg": "gray0",    "attrs": []},
```

**Comment by ZyX-I** [comment]
You must not add `-p`, it will check *only* the directory you pointed to and you just said that your color usage is located outside of it.

**Comment by ZyX-I** [comment]
And I have not spotted the issue earlier, but in your first post you said that you used `~/.config/powerline/config_files/colors.json`. `config_files/` component must not be present there.

**Comment by ZyX-I** [comment]
I cannot reproduce the error with script

```Shell
#!/bin/sh
set -e
set -x
mkdir -p ~/tmp
mkdir ~/tmp/powerline-cfgroot
mkdir -p ~/tmp/powerline-cfgroot/powerline/colorschemes/tmux
echo '{"colors":{"lime":[10,"00ff00"]}}' > ~/tmp/powerline-cfgroot/powerline/colors.json
echo '{"groups":{"active_window_status":{"fg":"lime","bg":"gray0","attrs":[]}}}' > ~/tmp/powerline-cfgroot/powerline/colorschemes/tmux/default.json
export XDG_CONFIG_HOME="$HOME/tmp/powerline-cfgroot"
powerline-config tmux setenv
```

: it does not do anything visible (tmux already started, if I replace `setenv` with `setup` I do have a visible effect), but it does not throw a error either.

**Comment by madchap** [comment]
powerline-lint on its own is throwing so much error, that it is pretty useless to me :-/ It doesn't seem to like the fact I have a `~/.config` with just "standalone" lines to be merged?

> And I have not spotted the issue earlier, but in your first post you said that you used `~/.config/powerline/config_files/colors.json`. `config_files/` component must not be present there.

OK, this works. I kinda feel silly here. I will read the doc again, but don't remember seeing this... sorry to have wasted your time, and thanks again for your answer, much appreciated.

**Comment by ZyX-I** [comment]
(Note: to rerun the script you need to remove `~/tmp/powerline-cfgroot`. It is intentional, did that to prevent accidentally removing a directory if you do need it.)

**Comment by madchap** [comment]
Thanks @ZyX-I 👍
