### ISSUE TITLE
2.7 not working for zsh?

### ISSUE THREAD

**Issue by b0rski** [powerline/powerline#1966]
Is there more config needed for zsh? This is my first try on zsh + powerline.

```
[...]
# configuration starts here
export TERM="xterm-256color"

export LANG="en_US.UTF-8"
export LANGUAGE="en_US:en"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_PAPER="en_US.UTF-8"
export LC_IDENTIFICATION="en_US.UTF-8"
export LC_NAME="en_US.UTF-8"
export LC_ADDRESS="en_US.UTF-8"
export LC_TELEPHONE="en_US.UTF-8"
export LC_MEASUREMENT="en_US.UTF-8"

path+=( ~/.local/bin )

powerline-daemon -q
source "$(python -m site --user-site)/powerline/bindings/zsh/powerline.zsh"
```
I'm using zsh 5.4.2 on Ubuntu 18.04 but all I see is this.

![image](https://user-images.githubusercontent.com/11145838/48962607-32b04580-ef82-11e8-99d8-ba5b493c8c92.png)

When I use powerline with bash everything runs nicely.

**Comment by ZyX-I** [comment]
This does not look like powerline promt at all. Most likely you just have something overriding powerline prompt: not uncommon occurrence if you have something like oh-my-zsh. You may check `echo "$PS1"`, it will either run `$POWERLINE_COMMAND` in `$()` with a bunch of arguments, or (rather uncommon as libzpython is not well known) just use `${ZPYTHON_POWERLINE_PS1}`.

Also note that your configuration is too exhaustive and partially incorrect: out of all `LC_…` variables you need to only define `$LANG` or `$LC_ALL` unless others are defined for some reason and you need to redefine them. And none of the variables you are setting, except for `$path`, should be present in zshrc:

- TERM must be set in terminal emulator configuration. It will be incorrect should you switch to another terminal emulator, *including* staying on whatever you have currently, but running screen or tmux inside, so it is exceptionally bad idea to set it in shell configuration.
- LANG should be set in system configuration, like /etc/env.d/99locale, as it should apply to GUI applications run from various WM/DE menus as well as WM/DE locale itself. I think it should already be there after installing system and needs not be explicitly set. Note that /etc/env.d/99locale is Gentoo-specific, other distributions may use different place. It may make sense to have it in shell configuration only if you need terminal applications have different locale, but this way you will observe differences between running GUI application from GUI and from terminal.

**Comment by b0rski** [comment]
Sorry to bother you with that. I'm new to zsh. It seems .zshrc contains a prompt set up per default. This was the problem.

```
autoload -Uz promptinit
promptinit
adam1
```

After removing it powerline works as expected.
