### ISSUE TITLE
Multiple status line printed(Still Same issue as #1652) 

### ISSUE THREAD

**Issue by dannyk0104** [powerline/powerline#1967]
![p](https://user-images.githubusercontent.com/23534258/48991611-35817680-f0f9-11e8-93f5-7f5571d56c49.PNG)
The problem is same as #1652.
I tried all the solutions(work around), but still could not fix it.

I put following on .tmux_conf file
# use UTF8 set -g utf8 set-window-option -g utf8 on

following to .bashrc file
export LC_ALL=en_US.UTF-8 export LANG=en_US.UTF-8 export LANGUAGE=en_US.UTF-8

and modified powerline.json file like following
"time": { "before": "" }

I am using windows subsystem linux with bash.
Without powerline, it works fine.

I really want to have powerline for my Tmux!!
Please help!!

**Comment by ZyX-I** [comment]
You clearly have no correct fonts installed, or have not enabled them correctly. Also unless tmux and whatever terminal emulator you are using agree on character width there is exactly nothing you can do unless you want to patch and recompile either of them (depending on which one thinks that powerline characters are double width, based on the display that may only be terminal emulator, you would get different results if it was tmux). Or give up on using powerline arrows as explained in the first comment in #1652.

Note that sometimes terminal emulators can be configured to display characters with ambiguous width as double width characters. If this is the case powerline symbols are normally considered ambiguous width and are affected by this option.

Please do not ask me how to configure WSL terminal emulator or how to install powerline fonts for WSL to find. I do not have WSL.
