### ISSUE TITLE
show exit status of individual pipeline items

### ISSUE THREAD

**Issue by anarcat** [powerline/powerline#1970]
the status code returned by bash (`$?`) notoriously refers only to the last item in the pipeline (barring some non-default configuration of course). But bash also knows the status code of each individual process in the pipeline. That is, as far as I know, a non-standard extension, but it can be used to display multiple status codes on complex pipelines, which I find quite useful. A trivial example from a home-made  prompt:

```
anarcat@curie:~(master)$ ( exit 0 ) | (exit 1) | (exit 2)
[2 (1 | 2)]anarcat@curie:~(master)$ 
```

That's how powerline sees that:

```
 anarcat   master  ~  ( exit 0 ) | (exit 1) | (exit 2)
 anarcat   master  ~  2  
```

Sorry, again, for the private unicode noise... It would be nice to expand that prompt to cover from those other exit values!

Thanks!

**Comment by ZyX-I** [comment]
That was already implemented in #1775 .

**Comment by anarcat** [comment]
i upgraded to powerline 2.7 and still don't see this - how is it configured?

**Comment by ZyX-I** [comment]
It is by default present in `default_leftonly` theme (and in `default` too, but on the right side and that is not supported by bash). If when you type `false | false<CR>` in bash you see only one `1` in prompt then you have outdated powerline (perhaps you forgot to restart daemon). If you see *no* segments with `1` in prompt then you are using `default` theme which was created for shells with right prompt present. If you have custom theme make sure that you use `last_pipe_status` segment rather then `last_status` segment.

**Comment by anarcat** [comment]
oh i probably just didn't restart the daemon - thanks for the precisions! :)
