### ISSUE TITLE
powerline-status does not work with bash version 4.4.23 (from homebrew) on macos when set as the login shell

### ISSUE THREAD

**Issue by paul-tcell** [powerline/powerline#1971]
Note it works fine with the default installed Apple bash, version 3.2.57.   It also works if you just run `/usr/local/bin/bash` from the apple `/bin/bash` and launch powerline-status.

To repro:

```
brew install bash
cat "/usr/local/bin/bash" >> /etc/shells # (do as root)
sudo chsh -s /usr/local/bin/bash $USER
```

Install powerline-status with pip as per OSX instructions.  https://powerline.readthedocs.io/en/master/installation/osx.html

```
. ~/Library/Python/3.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh
```
yields the errors:
```
-bash: ./Library/Python/3.7/lib/python/site-packages/powerline/bindings/bash/../../../scripts/powerline-config: No such file or directory
-bash: ./Library/Python/3.7/lib/python/site-packages/powerline/bindings/bash/../../../scripts/powerline-config: No such file or directory
```

Doesn't matter if `${HOME}/Library/Python/3.7/bin` is in the `PATH` or not.

Now switch to Apple bash to verify:
```
/bin/bash
. ~/Library/Python/3.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh
```
works fine.

**Comment by paul-tcell** [comment]
interestingly, if I run `exec /usr/local/bin/bash` from the existing /usr/local/bin/bash login shell, powerline works.

comparing the output of `set` between the two shells, the only diffs are BASHOPTS, BASH_REMATCH in the login shell, SHLVL (1 vs. 2), PS1, PROMPT_COMMAND

**Comment by ZyX-I** [comment]
The error looks much like $PATH issue. When you determined that it “doesn't matter if `${HOME}/Library/Python/3.7/bin` is in the `PATH` or not” did you check that it is path *at the point where `. ~/Library/Python…` command is called* or not?

**Comment by wydwww** [comment]
@ZyX-I I had the same issue with zsh on macOS. `.../bin` was added to PATH before `. ~/Library/Python…` in zshrc file, and I can directly execute powerline-config so it is in the PATH.
