### ISSUE TITLE
Powerline characters mess up when using Mobaxterm as ssh-client in Windows

### ISSUE THREAD

**Issue by tzengjh** [powerline/powerline#1972]
The pre-installed powerline plugin dispalys correctly when using PuTTY as remote ssh-client.
![image](https://user-images.githubusercontent.com/12627875/50423295-77374580-088e-11e9-9cd1-edad43376644.png)
However, it messes up when I switch to Mobaxterm.
![image](https://user-images.githubusercontent.com/12627875/50423281-553dc300-088e-11e9-9bfd-a04c25c56ac3.png)

I have tried to install powerline-fonts as it suggested.
https://github.com/powerline/fonts, but it didn't help.

And I install powerline-fonts in Windows by following this blog
https://medium.com/@slmeng/how-to-install-powerline-fonts-in-windows-b2eedecace58, then change the terminal fonts configure in Mobaxterm，but it didn't help too.

Is there anyone know how to fix this problem? Thank you very much !!

**Comment by hss14** [comment]
I met exactly the same problem, even my messed-up display is the same as yours.
So have u solved this problem ?

**Comment by tzengjh** [comment]
Not yet...

**Comment by GCZhang** [comment]
Update your MobaXterm to the latest version. It should work.

**Comment by Y0ngg4n** [comment]
Same Problem. Tried all Fonts fom Nerd Fonts but didn´t worked with Powerline Fonts in MobaXterm.

**Comment by kosiu** [comment]
Convertion Nerd Fonts: ttf -> otf solves the problem, unfortunately they are rendered by MobaXterm horribly.

**Comment by WoojunePark** [comment]
Had same problem here. [This font](https://github.com/halocaridina/.dotfiles_thinkpad_x230/blob/master/Xresources/.local/share/fonts/PragmataPro/PragmataPro%20for%20Powerline.ttf) works fine. 

source : https://superuser.com/questions/1134268/mobaxterm-powerline-font-issue

**Comment by BlitzKraft** [comment]
Stale issue. Closing.
