### ISSUE TITLE
ОНО СТЁРЛО ВСЮ МОЮ ИСТОРИЮ BASH!

### ISSUE THREAD

**Issue by kot-mapku3** [powerline/powerline#1974]
**Этот кусок дерьма после установки затёр историю команд, которые я хранил с самой переустановки. FUCK, это самое печальное, что я вообще делал. Я никогда не думал, что буду грустить насчёт истории bash, но это так! Урод!**

**Comment by lyda** [comment]
"""This piece of shit after installation wiped the history of commands that I kept from the very reinstallation. Fuck, this is the saddest thing I ever did. I never thought that I would be sad about the history of bash, but it is! Freak!"""

I fail to see how:

```bash
git clone git@github.com:powerline/powerline.git
cd powerline
git grep bash_hist
git grep HIST
```

Those last two return nothing.
