### ISSUE TITLE
powerline.commands module missing

### ISSUE THREAD

**Issue by MetaNite64** [powerline/powerline#1988]
I put `source ~/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf` into my tmux conf. The file is there and is executable, but manually sourcing my conf gives me `'powerline-config tmux setup' returned 1`. Manually running `powerline-config tmux setup` gave me two exceptions, both because of `ModuleNotFoundError: No module named 'powerline.commands'`. I don't know what to do. Please help!

**Comment by PH111P** [comment]
It looks like you installed powerline using python 2. Are you also trying to run `powerline-config` using python 2? 
As a side note, I'd recommend switching to python 3, as python 2 itself is deprecated.
