### ISSUE TITLE
powerline.segments.i3wm.mode missing required segment_info

### ISSUE THREAD

**Issue by jackwootton** [powerline/powerline#1995]
`powerline.segments.i3wm.mode` is not rendering anything because there is no `mode` key in `segment_info` dictionary ([#dev-segments-info](https://powerline.readthedocs.io/en/master/develop/segments.html#dev-segments-info)):

```
	{
		"function": "powerline.segments.i3wm.mode",
		"args": {
			"names": {
				"default": "default",
				"gaps": "gaps",
				"resize": "resize"
			}
		},
		"name": "mode"
	}
```

I added a debug statement and the key is missing (docstring removed for brevity):

```
@requires_segment_info
def mode(pl, segment_info, names={'default': None}):
	mode = segment_info['mode']

	# This is empty!
	pl.debug(segment_info.get('mode'))
	if mode in names:
		return names[mode]
	return mode
```

My log file:

`2019-04-01 13:17:07,476:DEBUG:wm:mode:None`

**Comment by PH111P** [comment]
Some more context would be appreciated; currently, I cannot reproduce this.
