### ISSUE TITLE
Can't get "fancy" mode working

### ISSUE THREAD

**Issue by sdondley** [powerline/powerline#2003]
I'm on a Debian install (no GUI) running iTerm2 via SSH from MacOS. I followed the instructions as well I was able. All the appropriate LANG* and LC* settings are en_US.UTF-8. As best I can tell, vim was compiled in "huge" mode which I'm guessing is better one more than "Big" mode. iTerm2 is set to UTF-8. It does ascii and UTF-8 fonts. I followed the instructions for installing the font with fc-cache. I installed the python module with pip3 following instructions from the website.

Alas, I still see little boxes with "?" in them where I'm guessing some cool graphic is supposed to appear. All this has been an awful lot of work, so far. There's no turning back for me.

Any advice for diagnosing what is wrong with my setup?

**Comment by PH111P** [comment]
See https://powerline.readthedocs.io/en/latest/usage.html#usage-terminal-emulators.
Also try to paste the powerline characters (` `) in your terminal and see if they work.

**Comment by PH111P** [comment]
Closing due to lack of responses.
