### ISSUE TITLE
my gVim showed strange characters on mac when enabled powerline plugin

### ISSUE THREAD

**Issue by Lynn-cc** [powerline/powerline#2018]
Here is the [stackexchange link](https://vi.stackexchange.com/questions/20591/my-vim-cant-print-chinese-right-on-my-mac?noredirect=1#comment36012_20591)

after I disabled this plugin in my .vimrc:

   `"Plugin 'powerline/powerline'`

gVim works right.

Ps、I found this problem on the old version: `Lokaltog/vim-powerline`, but the problem 
 also shows on the new version.

**Comment by danielnehrig** [comment]
you don't have the patched fonts installed

**Comment by BlitzKraft** [comment]
@Lynn-cc : In case you haven't resolved this yet, your terminal font needs to be set to something that supports the powerline glyphs.
