### ISSUE TITLE
tabline dividers background 

### ISSUE THREAD

**Issue by fdelacruz** [powerline/powerline#2021]
I have this issue where my tabline looks ok if it is only one:
<img width="571" alt="Screen Shot 2019-08-20 at 10 40 19 AM" src="https://user-images.githubusercontent.com/148098/63357387-55b42e00-c337-11e9-8db0-cd18cf9603c1.png">
But when I open a new tab I get this:
<img width="572" alt="Screen Shot 2019-08-20 at 10 40 51 AM" src="https://user-images.githubusercontent.com/148098/63357472-7da39180-c337-11e9-8b13-b4787ecbaaa1.png">
Where the divider looks like that. I tried changing the 'many_tabs' hightlights in the coloschemes/solarized file to no avail.
Any pointing in the right direction will be greatly appreciated.

@fdelacruz

**Comment by PH111P** [comment]
Try to change the `tab:divider` highlight group.
