### ISSUE TITLE
use `command -v` instead of `which`

### ISSUE THREAD

**Issue by paulohefagundes** [powerline/powerline#2027]
I'd like to ask if you guys could replace `which` for `command -v`.

I use Arch Linux and recently Arch no longer installs `which` by default through the [base package](https://www.archlinux.org/news/base-group-replaced-by-mandatory-base-package-manual-intervention-required/). The maintainers explained some reasons why `command -v` is better here
- https://www.reddit.com/r/archlinux/comments/de1er6/arch_linux_news_base_group_replaced_by_mandatory/f2v8uhu/

Currently as a workaround I installed `which` locally, but pretty much just because powerline uses it. I'd like to be able to remove `which` from my system once powerline no longer depends on it

**Comment by BlitzKraft** [comment]
Everything in the comments make sense, I was personally a victim of `which` - giving out the binary when a command executes an alias.

**Comment by BlitzKraft** [comment]
@paulohefagundes `which` is no longer needed by powerline for usage. Could you test and confirm? 

It is needed, for now, for testing and dev. I am working on the tests.

**Comment by BlitzKraft** [comment]
Here are the steps: 

* Clone/download the branch `[2027-use-command-v](https://github.com/BlitzKraft/powerline/tree/2027-use-command-v)` 

* `cd` to the directory, and `pip install .` 

This will install the new branch. Keep in mind, this will overwrite config files from the previous install.

**Comment by shal4** [comment]
ok, it looks like it is working :D

```
# uninstall the official power-status (was version 2.7)
python3 -m pip uninstall powerline-status
pacman -R which # uninstall which
which
    bash: which: command not found

git clone -b 2027-use-command-v --single-branch  https://github.com/BlitzKraft/powerline.git

python3 -m pip install --user powerline/

python3 -m pip show powerline-status
    Name: powerline-status
    Version: 2.7.dev9999-git.b-f9937ab922ff753164bac374b77cfab78bbe7ea0-
    Summary: The ultimate statusline/prompt utility.
    Home-page: https://github.com/powerline/powerline
    Author: Kim Silkebaekken
    Author-email: kim.silkebaekken+vim@gmail.com
    License: MIT
    Location: /home/user/.local/lib/python3.7/site-packages
    Requires: 
    Required-by: 
```

Thanks @BlitzKraft you were pretty quick about this :+1:

**Comment by BlitzKraft** [comment]
Sweet. Now to take a look at the failing tests. Please note that since the tests are failing it *might* not be stable.
