### ISSUE TITLE
Powerline Prompt not working in tmux

### ISSUE THREAD

**Issue by anupamsingh610** [powerline/powerline#2035]
The powerline prompt works fine on pure bash. As shown :
![Screenshot from 2019-10-25 00-53-35](https://user-images.githubusercontent.com/8946367/67518220-f02b4780-f6c1-11e9-8d1b-d2a7f4704a0f.png)

It is when I open tmux the prompt looks like the image attached
Note the tmux status works fine. It is only the prompt that doesn't work.

I have gone through the documentation and tried a couple of things but did not find any solution.
![Screenshot from 2019-10-25 00-48-10](https://user-images.githubusercontent.com/8946367/67517968-61b6c600-f6c1-11e9-9372-a78183f2438e.png)

I also tried running `run-shell "powerline-config tmux -s powerline_tmux_2.1_plus.conf setup"` as I have **tmux version 2.6** but it returned 2

**Comment by BlitzKraft** [comment]
@anupamsingh610: What happens when you run `source ~/.bashrc` inside the tmux shell? Expected result is bash shows powerline prompt after sourcing the bashrc.

**Comment by anupamsingh610** [comment]
> @anupamsingh610: What happens when you run `source ~/.bashrc` inside the tmux shell? Expected result is bash shows powerline prompt after sourcing the bashrc.

Thank you! It works. I still don't understand though why I have to explicitly run it. 
Nevertheless I added this to `~/.tmux.conf`

**Comment by BlitzKraft** [comment]
@anupamsingh610 : I am not sure why your .bashrc is not being executed. That might be a bug in the way tmux is invoking the shell. I am using tmux 2.9, I don't have this issue. When you update your tmux, you might find this resolved and no longer need to source bashrc again.

**Comment by anupamsingh610** [comment]
I'll try. Thank you so much :)

**Comment by vissieGP** [comment]
Hi. I am seeing the same behaviour. This post helped me to get powerline running. So thanks for the info. I do not understand why its happening or how to permanently fixing it. Some help will be appreciated.  
As stated, I have the same behaviour as above. powerline in Bash works, when I enter into tmux, it shows in tmux, not on the command line. 

if I run "source /usr/local/lib/python3.7/dist-packages/powerline/bindings/bash/powerline.sh", it works.
If I create a bash script, say run_tmux.sh, make that executable, add the above line in that shell script, it does NOT work.
I ended up adding a alias in my /etc/bash.bashrc file to run this line, and that seems to work:
alias stmux='source /usr/local/lib/python3.7/dist-packages/powerline/bindings/bash/powerline.sh'

so within tmux i just run stmux and the prompt is there. 

Any ideas how to get a more permanent fix? 

Vissie

**Comment by BlitzKraft** [comment]
@vissieGP I suspect your default python version does not match the env installed for powerline. 

On just plain bash window, get the output of `python --version` and `python3 --version`. Repeat the same within the tmux window. I am expecting a mismatch(es) here. 

Permanent fix would depend on the root of the problem.

**Comment by vissieGP** [comment]
Hi. Thx for the quick response!
Bash:
python --version -> Python 2.7.16
python3 --version - > Python 3.7.3
Tmux:
python --version -> Python 2.7.16
python3 --version -> Python 3.7.3

So they are the same.
