### ISSUE TITLE
Vim Fails To Open Files with powerline-status in .vimrc

### ISSUE THREAD

**Issue by albertjosedevera** [powerline/powerline#2040]
Hi,

When Powerline-status is included in `.vimrc`, MacVim and `/usr/bin/vim` on macOS Catalina fails to open any file. 

`.vimrc` contains the following:

```
set rtp+=/Users/xxxxuser/Library/Python/3.7/lib/python/site-packages/powerline/bindings/vim
```
Commenting out the above line gets MacVim and `/usr/bin/vim` working normally again.

I also get these error messages on the console:
```
error	01:48:06.396471-0400	kernel	Library Validation failed: Rejecting '/private/var/folders/1v/crcn56z50fzgsk19h1j6jbf80000gn/T/ffiTaieGT' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.398304-0400	kernel	Library Validation failed: Rejecting '/private/tmp/ffiGvrURr' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.400187-0400	kernel	Library Validation failed: Rejecting '/private/var/tmp/ffixKnmmg' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.401895-0400	kernel	Library Validation failed: Rejecting '/Users/xxxxxuser/ffiKOliF9' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.403891-0400	kernel	Library Validation failed: Rejecting '/private/var/folders/1v/crcn56z50fzgsk19h1j6jbf80000gn/T/ffid0xFIB' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.405714-0400	kernel	Library Validation failed: Rejecting '/private/tmp/ffiR66FGD' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.407653-0400	kernel	Library Validation failed: Rejecting '/private/var/tmp/ffiq4ueS3' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.409573-0400	kernel	Library Validation failed: Rejecting '/Users/xxxxxuser/ffi8nbTpr' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.411236-0400	kernel	Library Validation failed: Rejecting '/private/var/folders/1v/crcn56z50fzgsk19h1j6jbf80000gn/T/ffipbVBiQ' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.413059-0400	kernel	Library Validation failed: Rejecting '/private/tmp/ffi3EF2at' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.414808-0400	kernel	Library Validation failed: Rejecting '/private/var/tmp/ffibHSc7H' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.416347-0400	kernel	Library Validation failed: Rejecting '/Users/xxxxxuser/ffieKRu7j' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.418111-0400	kernel	Library Validation failed: Rejecting '/private/var/folders/1v/crcn56z50fzgsk19h1j6jbf80000gn/T/ffi6PXhIs' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
error	01:48:06.419910-0400	kernel	Library Validation failed: Rejecting '/private/tmp/ffiXm7hTE' (Team ID: none, platform: no) for process 'vim(3210)' (Team ID: none, platform: yes), reason: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed
```
I've tried using the release versions and the current development versions of powerline-status but the results were the same.

My system:
OS: macOS 10.15 Catalina
Software affected with Powerline-status: MacVIM and vim versions: 
  MacVim 8.1.2224 (160)
  ViM 8.1.1312 (the one that comes with macOS Catalina)

I am not sure if this is a Vim problem alone or some interaction with Vim, powerline-status, and macOS Catalina.

**Comment by BlitzKraft** [comment]
Is your vim/macvim installed using homebrew?

**Comment by albertjosedevera** [comment]
> Is your vim/macvim installed using homebrew?

Hi,

No. It used to be, but I uninstalled it some time ago. 

On my other Mac, there was never a homebrew version of MacVim, and macvim and Apple's vim exhibited the same behavior.

**Comment by BlitzKraft** [comment]
In mac settings, there should be a toggle to allow running unsigned/unverified programs. Could you run vim with powerline if you allow running unsigned programs? The expected result is you still have the same issue. You can toggle the setting back after checking this. 

Also, what's the terminal you're using for vim?

**Comment by albertjosedevera** [comment]
> In mac settings, there should be a toggle to allow running unsigned/unverified programs. Could you run vim with powerline if you allow running unsigned programs? The expected result is you still have the same issue. You can toggle the setting back after checking this.
> 
> Also, what's the terminal you're using for vim?

Hi,

I'll try that in awhile. As for the terminal I'm using, it's iTerm2.

**Comment by albertjosedevera** [comment]
Allowing unsigned/unverified programs didn't work either. I still had to call `mvim --clean` to open a file.

_Update_: MacVim 8.1.2234 (161) just got released which fixes "scripting languages not working (e.g. Python) in binary releases by using the correct entitlements. #979". 

It works now (with powerline enabled) when I call `/usr/local/bin/mvim` or `/Applications/MacVim.app/Contents/MacOS/MacVim -g` or `/Applications/MacVim.app/Contents/MacOS/Vim -g` but not when I click on the app icon. Apple's install of vim doesn't work still.

I guess this is more of a MacVim problem.

**Comment by albertjosedevera** [comment]
I removed the MacVim.app from `/Applications` and installed HomeBrew's  version. `MacVim.app` from `/usr/local/Cellar/macvim/8.1-161/` was copied to `/Applications`. Clicking on MacVim now works with powerline-status.

**Comment by BlitzKraft** [comment]
Good. Closing this, since it's not a powerline issue.
