### ISSUE TITLE
Segments not working in tmux on Windows Subsystem

### ISSUE THREAD

**Issue by dtynewydd** [powerline/powerline#2044]
I've installed powerline on wsl to use with tmux and a lot of segments don't display. Namely, the vcs segments and the weather segment display nothing.

default.json:
```
  1 {
  2     "segments": {
  3         "left": [
  4         ],
  5         "right": [
  6             {
  7                 "function": "powerline.segments.common.wthr.weather"
  8             },
  9             {
 10                 "function": "powerline.segments.common.time.date"
 11             },
 12             {
 13                 "function": "powerline.segments.common.time.date",
 14                 "name": "time",
 15                 "args": {
 16                     "format": "%H:%M",
 17                     "istime": true
 18                 }
 19             }
 20         ]
 21     }
 22 }
```
powerline tmux right (does not have a weather field) output:
```
#[fg=colour236,bg=default,nobold,noitalics,nounderscore] #[fg=colour247,bg=colour236,nobold,noitalics,nounderscore] 2019-11-12#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore] #[fg=colour252,bg=colour236,bold,noitalics,nounderscore] 16:25 
```

Powerline:
![image](https://user-images.githubusercontent.com/29239190/68689846-ef6f2e00-0568-11ea-9b1d-4a6a858e14e0.png)

I've tried restarting the daemon, exiting wsl and restarting my pc - nothing seems to change.

Am I missing something obvious?

**Comment by dtynewydd** [comment]
I've since seen that the weather segment doesn't currently work. Still an issue for the vcs segments however.

Also, no traceback seen when running powerline-daemon in the foreground.

**Comment by BlitzKraft** [comment]
In your `config.json`, the shell theme should be `default_leftonly` for the vcs. Or add the following segment in your `left` block 

```json
                        {                                                                                                                                                                      
                                "function": "powerline.segments.common.vcs.branch",
                                "priority": 40
                        },
```

The `left` section in powerline `default.json` shouldn't be empty, but your paste is. Is this a part of your customization?

**Comment by BlitzKraft** [comment]
@dtynewydd : Also, run powerline linter after editing. JSON is very stringent on the rules and a will throw a lot of irrelevant syntax errors if you get it wrong.

**Comment by PH111P** [comment]
Also note that if you want the `vcs` segment to appear directly in the `tmux` status bar, you need to add the segment there; your configuration shown above includes the `weather` segment (which is essentially defunct by now) but it does not include the `vcs` segment.

**Comment by dtynewydd** [comment]
@PH111P The above was just an example showing the weather segment. The same is also true for when using the vcs segments.

See below for my updated default.json:
```
 1 {
  2     "segments": {
  3         "left": [
  4             {
  5                 "function": "powerline.segments.common.vcs.branch",
  6                 "priority": 40
  7             }
  8         ],
  9         "right": [
 10             {                                                                                   11                 "function": "powerline.segments.common.time.date"                               12             },                                                                                  13             {                                                                                   14                 "function": "powerline.segments.common.time.date",                              15                 "name": "time",                                                                 16                 "args": {                                                                       17                     "format": "%H:%M",                                                          18                     "istime": true                                                              19                 }                                                                               20             }                                                                                   21         ]                                                                                       22     }                                                                                           23 }    
```

@BlitzKraft moving it to the left block doesn't seem to have helped. I must have cleared the left section while trying to get stuff to work before. Linter also throws no issues, still no backtrace either

**Comment by PH111P** [comment]
Try to add the segment to the `right` block, AFAIK, you cannot really configure the left part in `tmux`.

**Comment by dtynewydd** [comment]
Added vcs.branch to both right and left, also added an extra date segment to each to test that extra segments show up.

```
  1 {
  2     "segments": {
  3         "left": [
  4             {
  5                 "function": "powerline.segments.common.time.date"
  6             },
  7             {
  8                 "function": "powerline.segments.common.vcs.branch",
  9                 "priority": 40
 10             }
 11         ],
 12         "right": [
 13             {
 14                 "function": "powerline.segments.common.vcs.branch",
 15                 "priority": 40
 16             },
 17             {
 18                 "function": "powerline.segments.common.time.date"
 19             },
 20             {
 21                 "function": "powerline.segments.common.time.date"
 22             },
 23             {
 24                 "function": "powerline.segments.common.time.date",
 25                 "name": "time",
 26                 "args": {
 27                     "format": "%H:%M",
 28                     "istime": true
 29                 }
 30             }
 31         ]
 32     }
 33 }
```
Still no joy:
![image](https://user-images.githubusercontent.com/29239190/68766785-71b62b80-0617-11ea-827a-f5a1b7ab55d5.png)

`powerline-lint` is also happy with the above

**Comment by BlitzKraft** [comment]
@dtynewydd Are you sure you're in a directory with a git/vcs repo when testing that? Without that the vcs segment does not show up at all.

**Comment by dtynewydd** [comment]
@BlitzKraft yep definitely in a git repo directory

**Comment by BlitzKraft** [comment]
@dtynewydd The terminal width might not be sufficient to display everything. What is the output of `powerline-render tmux left`? This will print to stdout, all the variables/params configured to be displayed without regarding the width. Test with an expected vcs directory and a non-vcs directory.

**Comment by BlitzKraft** [comment]
@dtynewydd  The documentation refers to using shell-bindings in regards to using a VCS segment in the tmux statusline. Also notes that all shells may not work. 

[This](https://powerline.readthedocs.io/en/master/usage/other.html#tmux-statusline) is the part of the docs I'm referring to. Check the warning.

**Comment by dtynewydd** [comment]
![image](https://user-images.githubusercontent.com/29239190/69060808-e91cfe00-0a0f-11ea-8a98-cbca9aa34c5e.png)

powerline-render shows the vcs info when in a git dir.

I've gone through and added the shell-bindings so now I'm getting the vcs info on my prompt but still no joy on the tmux statusline.

I couldn't quite work out the components thing to just enable tmux and not the prompt but the docs say both should be enabled by default so if the prompt works tmux should too.

It isn't a width issue either as I can drop in more date segments no problem.

I'm also using bash so I figure that should be supported?

**Comment by BlitzKraft** [comment]
What happens if you remove the date segment, just keep the vcs segment? There is a tmux setting `status-left-length` - which by default has a value of 10. You can change that using 

`set -g status-left-length 40` - on the tmux commandline.

In addition to that, delete the priority setting in the vcs section. Or add it to the date section with the same value.

**Comment by BlitzKraft** [comment]
The priority is in the docs. It wasn't my first suspicion, though in retrospect, it should have been.
