### ISSUE TITLE
Can not install powerline fonts on Mac 10.14.6

### ISSUE THREAD

**Issue by dirainbow** [powerline/powerline#2049]
![image](https://user-images.githubusercontent.com/21090789/69305701-df89d500-0c5f-11ea-9194-df4968554051.png)

**Comment by BlitzKraft** [comment]
This issue belongs in powerline/fonts here: https://github.com/powerline/fonts/issues . Please post the same there. A temporary work around is to ignore the errors and install them anyway. I have not tested this.
