### ISSUE TITLE
Special Characters are not displayed in bar

### ISSUE THREAD

**Issue by jazz-g** [powerline/powerline#2055]
I have just installed powerline for bash, vim, and tmux.
OS: Arch Linux (installed through pacman -S powerline-vim powerline)
I'm using kitty as a terminal, but I can confirm it doesn't work in konsole or terminator too.
(`$TERM` is `xterm-kitty`)

My issue is the special characters are not displayed in any powerline bar. I have the powerline fonts working, but the text of the bar does not contain the powerline unicode characters which I checked through a unicode lookup.

I ran the command `python -c 'print(u"\ue0b0\ue0b1\ue0b2\ue0b3")'` which output the powerline characters in the terminal with the font working. Help is much appreciated.
[.bashrc](https://pastebin.com/p6yGyNtH)
[kitty.conf](https://pastebin.com/LcEHDh2T)
Let me know if you want other config files

**Comment by BlitzKraft** [comment]
I'm pretty sure powerline-vim is obsolete and just powerline is sufficient for vim. For the bars, you need to set the font of the bar to use one with the powerline glyphs. Does inconsolata have the glyphs included? I recall there's a patched inconsolata in the powerline/fonts repo. Also try that.

**Comment by jazz-g** [comment]
My hard drive conveniently failed. Got a new one and did a bottom up install, and powerline works fine now.
