### ISSUE TITLE
prompt path is not updated properly when moving between directories with automatic python virtualenv set up via pyenv

### ISSUE THREAD

**Issue by priestoferis** [powerline/powerline#2058]
I use `pyenv` to set my current virtualenv. In my ~/Downloads folder I have pyenv local set to `datascience`.
I will screenshot how my prompt changes, this is the start:
![image](https://user-images.githubusercontent.com/6343487/69972512-0975ae00-1522-11ea-8b3c-a62485719e11.png)
`cd Downloads`
![image](https://user-images.githubusercontent.com/6343487/69972573-24e0b900-1522-11ea-9ffc-7a2b49314bdf.png)
`ls`
![image](https://user-images.githubusercontent.com/6343487/69972614-37f38900-1522-11ea-9e7a-8ed0d4fd9035.png)
`cd ..`
![image](https://user-images.githubusercontent.com/6343487/69972638-45107800-1522-11ea-9250-77110afbe9ef.png)
`ls`
![image](https://user-images.githubusercontent.com/6343487/69972666-5194d080-1522-11ea-9dd3-719cedc8f91c.png)

It seems the prompt is somehow not updating properly straight away.

**Comment by BlitzKraft** [comment]
It seems pyenv works/behaves differently than other virtual envs. I am looking into it. 

So, the pyenv is activated on `cd`-ing to the `Downloads` directory? Without any further user input?

**Comment by priestoferis** [comment]
Yes. You can use a hidden file called `.python-version` with a single line content naming the desired virtualenv (or python version) to be loaded and it is set up automatically when changing into the directory. Unfortunately, I have no idea about the actual mechanism. You need to have both pyenv and [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv) to be activated in your .bashrc for this to work (`eval "$(pyenv virtualenv-init -)"` and `eval "$(pyenv init -)"`.

**Comment by BlitzKraft** [comment]
Does powerline-daemon running or not running affect this issue at all? I am not sure if this can be fixed entirely within powerline. virtualenv works, so if pyenv is wrapping around virtualenv, it should work without issues. 

In your example with images, after running `cd ..` the prompt still shows `Downloads` - is this correct? Or was there a mistake somewhere? 

So far, my best guess is that invocation order of powerline and virtualenv and pyenv is causing the issue.

**Comment by priestoferis** [comment]
Yes, the daemon is running (`/usr/bin/python /usr/local/bin/powerline-daemon -q` to be exact) and I did a double check with the behaviour and yes, when exiting Downloads only the environment disappears from the prompt, but still shows Downloads. Thanks for looking into this! Maybe the pyenv guys could have an idea?

**Comment by BlitzKraft** [comment]
Definitely. Raise an issue with them too just to find out how their process of handling the prompt differs compared to that of virtualenv. It will save me some time in figuring out how pyenv does it.

**Comment by priestoferis** [comment]
Ok, so I went over to open an issue, and found [this](https://github.com/pyenv/pyenv-virtualenv/issues/329) issue, which seemed similar enough so I switched the order of pyenv and powerline and in my bashrc and lo and behold it now works. So for anyone wanting to use pyenv virtualenv and powerline, this is the proper order:

```
powerline-daemon -q
source /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh

export PATH="/home/$USER/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

I'm not sure if I should follow this up on pyenv side or not or if there's anything further to be done.

**Comment by BlitzKraft** [comment]
Check and verify that the fix addresses all the aspects of the issue. Current working directory, current venv and that it updates as expected. This is a matter of updating the docs to suggest the right execution order. 

Closing this issue now. Feel free to add more info or re-open this.

**Comment by priestoferis** [comment]
It seems absolutely fine, I also tested creating a new env and setting local and global versions of python to be used and it works as expected.
