### ISSUE TITLE
simple question Change username, Please!

### ISSUE THREAD

**Issue by Nick-us** [powerline/powerline#2059]
I've tried everything, searched and found nothing, very sad!
I just want to change the username for $ e #
The only thing I could do was disappear with the username! But I find no way to modify it!
The default prompt is: username > ~
I want $ > ~

How do I do that?

**Comment by BlitzKraft** [comment]
To be clear, you want a "$" (dollar sign) in place of the username, right?

**Comment by PH111P** [comment]
To obtain a single `$`, try to add the following segment:
``` JSON
{
    "type":                  "string",
    "contents":              "$",
     "draw_soft_divider":    false,
     "highlight_groups":     ["user"]
},
```

**Comment by Nick-us** [comment]
> To be clear, you want a "$" (dollar sign) in place of the username, right?
Yes, exactly as I explained above.

**Comment by Nick-us** [comment]
> To obtain a single `$`, try to add the following segment:
> 
> ```json
> {
>     "type":                  "string",
>     "contents":              "$",
>     "draw_soft_divider":     false,
>     "highlight_groups":      ["user"]
> },
> ```

Yes, that worked! So I added root as follows

```
{
    "type":                  "string",
    "contents":              "$",
    "draw_soft_divider":     false,
    "highlight_groups":      ["user"]
},
{
    "type":                  "string",
    "contents":              "#",
    "draw_soft_divider":     false,
    "highlight_groups":      ["root"]
},
```
But then I noticed that root is blue as the user and not red as the default, any ideas?

**Comment by BlitzKraft** [comment]
There is not "root" highlight_group defined, by default. You either need to create it or use an existing highlight group. `warning:regular` or `critical:failure` are defined by default. One of them might suffice for your use case.

**Comment by Nick-us** [comment]
> There is not "root" highlight_group defined, by default. You either need to create it or use an existing highlight group. `warning:regular` or `critical:failure` are defined by default. One of them might suffice for your use case.

I don't understand what you are explaining!
The default Powerline without changing anything is already colored!
In mine it looks like this:
nick ~
or
root ~

nick is blue
root is red

I just wanna change nick for $
And I want to change root to #
But I want the colors to stay as they were in the default
So I don't understand anything when you talk about groups or something. I'm not changing groups or colors

**Comment by Nick-us** [comment]
**Updating the problem!**
I couldn't do it the normal way. Too many hours of failed attempts. Trying to understand the documentation, my English is not good, and it helps even less.

I think the documentation should have examples of configuration files, that would make it a little easier to understand.

So I did it the only way I can do it. I will explain in detail here so that others who also want to put in place of the written name the symbols.

After installing Powerline and not modifying anything!
I edited the file: /usr/lib64/python3.7/site-packages/powerline/segments/common/env.py

In the last lines notice that I commented on the line I removed
And below the commented line I added a line that tests the condition of the user group to assign the correct symbol in place of the name!

```
	euid = _geteuid()
	return [{
		# 'contents': username,
      'contents': '$' if euid != 0 else '#',
		'highlight_groups': ['user'] if euid != 0 else ['superuser', 'user'],
	}]
```

So this way I got a prompt that displays the symbol with the correct theme color, Blue for user and Red for root.

One advantage I found doing this is that it is modified for all users without having to configure each one separately.

**Comment by Nick-us** [comment]
Just adding more information
For those who have difficulties, I found that to paint red just put

```
         {
            "type":              "string",
            "contents":          "Good Morning!",
            "draw_soft_divider": false,
            "highlight_groups":  ["superuser"]
         },
```
As it seems most people here don't know there are only 2 groups in highlight_groups
user and superuser
user = Blue
superuser = Red

The tip I give to beginners is, look at the program sources, it's easier than reading the user manual, by sources you will later be able to better understand the manual

**Comment by PH111P** [comment]
https://powerline.readthedocs.io/en/latest/configuration/segments/common.html#powerline.segments.common.env.user

"Highlights the user with the superuser if the effective user ID is 0."

"Highlight groups used: superuser or user"
