### ISSUE TITLE
Confused manual with wrong information

### ISSUE THREAD

**Issue by Nick-us** [powerline/powerline#2060]
https://powerline.readthedocs.io/en/latest/configuration/segments.html

> Segments are written in Python, and the default segments provided with Powerline are located in powerline/segments/extension.py

This file does not exist!

**Comment by BlitzKraft** [comment]
That is right. The docs need updating. I believe it is referring to `segments/` directory. Feel free to update the docs and submit a pull request.

**Comment by Nick-us** [comment]
> That is right. The docs need updating. I believe it is referring to `segments/` directory. Feel free to update the docs and submit a pull request.

I do not know how to do it

**Comment by PH111P** [comment]
Note the italics in powerline/segments/_extension.py_: While there is indeed no file named `extension.py`, this is just a placeholder for the existing files for the various extensions. Perhaps it would be better to say that the default segments are all segments defined in `.py` files in the `powerline/segments` folder?

**Comment by BlitzKraft** [comment]
Ok, I too missed the italics until you pointed it out. I second that.

**Comment by Nick-us** [comment]
> Note the italics in powerline/segments/_extension.py_: While there is indeed no file named `extension.py`, this is just a placeholder for the existing files for the various extensions. Perhaps it would be better to say that the default segments are all segments defined in `.py` files in the `powerline/segments` folder?

I believe you are really right, he should not be referring to the file specifically, but to an example file, since in the folder there are files for each language.

But one reason the Powerline Handbook is a little better explained,
because it looks like it was encrypted! kkkkkkkk
