### ISSUE TITLE
multi-line shell prompt issue

### ISSUE THREAD

**Issue by taoyl** [powerline/powerline#2061]
Hello,

I have two working environments, one is in bash, the other is in tcsh. Sometimes I am confused which environment the current terminal is in. So I'd like to add the current shell type (bash or tcsh) to the second line of the promot. 
My default config is shown as below. Anyone can help to tell me how to modify the config json? Thank you very much

My current promot style is as below. I'd like to change the second line to 'bash $>' or 'tcsh $>' depending on current terminal environment.
![image](https://user-images.githubusercontent.com/12044286/70586434-02296100-1c02-11ea-86cf-dd22105a1565.png)

```
{
	"segments": {
		"above": [
			{
				"left": [
					{
						"function": "powerline.segments.shell.mode"
					},
					{
						"function": "powerline.segments.common.net.hostname",
						"priority": 10
					},
					{
						"function": "powerline.segments.common.env.user",
						"priority": 30
					},
					{
						"function": "powerline.segments.common.env.virtualenv",
						"priority": 50
					},
					{
						"function": "powerline.segments.shell.cwd",
						"priority": 10,
						"args": {
							"use_path_separator": true
						}
					},
					{
						"function": "powerline.segments.shell.jobnum",
						"priority": 20
					},
					{
						"function": "powerline.segments.shell.continuation",
                                                "draw_hard_divider": false
					}
				],
				"right": [
					{
						"function": "powerline.segments.shell.last_status"
					},
					{
						"function": "powerline.segments.common.time.date"
					},
					{
						"function": "powerline.segments.common.time.date",
						"name": "time",
						"args": {
							"format": "%H:%M:%S",
							"istime": true
						}
					},
					{
						"function": "powerline.segments.common.vcs.branch",
						"priority": 40
					}
				]
			},
			{
			}
		],
		"left": [
			{
				"function": "powerline.segments.shell.mode"
			},
			{
				"function": "powerline.segments.shell.last_pipe_status",
				"priority": 10
			},
			{
				"function": "powerline.segments.common.time.date",
				"args": {
					"format": "$"
				}
			}
		],
		"right": [
		]
	}
}
```

**Comment by PH111P** [comment]
Hi @taoyl,

I think that there is currently no easy way to display the current binding. Further, as bash and tcsh actually use the same binding internally (hence both using the same config), writing a segment may be somewhat more involved. 

However, as shells define some environment variables (such as `$SHELL`), you may try the following: 
* Add a segment for the relevant variable(s):
``` JSON
{
    "function": "powerline.segments.common.env.environment",
    "args": {
        "variable": "SHELL"
    }
}
```
* If there is no suitable variable, perhaps you need to define one yourself.

**Comment by taoyl** [comment]
@PH111P 
Hi Philip,
Your suggestion is working. 
$SHELL environment variable doesn't work in this case. It always points to the login shell, not the current shell (e.g. switching to tcsh from bash, $SHELL always equals to 'bash').
So I defined a new environment variable 'CURR_SHELL' in my bashrc and cshrc with the following command:
```CURR_SHELL="$(ps -p $$ | awk 'NR==2 {print $NF}')"```

Here is my final prompt. Thanks for your help:)
![image](https://user-images.githubusercontent.com/12044286/70679075-10917e80-1ccf-11ea-81f6-991c84649f6e.png)


> Hi @taoyl,
> 
> I think that there is currently no easy way to display the current binding. Further, as bash and tcsh actually use the same binding internally (hence both using the same config), writing a segment may be somewhat more involved.
> 
> However, as shells define some environment variables (such as `$SHELL`), you may try the following:
> 
> * Add a segment for the relevant variable(s):
> 
> ```json
> {
>     "function": "powerline.segments.common.env.environment",
>     "args": {
>         "variable": "SHELL"
>     }
> }
> ```
> 
> * If there is no suitable variable, perhaps you need to define one yourself.
