### ISSUE TITLE
[Question]Add a custom segment

### ISSUE THREAD

**Issue by taoyl** [powerline/powerline#2063]
Hi,

I tried to add [powerline-gitstatus](https://github.com/jaspernbrouwer/powerline-gitstatus) segments. I followed everything except for the installation step because my machine is unable to connect Internet so that I could not use pip.

The steps I did are as follows:

1. put powerline_gitstatus folder into the segments dir under my powerline install path, i.e. $HOME/powerline/powerline/segments/powerline_gitstatus. The powerline_gitstatus folder contains two python files __init__.py and segments.py
```
$ ls powerline/powerline/segments/powerline_gitstatus/
__init__.py  segments.py
```

2. Add a segment to my config file: ~/.config/powerline/themes/shell/default.json
```
{
	"function": "powerline.segments.powerline_gitstatus.segments.gitstatus",
	"priority": 40
}

```
Here I didn't use the ```"function": "powerline_gitstatus.gitstatus"``` as suggested from [powerline-gitstatus](https://github.com/jaspernbrouwer/powerline-gitstatus) because I think the correct path should be ```powerline.segments.powerline_gitstatus.segments.gitstatus```.

However, powerline-status is not working. Is there anything I missed to add such a custom segment? Thank you.

**Comment by taoyl** [comment]
@BlitzKraft 
Hi BK,  my shell is BASH.
I set log_level to 'DEBUG' and run your suggested command, as shown below. Looks like powerline_gitstatus doesn't work at all, no any debug messages outputted from powerline_gitstatus (powerline_gitstatus does have debug message like ```pl.debug('Executing command: %s' % ' '.join(command))``` in GitStatusSegment class.

![snapshot1](https://user-images.githubusercontent.com/12044286/71062015-6c16ad00-21a4-11ea-8f33-e335f284d3fa.png)

Here is my full configurations. Do you have any idea? Thank you.
```
{
	"segments": {
		"above": [
			{
				"left": [
					{
						"function": "powerline.segments.shell.mode"
					},
					{
						"function": "powerline.segments.common.net.hostname",
						"priority": 10
					},
					{
						"function": "powerline.segments.common.env.user",
						"priority": 30
					},
					{
						"function": "powerline.segments.common.env.virtualenv",
						"priority": 50
					},
					{
						"function": "powerline.segments.powerline_gitstatus.segments.gitstatus",
						"priority": 40
					},
					{
						"function": "powerline.segments.shell.cwd",
						"priority": 10,
						"args": {
							"use_path_separator": true,
							"dir_limit_depth": 200
						}
					},
					{
						"function": "powerline.segments.shell.jobnum",
						"priority": 20
					},
					{
						"function": "powerline.segments.shell.continuation",
                                                "draw_hard_divider": false
					}
				],
				"right": [
					{
						"function": "powerline.segments.shell.last_status"
					},
					{
						"function": "powerline.segments.common.time.date"
					},
					{
						"function": "powerline.segments.common.time.date",
						"name": "time",
						"args": {
							"format": "%H:%M:%S",
							"istime": true
						}
					},
					{
						"function": "powerline.segments.common.vcs.branch",
						"priority": 40
					}
				]
			},
			{
			}
		],
		"left": [
			{
				"function": "powerline.segments.shell.mode"
			},
			{
				"function": "powerline.segments.common.env.environment",
				"args": {
					"variable": "CURR_SHELL"
				}
			},
			{
				"function": "powerline.segments.common.time.date",
				"args": {
					"format": "$"
				}
			}
		],
		"right": [
		]
	}
}
```


> What is your shell? It's possible this might not be a powerline issue. Enable logging (instructions in the powerline docs) and check what's happening.
> Run powerline-render shell [left|right] to check. Provide any error output.

**Comment by BlitzKraft** [comment]
Could you try `powerline-render shell aboveleft`? I suggested a wrong option in my earlier comment. This will print out every configured segment, and *should* print the git status too, disregarding the width of the term. 

I think the combination of term width and the priority settings are not allowing the git_status to display. Please note that the priority is actually a rank. Lower number implies higher preference to be displayed. See [segment priority](https://powerline.readthedocs.io/en/master/configuration/reference.html#config-themes-seg-priority) in the docs.

**Comment by taoyl** [comment]
@BlitzKraft 
Hi BK, this command is useful. It shown an argument error. powerline_gitstatus is working after I fixed it.
Thank you for your tips on how to debug segment issues :)

> Could you try powerline-render shell aboveleft? I suggested a wrong option in my earlier comment. This will print out every configured segment, and should print the git status too, disregarding the width of the term.
> I think the combination of term width and the priority settings are not allowing the git_status to display. Please note that the priority is actually a rank. Lower number implies higher preference to be displayed. See segment priority in the docs.
