### ISSUE TITLE
I followed the install guide but no powerline displayed

### ISSUE THREAD

**Issue by jorijnsmit** [powerline/powerline#2077]
Added `. /Users/jorijnsmit/anaconda3/lib/python3.6/site-packages/powerline/bindings/zsh/powerline.zsh` to `~.zshrc`. No powerline.

Running that command manually I get:
>-bash: local: can only be used in a function
>-bash: integer: command not found
>-bash: /Users/jorijnsmit/anaconda3/lib/python3.6/site-packages/powerline/bindings/zsh/powerline.zsh: line 39: syntax error near unexpected token `_powerline_tmux_setenv'
>-bash: /Users/jorijnsmit/anaconda3/lib/python3.6/site-packages/powerline/bindings/zsh/powerline.zsh: line 39: `		function -g _powerline_tmux_setenv() {'

Running `powerline-daemon -q` I get:
>Traceback (most recent call last):
>  File "/Users/jorijnsmit/anaconda3/bin/powerline-daemon", line 175, in <module>
>    def safe_bytes(o, encoding=get_preferred_output_encoding()):
>  File "/Users/jorijnsmit/anaconda3/lib/python3.6/site-packages/powerline/lib/encoding.py", line 49, in get_preferred_output_encoding
>    or locale.getdefaultlocale()[1]
>  File "/Users/jorijnsmit/anaconda3/lib/python3.6/locale.py", line 562, in getdefaultlocale
>    return _parse_localename(localename)
>  File "/Users/jorijnsmit/anaconda3/lib/python3.6/locale.py", line 490, in _parse_localename
>    raise ValueError('unknown locale: %s' % localename)

What did I miss?

- macOS 10.15.3
- Terminal.app

**Comment by BlitzKraft** [comment]
Do you have `zsh` installed? from the error messages you posted, it seems you are using bash, but sourcing the zsh.

**Comment by jorijnsmit** [comment]
That is the case by default for macOS Catalina, or am I mistaken?

**Comment by BlitzKraft** [comment]
Yes, zsh is the default for catalina. I had to check, was unaware prior to this. However, your log messages clearly show "bash". So, the terminal has been configured to use bash.

It seems you might be following instructions correctly, but the shell is not the right one. Check the docs on the terminal app to change shell to zsh permanently. For a temporary fix, start `zsh` manually in the terminal. Then continue following the instructions for powerline. 

It should work after that or throw a more helpful error message.

**Comment by jorijnsmit** [comment]
You are very right, even though it is the default it wasn't activated yet after my upgrade. This has to be done manually. I did now, through `chsh -s /bin/zsh`.

`powerline-daemon` however still comes back with the same error:
> Traceback (most recent call last):
  File "/Users/jorijnsmit/anaconda3/bin/powerline-daemon", line 175, in <module>
    def safe_bytes(o, encoding=get_preferred_output_encoding()):
  File "/Users/jorijnsmit/anaconda3/lib/python3.6/site-packages/powerline/lib/encoding.py", line 49, in get_preferred_output_encoding
    or locale.getdefaultlocale()[1]
  File "/Users/jorijnsmit/anaconda3/lib/python3.6/locale.py", line 562, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/jorijnsmit/anaconda3/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

**Comment by jorijnsmit** [comment]
Running `locale` returned with `LANG=""`. Added these lines to the top of `~/.zshrc`:
```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```
