### ISSUE TITLE
big space 

### ISSUE THREAD

**Issue by AmirhosseinBayat** [powerline/powerline#2079]
I tried lot of ways in order to solve big space on my konsole.
![Screenshot_20200308_174426](https://user-images.githubusercontent.com/11735490/76164547-17f8e480-6165-11ea-8293-6a2e74643532.png)
currently im using manjaro and python 3.7 on my system.
but the result is different on centos when i used to it, and thereis no big space between command and blinker.
is there any solution? to solve this

**Comment by PH111P** [comment]
It looks like powerline somehow computes the width of the terminal wrong. Would you mind sharing some more information about your configuration (e.g. what shell are you using; did you configure something special)?

**Comment by AmirhosseinBayat** [comment]
I use fish shell, and no special configuration

**Comment by PH111P** [comment]
See https://github.com/powerline/powerline/issues/1514.
Do you per chance use true colors in fish? You can disable true colors by setting 
``` fish
set -g fish_term24bit 0
```
