### ISSUE TITLE
Powerline ignoring tmux config files

### ISSUE THREAD

**Issue by BradLewis** [powerline/powerline#2081]
I am trying to customise my powerline status bar in tmux, but none of the changes I make have an impact. 
I have tried editing the files both in {powerline_root}/config_files/themes and ~/.config/powerline/themes/tmux.
If I run powerline-lint I don't get any errors, however if I deliberately add errors to the config files, powerline-lint will find them. 
I am using tmux 3.0a with iTerm2 3.3.9 on MacOS 10.15.3.

Changes made in the vim config files affect the bar in vim.

**Comment by PH111P** [comment]
Do you perhaps use the `powerline-daemon`? If you do, did you try restarting it?

**Comment by BradLewis** [comment]
I am running `run-shell` 'powerline-daemon -q'` before running `source "powerline_root}/bindings/tmux/powerline.conf"` in my .tmux.conf.
I have also tried killing and restarting the daemon but it doesn't seem to do anything.

**Comment by PH111P** [comment]
`powerline-daemon -q` tries to start a new daemon, it will not kill already running ones. Try `powerline-daemon --replace`.

**Comment by BradLewis** [comment]
Yes that's what I meant about killing it and restarting it. I just tried it again with no result.

**Comment by PH111P** [comment]
Oh sorry I must have overlooked that. Actually, in this case I'm kind of clueless though. Perhaps there is another `tmux` config file flying around somewhere?

Also try running `powerline-render tmux right` in a terminal and check whether that outputs something that corresponds to your (changed) config.

**Comment by BradLewis** [comment]
Yeah there isn't a lot to go off.
`powerline-render tmux left` and `powerline-render tmux right` display what is actually shown in the bar.  
Is there some logging I can look at to determine where it is getting the config from?

**Comment by PH111P** [comment]
In python, try
``` python
from powerline import Powerline
Powerline('tmux').get_config_paths()
```

**Comment by BradLewis** [comment]
I tried that and I get 
`[{powerline-root}/config_files, {home}/.config/powerline]`.

I also get the same result if I change the input from `tmux` to `vim`, and in fact with anything else I enter. That is `Powerline('aaaaa').get_config_paths()` returns the same thing. I don't know if this is expected or not.

**Comment by BradLewis** [comment]
Okay well I'm entirely sure what I did to fix it, but it seems changes made in `{home}/.config/powerline/themes/tmux/default.json` are now working, however anything in `{powerline-root}/config_files/themes/tmux` don't. 

I'll close this now since it works. Thanks for all your help!
