### ISSUE TITLE
Segment `dbus_player` fails to run

### ISSUE THREAD

**Issue by ritiek** [powerline/powerline#2083]
Hi, and thank you all for making powerline! I find it really useful.

I'm trying to use `powerline.segments.common.players.dbus_player` to show the current status for (I think) one of the currently running media players which implements D-Bus interface.

I read the docs on [`powerline.segments.common.players.dbus_player` ](https://powerline.readthedocs.io/en/master/configuration/segments/common.html#powerline.segments.common.players.dbus_player), and so I added this to my `powerline/themes/tmux/default.json`:
```json
...
    {
        "function": "powerline.segments.common.players.dbus_player",
        "name": "player",
        "args": {
            "player_name": "player"
        }
    }
...
```

but this seems to be failing with the resultant traceback:

```shell
$ powerline-daemon --foreground

2020-03-12 23:56:52,164:ERROR:tmux:player:Exception while computing segment: _get_dbus_player_status() missing 4 required positional arguments: 'bus_name', 'player_path', 'iface_prop', and 'iface_player'
Traceback (most recent call last):
  File "/home/ritiek/.local/lib/python3.6/site-packages/powerline/segment.py", line 173, in process_segment
    contents = segment['contents_func'](pl, segment_info)
  File "/home/ritiek/.local/lib/python3.6/site-packages/powerline/segment.py", line 414, in <lambda>
    contents_func = lambda pl, segment_info: _contents_func(pl=pl, **args)
  File "/home/ritiek/.local/lib/python3.6/site-packages/powerline/segments/common/players.py", line 47, in __call__
    func_stats = self.get_player_status(**kwargs)
TypeError: _get_dbus_player_status() missing 4 required positional arguments: 'bus_name', 'player_path', 'iface_prop', and 'iface_player'
```

----------

On the otherhand, I also tried with [`powerline.segments.common.players.spotify`](https://powerline.readthedocs.io/en/master/configuration/segments/common.html#powerline.segments.common.players.spotify) and it seems to work perfectly fine.

**Comment by PH111P** [comment]
Hi @ritiek,
there is a small error in your configuration: The `dbus_player` segment requires some specific dbus bus names to function properly (and sadly, these bus names are usually different for every application).

As an example, here is the `dbus_player` segment configured to work with `vlc`:
``` JSON
            {
                "function":             "powerline.segments.common.players.dbus_player",
                "name":                 "vlc",
                "args": {
                    "format":           "{state_symbol}{artist} — {title} ({album})",
                    "player_name":          "vlc",
                    "bus_name":             "org.mpris.MediaPlayer2.vlc",
                    "player_path":          "/org/mpris/MediaPlayer2",
                    "iface_prop":           "org.freedesktop.DBus.Properties",
                    "iface_player":         "org.mpris.MediaPlayer2.Player"
                }
            },

```
Please refer to the docs for additional args: [dbus_player segment documentation](https://powerline.readthedocs.io/en/master/configuration/segments/common.html#powerline.segments.common.players.dbus_player)

**Comment by ritiek** [comment]
Thanks for the quick response! Your example works nicely for me.

> (Looking at the specific docs again, they seem to be kind of lackluster indeed...)

Yup. It isn't immediately apparent that one needs to pass these additional arguments to this specific segment (at least wasn't to me).

Anyway, it seems like one needs to explicitly specify the player they wish to access. So, I changed the code a bit so it would automatically select the 1st media player in the list of available media players which implement D-Bus interface when none of these arguments have been passed, in my fork [ritiek/powerline@assume-dbus-player](https://github.com/ritiek/powerline/tree/assume-dbus-player). Would you be interested in a for PR this?

**Comment by PH111P** [comment]
Looks good, I'd be happy to merge it!
