### ISSUE TITLE
Troubleshooting with installing powerline-status

### ISSUE THREAD

**Issue by mathildebuenerd** [powerline/powerline#2085]
I have troubleshoot making Powerline status bar work.

I have installed Powerline following the instructions. I have also installed the SourceCodePro Powerline font. I think the installation of powerline is successful because when I type `powerline` it prints `Must provide at least one argument.`. 

But the installation of powerline-status is not successful.

```bash
powerline-status -V
zsh: command not found: powerline-status
```

I have followed the instructions and added these lines to my `.zshrc`. 
* The `bin` folder contains several powerline commands such as `powerline`, `powerline-config`, `powerline-daemon` etc... but no `powerline-status`. 
* The `site-packages` folder contains the `powerline` and `powerline_status-2.7.dist-info` folders. 

```
export PATH=$PATH:$HOME/Library/Python/2.7/bin
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /Users/myusername/Library/Python/2.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh
```

I have no error when I open Iterm2.

<img width="266" alt="Screenshot 2020-03-13 at 08 44 01" src="https://user-images.githubusercontent.com/22640631/76600241-cf477f80-6506-11ea-9793-a47cdfe3c4bf.png">

I use zsh and Iterm 2.
Mac OS Catalina 10.15.3

Please tell me which more information should I provide. Thanks!

**Comment by PH111P** [comment]
There is no `powerline-status` command, so it's not an error if it doesn't exist.

Regarding your problems getting powerline to work, it looks like you're including the binding for bash instead of the one for zsh. Try to replace the last line you added with

``` zsh
. /Users/myusername/Library/Python/2.7/lib/python/site-packages/powerline/bindings/zsh/powerline.zsh
```

**Comment by mathildebuenerd** [comment]
Thank you it solved the problem! Thanks also for the explaination
