### ISSUE TITLE
Git branch not showing in tmux

### ISSUE THREAD

**Issue by matanras** [powerline/powerline#2086]
I have the following theme:

```
  1 {
  2         "segments": {
  3                 "right": [
  4                         {
  5                                 "function": "powerline.segments.common.vcs.branch",
  6                                 "priority": 40
  7                         },
  8                         {
  9                                 "function": "powerline.segments.common.sys.uptime",
 10                                 "priority": 50
 11                         },
 12                         {
 13                                 "function": "powerline.segments.common.sys.system_load",
 14                                 "priority": 50
 15                         },
 16                         {
 17                                 "function": "powerline.segments.common.time.date"
 18                         },
 19                         {
 20                                 "function": "powerline.segments.common.time.date",
 21                                 "name": "time",
 22                                 "args": {
 23                                         "format": "%H:%M",
 24                                         "istime": true
 25                                 }
 26                         },
 27                         {
 28                                 "function": "powerline.segments.common.net.hostname"
 29                         }
 30                 ]
 31         }
 32 }
```

This is basically config_files/themes/tmux/default.json with the addition of powerline.segments.common.vcs.branch which I've copied from the shell's default_leftonly.json.
The problem is that everything shows except for the vcs info. The vcs info does show using the shell binding with the theme default_leftonly, and the command `powerline tmux right` produces correct output. Also, adding `set -g status-right "#[fg=colour250,bg=colour236,nobold,noitalic,nounderscore] my_branch_name"` in tmux.conf correctly displays the segment.
Also, it appears that the segment does show if I run both the bash binding from bashrc and the tmux binding from tmux conf, and correctly update when I enter/leave a git repo folder.

**Comment by PH111P** [comment]
You may try to restart the powerline-daemon (via `powerline-daemon --replace`). Also check out https://github.com/powerline/powerline/issues/2081 or https://github.com/powerline/powerline/issues/1934.

**Comment by matanras** [comment]
`powerline-daemon --replace` worked! I've tried to run that command previously and it didn't work, perhaps it had something to do with multiple tmux sessions open. Thank you.

**Comment by matanras** [comment]
An update: The VCS info was showing when I was using both the shell and the tmux binding at the same time. I've removed the binding from bashrc, and the vcs info in the tmux status line stopped showing.
