### ISSUE TITLE
Powerline won`t start after adding the lines to .bashrc

### ISSUE THREAD

**Issue by geerizzle** [powerline/powerline#2087]
So I just installed powerline on my Arch Linux x86_64 and after I added the needed lines form the Arch Wiki, I got the following error:

`Traceback (most recent call last):
  File "/usr/bin/powerline-daemon", line 23, in <module>
    from powerline.shell import ShellPowerline
ModuleNotFoundError: No module named 'powerline'
bash: /usr/share/powerline/bindings/bash/powerline.sh: No such file or directory
`
And as i tried to navigate to /bindings directory the bash returned that the directory does not exist, even tho it was dispalyed when running an 'ls', but it was colored red. When I got the type of the directory, bash returned the following: 
'bindings: broken symbolic link to /usr/lib/python3.8/site-packages/powerline/bindings'

Anyone got an idea what might be the problem? Thanks!

**Comment by PH111P** [comment]
Try to replace `/usr/share/` with `/usr/lib/python3.8/site-packages/`.

**Comment by geerizzle** [comment]
> Try to replace `/usr/share/` with `/usr/lib/python3.8/site-packages/`.

I tried it, and when i added that to the .bashrc I got the same error. The line i addef was 
`. /usr/lib/python3.8/site-packages/powerline_shell/powerline.sh`

**Comment by PH111P** [comment]
Does the folder `/usr/lib/python3.8/site-packages/` exist? Are you using `bash` (and not `zsh`, `fish` or any other shell?)

**Comment by geerizzle** [comment]
Yea, the folder exists and i am using bash

**Comment by PH111P** [comment]
I just realized that your command is still not totally correct; the line to add should look like this:
`. /usr/lib/python3.8/site-packages/powerline/bindings/bash/powerline.sh`.
If that doesn't work, verify that `/usr/lib/python3.8/site-packages/powerline` exists; you can also try `powerline-render shell left` (If this command fails, your powerline installation is erroneous).
