### ISSUE TITLE
Can I use 2 seperate fonts for status bar and the file body?

### ISSUE THREAD

**Issue by in2Rafi** [powerline/powerline#2088]
I would like to use DejaVu Sans Mono font the gVim status bar. Iosevka for gVim file body. Is this possible? If so what should I put in my .vimrc file?

**Comment by BlitzKraft** [comment]
I do not think it is possible, but I could be wrong. As far as I know, gvim still uses ncurses, and it is not possible to use multiple fonts in ncurses.
