### ISSUE TITLE
Add `powerline.__version__`

### ISSUE THREAD

**Issue by fgrosshans** [powerline/powerline#2093]
Having `powerline.__version__` is pretty standard and would simplify some external config files and work-arounds known bugs. 

For example, ipython >= 7.0 is supported by powerline 2.8 but not by 2.7. To test for this in my current config file, I need to use a `try:`-`except:` construction, which is ugly.

**Comment by PH111P** [comment]
I strongly agree; will fix this.

**Comment by PH111P** [comment]
Done in 3dc174919d4bbb3260ef2f7e8f46b448034e6454.

**Comment by fgrosshans** [comment]
I’ve never had a bug report fixed so quickly !
