### ISSUE TITLE
Segment virtualenv isn't always as useful as I'd like...

### ISSUE THREAD

**Issue by dragonpaw** [powerline/powerline#2094]
I work on a lot of python projects, and a general standard with all of them seems to be a $PROJECT/.venv directory for that's $PROJECT's virtualenv. I move between projects a lot, and have to remember to `deactivate; activate` each time I do. Which of course I sometimes forget to do...

Unfortunately this means that my prompt is always:

`ash > (e) .venv > ~ > src > project`

Which has left me sometimes wondering which of the .venv's is active (since I've got like 6 of them.) And so I'm always second guessing myself about if I've changed or not.

Ideally, I think it'd be nice if instead of just the raw basename of the env directory being the segment, it was nice enough to show one directory level higher up if the basename is `.venv`. This way I'd get `(e) project` instead.

(Yes, I can, and likely will, write my own segment for this, but it seems a common enough use case to perhaps change the stock segment.)

**Comment by BlitzKraft** [comment]
Not discounting the merit of the idea. However, when in doubt, using `which python[3]` will output the full path to the executable.
