### ISSUE TITLE
Can't get solarized colorscheme to work in Ubuntu 20.04

### ISSUE THREAD

**Issue by bynare** [powerline/powerline#2099]
I've installed powerline via apt and this is my current config in `.config/powerline`:
```
{
	"common": {
                "term_truecolor": true
        },
	"ext": {
		"shell": {
			"colorscheme": "solarized"
		}
      }
}
```
This is what my bash shell prompt look like currently:
![Screenshot from 2020-05-27 09-53-11](https://user-images.githubusercontent.com/1852531/82953977-ebd05f80-9fff-11ea-9f33-0be74b03d1aa.png)

^ that is not the solarized colorscheme right?
I've rebooted, but no change...

Am I missing something here, or is this a bug?

Thanks!

**Comment by PH111P** [comment]
Looks solarized to me, though.
You can check the solarized colors here: [colors.json](https://github.com/powerline/powerline/blob/develop/powerline/config_files/colors.json ) (anything starting with `solarized`) any how they are used here: [solarized.json](https://github.com/powerline/powerline/blob/develop/powerline/config_files/colorschemes/solarized.json).
In particular, note 
```JSON
"user":                       { "fg": "solarized:base3", "bg": "solarized:blue", "attrs": ["bold"] },
"cwd":                        "information:additional",
"cwd:current_folder":         "information:regular",
"branch":                     { "fg": "solarized:base1", "bg": "solarized:base02", "attrs": [] },
```

**Comment by bynare** [comment]
Thanks for your help @PH111P - it is working indeed ;)
