### ISSUE TITLE
Tmux + fish returns wrong cwd

### ISSUE THREAD

**Issue by Pingger** [powerline/powerline#2101]
Hi,

I thought I'd migrate from tmux-powerline, but it seems there is a regression from tmux-powerline:
When using `fish` inside a `tmux` session, the tmux-powerline fails to detect changes in the `cwd`. This causes all segments requiring the `cwd` to break. (like `powerline.segments.common.env.cwd`, `powerline.segments.common.vcs.branch`,...)

Any idea what I can do to fix this issue?
- No not using `tmux` is not an option
- No not using `fish` is not an option

I'm using powerline from the debian package repositories. The installed version is **2.7.3**
fish and tmux are also from the debian package repositories with versions **3.1.2-1** and **3.1b-1** (respectively)

Greetings.

**Comment by PH111P** [comment]
Perhaps the discussion in https://github.com/powerline/powerline/issues/467 can yield some insights. As I understand it, the cwd segment currently just doesn't work in tmux directly.

**Comment by Pingger** [comment]
So we have a workaround for >5 years ... 
The easy way would be to just use this: `#{pane_current_path}` this expands to the path of the current tmux pane. Unfortunately I don't really do python ... Throw java/c/bash or even haskell at me, but for some reason python and me don't really mix.

The command to be run within the tmux session would be `tmux display -p "#{pane_current_path}"`. which is the equivalent of `echo $PWD`

I hope that helps.

Greetings

**Comment by abujalski** [comment]
@Pingger you can try this https://github.com/abujalski/powerline-segments

It works for me, hope it will work for you.

**Comment by StopMotionCuber** [comment]
This can be closed as #2127 got merged
