### ISSUE TITLE
Cannot use `cpu_load_percent` segment in bash prompt

### ISSUE THREAD

**Issue by nkakouros** [powerline/powerline#2102]
I have this in my `~/.config/powerline/themes/shell/default_leftonly.json`:

```
      {
        "function": "powerline.segments.common.sys.cpu_load_percent",
        "priority": 80
      },
```

But the cpu segment does not show. The rest of the segments show ok. I tried the `system_load` segment and it works ok. 

`powerline-lint` shows no errors.

The `psutil` module is installed.

I also run `python` and imported the segment:

```
>>> from powerline.segments.common.sys import cpu_load_percent
>>> cpu_load_percent(None)
[{'contents': '5%', 'gradient_level': 4.9, 'highlight_groups': ['cpu_load_percent_gradient', 'cpu_load_percent']}]
```

which shows me that it works ok.

I also tried a checkout of master for powerline.

But the segment still does not show in the prompt. What am I doing wrong?

**Comment by nkakouros** [comment]
I am using the solarized colorscheme and the relevant highlight groups (and many others) are missing.

**Comment by PH111P** [comment]
Did you try to restart the powerline-daemon?

If you did, perhaps the segment is hidden because powerline deems the horizontal space in the terminal to be insufficient. Try to remove the `priority` parameter.
