### ISSUE TITLE
How hard would it be to have a right prompt in bash?

### ISSUE THREAD

**Issue by nkakouros** [powerline/powerline#2103]
According to [this](https://superuser.com/questions/187455/right-align-part-of-prompt/1203400#1203400), one could implement a right hand prompt for bash. 

How hard would it be to have powerline produce sth like that? 

What part of the code should I need to look into if I tried to add support for sth like that?

**Comment by PH111P** [comment]
This should be trivial. Trivial as in, it is already implemented. Check out [the manual](https://powerline.readthedocs.io/en/latest/configuration.html). Also check out [the default shell theme](https://github.com/powerline/powerline/blob/develop/powerline/config_files/themes/shell/default.json) that has this functionality...

**Comment by nkakouros** [comment]
I had actually read #1149 that says it was not going to be supported. I also tried the default shell theme but no right prompt is showing. Is this an error on my side?

**Comment by PH111P** [comment]
Oh, indeed, you are correct, sorry for the confusion. Nevertheless, I think that implementing this should not be too hard: Take a look at [bindings/bash/powerline.sh](https://github.com/powerline/powerline/blob/develop/powerline/bindings/bash/powerline.sh) and specifically `_powerline_setup_prompt`. The powerline itself supports a RHS, you just need to call `_powerline_local_prompt` with `right` as the first argument.

**Comment by TomerGodinger** [comment]
I'm not sure if I should open an issue for this, but while the merged commit does add this feature, if I type something and then press Backspace, the parts on the right side disappear.

**Comment by digeomel** [comment]
Which version of Bash has this been fixed in? I'm on 5.1.16 on Ubuntu 22.04.5 LTS and I don't see it.
