### ISSUE TITLE
where to add configurations

### ISSUE THREAD

**Issue by pengu10** [powerline/powerline#2105]
I added 
"dir_limit_depth" : 1 
to "/home/admin/.config/powerline/themes/shell/default.json"

it looks like this:
```
/home/admin/.config/powerline/themes/shell/default.json
{
"function": "powerline.segments.shell.cwd",              
"priority": 10,
"dir_limit_depth":1
}

```
but nothing happens in my shell

https://i.imgur.com/x2wNW1P.png

what am i doing wrong?

**Comment by PH111P** [comment]
You were missing an "args". See https://powerline.readthedocs.io/en/master/configuration/reference.html#themes
``` JSON
{
"function": "powerline.segments.shell.cwd",              
"priority": 10,
"args": {
"dir_limit_depth":1
}
}
```
