### ISSUE TITLE
No activation instructions provided

### ISSUE THREAD

**Issue by MagnusBrzenk** [powerline/powerline#2107]
I'm new to this tool. I just tried installing with Vundle. I don't see any power bar. I'm left to wonder if I need to apply some activation command, or if my install was unsuccessful. So please supply an activation command somewhere early and obvious in your documentation, or a statement to the effect of "Now that it'a installed, you can expect to find the power bar next time you open vim"

**Comment by PH111P** [comment]
There is a manual here: https://powerline.readthedocs.org/en/latest/. It has a TOC (which is not perfect, though, I agree).

In particular, please take a look at https://powerline.readthedocs.io/en/latest/usage/other.html#vim-statusline. 
As it is written there, you should activate powerline via `call vam#ActivateAddons(['powerline'])`. There is also https://powerline.readthedocs.io/en/latest/troubleshooting.html#vim-issues with a list of common problems and fixes for them.

**Comment by MagnusBrzenk** [comment]
I added the line `call vam#ActivateAddons(['powerline'])` to my .vimrc file and now I just get the following error when I start up vim:

```
line   94:
E117: Unknown function: vam#ActivateAddons
```

**Comment by MagnusBrzenk** [comment]
@PH111P Could you please clarify how/where I am supposed to apply `call vam#ActivateAddons(['powerline'])`? I tried adding it to my vimrc file, and tried running it as a command in the vim terminal. Both times I get the error message "E117: Unknown function: vam#ActivateAddons"

A quick google suggests that this command requires another plugin -- "https://github.com/MarcWeber/vim-addon-manager" -- but that is not specified in the requirements of your documentation. Fairly lost at this point. Would appreciate it if you'd come down to my noob level.

**Comment by PH111P** [comment]
*sigh*, indeed that line only seems to work with vim addon-manager; the correct line should be `Bundle 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}` (no guarantee though), sorry I made an off-by-one error while copying the code from the manual.

Again, please read the relevant parts of the manual: https://powerline.readthedocs.io/en/latest/usage/other.html#vim-statusline.
