### ISSUE TITLE
Powerline is not reading /home/user/.config/powerline/config.json changes

### ISSUE THREAD

**Issue by mesa123123** [powerline/powerline#2114]
**Overview**
I'm having trouble configuring the powerline to respond to color configuration changes I'm making in the ~/.config/powerline/config.json file.

I've tried setting the XDG_CONFIG_HOME & XDG_CONFIG_DIRS to the ~/.config directory to no avail

I feel like I've boiled down the issue to the programme only reading the /usr/share/powerline/config_files directory because whenever I change the config.json in there to config.json.bak the terminal gives me this message:

![image](https://user-images.githubusercontent.com/22901019/88988988-a21d3180-d32e-11ea-97c8-dd31e9c1eb06.png)
 
and there is a perfectly good config.json in the ~/.config/powerline directory
Powerline can work on my system though because whenver I change the /usr/share/powerline/config_files/config.json file, the color scheme on the terminal reacts

![image](https://user-images.githubusercontent.com/22901019/88989133-063ff580-d32f-11ea-93bd-d186176785bf.png)

(svim is an alias for sudo vim btw)

Sys, info
Win10 - 1909
Terminal - Windows Terminal
WSL Distro - Ubuntu 20.04
Powerline Version - 2.7 (the one available through sudo apt install powerline)

**Comment by mesa123123** [comment]
Ok so it has something to do with the way the files are merging I believe?

**Comment by PH111P** [comment]
Please try the following (if you haven't done so yet):
* Try to restart any running `powerline-daemon` after changing your `.config/powerline/config.json` file (`powerline-daemon --replace`).
* Verify that your config files are valid (using `powerline-lint`)
* In python, check (and report) the output of 
``` python
from powerline import Powerline
Powerline('shell').get_config_paths()
``` 

(Also, please don't set the XDG variables manually, see here: https://github.com/powerline/powerline/issues/1964)

**Comment by mesa123123** [comment]
Yeah I managed to get it working eventually, sorry I should have closed this issue sorry.
I think this is more a problem with documentation....
I feel like it should be more clear in the docs that the configuration folders go through a kind of syncing phase when you run `powerline-daemon --replace`
