### ISSUE TITLE
iTunes segment not working

### ISSUE THREAD

**Issue by leranjun** [powerline/powerline#2117]
I'm running macOS 10.14.6, with powerline in my Terminal.app.

I tried to add the iTunes segment on the right but well, no luck.

`~/.config/powerline/themes/shell/default.json`

```json
{
    "segments":{
        "left":[
            {
                "function":"powerline.segments.shell.mode"
            },
            {
                "function":"powerline.segments.common.net.hostname",
                "priority":10
            },
            {
                "function":"powerline.segments.common.env.virtualenv",
                "priority":50
            },
            {
                "function":"powerline.segments.shell.cwd",
                "priority":10
            },
            {
                "function":"powerline.segments.shell.jobnum",
                "priority":20
            },
            {
                "function":"powerline_gitstatus.gitstatus",
                "priority":40
            }
        ],
        "right":[
            {
                "function":"powerline.segments.shell.last_pipe_status",
                "priority":10
            },
            {
                "function":"powerline.segments.common.vcs.stash",
                "priority":50
            },
            {
                "function":"powerline.segments.common.vcs.branch",
                "priority":40
            },
            {
                "function":"powerline.segments.common.players.itunes",
                "name":"player"
            }
        ]
    }
}
```

(And weirdly, it doesn't seem to **merge** the configs in my home folder and the main configs, but rather **replace** the main configs with my own ones, so I had to manually copy the whole thing)

`powerline-lint`

```
Error while checking theme (key /segments/right/list item 3/function)
found highlight groups list (player_fallback, player) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/fzhang/.config/powerline/themes/shell/default.json", line 42, column 63:
     ... werline.segments.common.players.itunes",
                                         ^

Error while checking theme (key /segments/right/list item 3/function)
found highlight group player_fallback not defined in the following colorschemes: solarized, default

Error while checking theme (key /segments/right/list item 3/function)
found highlight group player not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 3/function)
found highlight groups list (player_play, player) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/fzhang/.config/powerline/themes/shell/default.json", line 42, column 63:
     ... werline.segments.common.players.itunes",
                                         ^

Error while checking theme (key /segments/right/list item 3/function)
found highlight group player_play not defined in the following colorschemes: solarized, default

Error while checking theme (key /segments/right/list item 3/function)
found highlight group player not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 3/function)
found highlight groups list (player_pause, player) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/fzhang/.config/powerline/themes/shell/default.json", line 42, column 63:
     ... werline.segments.common.players.itunes",
                                         ^

Error while checking theme (key /segments/right/list item 3/function)
found highlight group player_pause not defined in the following colorschemes: solarized, default

Error while checking theme (key /segments/right/list item 3/function)
found highlight group player not defined in the following colorschemes: solarized

Error while checking theme (key /segments/right/list item 3/function)
found highlight groups list (player_stop, player) with all groups not defined in some colorschemes
(Group names were taken from function documentation.)
  in "/Users/fzhang/.config/powerline/themes/shell/default.json", line 42, column 63:
     ... werline.segments.common.players.itunes",
                                         ^

Error while checking theme (key /segments/right/list item 3/function)
found highlight group player_stop not defined in the following colorschemes: solarized, default

Error while checking theme (key /segments/right/list item 3/function)
found highlight group player not defined in the following colorschemes: solarized
```

`powerline shell right` returns the correct thing if I play some music on iTunes, but it doesn't show up in the command line.

I don't know anything Python, so I'm not sure what the problem is. Any help?

**Comment by PH111P** [comment]
Some things you can try:
* Restart the powerline-daemon
* (To also get rid of the linter errors): Add definitions for the highlight groups `player_stop`, `player_pause`, `player_play`, `player_fallback` (perhaps just copy and adjust the line starting with `"player"` in your `.config/colorschemes/default.json` configuration file.

**Comment by leranjun** [comment]
> * Restart the powerline-daemon

I did, several times.

> Add definitions for the highlight groups `player_stop`, `player_pause`, `player_play`, `player_fallback`

OK, I added those to `default.json` and `solarized.json`, and now the linter is fixed. But it's still not working :(

**Comment by PH111P** [comment]
Ah sorry for the earlier confusion, I just realized that you are trying to add the iTunes segment to your shell. Currently, the shell plugin does not update itself (that is, you have to manually reload to see any changes). In short, this means that segments like the player segment or the date/time segment won't properly work in a shell (and that is indeed intended / not really possible any other way, as far as I know).

**Comment by leranjun** [comment]
Roger that, thanks for the reply.

Any ideas on why it won't merge though?

**Comment by PH111P** [comment]
That depends on what you mean with "it won't merge".

* In your local config file, you define the `"segments"` array, this overwrites the default `"segments"` array for shells (but it does not change the default config for other plugins, the color schemes etc). (This is indeed the intended behavior, as it is not clear how to merge two different `"segments"` arrays: Should the new segments appear before or after already existing ones? What about segments appearing in both files? etc)

* What is merged however, are default values for specific segments: Say segment `a` has the arguments `b` and `c` with the default values `b = 4` and `c = 7`; if you now locally specify only the argument `c := 1`, the default argument for `b` is merged and the segment is called with the arguments `b = 4, c = 1`. (Again, the values for the arguments themselves are not merged but overwritten).

**Comment by leranjun** [comment]
Oh, so only arguments are merged in this case?

**Comment by PH111P** [comment]
Yes.
