### ISSUE TITLE
[Windows] IPython powerline [char]0xe0b0 (arrows) not showing.

### ISSUE THREAD

**Issue by rekaerst** [powerline/powerline#2119]
```
Environment : Windows_NT 10.0.19041.388 amd64
Python: Python 3.8.5 [MSC v.1924 64 bit (AMD64)] on win32
IPython: IPython 7.16.1
Powerline: powerline-status    2.8.1.dev9999-git.b-8c6874d85512318966b83d8bfebfef8d1cfaca1b
```
Configuration:
```python
from powerline.bindings.ipython.since_7 import PowerlinePrompts
c = get_config()
c.TerminalInteractiveShell.simple_prompt = False
c.TerminalInteractiveShell.prompts_class = PowerlinePrompts
```
IPython powerline [char]0xe0b0 not showing on Windows  ![image](https://user-images.githubusercontent.com/52642831/91019365-75092980-e623-11ea-8468-7996119c433a.png)
On Windows:
![image](https://user-images.githubusercontent.com/52642831/91019078-075cfd80-e623-11ea-94ee-aceea6bc8e9a.png)

It should be like this: (On Ubuntu)
![image](https://user-images.githubusercontent.com/52642831/91019535-b8fc2e80-e623-11ea-93b6-267005a922bf.png)

**Comment by BlitzKraft** [comment]
Did you check if arrow is being printed, but rendering in the same color as the background? Tried a different terminal?

One more test - select/copy the text with a mouse, with ipython running, and paste it in a text file. This is to confirm that the arrow is not being printed at all.

**Comment by rekaerst** [comment]
nothing is there.

**Comment by rekaerst** [comment]
```
[9.342852, "o", "\u001b[38;2;97;175;239m\u001b[8;4Hipython\u001b[?25h"]
[9.68674, "o", "\u001b[m"]
[9.707093, "o", "\r\n"]
[10.340829, "o", "\u001b[25l\u001b[HPowerShell 7.0.3\u001b[K\r\nCopyright (c) Microsoft Corporation. All rights reserved.\u001b[K\r\n\u001b[K\r\nhttps://aka.ms/powershell\u001b[K\r\nType 'help' to get help.\u001b[K\r\n\u001b[K\u001b[38;2;138;138;138m\r\n╭─\u001b[30m\u001b[107m  \u001b[97m\u001b[44m  ~ \u001b[34m\u001b[49m\u001b[m\u001b[88X\u001b[38;2;38;38;38m\u001b[88C\u001b[92m\u001b[48;2;38;38;38m ✔ \u001b[97m\u001b[38;2;38;38;38m\u001b[107m 11:50:32  \u001b[38;2;138;138;138m\u001b[49m─╮\r\n╰─\u001b[m \u001b[38;2;97;175;239mipython\u001b[m\u001b[98X\u001b[38;2;38;38;38m\u001b[98C\u001b[93m\u001b[48;2;38;38;38m 100%  \u001b[38;2;138;138;138m\u001b[49m─╯\u001b[m\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\u001b[9;1H\u001b[?25h"]
[10.352778, "o", "\u001b[25lPython 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]\r\nType 'copyright', 'credits' or 'license' for more information\u001b[24X\r\nIPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.\u001b[17X\u001b[13;1H\u001b]0;IPython: C:Users/Ubuntu\u0007\u001b[?25h"]
[10.371792, "o", "\u001b[25l\u001b[?7l\u001b[?7h\u001b[100m In [\u001b[97m1\u001b[39m] \u001b[90m\u001b[49m \u001b[1m\u001b[94m \u001b[m\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\u001b[13;11H\u001b[?25h"]
[11.458108, "o", "\u001b[25l\u001b[?7l\u001b[?7h\u001b[90m\r In [1]  \u001b[1m \u001b[22m\u001b[K\u001b[m\u001b[108C \r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\r\n\u001b[K\u001b[14;1H\u001b[?25h"]
[11.478415, "o", "Do you really want to exit ([y]/n)? "]
[12.733428, "o", "y"]
[13.097695, "o", "\r\n"]
[13.20829, "o", "\u001b]0;Administrator: C:\\Windows\\system32\\conhost.exe\u0007"]

```
This is the raw output of my terminal and those s are arrows.
![image](https://user-images.githubusercontent.com/52642831/91382376-301c0780-e85c-11ea-8a6f-38d2f7e262cb.png)

**Comment by PH111P** [comment]
This could be a problem related to the LOCALE being used in ipython; in particular make sure that the LOCALE for ipython includes "UTF-8".

**Comment by rekaerst** [comment]
Where should I set the LOCALE variable?

**Comment by PH111P** [comment]
What is the output of the command `locale`?
(It should look like this (the UTF-8 part is the important part):
```
LANG=en_US.UTF-8
LC_[...]="en_US.UTF-8"
...
```)

**Comment by rekaerst** [comment]
```
 C:\Users\Ubuntu>locale
'locale' is not recognized as an internal or external command,
operable program or batch file.
```
This is not a Linux program. I am on Windows

**Comment by PH111P** [comment]
That may be part of the problem. I think the following happens: (The ipython binding for) powerline does not recognize that your terminal supports unicode and returns the default (non-unicode) theme, which lacks `0xe0b0` (and any other non-ASCII characters).

(Considering that it does seem to work in your shell, this could be an ipython problem; but confirming that the locale is the problem would be a first step towards confirming my theory. Alas, `locale` doesn't seem to work on Windows, sorry for that. Perhaps there is some way to check whether you have Unicode support? Do the variables `LANG`, `LC_ALL` exist?)

**Comment by rekaerst** [comment]
Windows seems doesn't have env variables like LANG and LC_ALL. The closest thing is utf-8 and region settings.
![image](https://user-images.githubusercontent.com/52642831/91582004-cf86ea80-e981-11ea-9dc4-11860c73cb4b.png)
It's very odd that IPython can't display those arrows when the shell can display them
![image](https://user-images.githubusercontent.com/52642831/91583105-4c669400-e983-11ea-8551-7cd6f8fb4724.png)

**Comment by PH111P** [comment]
In ipython, try 
``` python
from powerline.lib.encoding import get_preferred_output_encoding
get_preferred_output_encoding( )
```

If the result does not start with `utf` (or `ucs`), ipython thinks that your terminal does not support Unicode.

**Comment by PH111P** [comment]
Looking at the source of `get_preferred_output_encoding`, it falls back to the following code when no LC_* variable are present:
`locale.getdefaultlocale()[1] or 'ascii'`, so the output of `locale.getdefaultlocale()` would also be interesting.

**Comment by PH111P** [comment]
Also, looking at https://github.com/powerline/powerline/issues/2071, perhaps your python locale needs some extra configuration.

**Comment by rekaerst** [comment]
Thanks for the hint 
Output of get_preferred_output_encoding( ) and locale.getdefaultlocale() :
```python
 In [1]   from powerline.lib.encoding import get_preferred_output_encoding

 In [2]   get_preferred_output_encoding()
 Out[2]   'cp1252'

 In [3]   import locale

 In [4]   locale.getdefaultlocale()
 Out[4]   ('en_US', 'cp1252')
```

**Comment by PH111P** [comment]
Ok, that confirms my suspicion, then. What you can try: A quick search suggests that `locale.setlocale(locale.LC_ALL, en.UTF-8)` may change the python locale also on Windows; this should be called before the Powerline object is constructed, so you can try to add it to your ipython config.

**Comment by rekaerst** [comment]
that didn't work 
![image](https://user-images.githubusercontent.com/52642831/91631311-46b49100-ea0b-11ea-9edf-b0cddc16cd7a.png)

**Comment by PH111P** [comment]
Do you have a powerline-daemon running? Does it work if you stop the daemon?
(In any case, just to make sure, you are running powerline also in the shell right? If the powerline-daemon uses the wrong locale, then that _should_ also affect the powerline in the shell, but the powerline in the shell seems to work just fine, weird...)

**Comment by rekaerst** [comment]
Sorry, I forgot to mention that the powerline theme in my shell(Powershell and windows cmd) is just a pure shell script profile . I am not using powerline-daemon in my shell.

**Comment by PH111P** [comment]
Ok, this could be a Windows problem then (although to confirm this, one would need to check whether the other powerline bindings are really also affected).

(Perhaps changing powerline to just assume that unicode is available would be the overall better solution to get rid of any locale-related problems altogether...)

**Comment by rekaerst** [comment]
Is there any way to debug ipython?

**Comment by PH111P** [comment]
Ok, I looked at the relevant source again, and here is what I think is happening:

``` python
def get_preferred_output_encoding():
 if hasattr(locale, 'LC_MESSAGES'):
  return (
   locale.getlocale(locale.LC_MESSAGES)[1]
   or locale.getdefaultlocale()[1]
   or 'ascii'
  )

 return (
  locale.getdefaultlocale()[1]
  or 'ascii'
 )
```

Calling `locale.setlocale` only changes the output of `locale.getlocale(locale.LC_MESSAGES)`—I suspect that Windows doesn't have the attribute `hasattr(locale, 'LC_MESSAGES')`, so the `locale.setlocale` call does absolutely nothing (and hence it didn't work).

What does this mean for your issue? Well, unless there is a way to change your locale directly in Windows to something suitable, you're essentially out of luck, sadly.

However, there is a hacky solution: Redefine `getdefaultlocale` in your `ipython` config (inspired by this [SO post](https://stackoverflow.com/questions/31469707/changing-the-locale-preferred-encoding-in-python-3-in-windows))

``` python
import _locale
_locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])

from powerline.bindings.ipython.since_7 import PowerlinePrompts

c = get_config()
c.TerminalInteractiveShell.prompts_class = PowerlinePrompts

# other configuration

```

**Comment by rekaerst** [comment]
That hacky solution works!
![image](https://user-images.githubusercontent.com/52642831/91666265-f4b85c00-eb2d-11ea-93fc-9e1657bf8351.png)
