### ISSUE TITLE
Arrows and branch icons not rendering properly

### ISSUE THREAD

**Issue by elroyalva** [powerline/powerline#2123]
So one fine day the fonts no longer work correctly. 
I use OS X terminal + zsh + oh-my-zsh + powerline if that helps. I haven't updated any of these packages recently. Thi sis on OS X 10.15.6

The `\ue0b0` icon appears as a `|` and the `\ue0a0` appears as `BR`
This is the behavior I see for all Powerline patched fonts 
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/8514311/94091116-47eb9a80-fdcc-11ea-9859-bf54c08abe3f.png">

**Comment by PH111P** [comment]
This looks like a problem with your locale, see https://github.com/powerline/powerline/issues/1697

**Comment by elroyalva** [comment]
> This looks like a problem with your locale, see #1697

I checked out that issue before I posted, but my locale seems to be set correctly. It was working a couple of days ago, and then it suddenly changed. Is there a place I need to set locale? I already have `export LC_ALL=en_US.UTF-8` and `export LANG=en_US.UTF-8` in my .zshrc file
<img width="884" alt="image" src="https://user-images.githubusercontent.com/8514311/94186166-2f769100-fe5b-11ea-8637-5749bb1ee31f.png">

**Comment by PH111P** [comment]
Are you using `powerline-daemon`? If yes, how do the powerlines look like if you stop `powerline-daemon`?
Did something change in your setup during the past days?

**Comment by elroyalva** [comment]
The weirdest thing happened. It all started looking fine after I killed the daemon. I tried to reproduce it, but it couldn't
<img width="885" alt="image" src="https://user-images.githubusercontent.com/8514311/94196138-ca299c80-fe68-11ea-8400-8677eca5f402.png">
