### ISSUE TITLE
i3 powerline config location

### ISSUE THREAD

**Issue by wow2006** [powerline/powerline#2126]
OS: Arch linux
Display manager: i3
powerline: 2.7 installed using pip

I am using powerline with i3 bar.
This my ~/.config/i3/config
```config
# ....
bar {
  font pango:DejaVu Sans Mono, FontAwesome 9
  position top
  status_command exec python ~/.local/lib/python3.8/site-packages/powerline/bindings/i3/powerline-i3.py
}
# ...
```

It just show date/time.

I want to custmize my i3 bar. I try both `~/.config/powerline/themes/wm/default.json` 
and `~/.config/powerline/themes/i3/default.json` and nothing happen. I am using powerline with tmux/bash. I use same config location but i3 don't work.

Could you tell me where to put my config file or what am I missing?

**Comment by PH111P** [comment]
Could you post the content of your config file `~/.config/powerline/themes/wm/default.json` (which should indeed be the correct location for the i3bar config)?

As a side remark, please consider switching to `lemonbar` and `powerline-lemonbar` (which has better powerline support, see [the documentation](https://powerline.readthedocs.io/en/latest/usage/wm-widgets.html#lemonbar-formerly-bar-aint-recursive) for more details).

**Comment by wow2006** [comment]
I made it empty json object to check which directory to use. I think it will ignore `wm/default.json` if it is empty. Thanks @PH111P I is working now :).
