### ISSUE TITLE
How to change bash welcome line color?

### ISSUE THREAD

**Issue by Ygarr** [powerline/powerline#2142]
How to change bash welcome color? e.g. from cyan to green
![temprrr2020-12-12_12-21](https://user-images.githubusercontent.com/14309871/101981328-afe7a980-3c74-11eb-9ed6-e4f88c9b6cab.png)

**Comment by PH111P** [comment]
Please consult the documentation. A quick start guide can be found here: https://powerline.readthedocs.io/en/latest/configuration.html#quick-setup-guide

**Comment by Ygarr** [comment]
Even so found such config
![image](https://user-images.githubusercontent.com/14309871/104192961-37693980-5428-11eb-8f26-41027d7bfefb.png)
