### ISSUE TITLE
After installation nothing happens

### ISSUE THREAD

**Issue by Databyte8** [powerline/powerline#2147]
When I cloned the rep and ran: `sudo python3.9 setup.py install` it will display an error at the top and it would just installing something.

`In file included from /usr/include/string.h:495,
                 from /usr/include/x86_64-linux-gnu/sys/un.h:37,
                 from client/powerline.c:7:
In function ‘strncpy’,
    inlined from ‘main’ at client/powerline.c:113:2:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin___strncpy_chk’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client/powerline.c: In function ‘main’:
client/powerline.c:113:2: note: length computed here
  113 |  strncpy(server.sun_path A, address, strlen(address));
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/python3/dist-packages/setuptools/dist.py:481: UserWarning: The version specified ("2.8.1.dev9999+git.b'999c84a5cba0d8dbc9d3875232b378d170da6af3'") is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
`
And then just comes running install and it would install. Then I reopen the Terminal but nothing changed. 
I am Using Kubuntu 20.04 and a bash terminal with python3.9

**Comment by PH111P** [comment]
In order for powerline to appear in your terminal, you need to change your shell configuration files. Please consult the documentation (https://powerline.readthedocs.io/en/latest/usage/shell-prompts.html) for further details.
