### ISSUE TITLE
Confused about the i3 integration and workspace indicator

### ISSUE THREAD

**Issue by gbraad** [powerline/powerline#2152]
When using `powerline-lemonbar.py --i3` I do not see the workspaces indicator on the bar. is that something that you would need to add as a segment to the configuration?

Because if I do, I get `Exception while computing segment: [Errno 2] No such file or directory`, which happens on the `_cmd_socket.connect`.

With the regular `powerline-i3` this would be a 'Exception while computing segment: 'WorkspaceReply' object is not subscriptable`

I have:
   * i3 4.19
   * i3ipc 2.1.1
   * powerline 2.8-3 (F33)
   * python 3.9.1

**Comment by gbraad** [comment]
Hmmmm... it might be related to the environment not setting `I3SOCK` correctly ?

**Comment by PH111P** [comment]
Your setup looks good so far; indeed you need to add a `powerline.segments.i3wm.workspaces` module to your config (which you tried, as far as I understand).
Hence, I think there might be a bug hidden here somewhere. Does `i3ipc` work on its own, that is, does the following python code work:
``` python
import i3ipc
conn = i3ipc.Connection()
conn.on('workspace::focus', lambda conn, evt: print(evt))
conn.on('mode', lambda conn, evt: print(evt))
conn.main()
```

**Comment by gbraad** [comment]
That seems to work:
```bash
$ python
Python 3.9.1 (default, Jan 20 2021, 00:00:00)
[GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

```python
>>> import i3ipc
c.Connection()
conn.on('workspace::focus', lambda conn, evt: print(evt))
conn.on('mode', lambda conn, evt: print(evt))
conn.main()>>> conn = i3ipc.Connection()
>>> conn.on('workspace::focus', lambda conn, evt: print(evt))
>>> conn.on('mode', lambda conn, evt: print(evt))
>>> conn.main()
<i3ipc.events.WorkspaceEvent object at 0x7f0c724c1220>
<i3ipc.events.WorkspaceEvent object at 0x7f0c724c1880>
<i3ipc.events.WorkspaceEvent object at 0x7f0c724c1220>
<i3ipc.events.WorkspaceEvent object at 0x7f0c724c1880>
<i3ipc.events.WorkspaceEvent object at 0x7f0c724c1220>
<i3ipc.events.WorkspaceEvent object at 0x7f0c724c1880>
```

**Comment by gbraad** [comment]
The full error message of the i3wm segment is:

```
2021-03-01 11:06:57,408:ERROR:wm:workspaces:Exception while computing segment: 'WorkspaceReply' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/powerline/segment.py", line 173, in process_segment
    contents = segment['contents_func'](pl, segment_info)
  File "/usr/lib/python3.9/site-packages/powerline/segment.py", line 412, in <lambda>
    contents_func = lambda pl, segment_info: _contents_func(pl=pl, segment_info=segment_info, **args)
  File "/usr/lib/python3.9/site-packages/powerline/segments/i3wm.py", line 53, in workspaces
    return [
  File "/usr/lib/python3.9/site-packages/powerline/segments/i3wm.py", line 55, in <listcomp>
    'contents': w['name'][strip:],
TypeError: 'WorkspaceReply' object is not subscriptable
```

**Comment by gbraad** [comment]
Also update from `i3ipc` `v2.1.1` which is distro provided, to the Pypi version which is `v2.2.1`. No difference

**Comment by PH111P** [comment]
Looking at 
```
  File "/usr/lib/python3.9/site-packages/powerline/segments/i3wm.py", line 55, in <listcomp>
    'contents': w['name'][strip:],
```
the problem seems to be that you are (somehow) using an outdated version (more on that later) of powerline: Some time ago, there was a breaking change in `i3ipc` and the above syntax stopped working. Alas, that is fixed in the current code already (See e.g. https://github.com/powerline/powerline/blob/1869cc8bedbd6085959e8566cad6729f3e7e2620/powerline/segments/i3wm.py#L55)

However, there hasn't been a new release since the corresponding fix was merged, so using the outdated version is not really your fault. Let me create a new release to fix this issue.

**Comment by gbraad** [comment]
Thanks!

After the new release is out I'll ping the package maintainer about this.

**Comment by gbraad** [comment]
@PH111P sorry about the off-topic question; but what happened to the `active_window` segment?

**Comment by PH111P** [comment]
As in, does it not work anymore?

**Comment by gbraad** [comment]
That segment is not available anymore... right?

On Mon, Mar 1, 2021 at 11:56 PM Philip Wellnitz
<notifications@github.com> wrote:
>
> As in, does it not work anymore?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 

   Gerard Braad | http://gbraad.nl

   STEM is the source, but BUILD is how you develop!
   [ Better Understanding Involves Learning and Doing ]

**Comment by PH111P** [comment]
To my surprise, an active window segment is indeed missing. However, looking at the history of `i3wm.py`, it seems as if such a segment never existed in the first place in this repo (which surprises me even more). In any case, here is rough source code for such a segment (taken from https://github.com/PH111P/powerline/blob/11094650ee6401dfa8912206ee43e2407f535bd6/powerline/segments/i3wm.py; note that the most recent version of that segment in the referenced repo does some more stuff which requires some other features not yet merged upstream):

``` python

def active_window(pl, cutoff=100):
        '''
        Returns the title of the currently active window
            :param int cutoff:
                Maximum title length. If the title is longer, the window_class is used instead.
        Highlight groups used: ``active_window_title``.
        '''

        focused = get_i3_connection().get_tree().find_focused()

        cont = focused.name
        if len(cont) > cutoff:
            cont = focused.window_class

        return [{'contents': cont, 'highlight_groups': ['active_window_title']}] if focused.name != focused.workspace().name else []
  ```

**Comment by gbraad** [comment]
Thanks. will see if I can contribute to this.
