### ISSUE TITLE
write() failed: Bad file descriptor

### ISSUE THREAD

**Issue by firsthubgit** [powerline/powerline#2154]
.bash_profile
. /Users/...../Library/Python/3.9/lib/python/site-packages/powerline/bindings/bash/powerline.sh

iTerm

![image](https://user-images.githubusercontent.com/10082460/109792249-457c4f00-7c4e-11eb-989a-447403e17a2a.png)

**Comment by PH111P** [comment]
Could you please provide some additional context (shell/powerline-binding, versions of involved programs, etc)? Thanks.

**Comment by firsthubgit** [comment]
![image](https://user-images.githubusercontent.com/10082460/109895251-de9c7b80-7cc9-11eb-9459-93305979b71a.png)

Vim  works well
![image](https://user-images.githubusercontent.com/10082460/109895350-07247580-7cca-11eb-950e-f524809e42b1.png)

**Comment by firsthubgit** [comment]
oh it works well in iterm.
maybe cause i use "pip install powerline-status -user"?

**Comment by Samdev13** [comment]
I get the same error, can you help me to fix this ? 
![Screenshot from 2021-07-15 17-11-07](https://user-images.githubusercontent.com/53824344/125829169-83a2920b-2083-4267-972c-fd879208f0ce.png)
