### ISSUE TITLE
i3 Workspaces segment does not render dividers

### ISSUE THREAD

**Issue by gbraad** [powerline/powerline#2155]
After some debugging and [configuration](https://github.com/powerline/powerline/issues/2054#issuecomment-791177948) I got the i3 workspaces segment working, but what I see is:

![image](https://user-images.githubusercontent.com/1894/110077972-02db8380-7dc2-11eb-97e3-d8997654ce33.png)

I would expect there are dividers between the id as:

![image](https://user-images.githubusercontent.com/1894/110078190-577efe80-7dc2-11eb-8768-8afb908c2ff8.png)

so it would look a little like:

![image](https://user-images.githubusercontent.com/1894/110078521-d5430a00-7dc2-11eb-964e-8db40da745ea.png)

**Comment by PH111P** [comment]
Try adding `draw_inner_dividers: true` and  `draw_soft_dividers: true`:

``` json
            {
                "function":             "powerline.segments.i3wm.workspaces",
                "draw_inner_divider":   true,
                "draw_soft_divider":    true
            },
```

**Comment by gbraad** [comment]
Didn't know about this and works ;-)

**Comment by gbraad** [comment]
![image](https://user-images.githubusercontent.com/1894/110237974-df5b3900-7f79-11eb-9846-6706dd8ef06b.png)
