### ISSUE TITLE
Docs: what do the elements of the default Vim statusbar mean?

### ISSUE THREAD

**Issue by JDeeth** [powerline/powerline#2156]
I've been using Powerline for a week or so, and I like the look of it, particularly the colour to indicate mode.

However I'm mystified as to what the other elements mean - the yellow M, the red ??, the various Greek letters - is there a guide somewhere I failed to find?

Sorry if this is a dumb question in the scheme of things…

![Screenshot from 2021-03-07 19-43-24](https://user-images.githubusercontent.com/847887/110252471-7e356480-7f7d-11eb-867b-3619a560b1b0.png)

**Comment by PH111P** [comment]
You can check out https://github.com/powerline/powerline/tree/develop/powerline/config_files/themes/vim for a quick overview of the default configuration (I'd especially recommend `default.json`); for a detailed overview what the specific segments do and display, also checkout the relevant section of the docs: https://powerline.readthedocs.io/en/latest/configuration/segments/vim.html

Regarding the greek letters, this seems to be a font-related issue (in their place, there should be the `>` and `<` symbols). Please check if you are using a font that contains the powerline glyphs.

Regarding the `M` and `??`, these should be status indicators from the `git` module.
