### ISSUE TITLE
uE0B0

### ISSUE THREAD

**Issue by EVRICA** [powerline/powerline#2170]
Instead of nice triangle symbol i got text btE0B0.
bt is username. You know PS1='\u'  returns username.
Why \uE0B0 returns usernameE0B0 ?

**Comment by EVRICA** [comment]
fonts were installed from
https://github.com/powerline/fonts.git

**Comment by EVRICA** [comment]
without these fonts I have empty little rectangle.
and after installation
userE0B0 construction

**Comment by PH111P** [comment]
Does your terminal support Unicode?

**Comment by EVRICA** [comment]
Seems no... I've tryed to paste " é " symbol and nothing happens, even cursor doesn't move

**Comment by EVRICA** [comment]
BUT hold on...
if I paste
echo -e "\xE2\x98\xA0"
it prints ☠

**Comment by PH111P** [comment]
I need more information (what OS/terminal emulator/shell are you using, etc) to give detailed answers about your setup. In any case, this looks like a configuration issue and not a powerline issue.

**Comment by EVRICA** [comment]
locale output

LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

**Comment by PH111P** [comment]
You should probably add/change your locale to something that contains "UTF-8".

**Comment by EVRICA** [comment]
using android 10 with vm debian/some defolt terminal, not using gui/bash shell

**Comment by EVRICA** [comment]
"You should probably add/change your locale to something that contains "UTF-8"."
Yeah, think so... I'll try that

**Comment by EVRICA** [comment]
ok now i able to ptint é
what was done:

locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales
sudo update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

**Comment by EVRICA** [comment]
stil no triangle
but instead of unameE0B0 I have empty little rectangle

**Comment by PH111P** [comment]
This is now a font problem. Try to install one of the powerline-fonts (See https://github.com/powerline/fonts).

**Comment by EVRICA** [comment]
done but nothing changed.
I'va tryed to apply utf8 to my xterm by:
xterm -en en_US.UTF-8
and tryed to change xterm font by:
xterm -fn "Source Code Pro for Powershell"
but in both cases error:
xterm: Xt error: Can't open display
xterm: DISPLAY is not set

aslo tryed this:
xterm -report-fonts
to see curently used font, butgot same error

Am I need to set up gui?

**Comment by EVRICA** [comment]
Seems so. This works with graphical interface.
$sudo apt install xfce4
$vncserver
Also you need not "xterm" terminal emulator, but "konsole" for example.
$apt install konsole (~250 mb)
$konsole
Now I able to see powerline symbls by
$echo $'\ue0b0'
