### ISSUE TITLE
Zsh prompt just shows `'common'`

### ISSUE THREAD

**Issue by s1gtrap** [powerline/powerline#2185]
Hi. I'm trying to get this working for zsh on macOS [using this guide.](https://powerline.readthedocs.io/en/master/installation/osx.html)

Using Homebrew, so I started with (which got me `python@3.9` as `python@2` is apparently not available)
```
brew install python
```
and followed it with
```
pip3 install powerline-status
```
It's working fine for vim, but adding the following to `.zshrc`
```
powerline-daemon -q
. /usr/local/lib/python3.9/site-packages/powerline/bindings/zsh/powerline.zsh
```
gives me this
<p align="center">
    <img width="682" alt="Screenshot 2021-11-22 at 09 08 27" src="https://user-images.githubusercontent.com/3110065/142825614-56b46ea4-2b06-4b61-9a04-a04f4662afe6.png">
</p>

So yea, I have no idea where this comes from. I can't tell what the problem is, not finding any newer docs or more recent guides, but I would assume the problem is with the python version? The `powerline-*` execs are in `PATH`, so I don't know..

**Comment by PH111P** [comment]
Hi @s1gtrap,

I think this might be an issue with your config files. Can you try `powerline-lint` (to find errors in your config) and `powerline-render shell left` (which should produce the desired powerline, or at least some more detailed errors).

**Comment by s1gtrap** [comment]
This seems.. weird. 

`powerline-lint` runs ok and prints nothing, and `powerline-render shell left` seems to be working fine?

<p align="center">
    <img width="682" alt="Screenshot 2021-11-22 at 19 08 53" src="https://user-images.githubusercontent.com/3110065/142913078-256df46b-faf6-4c8d-bab2-350aff5785a4.png">
</p>

**Comment by PH111P** [comment]
Indeed, that is somewhat weird. I could imagine that your `.zshrc` does some extra things that interfere with powerline in some way.

**Comment by s1gtrap** [comment]
<img width="682" alt="Screenshot 2021-11-23 at 09 30 05" src="https://user-images.githubusercontent.com/3110065/142991545-8996d8ae-afbe-4026-a686-19c77af75415.png">

**Comment by s1gtrap** [comment]
Okay, I don't know what I did wrong the first time, but after reinstalling everything it seems to be working lol.

Sooo should I close this?
