### ISSUE TITLE
Tmux status line redraw issue when emoji is present.

### ISSUE THREAD

**Issue by mlhadi** [powerline/powerline#2195]
Hi, 

Tmux status line does not redraw properly, causing the status line to be appended at the end of the screen everytime the segment refreshes.

My  tmux default.json file:
```json
{
    "segments": {
        "right": [
            {
                "function": "powerline.segments.common.sys.uptime",
                "priority": 50
            },
            {
                "function": "powerline.segments.common.time.date"
            },
            {
                "function": "powerline.segments.common.time.date",
                "name": "time",
                "args": {
                    "format": "%H:%M",
                    "istime": true
                }
            },
            {
                "function": "powerline.segments.common.bat.battery"
            },
            {
                "function": "powerline.segments.common.net.hostname"
            }
        ]
    }
}
```

The appended status bar:
![image](https://user-images.githubusercontent.com/34226619/152938670-931718db-e486-4146-a222-fc2ab68e6530.png)

I then changed the default.json to:
```json
{
    "segments": {
        "right": [
            {
                "function": "powerline.segments.common.sys.uptime",
                "priority": 50
            },
            {
                "function": "powerline.segments.common.time.date"
            },
            {
                "function": "powerline.segments.common.time.date",
                "name": "time",
                "args": {
                    "format": "%H:%M",
                    "istime": true
                }
            },
            {
                "function": "powerline.segments.common.bat.battery",
                "args": {
                    "online": "C",
                    "format": "{ac_state} {capacity:3.0%}"
                }
            },
            {
                "function": "powerline.segments.common.net.hostname"
            }
        ]
    }
}
```

Changing the `online` argument to just the character `C` (or even an empty string) seems to make the problem go away. Presumably, when the symbol is being inserted as `ac_state`, this causes some printing issue? I have no idea.
![image](https://user-images.githubusercontent.com/34226619/152939876-58afa336-2822-4b3b-8f87-6070f341729a.png)

I'm using Ubuntu 18.04.5 on WSL1. Not really a big issue for me, but the it suddenly came up and I noticed it's because of the lightning symbol. My laptop is usually always connected to the power adapter, but it won't charge depending on the current battery level, so when I first put up the battery segment, the symbol was not there (for some reason). 

Then a couple of days after, when I was opening up a tmux session, that's when it started.

**Comment by PH111P** [comment]
This is a known issue, please see https://github.com/powerline/powerline/issues/1652.
(TL;DR: choose a different font. :/)
