### ISSUE TITLE
getting errors then sourcing powerline in bash

### ISSUE THREAD

**Issue by lucasrj** [powerline/powerline#2214]
hey` i begin getting errors then I try to source powerline 

I'm sourceing /usr/share/powerline/bindings/bash/powerline.sh

I am running ubuntu 20.04 with xfce4 desktop envierment

`
bash: cd: too many arguments
bash: cd: too many arguments

Command '' not found, but can be installed with:

sudo apt install mailutils-mh  # version 1:3.7-2.1, or
sudo apt install meshio-tools  # version 4.0.4-1
sudo apt install mmh           # version 0.4-2
sudo apt install nmh           # version 1.7.1-6
sudo apt install termtris      # version 1.3-1

Command '' not found, but can be installed with:

sudo apt install mailutils-mh  # version 1:3.7-2.1, or
sudo apt install meshio-tools  # version 4.0.4-1
sudo apt install mmh           # version 0.4-2
sudo apt install nmh           # version 1.7.1-6
sudo apt install termtris      # version 1.3-1
`

**Comment by lucasrj** [comment]
@PH111P  that info is it that is needed?

**Comment by PH111P** [comment]
Hi @lucasrj,

with the information you provided, it is not possible for me to understand what exactly is going wrong with your installation. Assuming you followed the installation guide, it would be useful if you could at least share the relevant parts of your bashrc and powerline config files, as well as more information on your environment (python version, powerline version, version of any other relevant software, etc).
`powerline-lint` may also yield useful information.

Thanks.

**Comment by lucasrj** [comment]
I found the problem.
the  problem was not with powerline.
I had by error created an alias test, the powerline problem was just a symptom of my stupidity.
