### ISSUE TITLE
Edges mismatch

### ISSUE THREAD

**Issue by UtopianElectronics** [powerline/powerline#2220]
My powerline suddenly looks like this:

![powerline](https://user-images.githubusercontent.com/63358324/203600929-42482cfb-25f0-4665-ab2b-327c0e782737.png)

```
OS: Fedora Linux 36 (Workstation Edition) x86_64 
Kernel: 6.0.8-200.fc36.x86_64  
Shell: bash 5.2.2 
DE: GNOME 42.5 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal
```
What's the culprit? How can I diagnose and fix what's causing this?

**Comment by UtopianElectronics** [comment]
Just uninstalled and reinstalled both `powerline` and `powerline-fonts` and right after the installation and in a new tab everything was fine until I closed the terminal and opened it again. Now the problem has appeared again.

**Comment by PH111P** [comment]
See #1898.
