### ISSUE TITLE
No such file or directory (sometimes)

### ISSUE THREAD

**Issue by Hex-4** [powerline/powerline#2230]
I'm on Kubuntu 22.10, using zsh. When I open Konsole, I get the error
`/home/hex4/.local/lib/python3.10/site-packages/powerline/bindings/zsh/powerline.zsh:210: no such file or directory: /home/hex4/.local/lib/python3.10/site-packages/scripts/powerline-config`
and the same for line 214. The scripts directory doesn't exist. But when opening the vscode integrated terminal, everything works fine, and when you spawn a new shell with `zsh`, everything works too.

**Comment by pcxmac** [comment]
look at your PYTHONPATH variable when it gives you the error and when it doesn't. I define mine in the .zshrc. 

powerline installs itself in to this path ~/.local....site-packages/powerline . It really depends on how you are integrating powerline, did you use a package system, or did you just drop it in to your home directory. 

https://github.com/pcxmac/user/blob/main/.zshrc << check this out for reference. 

specifically this set of lines : 

############################ MISC #########################################################

# PYTHON ######################################################################

export PYTHONPATH=~/.local/lib64/python2.7/site-packages

# POWERLINE ###################################################################

	# installed ? (if not) then install
		# git clone
		if [ ! -d ~/.powerline ]
		then
			git clone https://github.com/powerline/powerline.git .powerline

		fi

		if [ ! -d ~/.local/lib64/python2.7/site-packages ]
		then
			mkdir -p ~/.local/lib64/python2.7/site-packages
			# link .powerline/powerline to .local/lib64/python2.7/sites-packages/powerline
			ln -s ~/.powerline/powerline ~/.local/lib64/python2.7/site-packages/powerline
		fi

	PATH=~/.powerline/scripts:$PATH

	# export powerline bin and bind zsh
	. ~/.local/lib64/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh

	# utilize powerline-daemon for quicker responses from powerline
	powerline-daemon -q
