### ISSUE TITLE
Centre segments section

### ISSUE THREAD

**Issue by hrai** [powerline/powerline#2233]
Is there a way to centre the rightmost segments? It seems to include the window number and the app that's currently running in it. 

![image](https://user-images.githubusercontent.com/4055444/228381770-29bfa655-285f-43a2-810f-47fe057ca774.png)

Also, what's the name of these in built segments?
- tmux session (0 in the screenshot above)
- tmux window and running app (1* > zsh in the screenshot above)

My left segment doesn't specify them.

Here's my config:
```
{
  "segments": {
    "left": [
      {
        "function": "powerline.segments.common.vcs.branch",
        "priority": 50
      },
      {
        "function": "powerline.segments.common.env.cwd",
        "before": " "
      },
      {
        "function": "powerline.segments.common.vcs.branch"
      }
    ],
    "right": [
      {
        "function": "powerline.segments.common.time.date",
        "before": " "
      },
      {
        "function": "powerline.segments.common.time.date",
        "name": "time",
        "before": " ",
        "args": {
          "format": "%H:%M",
          "istime": true
        }
      },
      {
        "function": "powerline.segments.common.net.hostname"
      }
    ]
  }
}
```

**Comment by PH111P** [comment]
Hi @hrai,

The left part of the tmux bar (the tmux session, window etc) is unfortunately baked into tmux and not really configurable, as far as I understand. Also, I would advise against using cwd-dependent segments in tmux; if I recall correctly, they don't really work as expected (don't get updated if you move to a different dir within tmux).

As for center segments; these are currently not supported here at all and require rewriting both the config parser, as well as the bindings (read: this is work). I once did something like that for the lemonbar binding, but I'm not sure if that solution is suitable for a wider roll-out (in particular, one would still need to rewrite a binding for tmux).
