### ISSUE TITLE
The imp module is removed in Python 3.12

### ISSUE THREAD

**Issue by jelly** [powerline/powerline#2250]
Python 3.12 removed the [imp module](https://docs.python.org/3/whatsnew/3.12.html#imp) which is used in powerline's [tests](https://github.com/powerline/powerline/blob/14cc0d2df8e85fd88aad0e1152c4b1f998f4a7b0/tests/modules/lib/__init__.py#L4). It has been replaced by importlib since 3.1

**Comment by KiYugadgeter** [comment]
This is also one of the cause of block to update Arch Linux's python version

**Comment by dvzrv** [comment]
This one should be trivial to fix by removing the `import imp` and replacing this
https://github.com/powerline/powerline/blob/14cc0d2df8e85fd88aad0e1152c4b1f998f4a7b0/tests/modules/lib/__init__.py#L103

with `types.ModuleType(name)`

**Comment by PH111P** [comment]
Hi @dvzrv,

thanks for the potential fix. Can I ask you to create a pull request (which I could then merge)?

Thanks!

**Comment by Antiz96** [comment]
> Hi @dvzrv,
> 
> thanks for the potential fix. Can I ask you to create a pull request (which I could then merge)?
> 
> Thanks!

Hi @PH111P,

I opened a pull request for the fix at https://github.com/powerline/powerline/pull/2251 :slightly_smiling_face:
