### ISSUE TITLE
Powerline loses colors

### ISSUE THREAD

**Issue by jakubgs** [powerline/powerline#230]
Hello there,

After some time without updating I've run BundleUpdate today and to my surprise Powerline stopped having colors like so: ![black-n-white-powerline](https://f.cloud.github.com/assets/2212681/164924/543ba61e-78fe-11e2-95d9-38b54d606734.png)

I could get the colors by sourcing my vimrc but once I edited a new file or saved one the colors would disappear. It's all white on black.

I have no idea what might be causing this.

I use jellybeans colorscheme if that might be relevant.

Here is my vimrc: http://pastebin.com/kr9AuYgJ

**Comment by SephVelut** [comment]
Issue still exists when opening new file/buffer.

`let g:miniBufExplForceSyntaxEnable = 1` fixes it.

**Comment by SephVelut** [comment]
If you're using any kind of buffer autocmds (BufNewFile, BufRead, etc) then try placing `nested` between the buff discrip and the command:

`autocmd BufNewFile,BufRead *.rb nested colorscheme gotham`
