### ISSUE TITLE
Make powerline look like old powerline

### ISSUE THREAD

**Issue by BlakeWilliams** [powerline/powerline#244]
It's not exactly clear through the documentation on how to make a good looking powerline config without using the patched fonts. Is there a way to config powerline to look more like the following image rather than how it currently looks?
![Screen Shot 2013-02-20 at 5 52 39 PM](https://f.cloud.github.com/assets/342554/178435/a3844e62-7bb8-11e2-9da3-aa07d0aa1beb.png)

**Comment by therockmandolinist** [comment]
Sorry to open this issue again, but I too am wondering how to make powerline look like vim-powerline... I'm not sure I understand the discussion here or if it's even up to date (pretty new to vim, excuse my ignorance)

**Comment by ZyX-I** [comment]
@therockmandolinist There is http://powerline.readthedocs.io/en/master/configuration/reference.html#config-ext-top-theme to choose one of the predefined set of dividers and other symbols, including ASCII-only theme.

And I have no idea what exactly do you mean by “make powerline look like vim-powerline”, I did not use it for a few years. The reply above concerns the dividers.

**Comment by therockmandolinist** [comment]
Ah, thanks for the quick reply. What I meant was to get it to look like in the original poster's image on this issue.
