### ISSUE TITLE
Indicating visual activity

### ISSUE THREAD

**Issue by dhruvasagar** [powerline/powerline#258]
Hey previously I was using the following configuration in my tmux conf :

```
setw -g monitor-activity on
set -g visual-activity on
```

This is quite useful as it monitors tmux windows for any activity and visually indicates the same by highlighting the tmux tab in the statusline.

Currently this breaks since the highlighting since highlighting doesn't have the special characters:

![Screenshot from 2013-02-23 09:39:20](https://f.cloud.github.com/assets/88258/187586/d9015528-7d6e-11e2-92f1-683f6517099b.png)

Do you already support this feature somehow ? Do you have any plans ?

**Comment by c02y** [comment]
@dhruvasagar `set-window-option -g window-status-activity-attr bold,blink,underscore` is nice, but can I make it blink after the task finishes?

**Comment by dhruvasagar** [comment]
@c02y I don't think that's possible, at least not that I know of.

**Comment by c02y** [comment]
@dhruvasagar what about the interval of blink?

**Comment by dhruvasagar** [comment]
@c02y That's os specific, for osx I have found it is possible https://www.maketecheasier.com/change-cursor-blink-rate-os-x/, not sure about other platforms (from a quick google search), but I am hoping there might be.

**Comment by c02y** [comment]
@dhruvasagar You were saying the blink in tmux is the problem of the OS? I thought the interval can be controlled by a variable defined by tmux or something.

**Comment by c02y** [comment]
You were saying the blink in tmux is the problem of the OS? I thought the interval can be controlled by a variable defined by tmux or something. 

于 2015年7月17日 GMT+08:00下午5:59:31, Dhruva Sagar <notifications@github.com> 写到:

**Comment by dhruvasagar** [comment]
@c02y the blink character, afaik, is an os thing, in tmux there's only a config to make it blink or not, and that too doesn't work across all platforms / terminals, again because it is os specific.
