### ISSUE TITLE
Installed with vundle, nothing happens.

### ISSUE THREAD

**Issue by trusktr** [powerline/powerline#414]
Seems installing powerline doesn't work with vundle, but vim-bundle does. Also, which python does it work with? I have both 2.7 and 3 on my system.

**Comment by yarving** [comment]
Bundle 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
This line works

**Comment by klassegeljakt** [comment]
Plug 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}

Works if you are using Plug
