### ISSUE TITLE
multi-line shell

### ISSUE THREAD

**Issue by treyhunner** [powerline/powerline#462]
To achieve a two-line shell prompt I tried adding the following to "segment_data" for the shell configuration but it resulted in the triangle being placed on the next line.

```
    "cwd": {
        "after": "\n"
    }
```

Result:

![Selection_029](https://f.cloud.github.com/assets/285352/417696/472ce258-ac75-11e2-9981-d7d80c82c198.png)

**Comment by ovidiub13** [comment]
I've looked and looked, and can't for the life of me figure out how can I have this on 2 lines.
Can you please provide a small example ?

**Comment by yongjhih** [comment]
https://github.com/yongjhih/rc/blob/master/.config/powerline/themes/shell/default.json for example.

**Comment by ovidiub13** [comment]
Thank you.
