### ISSUE TITLE
cwd segment not working in tmux

### ISSUE THREAD

**Issue by pablox-cl** [powerline/powerline#467]
I dunno why, I have added the `cwd` segment, and the only thing I'm getting is the `~` sign.

I run `powerline tmux right` and the output it's okay (showing the cwd), but the status line in tmux doesn't change at all.

How can I continue debugging the issue?

**Comment by symbolix** [comment]
I am trying to implement the solution described here, however, I am getting some nasty errors:

<ERROR>

Any ideas?

**Comment by ZyX-I** [comment]
@symbolix This issue was created in 2014, configuration format changed.

**Comment by symbolix** [comment]
Hi,

Yes. I have figured it out. Apologies. I thought I have to hack my way around to get the `cwd` segment working. It seems like it is already implemented as one of the `common` segments.

However, we still need to have the:

```
export POWERLINE_NO_SHELL_PROMPT="TRUE"
. /usr/local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh
```

trick in there to get a dynamic path display, is that correct? Without the `bash` binding, the value is set only once and with the lines listed above added to my `.bashrc` file, I can see the `cwd` segment updating.

Thanks.
