### ISSUE TITLE
vim powerline question

### ISSUE THREAD

**Issue by jdash** [powerline/powerline#521]
This may be a dumb question, and if so I apologize. but I've got powerline working (I know the tmux version is working) I've added the line to my .vimrc and it's not giving any errors, but it's not doing anything either, there is no change to the display or look for vim? I'm assuming there is some default template (I know I can change it)?

**Comment by SimZhou** [comment]
> I was having that issue and the key was on the loaded paths for python. You can check yours in vim by running
> 
> ```viml
> :python import sys; print(sys.path)
> ```
> 
> I solved it by adding the path
> 
> ```viml
>     python import sys; sys.path.append("/Library/Python/2.7/site-packages")
>     python from powerline.vim import setup as powerline_setup
>     python powerline_setup()
>     python del powerline_setup
> ```

Correct answer deserves thumb up and rockets!!!

btw, I solved it with lines above, plus changing python to python3
