### ISSUE TITLE
Custom font not working for iTerm2

### ISSUE THREAD

**Issue by sheerun** [powerline/powerline#58]
In terminal, I get funny colored characters: http://d.pr/i/KFFv

But in iTerm2 they are displayed as question marks (I've tried two different modified fonts): http://d.pr/i/AUy4

OS X 10.8.2, iTerm2 1.0.0.20120724, zsh 5.0.2 (x86_64-apple-darwin12.2.1)

**Comment by maurobaraldi** [comment]
After I've updated terminal to last iTerm2 version, I installed [this  font](https://github.com/powerline/fonts/blob/master/Meslo%20Slashed/Meslo%20LG%20M%20Regular%20for%20Powerline.ttf), and then it works.
