### ISSUE TITLE
Custom fonts are not supporting transparency on iTerm2

### ISSUE THREAD

**Issue by sheerun** [powerline/powerline#65]
http://d.pr/i/vtt0

**Comment by polarathene** [comment]
Came across this issue when troubleshooting via Google, in case anyone else lands here I've made a [PR for iTerm2](https://github.com/gnachman/iTerm2/pull/277) that should hopefully get merged to fix this issue :)

This does not make the separator glyph consistent with transparency with the segments, instead it does the opposite keeping both fully opaque while the main BG can be transparent.
