### ISSUE TITLE
shell: add window title segment to update window title

### ISSUE THREAD

**Issue by Glandos** [powerline/powerline#727]
Currently, powerline doesn't write any escape sequence in PS1 to update window title. This could be a great segment to add.

**Comment by ghost** [comment]
This seems to be a valid bug. With the default PS1 on Ubuntu, in WSL, my window title is always updated. As soon as I enable powerline (`. /usr/share/powerline/bindings/bash/powerline.sh`), it stops updating, so if I do anything with any other system that sets a window title, then exit back to my local session, my local session is stuck with that other system's title until I ssh somewhere else, and then I'm stuck with that title, nor does changing directories locally update the window title any more.
