### ISSUE TITLE
Using with zsh.

### ISSUE THREAD

**Issue by trusktr** [powerline/powerline#736]
I've git cloned the repo and `sourc`ed `powerline/bindings/zsh/powerlie.zsh` in my .zshrc but when it's time to render the prompt I get `zsh: command not found: powerline`. What am I missing?

Ideally I'd like to simply install this with antigen (plugin manager for zsh).

**Comment by neurogenesis** [comment]
Once powerline is installed you could do something like...

```
source antigen.zsh
antigen use oh-my-zsh
antigen theme prikhi/molokai-powerline-zsh molokai-powerline-zsh
antigen apply
```

**Comment by ZyX-I** [comment]
@neurogenesis [That theme](https://github.com/prikhi/molokai-powerline-zsh) has nothing to do with this powerline, probably except for it using powerline glyphs.

**Comment by neurogenesis** [comment]
@ZyX-I correct. many people have commented that pip is still the recommended way to install a *portion* of powerline. you still have to install the fonts, add includes for vi, etc. etc.. I was merely pointing out that once it's installed, antigen (as used above) can still be used to manage powerline themes.

**Comment by ZyX-I** [comment]
@neurogenesis These are not powerline themes, these are themes using powerline glyphs. AFAIK nobody has written powerline theme for use with antigen (though it looks like a simple task).
