### ISSUE TITLE
solved: ZSH+CURSOR position shifts to the right w/ MASTER branch in GIT repository for ZSH.

### ISSUE THREAD

**Issue by pcxmac** [powerline/powerline#793]
There is a problem with powerline & zsh (console independent from what I can tell).

The problem is there is a space missing between the powerline_command (colored bar) and the cursor when ever I run zsh. This is not a problem when I am in a GIT folder however, as the cursor comes out 1 space in front in that case (probably has something to do with the git status/tree that pops up opposite the cursor).

This problem does not occur in bash + powerline, as there is a space in between the powerline_command and the prompt/cursor at all time.

This problem is really only a problem during tab completion and some commands because the cursor will set itself properly (most rearward position) upon tab completion leaving the character fixed between the powerline_command and input prompt.

example.
(tab completion shifts cursor right and leaves artifact (extra L)
 :: > directory >LLS -l  
where it would be 
:: > directory > LS -l 
in a git directory or bash

$PS1 = "$($POWERLINE_COMMAND shell left -r zsh_prompt --last_exit_code=$? --last_pipe_status="$pipestatus" --jobnum=$_POWERLINE_JOBNUM)"

**Comment by steadystatic** [comment]
This seems related to what's happening to me (and another user I met in the freenode#zsh room), illustrated by a GIF, my locale is set and I am using zsh 5.0.5 and oh-my-zsh:

![zsh-tab-issue](https://cloud.githubusercontent.com/assets/130587/10947247/2e9de974-82e4-11e5-97d3-ee8c2c266e51.gif)
