### ISSUE TITLE
Support 24-bit color in terminal

### ISSUE THREAD

**Issue by ZyX-I** [powerline/powerline#81]
There is ISO-8613-3 standard for 24-bit color in terminals: `\e[38;2;{R};{G};{B}m` (foreground, 48 for background) ({R},{G},{B} are decimal integers from 0 to 255). Currently it is fully supported only* by konsole and partially** in xterm. On Windows there is support for this in ConEmu. I am working on supporting this in vim (it will use guifg/guibg attributes in terminal). [Working version](https://bitbucket.org/ZyX_I/vim), bookmark 24-bit-xterm. Does not work if you try to compile with gui support enabled.

Issue is not urgent, but nice-to-have. I will probably look at it later as it should be easy to add.

\* Checked all terminals that have at least one stable version in Gentoo main portage tree.

** Uses nearest color from 8-bit palette.

**Comment by ryneeverett** [comment]
@ZyX-I Do you know of any reason `set spell` would have no visible effect with `set guicolors`?

**Comment by ZyX-I** [comment]
@ryneeverett By default `SpellBad` highlight group sets colors for terminal (they are ignored because gui colors are used), `undercurl` `gui` attribute (ignored because `cterm` attributes are used, not `gui` attributes) and `guisp` color for gui (ignored because terminal does not have corresponding capability).

So default highlight group sets only properties that are ignored for one or the other reason.

**Comment by ZyX-I** [comment]
By the way, this is unrelated issue that is long since closed.
