### ISSUE TITLE
Bad/partial powerline fonts in st and urxvt. No problem with gvim or lxterminal

### ISSUE THREAD

**Issue by xfim** [powerline/powerline#823]
I really don't know how to solve the issue of powerline fonts not working properly in my system.

I use gentoo, with awesome as window manager and urxvt as the terminal emulator.

The problem / paradox is the following:

urxvt does not fully show the > and < separators:
![urxvt-inconsolata](https://f.cloud.github.com/assets/674675/2269495/be60c652-9eda-11e3-88d0-75331e19454f.png)

st neither does it:
![st-inconsolata](https://f.cloud.github.com/assets/674675/2269499/cb749bf2-9eda-11e3-97d4-d39a905b126b.png)

vim from inside each of the terminals is not working properly neither:
![vim_from_urxvt](https://f.cloud.github.com/assets/674675/2269500/d4c9e2b6-9eda-11e3-8b30-a6526860d635.png)
![vim_from_st](https://f.cloud.github.com/assets/674675/2269501/d99366a0-9eda-11e3-81ea-148898b7453a.png)

When I open a tmux session in each of the consoles, urxvt still gives trouble with everything:
![tmux_from_urxvt](https://f.cloud.github.com/assets/674675/2269506/e29bb220-9eda-11e3-9597-a39dfbd593ce.png)

but st only has problems with separators (but not with clocks, etc):
![tmux_from_st](https://f.cloud.github.com/assets/674675/2269511/ed336818-9eda-11e3-946b-4a66a54ba8cc.png)

In addition to st, I have also tried lxterminal, and it works perfectly out of the box:
![lxterminal](https://f.cloud.github.com/assets/674675/2269514/f7d2ea50-9eda-11e3-8e75-d1fe20d97424.png)

More? Yes. Gvim shows the font and the > and < separators properly
![gvim](https://f.cloud.github.com/assets/674675/2269517/feb3883e-9eda-11e3-9862-05502386fdaf.png)

So I am sure that there is something that escapes out of my mind. Why lxterminal works but not st and urxvt? Well probably it must be related to the font. Well, then, why st works partialy when a tmux session is working inside the emulator, but not urxvt?

I am using urxvt version 9.19 with unicode3 and xft compiled in. I have tried many specifications of different fonts (Meslo, with and without "for powerline" replacemenets, with different pixelsizes as suggested by https://github.com/Lokaltog/powerline/issues/453#issuecomment-16825527, obviously running `xrdb -merge .Xdefaults` each time), but with no luck or better results. The screenshots have been taken with the following fonts specifications:

```
URxvt*font: xft:Inconsolata,pixelsize=8,xft:Inconsolata for Powerline:pixelsize=8
URxvt*boldFont: xft:Inconsolata:bold:pixelsize=8,xft:Inconsolata for Powerline:bold:pixelsize=8
```

st with:

```
static char font[] = "Inconsolata:pixelsize=12:antialias=false:autohint=false";
```

As for the font installation method, I have tried both the Fontconfig (lxterminal and st should work with that method according to http://askubuntu.com/questions/283908/how-can-i-install-and-use-powerline-plugin/283909#283909) and the "patched font" version for "urxvt".

Thank you.

**Comment by eugenelet** [comment]
Anyone still working on this thread? Really need help. I've tried all of the methods above, changing to Consolas and stuff, still can't get it working, any ideas?

![image](https://cloud.githubusercontent.com/assets/13523904/14231389/f2b8673a-f9b3-11e5-80c5-eb8441e4e6c4.png)

**Comment by BlitzKraft** [comment]
I have similar issue. The fonts work just fine in gnome-terminal. In uxterm, the arrows are good, but no other glyphs show: musical note, gamified battery display - hearts, mail glyph in email count segment, weather, lock and clock. The glyphs are boxes.  

In rxvt and urxvt, not even the arrows show up.

**Comment by MasterSergius** [comment]
I have this in uxrvt with FantasqueSansMono:

![screenshot from 2016-05-04 17 26 14](https://cloud.githubusercontent.com/assets/3962779/15017325/ca605464-121d-11e6-8df1-77185dc6f7d3.png)

So, how to resolve this? (in gnome-terminal or xfce4-terminal it works perfect with Meslo fonts for Powerline)

**Comment by artsi0m** [comment]
I have same problem with st . Should I write something in `ascii_printable[]` ?


![ascii](https://cloud.githubusercontent.com/assets/18009816/19014489/c1b9ddae-87f6-11e6-9727-428f0087e2a7.png)

**Comment by byteofsoren** [comment]
Have the same problem my self when i use uxrvt with vim or fish shell.
The image show fish shell in terminator (left and works) and uxrvt.(right and don't work)
![2017-01-10-183822_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1524209/21817526/97f4dfe2-d764-11e6-85a0-bf8574c286cd.png)

**Comment by BlitzKraft** [comment]
What is the output of `locale` command ? 

Change that to support utf-8 by following the [instructions here](http://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue). That should solve the problem.

**Comment by byteofsoren** [comment]
Managed to brick my urxvt so it did not start at al because it asked for some fonts i didn't have.
`urxvt: unable to load base fontset, please specify a valid one using -fn, aborting.`
Solved that issue by.
```
xset +fp /usr/share/fonts/75dpi/
xset fp rehash
```
Then that solved both issues. =)
