### ISSUE TITLE
tmux 1.9a hangs after installing powerline in virtualenv?

### ISSUE THREAD

**Issue by oglops** [powerline/powerline#875]
centos 6.4 x64,  i don't have root privilege, but i have virutalenv and python2.7 installed,  after adding 
```
source '/home/xxx/Envs/myEnv27/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf'
```
to `~/.tmux.conf`, tmux won't open, it just hangs there.  but tmux 1.6 works fine. how to troubleshoot ? thanks !

edit: i found that i have to goto the installation directory to run it, then it's working , what am i missing ?
i need to `cd ~/apps/tmux` then run `tmux` . like this :
```
cd ~/apps/tmux/bin ; ~/apps/tmux/bin/tmu
```

i compiled tmux with `./configure --enable-static` , is this related to my issue ?

**Comment by mjc-** [comment]
python 2.7.9  / tmux 1.9a / pyenv (no virtualenv) / zsh and seeing the same behaviour. ironically, running it under strace, the problem disappears. when not stracing, there is a "sh [defunct]" that is created.

**Comment by ZyX-I** [comment]
@mjc- It is better to report as a tmux bug, because I am not doing anything which should result in a hang. But before doing this can you reproduce the bug using

    mkdir /tmp/nonexistest-directory
    cd /tmp/nonexistent-directory
    tmux -2 -f /path/to/powerline.conf -vvvv -S ./tmux-socket new-session zsh

and post logs from /tmp/nonexistent-directory found after killing tmux (to kill try *in order*

1. try `tmux -S /tmp/nonexistent-directory/tmux-socket kill-server`.
2. `kill -INT {PID}`
3. `kill -TERM {PID}`
4. `kill -KILL {PID}`

. Reasoning: if you first do `kill -KILL` I am not sure that full logs will survive.)

**Comment by lessenich** [comment]
Same problem here with tmux 1.9a, python3.3, and powerline 
b40e45a.
I ran 'tmux -2 -f /usr/share/powerline/tmux/powerline.conf -vvvv -S ./tmux-socket new-session' and it hangs, ps showing defunct processes. Killing via kill-server worked.
client log is empty,. here is the output of the server log:
```
$ egrep -v 'got [0-9]{3} from client [0-9]' tmux-server-21269.log 
server started, pid 21269
socket path ./tmux-socket
new client 7
loading /usr/share/powerline/tmux/powerline.conf
/usr/share/powerline/tmux/powerline.conf: if-shell 'test -z "$POWERLINE_CONFIG_COMMAND"' 'set-environment -g POWERLINE_CONFIG_COMMAND powerline-config; run-shell "env \"\$POWERLINE_CONFIG_COMMAND\" tmux setup"' 'run-shell "env \"\$POWERLINE_CONFIG_COMMAND\" tmux setup"'
/usr/share/powerline/tmux/powerline.conf: # vim: ft=tmux
cmdq 0x6a2f50: if-shell "test -z "$POWERLINE_CONFIG_COMMAND"" "set-environment -g POWERLINE_CONFIG_COMMAND powerline-config; run-shell "env \"\$POWERLINE_CONFIG_COMMAND\" tmux setup"" "run-shell "env \"\$POWERLINE_CONFIG_COMMAND\" tmux setup"" (client -1)
run job 0x6a3240: test -z "$POWERLINE_CONFIG_COMMAND", pid 21270
job write 0x6a3240: test -z "$POWERLINE_CONFIG_COMMAND", pid 21270, output left 0
job error 0x6a3240: test -z "$POWERLINE_CONFIG_COMMAND", pid 21270
new client 5
cmdq 0x6a6f60: kill-server (client 5)
writing 203 to client 5
writing 210 to client 7
writing 210 to client 5
lost client 5
lost client 7
```

**Comment by ZyX-I** [comment]
@lessenich So, tmux hangs on running `test -z`? What if you run tmux like you did, but with `-f /dev/null` and manually run `powerline-config tmux setup` from within?

Also try using `-f <(echo $'if-shell \'test -z "$SOME_NONEXISTENT_VAR"\' \'show-environment -g\' \'show-options -g\'')` and `-f <(echo $'if-shell \'test -z "$PATH"\' \'show-environment -g\' \'show-options -g\'')`. If this freezes you can report the bug to tmux developers because this configuration has absolutely nothing to do with powerline (show-environment and show-options are just some random commands that came to my mind).

Also check out whether replacing sourcing of powerline configuration file with just `run-shell 'powerline-config tmux setup'` will fix the freeze. If not, run like above (with `-f <(echo $'run-shell "powerline-config tmux setup"')` and post the log.

**Comment by lessenich** [comment]
Thank you for looking into this!
Unfortunately, it still hangs with the latest version :(
When I run `powerline-config tmux setup` manually, it executes, but there are issues with the status bar (works just sometimes for a short amount of time), and there is a lot of this in the log:
```
job error 0x14e7d30: env $POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS tmux left, pid 14335
job error 0x15047b0: env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=`tmux display -p "#D"`, pid 14336
run job 0x14eb500: env $POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS tmux left, pid 14339
run job 0x14e96a0: env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=`tmux display -p "#D"`, pid 14340
job write 0x14eb500: env $POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS tmux left, pid 14339, output left 0
job write 0x14e96a0: env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=`tmux display -p "#D"`, pid 14340, output left 0
cmdq 0x14e8020: display-message -p #D (client 16)
writing 213 to client 16
writing 203 to client 16
lost client 16
```

also, there is sometimes a large block of this:
```
job error 0x14df4c0: env $POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS tmux left, pid 14782
job error 0x14e7fa0: env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=`tmux display -p "#D"`, pid 14783
job died 0x1504bc0: env $POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS tmux left, pid 14708
free job 0x1504bc0: env $POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS tmux left
job died 0x1504b70: env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=`tmux display -p "#D"`, pid 14709
free job 0x1504b70: env "$POWERLINE_COMMAND" $POWERLINE_COMMAND_ARGS tmux right -R pane_id=`tmux display -p "#D"`
job died 0x14e8040: env $POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS tmux left, pid 14712
free job 0x14e8040: env $POWERLINE_COMMAND $POWERLINE_COMMAND_ARGS tmux left
```

**Comment by ZyX-I** [comment]
@lessenich This commit is not the result of looking into the problem, just some refactoring of tmux bindings that was there to fix a different issue (occasionally failing tests). Did you test tmux without powerline as I requested? Tmux hang does not look related to powerline according to your previous log.

Job errors from `env $POWERLINE_COMMAND` look strange, but should be unrelated to tmux hanging. What does it show if you run these errorring commands from log from within the started shell? Also are you using daemon? (AFAIK though with daemon powerline clients are not going to ever exit with something, but zero.)

**Comment by lessenich** [comment]
@ZyX-I You were right: Both `-f <(echo $'if-shell \'test -z "$SOME_NONEXISTENT_VAR"\' \'show-environment -g\' \'show-options -g\'')` and `-f <(echo $'if-shell \'test -z "$PATH"\' \'show-environment -g\' \'show-options -g\'')` do cause a freeze. This is strange - I'll report that to the tmux devs. Anyway, thanks for the help!
