### ISSUE TITLE
Git branch status coloring is inconsistent

### ISSUE THREAD

**Issue by scottsuch** [powerline/powerline#886]
Perhaps I'm missing something, but the color of the branch should revert to gray when clean. Sometimes this is the case and sometimes it's not and I'm not sure what info to provide you with aside from the screenshots below.

This screenshot shows powerline behaving improperly:
![screenshot 2014-05-28 14 22 26](https://cloud.githubusercontent.com/assets/897179/3108977/514208d0-e695-11e3-9d75-4706af71024b.png)

This screenshot shows powerline behaving correctly:
![screenshot 2014-05-28 14 22 46](https://cloud.githubusercontent.com/assets/897179/3108976/5141f1d8-e695-11e3-98e3-e6642b1759c3.png)

**Comment by lantrix** [comment]
I have the same colour inconsistency in bash/Mac. Installed pyuv (and ergo libuv) but don't see any change.

**Comment by ZyX-I** [comment]
@lantrix And did you restart after this? Note that you must restart the *daemon*, restarting shell is completely useless.

**Comment by lantrix** [comment]
I did do a:

    sudo launchctl stop /System/Library/LaunchDaemons/com.apple.fseventsd.plist
    sudo launchctl start /System/Library/LaunchDaemons/com.apple.fseventsd.plist

prior to a shell restart; but no luck. Maybe I need to bounce the Mac.

**Comment by ZyX-I** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On April 8, 2015 9:01:53 AM EAT, Lantrix <notifications@github.com> wrote:
>I did do a:
>
>sudo launchctl stop
>/System/Library/LaunchDaemons/com.apple.fseventsd.plist
>sudo launchctl start
>/System/Library/LaunchDaemons/com.apple.fseventsd.plist
>
>prior to a shell restart; but no luck. Maybe I need to bounce the Mac.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/powerline/powerline/issues/886#issuecomment-90811852

powerline daemon. Did not remember that Mac uses daemon for FS Events so you may read that this way.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJNBAEBCgA3BQJVJQQaMBwfMDI7PjIgHTg6PjswOSAQOzU6QTA9NEA+MjhHIDxr
cC1wYXZAeWFuZGV4LnJ1PgAKCRBu+P2/AXZZImsqEAC0Z9cld+he8nyU8rGpbvO5
E/74bMUFoGdjqtE9pysPqzp+agLOjWXbwpx0lHsduYGkkUVutUocOhbfKc7gzlHA
VgeuPoPxxWmbLNpygRNA0irWEU3N8mbZObR1LwHL+kZVzGWd0DtVRhpw6sGC7XQJ
N88u6//dJl8x3AmLoewTkd+yQ2dYqy/2fQos4DSz06H2KtxYGQMmA3c2WUtUlInz
oZ7YndLXl8VfoQpU3nLc1PqO7Z1ieK7ikNe3rlWZvW3Efg0GFaMs/oyYW9zHaQaq
wT9jD8DzW5Azy1BIZZUqUHo6ED1VIpILCu5xnQa30gvkzoa48CbOc/c6AN601FZz
5/1Ep3rWhc8/rwe9V7OKVQm73s6Z+9UCjft5hlyLp07yUvulvMusYpmjGYGXafUo
QD26Vox0m+L2KxMOq264XKqkZG7rIXzdHlap4H60kgsXneo2F+DO4ey+6NDPviTT
QxBOmeVq+q35squ6TMG2z27Xb6woINmL2PJf6G5m84DjCtQqntHL8C4bVlC89PGp
V72oZobZc6Fy9MFY9c8iZa1ji4d8s/ALPXylTIvU829i895/wbkTZ2yICmoMjnb8
w3ThHtsHn03mFr1H/qpxSoFBIUi3wxF3jdi0lrND1ecyQtZZxIg6dSuO/0vKBcs2
B4j/xotZD0VXfNAdbOT+3A==
=tcPv
-----END PGP SIGNATURE-----

**Comment by lantrix** [comment]
Ahaa. An easy mistake.

It seems #906 did indeed fix this for Mac OS X using Bash; after installing `pyuv` and restarting the powerline-daemon.

![screenshot 2015-04-08 22 41 33](https://cloud.githubusercontent.com/assets/117008/7045329/aba2a98a-de40-11e4-9380-e0972a4c84d0.png)
