### ISSUE TITLE
tmux status bar not rendering properly

### ISSUE THREAD

**Issue by heidar** [powerline/powerline#901]
It's like the default bar is there underneath and there is a weird space on the left for some reason.

I'm on Iterm2, zsh and I installed via pip from github today on OS X. Font is patched source code pro. Only thing in my tmux config is setting TERM to screen-256color.

![tmux](https://i.imgur.com/HObzApA.png)

**Comment by cyklee** [comment]
@dutchgecko @ashishsc I'm quite late to the party, but for others suffering from the same problem, I solved it by moving

`run-shell "powerline-daemon -q"
source "/{powerline root directory}/powerline/bindings/tmux/powerline.conf"`

to the end of tmux.conf.
