### ISSUE TITLE
Unable to modify to background of Powerline on tmux?

### ISSUE THREAD

**Issue by phongvcao** [powerline/powerline#907]
Hi everyone,

I am having trouble changing the background of Powerline, particularly on the tmux's session name section. Here is the screenshot:

![screenshot from 2014-06-29 10 39 14](https://cloud.githubusercontent.com/assets/874795/3423536/5c93f4a8-ff9c-11e3-8a87-b634423a5987.png)

So those black spots in the tmux's session name background are not in sync with the whole background color of Powerline on tmux. Is this an issue with either tmux or Powerline or it's just me who doesn't know how to adjust it?

**Comment by phongvcao** [comment]
Today I am back to using Tmux and Powerline and the Black spot still persists. Does anyone know how to setup Solarized Powerline for Tmux so that we can get rid of this little black spot on the left of the bottom Tmux powerline bar?

![selection_002](https://cloud.githubusercontent.com/assets/874795/6497403/2f1c188c-c2ad-11e4-8b02-69f0160c4592.png)

Also, in order to get this theme works, I have done lots of customization. I may fork the project and create a Pull Request for the tmux/solarized.json theme if this black spot can be fixed. I use Solarized for everything in my desktop. Thanks guys!

**Comment by kejadlen** [comment]
This works for me:

``` shell
❯ cat powerline/colorschemes/tmux/default.json
{
        "groups": {
                "background":           {"bg": "gray1"},
                "active_window_status": {"bg": "gray1"},
                "window_status":        {"bg": "gray1"},
                "activity_status":      {"bg": "gray1"},
                "bell_status":          {"bg": "gray1"},
                "window":               {"bg": "gray1"},
                "window:divider":       {"bg": "gray1"}
        }
}
```

**Comment by phongvcao** [comment]
@kejadlen thanks bro I finally got it working! Problem solved!

**Comment by NickolasHKraus** [comment]
You can remove the window status with:

```
# remove window status
set -g window-status-current-format ""
```

![Screen Shot 2019-11-23 at 14 18 48](https://user-images.githubusercontent.com/14130403/69484736-46dc8c00-0dfc-11ea-9e9e-cd968385cb2b.png)

**Comment by NickolasHKraus** [comment]
I also use the following for `status-left`:

```
# set status-left
set -g status-left "#{?client_prefix,#[fg=colour252]#[bg=blue]#[nobold]#[noitalics]#[nounderscore],#[fg=black]#[bg=colour252]#[nobold]#[noitalics]#[nounderscore]} #S #{?client_prefix,#[fg=blue],#[fg=colour252]}#[bg=colour0]#[nobold]"
```

![Screen Shot 2019-11-23 at 16 07 57](https://user-images.githubusercontent.com/14130403/69485939-6f1fb700-0e0b-11ea-8a79-6903d785014a.png)
