### ISSUE TITLE
powerline-daemon usage is outputted repeatedly when using tmux

### ISSUE THREAD

**Issue by davidjb** [powerline/powerline#960]
After configuring `tmux` for Powerline and starting `tmux` from a `bash` shell (with powerline successfully enabled), the tmux status line is enabled correctly.  However, for every command that I execute in the tmux shell, the following is outputted:

```
> echo 'test'                                                                                                               
test
usage: powerline-daemon [-h] [-r MODULE] [-w WIDTH] [--last_exit_code INT]
                        [--last_pipe_status LIST] [--jobnum INT]
                        [-c KEY.KEY=VALUE] [-t THEME.KEY.KEY=VALUE]
                        [-R KEY=VAL] [-p PATH]
                        ext [{left,right,above,aboveleft}]
```

The unusual thing is that this argparse help doesn't appear to match that of `powerline-daemon` itself.  If I run the following command, still within tmux, I get the following output:

```
> powerline-daemon --help
usage: powerline-daemon [-h] [--quiet] [--kill | --foreground | --replace]

Daemon to improve the performance of powerline

optional arguments:
  -h, --help        show this help message and exit
  --quiet, -q       Without other options: do not complain about already
                    running powerline-daemon instance. Will still exit with 1.
                    With `--kill' and `--replace': do not show any messages.
                    With `--foreground': ignored. Does not silence exceptions
                    in any case.
  --kill, -k        Kill an already running instance
  --foreground, -f  Run in the foreground (dont daemonize)
  --replace, -r     Replace an already running instance
usage: powerline-daemon [-h] [-r MODULE] [-w WIDTH] [--last_exit_code INT]
                        [--last_pipe_status LIST] [--jobnum INT]
                        [-c KEY.KEY=VALUE] [-t THEME.KEY.KEY=VALUE]
                        [-R KEY=VAL] [-p PATH]
                        ext [{left,right,above,aboveleft}]
```

It seems as though the `powerline-daemon` might be being overridden somewhere as these argument outputs don't match.  Since the output continues to be displayed every time the prompt is shown, I presume this must be in the prompt display code somewhere.  The same issue doesn't occur in a standard bash shell outside of tmux.

My .tmux.conf looks like:

```
source "~/.vim/bundle/powerline/powerline/bindings/tmux/powerline.conf"
```

and nothing else.  My installation is via Vim's Bundle tool, and scripts installed via `pip install -e [path]` so there's only the one install of Powerline.  I'm on Ubuntu 14.04 with Python 2.7.6.

**Comment by sryze** [comment]
I have a similar problem with powerline for bash in a chroot: evey time I use (s)chroot I get the usage message for powerline-daemon and no command prompt. I have a working configuration in my main system and I'm using it inside the chroot.

My `PS1` is `\[\e]0;(trusty32)\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w\$` if that helps. Also `PROMPT_COMMAND` is set to `_powerline_set_prompt` and `POWERLINE_COMMAND` is `powerline`.

Any ideas what could be wrong? I guess I might be missing some package but I have not idea which one...

**Comment by ZyX-I** [comment]
@sryze Your PS1 immediately gets overridden by `_powerline_set_prompt`. I cannot be sure what is wrong without seeing `type _powerline_set_prompt` and your powerline version (most likely it is incompatible versions of bindings and powerline). Make sure that what you source in bash configuration and the output of `python -c 'import powerline; print(powerline.__file__)'` are consistent.

And do not taint unrelated issues.
