### ISSUE TITLE
fish: No prompt until manually calling `powerline-setup`

### ISSUE THREAD

**Issue by oschrenk** [powerline/powerline#983]
I added

```
# Powerline
set fish_function_path $fish_function_path "/usr/local/lib/python2.7/site-packages/powerline/bindings/fish"
powerline-setup
```

as my last lines in `.config/fish/config.fish` but whenever I create a new terminal tab or window I get greeted with an empty prompt. I have to call powerline-setup myself to start.

I'm not sure if this is a fish/powerline/configuration issue but I hoped that you have some ideas on how to solve this problem.
- Running  fish 2.1.0
- Installed lokaltog/powerline via `pip`.

**Comment by tommyjcarpenter** [comment]
I have this exact same issue.

**Comment by tommyjcarpenter** [comment]
Even with the most recent powerline 2.5.2 and the most recent fish, I still have this issue.

**Comment by tommyjcarpenter** [comment]
I have tried the 2x thing, still does not work. Using iterm2 nightly build 3.22.2017.

**Comment by ZyX-I** [comment]
@tommyjcarpenter This means that you have some code which overrides prompt after powerline sets the prompt up. And this issue is *solved*, you can’t have the same one. No reopening. And you have a separate issue already.
